### ISSUE TITLE
Issue When Uploading New Report Templates In Webform (QA) Site

### ISSUE THREAD

**Issue by dgalvanmeza** [tedrick/Survey123-Testing#100]
**Application:** Website

**Device:** Desktop PC

**Operating System:** Windows 10

**Browser:** Chrome

**Error Description:** 

**How to reproduce:**
- In the data tab on the site, where individual responses are shown, edit an existing report template by uploading a new word doc. A green success message appears, but does not leave the screen or give you the option to close it. You have to refresh the page to use the buttons behind it (Report, Export, Open in MapViewer). 

**Have you tested with another survey?** 
- N/A

**Comment by tedrick** [comment]
Added issue to internal repo: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/2170

**Comment by tedrick** [comment]
@dgalvanmeza - Did you get a reproducible set of steps.  We are seeing this sporadically; we need a reliably reproducible case to be able to solve.

**Comment by dgalvanmeza** [comment]
@tedrick - During testing, I was able to reproduce it consistently on the QA site by doing the following:

1. Sign in to Survey 123 QA Site.
2. Click on any survey.
3. Click on "Total Records".
4. Click on "Report (Beta)" and select "Manage Templates".
5. Edit an existing template and choose a new doc template to replace the existing one.
6. Click "Save".
7. The "Saved Successfully!" animated message should appear, and then stay stuck even after closing the editing window behind it. 

During the testing, the second animation for this message to disappear would not occur, however, on my current it is disappearing (as expected). I am currently running Windows 10 64 Bit and Chrome 63.0.3239.132.

I hope this helps out!

**Comment by zhif7782** [comment]
Hi @dgalvanmeza , thanks for the steps. However, I cannot reproduce the issue by following above steps currently. Please let us know anytime if you find some other steps that can reproduce the issue in the future.

![aaa](https://user-images.githubusercontent.com/7665168/35313275-74187f32-00fa-11e8-8741-4da0fd9605fb.gif)
