### ISSUE TITLE
FEEDBACK: Connect List Type Hinting

### ISSUE THREAD

**Issue by slawdis** [tedrick/Survey123-Testing#102]
Application: Connect

Device: Macbook Pro

Operating System:** MacOS High Sierra

Browser:** Safari 11.02

Feedback: The XLSForm dropdown for choice lists shows select_one [list_name]. I struggled at first to realize I needed to remove the brackets with my choice list name. My first instinct was to place my choice list name between them at first.

**Comment by tedrick** [comment]
Added to discussion issue on template format
