### ISSUE TITLE
Year and Year-Month Appearance questions do not submit as expected

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#103]
**Application:** Connect | Field App | Website

**Browser:** Edge

If you design a survey in Connect that uses the Year or Year-Month Appearance, the field app will properly display JUST the year, and JUST the year and month. If you take the survey in the Web Browser, the entire date is shown (Day, Month, Year). It always assumes the first of the month.
![image](https://user-images.githubusercontent.com/22916127/35176863-8a30694c-fd30-11e7-9e55-af06acc1c0b7.png)

But whether you submit the data from the Field App or from the browser, the data is submitted as it is viewed in the browser (Day, Month, Year, always assuming the first of the month)
![image](https://user-images.githubusercontent.com/22916127/35176894-bd3213fe-fd30-11e7-9824-9e7193cf5940.png)

**Comment by zhif7782** [comment]
@sbubka94 even with the year or year-month appearance, the value behind will actually be submitted with the full date value, it's an expected behavior.

For the displaying issue in webform, we have a known issue in webform repo: https://github.com/ArcGIS/survey123-webform/issues/296
cc @tedrick
