### ISSUE TITLE
End to End Scenario: Asset Inspection

### ISSUE THREAD

**Issue by JohnHasthorpe** [tedrick/Survey123-Testing#104]
**End to End Scenario: Asset Inspection**

You are tasked with creating an asset inspection survey for assets around the Redlands campus. The asset can be anything trees, lamp posts etc, but you must perform the steps outlined below.

Use the documentation to help you:
http://doc.arcgis.com/en/survey123/

1) Build the feature layer (asset) and table (inspection) in Desktop - you may use a solution data set or build your own from scratch. Build the feature/table relationship and publish the service to portal as a hosted feature service. Make sure the inspection table supports attachments.
2) Create 2 surveys from this existing feature service - making sure that you utilise the XLSForm functionality to make the form Smart. One would be for capturing the assets (features) and the other for revising the asset and completing an inspection (table records).  Ensure that the inspection form supports image capture.
3) Publish the surveys and download them to the field app.
4) Go out into the field and complete a number of runs: the first collecting the asset information and rest completing the asset inspections (e.g. condition).
5) On completion, get back to the office and use the Survey123 website to view and analyse the results.
6) Create a custom report template and use it to print out a selection (one by one) of survey responses.
7) Finally, submit some additional surveys (both forms) using the webform. Check that the functionality matches that of the field app and view and analyse the results in the website once more.

- [x] @tedrick Please review. Thanks

**Comment by RITI8169** [comment]
[Connect_Create Survey.xlsx](https://github.com/tedrick/Survey123-Testing/files/1717287/Connect_Create.Survey.xlsx)

I will keep adding issues to this file

**Comment by JohnHasthorpe** [comment]
Closing issue for next round of Holistics.
