### ISSUE TITLE
Feedback: Coordinate Entry and GeoSearch

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#105]
The map widget is being enhanced to incorporate geosearch functionality. This allows field users to more easily center the map at a particular address, placename or coordinate pair. Additionally, geosearch allows the author of the survey to store the user-selected placename or address as an attribute in the GIS features.

**Highlights**

- Placename and address lookups are only available while online.  When working offline, geosearch only is available for coordinate entry.
- All geocoding and reverse geocoding is performed against the Esri World Geocoding service
- Coordinate entry formats supported include:
- Decimal degrees
- Degrees,minutes, seconds
- USNG
- MGRS
- 

Sample  XLSForm:  
[GeoSearch_Basics.xlsx](https://github.com/tedrick/Survey123-Testing/files/1765193/GeoSearch_Basics.xlsx)

Your feedback is welcomed:
* Do you like the user experience? Assume geosearch input will be enabled by default always once the map is expanded.
* Would you like this to default to the Esri World Geocoding service (as currently)? Or would you prefer that it uses the default locator specified in your organization?
* Do you like the pulldata() approach to get the address stored as a GIS attribute?
* Do you need to trigger reverse geocode automatically so an address is persisted every time the location changes?

**Comment by tedrick** [comment]
Bill

**Comment by menzelc** [comment]
Using map widget with beta 2.7 via Survey123 beta on Windows.
Don't have the same dialog as James showed to enter my own address. 
Click Map
![image](https://user-images.githubusercontent.com/4838513/36863148-e0f71b36-1d56-11e8-9871-3f9e7d0b2629.png)

Click top bar (the word location in my case), the map becomes active BUT

1. the location moves north, which is probably OK b/c it is moving to the point that the word "location" is on top off.  
2. the dialog to enter an address does not appear.

User error probably but need more information on how to enter my own address.

![image](https://user-images.githubusercontent.com/4838513/36863359-7b7bdd36-1d57-11e8-819b-10e3049343ac.png)
