### ISSUE TITLE
CHALLENGE: Create a webhook for a Survey

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#108]
Using the instructions in the Early Adopter Community, create a survey with a webhook.

Webhook providers:
Microsoft Flow
Zapier
Integromat
?

**Comment by tedrick** [comment]
Bill

**Comment by tedrick** [comment]
Note on using MS Flow: You need to provide the JSON schema.  Attached is a sample; modify to suit your fields:
[sample webhook schema.txt](https://github.com/tedrick/Survey123-Testing/files/1772611/sample.webhook.schema.txt)
