### ISSUE TITLE
CHALLENGE: iOS 11

### ISSUE THREAD

**Issue by IsmaelInRedlands** [tedrick/Survey123-Testing#11]
**Context:** [iOS 11 will ship soon](https://www.apple.com/newsroom/2017/06/ios-11-brings-new-features-to-iphone-and-ipad-this-fall/). Post here any issues you find when running Survey123 on iOS11

**Comment by sbubka94** [comment]
My Surveys page appears with smaller icons on iPhone 7 Plus 10.3.3
Collect page also appears with smaller icons than usual
Settings > Scale % helps when actually taking the survey, but not for My Surveys or Collect page

iOS 11 may help? Will try installing beta iOS for testing

**Comment by JohnHasthorpe** [comment]
Issue raised: https://devtopia.esri.com/Melbourne/Survey123/issues/1852

**Comment by JohnHasthorpe** [comment]
2.4 testing complete
