### ISSUE TITLE
Documentation: How to pass parameters to Survey123 Connect

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#116]
Pass parameters to Survey123 Connect

The URL scheme used by Survey123 Connect is arcgis-survey123connect://, which will allow the user to automatically download and open a survey, ready for editing.

This URL scheme accepts different parameters than the field app or web app, however, instead accepting the form's item ID and the URL for the portal that the item is stored on. This example URL opens a specific survey in Survey123 Connect from the ArcGIS Enterprise portal provided, downloading it if it isn't already present.

arcgis-survey123connect://?portalUrl=https://exampleportal.esri.com/arcgis&itemID=36ff9e8c13e042a58cfce4ad87f55d19

If your survey is saved in ArcGIS Online, you still need to provide the portal URL for ArcGIS Online.

arcgis-survey123connect://?portalUrl=https://www.arcgis.com/&itemID=36ff9e8c13e042a58cfce4ad87f55d19

Note:
Currently, these URL parameters can only be used to open forms that you are the owner of. It can't be used to open surveys that you have access to, but did not create.

**Comment by JohnHasthorpe** [comment]
Closing issue for next round of Holistics.
