### ISSUE TITLE
End to End Scenario Part 2 - Utilize Cascading Selects, Pulldata, and Sharing/Submitting

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#117]
For this workflow, the goal is to create a survey based on the data which is included in the attached CSV, share the survey with ‘The Public’, submit records to the survey, and then analyze the results at survey123.arcgis.com. 

Included in the CSV, you will find records representing “collection stations”. These are designated stations where the public can observe and document the amount of water that has been collected in a rain gauge over a 24 hour period and then submit a survey with corresponding results. 

1. Download attached XLSX file and save it as CSV
[Stations.xlsx](https://github.com/tedrick/Survey123-Testing/files/1808798/Stations.xlsx)

2. Create a user friendly survey that helps guide and limit the choices available to the survey submitter.  

Consider using relevant statements, cascading selects, pulldata, etc…  (workflow might be to utilize cascading selects, so the survey submitter will select what state > county > city they are in, which will then present them with a list of corresponding stations for that city.  Or, alternatively, use pulldata to utilize the existing coordinate information provided in the CSV to create a record at the known location. The idea would be that the survey submitter would show up at a station, enter a unique location ID, and information related to the city, state, zip and location would be auto populated by using pulldata.)

IMPORTANT: Keep in mind, you will likely only utilize one method (Cascading Selects or Pulldata) during the workflow mentioned above.  You can choose whichever one you find to be more user friendly.

Once you determine how to best represent the information provided in the CSV, the goal would then be for the submitter to enter in precipitation information (i.e. how many inches of rain are in the gauge?)

Make sure to also include the date and time for when the survey was taken and maybe a place for them to take notes

3. After publishing the survey, share it with the public

4. Accumulate 20 or more submissions using various methods (field-app, web form, desktop field app).  (Consider sharing survey with others to take as well)

5. Analyze the results using the Survey123 website and note any observations

**Comment by JohnHasthorpe** [comment]
Try submitted to the survey using the web and field app

**Comment by RITI8169** [comment]
1. The Calculate Location from CSV sample in Connect App has an error in it. The name fields has upper case letters and so the survey cannot be published.
2. The Calculate Location from GeoPoint and Cascading samples show Data Validation Error in the excel sheet. They work fine but this error can be misleading to users.

**Comment by JohnHasthorpe** [comment]
@RITI8169 Thanks for the above - we will raise issues to fix these

**Comment by RITI8169** [comment]
Unable to download sample report template
After uploading a report template successfully, the Report and Export drop downs become inaccessible and the Saved Successfully message does not go away.


![reporttemplate](https://user-images.githubusercontent.com/31448327/37844790-0fb5be88-2e86-11e8-9ffb-15a362f1ce7b.JPG)

**Comment by JohnHasthorpe** [comment]
@RITI8169 1 is expected. In terms of 2 can you share the survey url? Thanks

**Comment by JohnHasthorpe** [comment]
Closing issue for next round of Holistics.
