### ISSUE TITLE
Double display in S123 App on maximizing window

### ISSUE THREAD

**Issue by RITI8169** [tedrick/Survey123-Testing#118]
**Application**: Field App 
**Device**: PC
**Operating System**: Windows 7
**Error Description**: There is double display in Survey 123 App on maximizing window
**How to reproduce:** 
1. Open the Survey 123 Field App
2. Maximize the window by double clicking on the title bar
3. The contents in the App are displayed twice overlapping in the window.
On clicking anywhere outside, the display is corrected

![s123_doubledisp](https://user-images.githubusercontent.com/31448327/37435945-bf741b02-27a2-11e8-8735-94c6c1b0331b.jpg)

**Comment by RITI8169** [comment]
The same issue happens in Survey 123 Connect Application too.

**Comment by BrandonArmstrong** [comment]
@RITI8169 Can you still reproduce this behavior?  I have a Windows 7 machine and am not seeing it when attempting to repro.

**Comment by JohnHasthorpe** [comment]
Not reproducible - Closing issue for next round of Holistics.
