### ISSUE TITLE
FEEDBACK: Nested Repeats

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#119]
With Survey123 3.0, we plan to support nested (multiple levels) of repeats.  Please create forms that use multiple levels of repeats and note any issues publishing or using the forms.

**Comment by Temmermand** [comment]
Template for Repeat Aggregate doesn't calculate the oldest birthday.

![image](https://user-images.githubusercontent.com/38793244/39387006-208d87ba-4a2c-11e8-8da2-90b1583d6a11.png)

![image](https://user-images.githubusercontent.com/38793244/39387026-33e911c6-4a2c-11e8-9212-33e25b864a46.png)

**Comment by JohnHasthorpe** [comment]
Closing issue
