### ISSUE TITLE
FEEDBACK:  Survey123 Website - Collaborate Page improvements

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#121]
The Collaborate page has a new capability to set which features a viewer of the survey can see (note: the feature service owner will always be able to see all of the data).  The link to access the forms is also being processed via a URL shortener.  Please provide feedback on the improvements

**Comment by tedrick** [comment]
Colin, Bill

**Comment by tedrick** [comment]
@billwie - interesting.  BTW, today's test is on survey123dev.arcgis.com, not qa (we had to hold qa on a 2.7 release this week)

**Comment by sbubka94** [comment]
The field app crashes anytime I try to launch it using the shortened URL. It also crashes if I use the old formatted URL (survey123.arcgis.com/share/xxxxxx?open=native)

iPhone 7 Plus, iOS 11.3

Did not reproduce on Galaxy S7, Android 7.0

**Comment by billwie** [comment]
I believe Enterprise 10.6 is required for me to use this feature (reliant on Feature Layer Views correct?). I'm 10.5.1 i'll attempt to get a 10.6 Portal up and running to test it against.
![survey123collaboratesharenotsupported20180427](https://user-images.githubusercontent.com/35609547/39379889-48e84808-4a22-11e8-9bf0-cac123b1da7a.png)

**Comment by zhif7782** [comment]
@billwie thanks for pointing out the scrollbar in Collaborate page, it should be improved to have a better user experience, I've logged an issue in the dev repo.

On the Collaborate->Viewer tab, yes it will rely on the feature layer view, so it's not available for portal before 10.6 release.

**Comment by JohnHasthorpe** [comment]
Closing issue for next round of Holistics.
