### ISSUE TITLE
FEEDBACK: Analyze page image gallery

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#122]
The Analyze tab of the Survey123 website now has an image gallery to review photos.  Try it out (with date filtering, access permissions, etc.) and provide feedback

**Comment by RITI8169** [comment]
_The two delete buttons for Image in S123 website are identical and have no hints associated with them._

1. Create a survey
2. Add an Image question
3. Publish and open on the website
4. Attach an Image
5. Hover over the image attached

Two delete buttons are displayed (for name and image itself). Both the buttons are identical and there is no way to know which is for which functionality. No associated hint and looks a little confusing.

![s123 holistic1](https://user-images.githubusercontent.com/31448327/39378763-2a6342ca-4a0e-11e8-801e-93c160ac4afa.JPG)

**Comment by RITI8169** [comment]
**Default name of the Image uploaded is not the saved name in the Field App**

1. Create a Survey
2. Add Image question
3. Publish and open in website and Field App
4. Upload the same image (saved as 7.jpg on the machine) to both the website and the App

The Website shows the image name as 7.jpg while the Field App shows something different.

See screenshot

![imagename](https://user-images.githubusercontent.com/31448327/39379175-566284ac-4a0f-11e8-87ea-cddb03ec226c.PNG)

**Comment by colinlawr** [comment]
Images attached to response from phone's gallery appear rotated in the Analyze Gallery. The image will appear correctly if clicked to view full screen. 

Survey submitted from Samsung Galaxy S7 running Android 7.0

![rotation](https://user-images.githubusercontent.com/15009559/39383661-eaf45104-4a1e-11e8-9da8-05e64baaac6f.PNG)

**Comment by colinlawr** [comment]
The geocoded map preview will appear correctly for the first image opened, but will not change (along with the other metadata) when using the arrows to navigate photos.

Closing and then opening another picture full screen will produce the correct map preview.

![map_preview](https://user-images.githubusercontent.com/15009559/39383779-66327e72-4a1f-11e8-87c9-497a6f643378.PNG)

**Comment by colinlawr** [comment]
Maybe a bit nit-picky...but HTML formatting is not honored in the metadata text, referring to the repeats in the image above.

**Comment by Temmermand** [comment]
Hide table and show table do not do anything.

![image](https://user-images.githubusercontent.com/38793244/39386309-e2d84264-4a28-11e8-8a03-59d626fe536f.png)

**Comment by zhif7782** [comment]
@RITI8169 @colinlawr @Temmermand thank you for all the feedbacks. Would you mind sharing some details of the image question when you see the Show/Hide table? From our tests agains plain image question and also image question in nested repeats, the Show/Hide table are both hidden as by-design.

* The missing icons for Image question in web form will be fixed before the release of 2.8
* Show/Hide table will be removed once we can reproduce the issue
* We will try to rotate all images correctly in the gallery, but it may not be implemented if bad performance issue encountered 
* In image viewer, displayed image will unlink with detail info on the right panel -> will be fixed before release of 2.8
* HTML formatting will be removed in the title of the right panel inside image viewer for consisitent UI on a dark background


@phil-wilson you may want to take a look at the image filename issue in field app.

**Comment by JohnHasthorpe** [comment]
Closing issue for next round of Holistics.
