### ISSUE TITLE
FEEDBACK: Survey123 Webhook Settings Page

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#124]
For 3.0, Survey123 will be introducing a setting page for web hook - but it's already available for testing!  Try to create a webhook from the setting page and let us know any issues!

**Comment by billwie** [comment]
Able to successfully submit against Microsoft Flow and Flow receives using Survey123Dev website to submit. I was able to scrape the JSON from the Chrome console and put it into Flow. Now working on getting some of the submitted attributes to populate an outgoing email in Flow.

**Comment by Temmermand** [comment]
![image](https://user-images.githubusercontent.com/38793244/39386533-f7fd1a10-4a29-11e8-9f41-24c0c4335829.png)
 Cannot access Getting start link.

**Comment by zhif7782** [comment]
@sschwoppe @Temmermand thanks for your feedback.

The doc page has not been established yet, but will be ready in 3.0 release which will make the webhook setting page publicly available.

**Comment by JohnHasthorpe** [comment]
Closing issue
