### ISSUE TITLE
FEEDBACK: 'Version Locking' a web form

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#125]
With version 2.8, the Survey123 website will allow a survey author to 'lock' the version of the web form, ensuring consistent display in the future after version releases.  This is available via the new Settings tab.  Provide feedback below!

**Comment by RITI8169** [comment]
There is not much to tell right now, but when there is a newer version add a link to the page which lists the changes and improvements in the latest version. It will help the user decide whether to use Version Locking or not.

**Comment by zhif7782** [comment]
@RITI8169 thanks for the suggestion, I've logged it in dev repo and so we could have the enhancement in the future.

**Comment by JohnHasthorpe** [comment]
Closing issue
