### ISSUE TITLE
Launching Survey123 Connect via the Design tab creates a duplicate survey in Connect

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#126]
**Application:** Connect | Website 

**Operating System:** Win 10

**Browser:** Edge

**Error Description:** 

**How to reproduce:** Create a survey from Connect > publish. Navigate to the Survey123 website, open the survey and click the Design tab. It will ask you to launch Connect, and the following message appears:
![image](https://user-images.githubusercontent.com/22916127/39376763-ab321eb4-4a07-11e8-83bf-0d3d6d06e78b.png)

When I click Yes, a duplicate survey is added. This only happens once, so it will not continue creating duplicates after the first time.

![image](https://user-images.githubusercontent.com/22916127/39376817-d72efc30-4a07-11e8-91d2-37ac505a9cb4.png)

**Have you tested with another survey?** Yeah, tested with 2

**Comment by colinlawr** [comment]
To add on to this issue:

I deleted the duplicate survey from Survey123 Connect and then tried to download again from the Website and was presented with the error, "Item does not exist of is inaccessible."
![download_error](https://user-images.githubusercontent.com/15009559/39377911-ab504a52-4a0b-11e8-9fbc-f1fbfee5852a.PNG)

**Comment by JohnHasthorpe** [comment]
Closing issue (issue resolved)
