### ISSUE TITLE
Audio attachment is missing from Individual Response

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#128]
***Application*** : Website

If you have an audio question, an audio attachment is submitted with the survey. But currently, it looks like there is no way to retrieve the audio attachment without navigating to ArcGIS Online.

Spoke with James - sounds like the audio attachment used to appear in the Individual Response, but got removed at some point.

**Comment by zhif7782** [comment]
@sbubka94 thanks for the feedback, this should be a regression issue we're trying to fix it in 2.8 release.

**Comment by JohnHasthorpe** [comment]
Closing issue (issue addressed)
