### ISSUE TITLE
holistic website 2.8 - editing a Survey in Connect defaults to download and overwrite

### ISSUE THREAD

**Issue by Temmermand** [tedrick/Survey123-Testing#129]
**Application:** Connect | Website 

**Device:** Dell Latitude laptop

**Operating System:** Windows 10 Enterprise

**Browser:** Version 65.0.3325.181 (Official Build) (64-bit)

**Error Description:** Is the survey from ArcGIS Online supposed to download and overwrite the local survey in Survey123 Connect by default?

**How to reproduce:** Use website 2.8. Click edit on a Survey that was published from Survey123 Connect. Survey123 Connect (version 2.7.72) opens with a warning to download and overwrite the Survey. Should this error appear if the Surveys are the same? Should this error appear if the local version was a newer draft of the Survey hosted on ArcGIS Online?

**Have you tested with another survey?** No

![image](https://user-images.githubusercontent.com/38793244/39377828-65fb2774-4a0b-11e8-9340-6f72d912e802.png)

**Comment by Temmermand** [comment]
After I download and overwrite, it doesn't. It just creates a second survey, and neither one opens.

![image](https://user-images.githubusercontent.com/38793244/39378219-a0330b7c-4a0c-11e8-8d21-1a1aa66e93b9.png)

**Comment by JohnHasthorpe** [comment]
Closing issue
