### ISSUE TITLE
CHALLENGE: Autosave

### ISSUE THREAD

**Issue by JohnHasthorpe** [tedrick/Survey123-Testing#13]
**Context:** We hope that this does not ever happen - but if your app or device crashes, you probably don't want to have to re-enter answers for the form you were in the process of completing (especially if it was a big form).  So at 2.4, on restarting the app after a crash, you will be provided with the option to re-load the data from a recovery file (autosave.json). 

Behind the scenes, when you complete a question and then move onto the next – the change in focus will trigger all previous answers to be written to the recovery file. By default this happens for all questions, but you can choose to specify which questions will trigger a save by setting the questions bind::saveIncomplete parameter to be true. 

A known limitation is that saveIncomplete can not be applied to geopoint questions.

**Challenge:** We would like to get this functionality tested using as many different surveys as possible. So the idea is for you partially complete surveys and simulate crashes, and then verify that the data is being recovered when you re-open the app.

Using one of your existing surveys, or one selected from the templates or community in connect, complete the following steps:

DEFAULT TESTS
- In Connect, publish the survey
- Download the survey to the field app
- Enter data into some or all of the questions (you may include gaps)
- Crash/close the app (at the OS level)
- Reopen the app  - you should see a message giving you the option to recover your survey.
- On accepting, the form should open and be populated with all values entered for questions up to (but not including) the last question you completed.
- Repeat the data entry/crash sequence a number of times, with different combinations of questions completed to ensure the behaviour is consistent.

BINDING TESTS
- Back in connect, open the survey xls for the survey used in the tests above.
- Add the _bind::saveIncomplete_ column to the survey and set the value to **TRUE** for one or more of the survey questions (excluding the geopoint). Questions with a value of true will trigger an autosave on change of focus.
- Republish the survey, and re-download to the field app.
- Enter data into some or all of the questions (you may include gaps)
- Crash/close the app (at the OS level)
- Reopen the app  - you should see a message giving you the option to recover your survey.
- On accepting, the form should open and be populated with all values entered for questions up to (but not including) the last question that had a bind::saveIncomplete value of true.
- Repeat the data entry/crash sequence a number of times, with different combinations of questions completed to ensure the behaviour is consistent.

**Questions:**
- Does this approach to recovery meet your needs? Please provide feedback either way.
- Is the ability to control when the save happens (through saveIncomplete) useful?
- Did you experience any real crashes?

**Comment by tedrick** [comment]
Sarah, Kanchana

**Comment by bethanyw** [comment]
I tested this a few times on the Windows field app and it seemed to work flawlessly. I think our customers will love this.

**Comment by JohnHasthorpe** [comment]
2.4 testing complete
