### ISSUE TITLE
Unable to select 'Done' on Android keyboard when inputting integer values

### ISSUE THREAD

**Issue by colinlawr** [tedrick/Survey123-Testing#130]
**Application:** Connect | Field App | Website | On Premises | _Other_
Field App (Alpha 3.0.12)

**Device:** _Important for Field App especially_
Samsung Galaxy s7 edge

**Operating System:** _Provide version, i.e., Android 5.0.1_
Android 7.0

**Browser:** _For the website_
n/a

**Error Description:** 
n/a

**How to reproduce:**
1. create a survey from Connect with an integer question and publish
2. open survey on device and enter an integer value
3. click done and the keyboard will remain, the integer value in the field will turn red
4. you can hit the back key to close the keyboard and the value will remain

**Have you tested with another survey?** 
Yes, one within nested repeats and then a fresh survey with only an integer question

Its import to note that this caused issues with the nested repeats form because I was using a repeat count based on an answer to an integer question. It would not see the integer entered as a valid value and therefor the nested repeat section would not appear.

**Comment by colinlawr** [comment]
![screenshot_20180427-153843](https://user-images.githubusercontent.com/15009559/39387980-af36eaec-4a31-11e8-939d-a93ab69b1c49.png)

**Comment by JohnHasthorpe** [comment]
Closing - internal issue: https://devtopia.esri.com/Melbourne/Survey123/issues/2531
