### ISSUE TITLE
FEEDBACK: Survey123 Architecture changes

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#131]
We are looking to change how we serve some components of the Survey123 website.  Please access https://survey123qa-cf.arcgis.com and provide any feedback on the website functionality compared to survey123.arcgis.com

**Comment by sbubka94** [comment]
There is no Settings tab on survey123qa-cf.arcgis.com

Checked survey123qa-cf.arcgis.com/version.txt and it appears to be at build 2.8.39

**Comment by colinlawr** [comment]
'File upload' question type missing from selectable Common Questions list

**Comment by colinlawr** [comment]
Received error when attempting to publish survey. I created the same survey in survey123dev.arcgis and it published successfully. 

It included 3 question types: singe choice grid, rating, and signature. I had also modified the schema by changing some name values. 

![publish_error](https://user-images.githubusercontent.com/15009559/39384631-5eed1084-4a22-11e8-807f-a09d3343d1de.PNG)

**Comment by sbubka94** [comment]
If the survey contains audio attachments, a custom report cannot be generated. This is also reproducible in 2.7 and dev 2.8.

A bug is logged on the Salesforce side from Support. Just wanted to bring up that it is still reproducing in qa-cf environment

**Comment by colinlawr** [comment]
Opening the data tab for a survey shared with me presents the error below. I can open successfully on the survey123dev page. It should be noted this survey uses nested repeats.

![data_error](https://user-images.githubusercontent.com/15009559/39386839-56e3b074-4a2b-11e8-9f78-10c23d5f4804.PNG)

**Comment by zhif7782** [comment]
@sbubka94 @colinlawr Settings page in the website, as well as File Upload question type in Design page, are both internal features now, which can only be accessed from the two domains: survey123dev.arcgis.com and survey123qa.arcgis.com. It's an expected result currently.

**Comment by zhif7782** [comment]
@colinlawr the error message "The survey element named 'generated_note_surveyDescription' has no label or hint" indicate that one of your question is missing the question label, you may want to have a check before publishing.

**Comment by JohnHasthorpe** [comment]
Closing issue - no repro case provided
