### ISSUE TITLE
Enhancement: Add Minimum version to form metadata

### ISSUE THREAD

**Issue by mgayheart1** [tedrick/Survey123-Testing#132]
**Application:** Connect | Field App | Website | On Premises | _Other_
Connect 3.0 /Field App 2.7

**Error Description:** 
Right now there is no check for version compatibility.
**How to reproduce:**
Example of where this would be useful:
1. Publish a survey in Connect 3.0 using new feature such as nested repeats.
2. Fill out survey in Field App 2.7 and try to submit.
3. Process hangs.

Instead, if Connect added metadata in form to say min_version=3.0 and Field App 2.7 (obviously can't change this behavior, but could for the future) read that metadata and didn't allow user to fill it out before upgrading to 3.0, then this wouldn't happen.

The trick would be adding logic in Connect to know when new features are being used and setting the min version accordingly.
**Have you tested with another survey?** 
No.

**Comment by JohnHasthorpe** [comment]
Internal issue: https://devtopia.esri.com/Melbourne/Survey123/issues/2540
