### ISSUE TITLE
Unable to see results for nested repeat questions

### ISSUE THREAD

**Issue by asester1** [tedrick/Survey123-Testing#133]
**Application:** Connect

**Device:**NA

**Operating System:** Windows 10

**Browser:**Chrome

**Error Description:** When analyzing the response to my survey, all of the nested repeat questions show 'There are no answers to this question yet.' 

**How to reproduce:** Create Survey using Survey123 Connect v3.0.14 with nested repeats. Submit survey responses. Mange in Survey123 website. Select the Analyze tab. results for the first repeat question are displayed. (Survey 'Form 3' - Desk Information (repeats) shows responses to this question; Desk Information (repeats)>User Information (repeats) all of these questions display 'There are no answers to this question yet')

**Have you tested with another survey?** yes (my surveys Form, 2, Form 3, and Form 4)

**Comment by zhif7782** [comment]
Hi @asester1 , can you please share the XLSForm to the survey or share the result viewer publicly for us to investigate (Collaborate -> Viewer, check Everyone (public, then sharing the link here) ?

**Comment by JohnHasthorpe** [comment]
No repro case provided. Closing issue for next round of Holistics.
