### ISSUE TITLE
Unable to submit responses to survey questions that have geopoints in the nested repeats

### ISSUE THREAD

**Issue by asester1** [tedrick/Survey123-Testing#134]
**Application:** Survey123 web app

**Device:**NA

**Operating System:** Windows 10

**Browser:** Chrome

**Error Description:** "Failed to submit'

**How to reproduce:** Create survey in Connect with geopoint question within a nested repeat. 

**Have you tested with another survey?** No, tested multiple scenarios within the survey (my survey titled Form4) Only unable to submit response when there are multiple geopoints in the nested repeat. With one geopoint in the nested repeat I am able to submit the response.

**Comment by zhif7782** [comment]
Hi @asester1 , thanks for the feedback. 

Unforturnately, submitting a survey which has nested repeats was just supported in field app but not in the web form yet, I will raise your voice in the feature in our backlog.

**Comment by JohnHasthorpe** [comment]
Webform issue: https://github.com/ArcGIS/survey123-webform/issues/378
