### ISSUE TITLE
FEEDBACK: Reverse geocoding and map coordinate transformations

### ISSUE THREAD

**Issue by phil-wilson** [tedrick/Survey123-Testing#137]
The pulldata() function has been significantly enhanced by adding extra properties into the pulldata("@geopoint") expression.  Starting with version 3.0, you can perform reverse geocoding on an existing geopoint and also perform map coordinate format transformations. 

- **Reverse geocoding** is very handy when you want to precompute the address of a location, its postal code etc.   Using reverse geocoding against your own custom asset locator, you can also precompute the unique identifier of an asset based on the user's location.   This is a very relevant enhancement that will boost the productivity of field users and help with user input validation. As of version 3.0, reverse geocoding is only supported in the Survey123 field app, and we are working to support it in our Survey123 web in our next update.

- **Map Coordinate Transformations**: A new extension to the pulldata function lets you extract MGRS, USNG and other common map coordinate formats from a geopoint. This is useful when you want to persist the coordinates of an event as a GIS attribute, using different coordinate notations.  For example, the Search and Rescue community often use coordinates expressed in USNG format, MGRS is a widely accepted standard for military use and UTM coordinates are used globally.  Map coordinate transformations are supported in both the Survey123 Web and Field apps and work while online and offline.

Documentation can be found here: http://doc.arcgis.com/en/survey123/desktop/create-surveys/geopoints.htm#ESRI_SECTION1_48C66C92612A414F97F5D843DE8C909C

Example survey: [Reverse Geocode.xlsx](https://github.com/tedrick/Survey123-Testing/files/2326081/Reverse.Geocode.xlsx)

**Comment by phil-wilson** [comment]
We want your feedback on reverse geocoding and coordinate transofrmations, try the following:

- Design and publish a survey from Connect (see above example for ideas)
- Include different question types, calculations, defaults, constraints etc in your survey
- Enable the Inbox to test your survey and when editing existing surveys
- Open your survey in the field app and test collecting new surveys, saving to drafts, outbox, sent folders and then also test editing via the inbox, drafts and sent.
- View your submitted surveys on the Survey123 website and AGO.

**Comment by JohnHasthorpe** [comment]
Gee
Paul
Daniel
Neale
Ryan

**Comment by Hutcho3151** [comment]
The reverse geocode wouldn't work in Connect (Beta) until logged in due to the small costs of the service.
It worked well, even in quite remote locations and the tools with the map screen are useful.

**Comment by JohnHasthorpe** [comment]
Enhancement created to update the sample to provide feedback to the user, as to whether they are signed in.
