### ISSUE TITLE
FEEDBACK: GNSS (1) - our form, our feature service, our webhook

### ISSUE THREAD

**Issue by marikavertzonis** [tedrick/Survey123-Testing#138]
This scenario requires the least amount of configuration and allows you to focus on trying out GNSS receivers with your device.

1) connect a GNSS receiver to your device. Follow steps on EAC https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={9AEF4173-09CC-4134-9811-0AA2B3B405DD}

2) launch this url - https://arcg.is/9SnDi - on your device to download the survey 

3) go outside and collect the 3 points described in the survey

4) send the records from the field (if you have data connection) or send upon return to the office
    - see the notification emails in the meeting room
    - take a look at the points collected in the feature service here http://www.arcgis.com/home/item.html?id=0921493eec9844b4affcf02f1e9c2200

**Comment by JohnHasthorpe** [comment]
- Britany
- Chris
- Gareth
- Paul

**Comment by JohnHasthorpe** [comment]
No feedback - closing
