### ISSUE TITLE
CHALLENGE: Android Location Response time and Accuracy

### ISSUE THREAD

**Issue by JohnHasthorpe** [tedrick/Survey123-Testing#14]
#**Context:** Previous versions of the field app did not use the position provided by the network (i.e. WIFI or cellular) if a GPS signal was not available. This would prevent you from getting a location when operating indoors. We have fixed this and want you to help verify it works on a range of devices.

**Challenge**: Using any survey that contains a geopoint question:
- Make sure that field app is not running on your device (kill it)
- Move to a location that has no GPS (inside a basement or elevator is ideal) - the sky should not be visible.
- Make sure your location service is running and you have network/WIFI coverage
- Open the app and a survey that contains a Geopoint question
- Click on the Geo-point question and verify (despite lack of GPS) that 
        --your location has been updated 
        --your location is accurate . 
 You may have to click on the location button to prompt an update.

**Questions**
- Was the location update immediate?
- Do you have a use case for using the field app indoors?

**Comment by tedrick** [comment]
Colin

**Comment by colinlawr** [comment]
At this time I am unable to access a location with minimal to no GPS coverage. I will test again when back to the fortress of building V. 

However, through multiple tests, it seems it takes roughly 2-3 seconds each time to get a location fix. This is an improvement from previous versions.

Potential use cases for indoor field app usage would be for warehouse or distribution center maintenance or inventory. There would be of course be potential limitations in multi-story buildings. 

Colin

**Comment by JohnHasthorpe** [comment]
2.4 testing complete
