### ISSUE TITLE
FEEDBACK: Variable Replacement in Labels (Question Piping)

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#142]
In the upcoming release of Survey123, we have added the ability to utilize variable replacement in the label column of your surveys.

So, for instance, if you have a text question with the name 'applicant' and in a subsequent 'note' question, you want to thank the applicant for filling out the form, you can enter the following into the label column...

Thank you for sharing your information, ${applicant)!

Please try the following and give feedback

* Publish the attached XLSForm using Survey123 Connect and download to field app.  Verify that the values in the label are appropriately displayed
* Practice implementing Label Replacement (Question Piping) on your own survey(s)

Label Replacement Example: [Label_Replacement.xlsx](https://github.com/tedrick/Survey123-Testing/files/2330588/Label_Replacement.xlsx)

**Comment by JohnHasthorpe** [comment]
- Jamie
- Richard

**Comment by J8L** [comment]
@JohnHasthorpe  Passing URL (arcgis-survey123://?itemID=5862fd859a4a4da7b32d32c7ae7156ba&field:segment={SEGMENT_NM}&field:site={SHORT_NM}) then using inputs to pull coordinate data from a .csv in the Media folder. Correct location resolves, however the device GPS location then overwrites the calculated location (concat(number(pulldata('PLN_Surveillance_Points', 'LAT', 'SHORT_NM', ${site})),' ', number(pulldata('PLN_Surveillance_Points', 'LON', 'SHORT_NM', ${site}))))

**Comment by BrittanyDahl** [comment]
I published the example, and tested using it with the inbox and it worked as expected 👍

**Comment by BrandonArmstrong** [comment]
Thanks for testing @BrittanyDahl 

Closing out this issue
