### ISSUE TITLE
BUG: Drag to create a survey from a spreadsheet with a dot in the name breaks Connect

### ISSUE THREAD

**Issue by paul-gpsit** [tedrick/Survey123-Testing#146]
**Application:** Connect

**Device:** PC

**Operating System:** Windows 10 

**Error Description: After trying to create a survey from a spreadsheet with a dot in the name, clicking on any survey from the main menu attempts to download it, regardless of whether it's already downloaded.

**How to reproduce:
Start with a spreadsheet that has a dot in the name. e.g. "Street.Lights.xlsx". Drag and drop in Survey Connect to create a survey. The survey 'creates' locally, but cannot be published.
Now fixed the spreadsheet name e.g. rename to "Street Lights.xlsx". Drag and drop and then publish the survey.
Everything works from the survey perspective, but in Survey Connect on this machine, now the Connect app has multiple folders with the same named survey and it gets confused, leading to perpetual downloads.

**Comment by phil-wilson** [comment]
We already have an open issue for using periods in Excel files and opening in Connect. Existing issue #1438 has been updated with comments. This will added to backlog to be addressed in future.
