### ISSUE TITLE
Device GPS overwrites calculated location

### ISSUE THREAD

**Issue by J8L** [tedrick/Survey123-Testing#147]
**Application:** Connect
**Device:** iPad
**Operating System:** 11.4.1

@JohnHasthorpe  Passing URL (arcgis-survey123://?itemID=5862fd859a4a4da7b32d32c7ae7156ba&field:segment={SEGMENT_NM}&field:site={SHORT_NM}) then using inputs to pull coordinate data from a .csv in the Media folder. Correct location resolves, however the device GPS location then overwrites the calculated location (concat(number(pulldata('PLN_Surveillance_Points', 'LAT', 'SHORT_NM', ${site})),' ', number(pulldata('PLN_Surveillance_Points', 'LON', 'SHORT_NM', ${site}))))

**Comment by JohnHasthorpe** [comment]
Not replicated in 3.0.149
Not replicated in 3.1.37
Replicated in 3.2.47

Needs looking into
