### ISSUE TITLE
ENH: Moving Survey123 Connect Surveys between Portals/AGOLs

### ISSUE THREAD

**Issue by BrittanyDahl** [tedrick/Survey123-Testing#149]
**Application:** Connect
**Device:** Windows 10 Laptop, Browser: Chrome
**Browser:** Chrome (latest version) 
**Error Description:** 

I am unable to migrate or move Survey123 Connect Survey and Web App forms between Portals/AGOLs using AGO Assistant (https://ago-assistant.esri.com/).
![ago_assistant_survey123](https://user-images.githubusercontent.com/20454586/44830171-c57f6380-ac63-11e8-9ac4-42676fc4cc35.jpg)

The forms are greyed out in AGO Assistant, so I seem to be unable to move them over to create a copy. It is possible to create copies inside Connect or Survey123 Web App in a single AGOL or Portal, but not for moving between different ones (such as Dev to Test to Production). 

**How to reproduce:**

Navigate to AGO Assistant (https://ago-assistant.esri.com/).
Sign in with an AGOL or Portal account. 
Select I want to: "Copy To"
Try to copy across a Survey123 Form

**Have you tested with another survey?** 
Yes

**Comment by JohnHasthorpe** [comment]
Moved to github repo as an area for research
