### ISSUE TITLE
CHALLENGE: Editing with repeats

### ISSUE THREAD

**Issue by JohnHasthorpe** [tedrick/Survey123-Testing#15]
**Context:** If you have repeats in your surveys, you can now view and edit them through the sent box and inbox. From 2.4 you are able to add new repeats and update existing ones, and on resubmitting the survey, any updates you make will be sent the underlying feature service. 

**Challenge:** Using your own survey(s) or sample/community surveys in Connect, that include repeats, attachments, and have the inbox enabled (ideally with data sets larger than 2000 features). Do the following:

GENERAL EDITING
- Attempt to edit existing survey data in the default configuration (i.e no parameters applied to the repeat). 
- Test both the sent box and inbox by attempting to update questions and attachments in both the feature layer and repeat, and then resubmit the survey.
Expected results:
    --You should be able to add new repeats only (not update) and edit those that have not yet been submitted.
    --Previously submitted repeats should not be visible in the Inbox. 
    --Previously submitted repeats should be visible, but not editable in the Sent box

ATTACHMENTS
- Test editing of attachments within repeat through both sent box and inbox by attempting to update them (i.e photos, signatures, draw, audio)
Expected results:
    --Sent box - Attachments should be visible but not editable
    --Inbox - Attachments should not be visible and not editable

DELETION
- Attempt to delete a repeat record.
Expected result: 
    --Deletion should only be possible for records that have not yet been submitted to the server.

**Questions:**
1) Do the default editing settings work for you (i.e. only add new repeats)
2) Is the ability to not view or edit attachments an issue?
3) Will the implementation support new workflows in your organisation and if so what are they?
4) Is the syntax for the parameters flexible and intuitive enough?

**Comment by tedrick** [comment]
Jess, Christian, Rose, Kanchana, Justin, Sarah

**Comment by kunjoo91** [comment]
Editing not working for one of my forms. Form and feature service shared with **Survey123 Product Team**  group in HAPS org.

**Comment by cwhitehe** [comment]
I have not had any issues with editing. The syntax is easy to understand, and the workflow is easy to follow.

**Comment by JohnHasthorpe** [comment]
2.4 Testing Complete - Closing
