### ISSUE TITLE
ENH: Improvements to the inbox view

### ISSUE THREAD

**Issue by BrittanyDahl** [tedrick/Survey123-Testing#150]
**Application:** Connect and Field App
**Device:** iOS
**Error Description:** 

Ideas relating to improvements to the inbox view:

I work with organisations that would like:
- The “map” view in the inbox mode to be the default view, rather than “list” view. Could this be a new option?
- The Inbox mode not limited to more than 2,000 features upon downloading

The organisations have various surveys that have more that 2000 features in the inbox that they wish to download and take completely offline for field work. However, they currently have to use a work around, where they go to the map view, then zoom to the location they might plan to visit, then download for offline. Then go back online if they need to download any other features. 

**Have you tested with another survey?** 
I can provide survey examples, but most are on an internal Portal

**Comment by JohnHasthorpe** [comment]
Linked internal issues: 1574, 2545
Closing
