### ISSUE TITLE
Cannot add .PDFs through internet browsers - if a survey was initially published through Connect 

### ISSUE THREAD

**Issue by g8f** [tedrick/Survey123-Testing#151]
**Application:** Connect | Field App | Website | On Premises | _Other_

**Device:** _Important for Field App especially_

**Operating System:** _Provide version, i.e., Android 5.0.1_

**Browser:** All internet browsers.

**Error Description:** 

**How to reproduce:**

**Have you tested with another survey?**

**Comment by JohnHasthorpe** [comment]
@g8f This is possible:

The default MIME types supported by the ```file``` question are found in the ```mediatype``` attribute of the upload control - 

```xml
<upload mediatype="text/plain,application/pdf,application/vnd.ms-excel,application/msword,text/richtext,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/zip,application/x-zip,application/x-zip-compressed" ref="/Upload_Types/pdf">
```

This can be modified in an XLSForm via the ```body::mediatype``` column - e.g.

![db4dc952-cacf-11e7-832b-86c7f564d882](https://user-images.githubusercontent.com/24929507/44893274-a64d0880-ad2d-11e8-9d59-055a1bc13407.png)


[File_attach.xlsx](https://github.com/tedrick/Survey123-Testing/files/2338809/File_attach.xlsx)
