### ISSUE TITLE
ENH: Improvements to Survey123 Connect Style Options

### ISSUE THREAD

**Issue by BrittanyDahl** [tedrick/Survey123-Testing#152]
**Application:** Connect
**Operating System:** Windows 10
**Browser:** Chrome (latest version)
**Error Description:** 
Ideas for Improvements to Survey123 Connect Style Options:

It would be great to make it easier to change the “surround colour” for Survey123 Connect Forms, rather than editing the info file. Making this part of the UI would be excellent.

It would also be great to make it easier to change the Survey header to be a URL image in Connect. This is functionality in the Web App, but doesn't appear to be supported in Connect. It is possible to add an image as a note, but a URL does not appear to work. 

**How to reproduce:**
**Have you tested with another survey?** 
I can supply .xlsx forms with the issues above.

**Comment by JohnHasthorpe** [comment]
Raised as an internal issue for consideration: 2543
Closing this issue
