### ISSUE TITLE
No 'Internet Required' warning when creating a new survey, just hangs

### ISSUE THREAD

**Issue by ccounsell** [tedrick/Survey123-Testing#153]
**Application:**
Connect 3.2.35

**Operating System:** 
Windows 10

**Error Description:** 
Clicking 'New Survey' without an internet connection leaves Connect loading. There is no warning stating that an internet connection is required.
Understand that the API is required to convert the xlsform to a survey. It's not clear to the user.
In this instance I wanted to work on an XLSForm without internet. Looking for possibility of not having a loading screen hanging (warning message) and XLSForms templates saved to system.

**How to reproduce:**
Turn off Internet on device, open Connect, click 'New Survey'.

**Comment by JohnHasthorpe** [comment]
The Internet is a requirement for publishing surveys and is documented in the system requirements.
If this is an issue, then install the on-premises version of the API (this is available through EAC).

Closing issue.
