### ISSUE TITLE
FEEDBACK: Predictive text selection

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#154]
With 3.1, predictive text (auto-correct) has been disabled by default for text questions in Android.

3.1 also introduces 2 new appearances to control predictive text behavior on all platforms.
- predictivetext - manually enable predictive text
- nopredictivetex - manually disable predictive text

**Comment by tedrick** [comment]
Francisco Andrade
Bill

**Comment by fandrade86** [comment]
[Predictive text.docx](https://github.com/tedrick/Survey123-Testing/files/2448068/Predictive.text.docx)

Issues:
Scenario: Multiline Text and Predictive text
The textbox does not update to multiline view it stays as single text.

**Comment by JohnHasthorpe** [comment]
Internal issue: https://devtopia.esri.com/Melbourne/Survey123/issues/2639
