### ISSUE TITLE
Feedback: Character counts

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#155]
With 3.1, both the field app and the website now feature character counts on text questions.  These counts are based off of the size of the field (allowable number of characters to submit).

**Comment by tedrick** [comment]
Francisco Andrade

**Comment by tedrick** [comment]
Alex Garrish

**Comment by fcxagerr** [comment]
Survey123 Field App 3.1.92(94)
Device: iphone 7; Samsung Galaxy Tab A3; Samsung Galaxy Tab S3
Operating System: iOS 11.4.1; Android 7.1.1
Browser: Google Chrome 69

Tested field app with differing field lengths both new and from feature services. Character count readout remained consistent with standard entry, special characters, and copy/paste. Counts were consistent between field app and website from the two surveys and workflows I tested.

Noticed the count turned red at 25% of the total, users will like that.
