### ISSUE TITLE
FEEDBACK: Alerting system

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#157]
With 3.1, a new alerting system is introduced to the field app, initially relaying location system issues (no location found, GPS disabled, connection lost, etc.).  Please try to cause issues with location and note feedback on the resulting alerts.

**Comment by sbubka94** [comment]
Should the satellite symbol disappear if I do not have the "detect my location" button highlighted? The satellite symbol never seems to go away on my device.

![image](https://user-images.githubusercontent.com/22916127/46503551-feb96f00-c7df-11e8-8fc5-2b21c2b05f70.png)

![image](https://user-images.githubusercontent.com/22916127/46503556-02e58c80-c7e0-11e8-9f31-87bfeddb81c1.png)

![image](https://user-images.githubusercontent.com/22916127/46503559-08db6d80-c7e0-11e8-9cfc-57230461a874.png)

**Comment by JohnHasthorpe** [comment]
@sbubka94 please share the device you are using

**Comment by JohnHasthorpe** [comment]
@sbubka94 - This is because of the connection mode you are using. If you use on demand - you will not see this. Closing this one off.

**Comment by sbubka94** [comment]
Hi @JohnHasthorpe. I was under the impression I was using "on demand" by selecting "as needed." What option should I select if I don't want to constantly see the satellite?
