### ISSUE TITLE
FEEDBACK: Feature Report Service

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#161]
With 3.1, we've made improvements to the Feature Report service that should reduce the number of error/time-outs that occur.  Please try to generate reports with your existing templates (that have both worked and not worked) and provide feedback.

**Comment by tedrick** [comment]
Christian

**Comment by fandrade86** [comment]
I was able to download more than 15 reports at a time but not able to download more than 30. So far testing has been successful.

Future request: It would be nice if the zip file would automatically download or display for the user to download. Current process the use has to login to arcgis online to download the file.

**Comment by fandrade86** [comment]
After selecting the first survey's report and I attempted to view another report, it took over 3 minutes to update the report page. attached is the XLS form.
[Vegetation Maintenance Job Request v2.xlsx](https://github.com/tedrick/Survey123-Testing/files/2448252/Vegetation.Maintenance.Job.Request.v2.xlsx)
