### ISSUE TITLE
FEEDBACK: The Settings page in the Field App has been redesigned

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#162]
The Settings page has been redesigned with version 3.1

Beyond taking a look letting us know what you think, **test out the ability to change the app's font and provide feedback**.

**Comment by tedrick** [comment]
Nick
Sarah

**Comment by sbubka94** [comment]
Very exciting that you can change fonts! Is this determined by the fonts installed on the machine? Is there a way to limit the fonts or is there a specific location we're referencing these from? For example, I can't see Windings being of any practical use.

**Comment by nezisk** [comment]
Agreed, many Fonts are not suitable. However, this has always been an issue. Fonts are standard loads and you only use the ones you need for the application at the time.

**Comment by JohnHasthorpe** [comment]
@sbubka94 - Yes the font picker is from the device/OS and fonts cannot be configured from the app.
