### ISSUE TITLE
CHALLENGE: Apply a Custom Theme to your survey using the Web Designer and view in Web App

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#163]
With version 3.1 we are introducing Custom Themes for your surveys.

This means that you can apply different colors, images, and styles to your survey.  Try this out and let us know using the following steps:

1. Navigate to survey123qa.esri.com > login
2. Create New Survey
3. Select 'Appearance' tab 
4. Select Edit theme

Once you have applied colors and images, publish, and then load the web app in one or multiple browsers on your desktop as well as your phone.

**Comment by tedrick** [comment]
Carmen

**Comment by carmencarina1** [comment]
In design- appearance -Layout appearance,  have the capability to save a custom theme to use for future surveys.

**Comment by carmencarina1** [comment]
Design- layout appearance -Edit theme. It would be useful to have a "go to previous option" possible to the last save

**Comment by JohnHasthorpe** [comment]
Internal issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/2925
