### ISSUE TITLE
FEEDBACK: Multiline Text Questions now provide a character count

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#165]
Multiline text questions should now have an indicator in the bottom right corner of the text box, informing the survey submitter of the maximum word count (default is 1000)

Test this out by creating a survey with the Web Designer and inputting text (word count should dynamically be reflected)

Test the reflected behavior within the web browser on your desktop as well as mobile devices

**Comment by tedrick** [comment]
Francisco Andrade

**Comment by fandrade86** [comment]
[TestingOnWindows(Google Chrome).docx](https://github.com/tedrick/Survey123-Testing/files/2447581/TestingOnWindows.Google.Chrome.docx)
[TestingOnWindows(Internet Explorer).docx](https://github.com/tedrick/Survey123-Testing/files/2447582/TestingOnWindows.Internet.Explorer.docx)
[TestingOnWindows(Andriod).docx](https://github.com/tedrick/Survey123-Testing/files/2447583/TestingOnWindows.Andriod.docx)

Issues on Google Chrome and Internet Explorer: 
Scenario: Attempting to submit a survey without any characters and the minimum character count is 1.

Recommendations:
- If the user is required to input a minimum of one character, the user should not be allowed to submit the survey and error should be displayed.
- A character count should be displayed on a single text.
- For both multiline and single text, the user should not be allowed to go over the limit of character whether the limit is set by the max amount of characters or character count limit on the attribute.

Issues on Android Device: 
Scenario: If the user attempts to submit a survey with the more characters allowed than the max and clicks the submit button, the user is unable to edit the text in the multiline field. User must close survey and redo survey.
Scenario: Attempting to submit a survey without any characters and the minimum character count is 1.

Possible Issue: 
- The attribute total character count is 255 but the user is only allowed to input a total of 50 characters max. Should the character count display the max allowed character count as it does on the web version of the survey.

Francisco Andrade

**Comment by JohnHasthorpe** [comment]
https://github.com/ArcGIS/survey123-webform/issues/501

https://github.com/ArcGIS/survey123-webform/issues/502
