### ISSUE TITLE
CHALLENGE: Reverse geocoding in the web form

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#166]
With 3.1, the web form now supports the reverse geocoding functionality is supported in the web form.
Example file
[reverse geocode.xlsx](https://github.com/tedrick/Survey123-Testing/files/2443003/reverse.geocode.xlsx)

Try this or make a survey against other locators (your organization, What3Words, etc.)

**Comment by tedrick** [comment]
Sarah Bubka

**Comment by sbubka94** [comment]
I published the sample Reverse Geocode from Survey123 Connect, then launched the survey at survey123qa.arcgis.com, but I'm receiving errors for each of the JSON values that I want returned.

I am launching the survey, zooming in to a specific location on the map, then choosing YES to run the reverse geocode. 

![image](https://user-images.githubusercontent.com/22916127/46491710-4fb96b00-c7c0-11e8-9aad-b427b9523e3c.png)

Do I have to "accept" the value on the map for this work? Maybe I'm missing something.

**Comment by JohnHasthorpe** [comment]
Fixed form: [rev-geo-web.xlsx](https://github.com/tedrick/Survey123-Testing/files/2449177/rev-geo-web.xlsx) and associated issue: https://github.com/ArcGIS/arcgis-survey123/issues/1008
