### ISSUE TITLE
When Editing the Survey Description in the Web Designer, hint is not present for line placement

### ISSUE THREAD

**Issue by gisguy007** [tedrick/Survey123-Testing#168]
![hint suggestion](https://user-images.githubusercontent.com/43858983/46496401-ceb4a080-c7cc-11e8-8f9c-672fb46ec020.PNG)

**Comment by JohnHasthorpe** [comment]
Internal issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/890
