### ISSUE TITLE
Undesirabale behavior when zooming in on the map

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#169]
**Application:** Field App

**Device:** Windows 10 / iOS 12 (iPhone 7+)

**Error Description:** When zooming in, if you continue clicking the greyed out + button, the map will jump to the right as it thinks you're trying to place the point underneath the +. If the user is a "button masher" they may end up inadvertently moving their point.

http://www.screencast.com/t/dbPn9rW8

**Have you tested with another survey?** Tried multiple surveys

**Comment by BrandonArmstrong** [comment]
Internal Issue: https://devtopia.esri.com/Melbourne/Survey123/issues/2637
