### ISSUE TITLE
FEEDBACK: Feature Report performance

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#171]
With 3.2, we have made several improvements with the feature report service capability in processing long and complex reports.  Please create surveys many pages long, utilizing multiple maps or images and provide feedback on the success/failure.  Test report generation at https://survey123qa.arcgis.com/  If you have a failure, please provide:

- The jobID that failed
- The MS Word template
- The form
- Sample data that caused the crash (for example, by exporting the fGDB of the data)

**Comment by BrandonArmstrong** [comment]
No issues encountered related to performance
