### ISSUE TITLE
FEEDBACK: Working with repeats

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#173]
Working with repeats in a report template can be challenging at times.  Please create a survey with at least one repeat section and include it in a report template.

Areas of feedback:
- How easy it is to get the repeat to display in a manner you want?
- What are difficulties in using repeat sections?

**Comment by BrandonArmstrong** [comment]
@fandrade86 Can you also please upload yhe XLSForm that was used to create the survey?  OR send to barmstrong@esri.com

Thanks

**Comment by fandrade86** [comment]
Attached is the XLSForm

[Vegetation Maintenance Job Request v2.xlsx](https://github.com/tedrick/Survey123-Testing/files/2770886/Vegetation.Maintenance.Job.Request.v2.xlsx)

**Comment by BrandonArmstrong** [comment]
Thanks for feedback

Also unable to open uploaded MS Word doc (generated report).  Noticed that when attempting to create a survey from provided XLSForm there were periods in the name.  Removing these allowed.  Published survey, submitted survey, generated default template and successfully generated and opened a report.

This may need to be looked or more information gathered in a separate discussion.
