### ISSUE TITLE
FEEDBACK - Feature Report Conditional Elements 

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#174]
Elements of a feature report can be shown or hidden conditionally using if statements.

By referencing the documentation linked below, try some of these conditional elements out and let us know how they work.

https://docdev.arcgis.com/en/survey123/browser/analyze-results/featurereporttemplates.htm (Navigate to Conditional Elements section)

**Comment by tedrick** [comment]
Allison, Max
