### ISSUE TITLE
Feedback: Feature Report Syntax Checking

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#175]
In 3.2, the Survey123 website will examine a template when it is uploaded and alert the user to any errors that would prevent publishing.  As you make forms, please note any issues with the syntax checker feedback.  Also, try to create surveys that have deliberate errors and provide feedback on the syntax checker's response.

**Comment by jerjer007** [comment]
Error report. I removed the ending syntax bracket, "}" from all of the questions in my work document and opened the template.  The error popup reported all of the instances of a missing end bracket. Below is the a screenshot of the error popup.
![image](https://user-images.githubusercontent.com/46798139/51351666-6084a880-1a60-11e9-81f7-57b0a3b784e5.png)
So, it would appear that the error popup lists all the errors of the same type.

**Comment by BrandonArmstrong** [comment]
Added to https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3033.  Closing.
