### ISSUE TITLE
FEEDBACK: Feature Report Timeouts

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#176]
In 3.2, the Feature Reports have implemented measures to reduce the number of hung jobs.  If you experience a timeout situation (no change in status for an half hour), please provide:
- the JobID (required)
- the Word template (optional, but useful)
- the Form (optional)
- data used (optional)

**Comment by fandrade86** [comment]
I was able to mass generate reports on Google Chrome, Firefox and Internet Explorer (Document mode: Edge).

When downloading 26 survey reports on Internet Explorer (Version 11.0.9600.19204 CO) the reports started to download but the survey123 website didn't update and advise that the reports had been finished generating. I logged into AGOL and noticed the file was saved on my root folder which is the area I designated for saving the ZIP file.

**Comment by BrandonArmstrong** [comment]
@fandrade86 Thank you for the feedback. Are you able to reproduce this behavior consistently?  I was able to generate 28-30 records several times in IE with expected results.

**Comment by fandrade86** [comment]
Good morning Brandon,
I have now tried it on a different computer and it works. It looks like it is an issue with my IE.

**Comment by BrandonArmstrong** [comment]
Thank you testing @fandrade86
