### ISSUE TITLE
CHALLENGE: Website data view/print template improvements

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#18]
**Context:**  Currently, the Survey123 website does not display questions that are in multiple levels of groups and/or repeats.  This prevents them from being displayed wither in the individual response or in a print template on the Data page.  Additionally, the data page did not read Survey123 map settings, causing the survey viewer to manually zoom to a relevant scale.

**Challenge:** Using the in-development website ( https://survey123dev.arcgis.com ), view your survey123 forms that have nested groups or nested group/repeat structures.  Make sure that all questions are displayed.  Author a print template using all fields and check to make sure the entries are properly substituted in.  For surveys that had map settings set in Survey123 Connect, make sure the map zooms as expected

**Comment by sbubka94** [comment]
On Collaborate tab, > Submit, when checking 'Following Groups:' all of the Groups will stay greyed out and when hovering over the check box, it appears with a red X. But if you click the check box, it works.

(red X does not appear in screenshot but when hovering over any greyed out group, the red X appears)

![image](https://user-images.githubusercontent.com/22916127/29838355-d209426c-8caf-11e7-97fc-937c0378ddb4.png)

**Comment by zhif7782** [comment]
Hi @sbubka94 thanks for the feedback. Seems you encountered a known issue only happens to Edge, where the check box displays in a wrong way but actually behaves correctly. You can use Firefox or Chrome as a workaround.
![abc](https://user-images.githubusercontent.com/7665168/29866301-9c73f15a-8daa-11e7-9568-371670c8255a.gif)

**Comment by JohnHasthorpe** [comment]
2.4 Testing complete - closing.
