### ISSUE TITLE
FEEDBACK: Special Character processing (newline, <>, &)

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#180]
Multiline text questions, either created through adding a Multiline Text question in the Survey123 web designer or using the multiline appearance for a text question in Survey123 Connect, will ignore carriage returns by default, displaying the response in a single block of text. An expression can be used to display the response to the question with carriage returns:

Test this out by inputting an expression like the following within your Feature Report template ${multilinetext1 | appearance:"multiline"}

Keep in mind, this expression will cause errors if not placed on a dedicated line.

Documentation: https://docdev.arcgis.com/en/survey123/browser/analyze-results/featurereporttemplates.htm#ESRI_SECTION1_74E9041F114B4CD9B5FFBA4FF93209FD

**Comment by sbubka94** [comment]
The multiline appearance does not honor the spacing that you set in the Word Doc.

How the data looks in the attribute table:
![image](https://user-images.githubusercontent.com/22916127/51353065-5369b880-1a64-11e9-94ef-5873d3d2beb8.png)

How I set the spacing in the word doc:
![image](https://user-images.githubusercontent.com/22916127/51353070-56fd3f80-1a64-11e9-8fc5-c2eb1a2e9a95.png)

The output I get:
![image](https://user-images.githubusercontent.com/22916127/51353074-5b295d00-1a64-11e9-9d0e-506d5844ca5b.png)

The output I'd expect:
![image](https://user-images.githubusercontent.com/22916127/51353156-9fb4f880-1a64-11e9-881b-f9c02c2e035f.png)

**Comment by BrandonArmstrong** [comment]
@sbubka94   

Thanks for feedback.  Were the 'spaces' added in the report result?

**Comment by sbubka94** [comment]
@BrandonArmstrong I did not add spaces in the report result. In the RESULT, it came with 8 pt spacing. But when I set it in the report TEMPLATE, I put 0 pt spacing.

**Comment by BrandonArmstrong** [comment]
Thank you for feedback
