### ISSUE TITLE
FEEDBACK: Survey123 Connector for Integromat

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#183]
We have in beta a Webhooks connector for the Integromat platform.  Find more information in the [Early Adopter Program](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={39533B7D-7BC0-4206-84CF-8512840CC314}).  Provide feedback on using the connector here.

**Comment by tedrick** [comment]
Peter, Sarah

**Comment by sbubka94** [comment]
Will the Connector become available without the need for an invitation and/or act like the rest of the connectors (searchable)?

**Comment by BrandonArmstrong** [comment]
@sbubka94 Yes, it will.

Thank you for feedback
