### ISSUE TITLE
FEEDBACK: On premises website installation

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#184]
We are beginning retesting of the Survey123 website on-premises installation.

Installation files and instructions can be found at the Early Adopter Community:
- [Documentation](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={069BB65F-7C30-4422-B48A-DA5DFE1859FE})
- [Download](https://earlyadopter.esri.com/project/version/default.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid=beb1a53bed9e470e9b609402a33d970b)

Please try to install (and connect to your ArcGIS Enterprise installation) and provide feedback.

**Comment by tedrick** [comment]
Peter

**Comment by BrandonArmstrong** [comment]
Thank you for feedback

@JohnHasthorpe 

Can you please review and close as you see fit?

**Comment by JohnHasthorpe** [comment]
Thanks - I'll look into the above and create issues as needed.
