### ISSUE TITLE
Item type of batch documents

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#185]
The item type of a batch set of Word documents is set as a `Code Sample`.  It would be much more intuitive to use an item type that reflects the contents (Survey123 Feature Reports).

Raised by @sbubka94

**Comment by Temmermand** [comment]
maybe call it "zip file default"

**Comment by BrandonArmstrong** [comment]
Raised as internal issue:

https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3279

Closing
