### ISSUE TITLE
Enhancement Idea: Automate Triggered Report Generation

### ISSUE THREAD

**Issue by londonhb** [tedrick/Survey123-Testing#186]
I would like to see reports generated automatically (or nightly) that would be triggered using a question within the form.

For example:  I have valve inspection form where field techs are having to inspect valve stations once a year.  They collect all the data in survey123 mobile app and then submit the form for review.   The form now has a status of "Submitted for Review".  Then the manager for reviewing the valve forms would review the submitted form within AGO and approve it by changing the status field to "Approved".  Once the form is changed to "Approved", the report is automatically generated at the end of the day without having to specifically select each "Approved" form to create a report.

Would this be something that could be done with scripting using the API?

**Comment by tedrick** [comment]
Closing - This is now doable in based on the webhooks or Python API for ArcGIS
