### ISSUE TITLE
HTML tags appear in Word Cloud

### ISSUE THREAD

**Issue by Temmermand** [tedrick/Survey123-Testing#187]
**Application:** Website 

**Device:** Desktop - HOLISTIC57 

**Operating System:** Windows 10 Enterprise, Version 1803

**Browser:** Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Error Description:** Word cloud displays HTML tags

**How to reproduce:** Store HTML tags as part of the answer. Complete more than 20 surveys. View word cloud.

**Have you tested with another survey?** No.

![image](https://user-images.githubusercontent.com/38793244/51342103-d4668700-1a47-11e9-898c-9d2dfa789688.png)

**Comment by Temmermand** [comment]
Likewise, three hyphens is treated as a word.

![image](https://user-images.githubusercontent.com/38793244/51342274-59ea3700-1a48-11e9-82a7-0f76a3e6d146.png)

**Comment by Temmermand** [comment]
Also, it is a bit odd that href="https://assets.esri.com/content/dam/esrisite appears as the same size as ArcGIS in the unfiltered word cloud, but disappears in the filtered word cloud.

![image](https://user-images.githubusercontent.com/38793244/51342589-2a87fa00-1a49-11e9-8890-89e2e31e1f4c.png)

![image](https://user-images.githubusercontent.com/38793244/51342640-41c6e780-1a49-11e9-9544-eebee66bf854.png)

**Comment by Temmermand** [comment]
Also, the word "Platform</a>" disappears from the word cloud, even though it still appears in the table.

![image](https://user-images.githubusercontent.com/38793244/51342793-ab46f600-1a49-11e9-9df7-0bd5772de476.png)

**Comment by BrandonArmstrong** [comment]
Thank you for feedback

Logged internal issue.  
https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3254

Closing
