### ISSUE TITLE
Enhancement: Pages navigation in web app

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#189]
**Application:** Website 

**Operating System:** Windows 10

**Browser:** Chrome

Navigating through Pages on the Web App does not provide the same options as the field app. If I have 10 pages and need to navigate quickly from Page 2 to Page 7, I have to use Next until I get to page 7. There should be a way to navigate quickly across pages, like the ability to enter the page number in the field app.

Another note: Do the Next and Back buttons have to do at the bottom of the form? If I have a different number of questions on each page, the Next and Back buttons are located at different spots on the page. So if I'm trying to quickly go through each page and review the content, it would be preferable to be able to keep my cursor in one position on the page and have the ability to simply click to go quickly through each page.

![image](https://user-images.githubusercontent.com/22916127/51342711-6cb13b80-1a49-11e9-99c0-cf0f62614518.png)

![image](https://user-images.githubusercontent.com/22916127/51342716-70dd5900-1a49-11e9-83a0-7d0518bd624e.png)

(^^^ Next and Back buttons are at different spot on web page)

**Comment by BrandonArmstrong** [comment]
Thank you for the feedback.  This has been raised an internal backlog.
