### ISSUE TITLE
CHALLENGE: Answers are removed when deleted 

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#19]
**Context:** When an answered is cleared from a question, that should be interpreted as a deliberate deletion of the answer and an appropriate value sent to update the record.  Prior to 2.4, deletion resulted in no change of answer.

**Challenge:** Set up a survey with editing.  Load data and revise forms. Ensure that when a question has it's answer cleared, the form will remove the answer upon submitting the updated null value.  This should work for all question types.

**Comment by JohnHasthorpe** [comment]
2.4 Testing completed - Closing
