### ISSUE TITLE
Enhancement: add scroller to the survey editor

### ISSUE THREAD

**Issue by maxi6834** [tedrick/Survey123-Testing#191]
**Application:** Web Site

**Device:** Surfacebook

**Operating System:** Win 10

**Browser:** Firefox

**Error Description:** Add first two questions, first a drop down question, then the "image" question. Both are shown on the screen:

![image](https://user-images.githubusercontent.com/5098162/51343858-35905980-1a4c-11e9-888c-869eeb40c7b1.png)

Now add third question of type "Signature". At that point I was confused - my first two questions were gone, and there's no scroll bar that would indicate that my previous questions are just scrolled above.

![image](https://user-images.githubusercontent.com/5098162/51343945-61abda80-1a4c-11e9-9c1b-e67318984a6d.png)

**How to reproduce:**

**Have you tested with another survey?**

**Comment by BrandonArmstrong** [comment]
Thank you for feedback
Added to general enhancements doc
