### ISSUE TITLE
Field App won't pick up basemap selected in Web Editor

### ISSUE THREAD

**Issue by maxi6834** [tedrick/Survey123-Testing#192]
**Application:** Field App + Website 

**Device:** Surfacebook

**Operating System:** Win 10 + Android

**Browser:** Firefox

**Error Description:** Field app always shows StreetMap basemap regardless of what's selected in the survey settings

**How to reproduce:**
Create a survey, add a Geopoint question, and for that question switch the map to Open Streetmap

![image](https://user-images.githubusercontent.com/5098162/51344698-11357c80-1a4e-11e9-840e-9eba5bec61dc.png)

Publish it, download into Field app and try to collect.

The map shows StreetMap, not Open Streetmap

![image](https://user-images.githubusercontent.com/5098162/51344986-b7818200-1a4e-11e9-9a5a-abc9bd7f189a.png)

**Have you tested with another survey?**

**Comment by BrandonArmstrong** [comment]
Thank you for feedback

Converted to internal issue:
https://devtopia.esri.com/Melbourne/Survey123/issues/2896
