### ISSUE TITLE
White text on white background in Location search

### ISSUE THREAD

**Issue by maxi6834** [tedrick/Survey123-Testing#193]
**Application:** Field App 

**Device:** Samsung S7

**Operating System:** latest

**Browser:** N/A

**Error Description:** When entering the location, do search, and start typing "Redlands". It types with while on white background

![image](https://user-images.githubusercontent.com/5098162/51345437-d6344880-1a4f-11e9-90fe-5e26b57c5cbb.png)

**How to reproduce:**

**Have you tested with another survey?**

**Comment by BrandonArmstrong** [comment]
Thank you for feedback

Raised Internal Issue: https://devtopia.esri.com/Melbourne/Survey123/issues/2849
