### ISSUE TITLE
Reports use plain text and do not translate HTML

### ISSUE THREAD

**Issue by Temmermand** [tedrick/Survey123-Testing#196]
**Application:** Website 

**Device:** Desktop - HOLISTIC57 

**Operating System:** Windows 10 Enterprise, Version 1803

**Browser:** Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

Repro steps:
1) store HTML in the question,
2) run a report,
3) see that HTML formatting is not applied. Note sure if this is an enhancement you plan to address.

![image](https://user-images.githubusercontent.com/38793244/51348493-bf91ef80-1a57-11e9-94d8-bbc63d2cf12f.png)

**Comment by BrandonArmstrong** [comment]
Thank you for feedback.  

Added to existing Feature Report Enhancement
https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/2092
