### ISSUE TITLE
Word document names cannot be used twice for report templates

### ISSUE THREAD

**Issue by Temmermand** [tedrick/Survey123-Testing#197]
**Application:** Website 

**Device:** Desktop - HOLISTIC57 

**Operating System:** Windows 10 Enterprise, Version 1803

**Browser:** Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Error Description:** If you try to create two templates with different names from the same word document name, you get an error.

**How to reproduce:**
If you try to save a report template file twice with two different names, you will receive an error if the underlying name of the Word docx already exists.

![image](https://user-images.githubusercontent.com/38793244/51348724-434bdc00-1a58-11e9-8ad2-0d4490891541.png)

**Comment by BrandonArmstrong** [comment]
@Temmermand This is as designed, as the report template names have to be unique.  There is the ability to Edit an existing template as opposed to creating a new one.  

Would a link to documentation or further explanation have been helpful?

**Comment by Temmermand** [comment]
@BrandonArmstrong I don't need documentation. The error message was very clear. 

My issue was more about how it is designed. Let's says I have a homeless survey and a damage assessment survey. 

For the homeless survey, I download the report template file (report_of_results.docx). Then, I configure my report. Then, I upload that report template file (report_of_results.docx) and save it with a relevant name (homeless report).

For the damage assessment survey, I download the report template file (report_of_results.docx). Then, I configure my report. Then, I upload that report template file (report_of_results.docx) and save it with a relevant name (damage assessment report). Only, this time I cannot save "damage assessment report." From a user perspective, I would think that they save error would occur only if I already have a "damage assessment report" and not based on the original name of the underlying *.docx file. I don't recall if the original name of the *.docx file is exposed to the user, so whether or not you can anticipate the error is kind of like hitting a landmine.

**Comment by Temmermand** [comment]
@zhif7782 

I think you are correct. Reusing the name of the .docx with two different surveys should be fine, I ran into that error when building reports for a single survey.

**Comment by BrandonArmstrong** [comment]
Thank you for feedback

Closing this issue at this time with potential for a doc issue being raised regarding the AGOL known limitation of needing unique names for items in the same folder
