### ISSUE TITLE
doc enh: Code sample for conditional report elements would make the structure easier to understand

### ISSUE THREAD

**Issue by allisonmuise** [tedrick/Survey123-Testing#199]
https://doc.arcgis.com/en/survey123/browser/analyze-results/featurereporttemplates.htm

I've read and re-read the conditional section on this page and found myself asking questions in order to understand what was needed. Questions that didn't have obvious answers from the current content included:

1) Misunderstanding the application to entire blocks of responses, not just the question specified in the initial 'if' statement.

2) Not sure how to handle 'if the answer to a multi-select question contains one of these values'

3) How do I create a conditional that allows me to access the value provided for an 'other' response to a multi-select question with an or_other property?

Some brief (but more complete) examples or code snippets here would be very helpful in understanding how to get the most from this capability

**Comment by BrandonArmstrong** [comment]
Thank you for feedback

Linked tointernal issue  https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3282 in event that doc needs to be created
