### ISSUE TITLE
Feedback: Print Templates

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#20]
Please provide feedback on your experience using print template functionality.  Please include the issue you experience, along with the docx template and sample download of the data to match the template.

**Comment by jessnoo** [comment]
In the printed template, i want to see all of my multiple choice question choices, but i only see the answer.

**Goal:** For example, the form that is filled out to submit filed samples for testing looks like:
![sample_submission_goal](https://user-images.githubusercontent.com/6181441/29836573-81ad4566-8caa-11e7-9d7c-73249a383bb9.png)

**Current Result:** in my printed form, it seems like i can only get the answer printed?
![sample_submission_survey123_out](https://user-images.githubusercontent.com/6181441/29836742-f86dd486-8caa-11e7-9e6e-53a2729efb63.png)

sample formal form: 
[Specimen Submision Form.pdf](https://github.com/tedrick/Survey123-Testing/files/1261254/Specimen.Submision.Form.pdf)


print template:
[Specimen_Submission_Form.docx](https://github.com/tedrick/Survey123-Testing/files/1261255/Specimen_Submission_Form.docx)


data sample: 
[S123_75b82caf32744170b38cc0dc0e825962_CSV.zip](https://github.com/tedrick/Survey123-Testing/files/1261257/S123_75b82caf32744170b38cc0dc0e825962_CSV.zip)

**Comment by jessnoo** [comment]
Can I create these print outs in a batch form?  iow, is there is a URL i can put in a pop up or data field that would generate that form from the web map or other app?

or - can I multi select in the data table and get this print out for many records at once?

**Comment by odibie** [comment]
Hello Jess, I will advise shortly.

**Comment by odibie** [comment]
Hello Jess, We currently do not support batch printing but we're currently looking into adding the batch printing functionality.

**Comment by tedrick** [comment]
@jessnoo - Would like print on submission or print at end of work day

**Comment by zhif7782** [comment]
Hi @jessnoo , for the appearance in the template, I think you can achieve the goal by using the additional "selected" method to the question:
![image](https://user-images.githubusercontent.com/7665168/29863723-28a66534-8da3-11e7-8ee3-a53c3b514d48.png)

![image](https://user-images.githubusercontent.com/7665168/29863363-0c076c62-8da2-11e7-852c-4c7b3b2530cb.png)

**Comment by JohnHasthorpe** [comment]
2.4 testing complete
