### ISSUE TITLE
Sharing survey publicly that was created by IWA-authenticated user prompts for authentication (401 challenge)

### ISSUE THREAD

**Issue by PeterKlingman** [tedrick/Survey123-Testing#200]
**Application:** Connect | Field App | Website | On Premises | _Other_

Website

**Device:** _Important for Field App especially_

Dell Desktop Computer - Precision 5820

**Operating System:** _Provide version, i.e., Android 5.0.1_

Windows 10 x64

**Browser:** _For the website_

Chrome, latest

**Error Description:** 

Sharing survey publicly that was created by IWA-authenticated user prompts for authentication (401 challenge)

**How to reproduce:**

Create and publish survey from Survey123 website when signed in as IWA-authenticated user. 
Share the survey with Everyone from the Collaborate Tab. Save the survey and copy the link to the survey. 
Open the survey in an incognito or private window. Notice the 401 authentication challenge for active directory credentials.

**Have you tested with another survey?** 

Yes. Not reproducible with survey created from built-in login.

**Comment by BrandonArmstrong** [comment]
Thank you for feedback

Added to internal issue: https://github.com/ArcGIS/survey123-webform/issues/503

Closing
