### ISSUE TITLE
Saved successfully! sticks around and doesn't go away.

### ISSUE THREAD

**Issue by Temmermand** [tedrick/Survey123-Testing#201]
**Application:** Website 

**Device:** Desktop - HOLISTIC57 

**Operating System:** Windows 10 Enterprise, Version 1803

**Browser:** Google Chrome Version 71.0.3578.98 (Official Build) (64-bit) and IE

**Error Description:** Saved successfully! sticks around and doesn't go away

**How to reproduce:** Save a few different templates, close the Manage templates and the menu sticks around.

![image](https://user-images.githubusercontent.com/38793244/51350087-20232b80-1a5c-11e9-8990-6bcef7da8c68.png)

![image](https://user-images.githubusercontent.com/38793244/51350109-2dd8b100-1a5c-11e9-8cd5-e39d3eb39f10.png)

**Comment by maxi6834** [comment]
Seeing this too

**Comment by BrandonArmstrong** [comment]
Thank you for feedback
Raised internal issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3253

Closing
