### ISSUE TITLE
Can bypass errors when uploading new reports templates just by clicking Save.

### ISSUE THREAD

**Issue by Temmermand** [tedrick/Survey123-Testing#202]
**Application:** Website 

**Device:** Desktop - HOLISTIC57 

**Operating System:** Windows 10 Enterprise, Version 1803

**Browser:** Google Chrome Version 71.0.3578.98 (Official Build) (64-bit) and Firefox and Edge

**Error Description:** Can bypass errors when uploading new templates.

**How to reproduce:**
1. Choose a report template with an error, such as Failed to parse "${email | selected:"value of a choice item"}". Filter " selected:"value of a choice item"" is not supported." 
2. Click Save, and the template saves anyway.
3. close the Report (Beta) window.
4. Saved successfully! sticks around.

![image](https://user-images.githubusercontent.com/38793244/51350536-3e3d5b80-1a5d-11e9-9ac7-9c9e4f438a5d.png)

**Comment by BrandonArmstrong** [comment]
Thank you for feedback

Moved to internal issue
https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3263
