### ISSUE TITLE
Default connection mode for GNSS receivers

### ISSUE THREAD

**Issue by colinlawr** [tedrick/Survey123-Testing#203]
**Application:** Field App

**Device:** Google Pixel 2

**Operating System:** Android 9.0

**Browser:** n/a

**Error Description:** 
When connecting to an external receiver, the default Connection Mode is "as needed". This setting will result in you disconnecting from the receiver once you leave the settings page. I understand and confirmed that it will reconnect when you open an Geopoint question or the settings again, but this can be very confusing to the user when first configuring. This is especially true with receivers that have a screen that would indicate the Bluetooth connection was lost. 

I am sure this is/will be documented in the documentation, but setting the Connection Mode to "When the app is open" as the default I think would result in better user experience.

**How to reproduce:**
1. Connect to an external Bluetooth GNSS receiver
2. From the Menu in the field App, select Settings > Location >Settings next to your receiver > Connection Mode > Set to "as needed"
3. Back all the way out to the Settings or home screen and notice that your receiver is no longer connected via bluetooth

**Have you tested with another survey?** n/a

**Comment by BrandonArmstrong** [comment]
Thank you for feedback

As other Bad Elf worked successfully, will close for now and revisit if encountered again with Google Pixel or Android 9.0
