### ISSUE TITLE
Pinhead cut off in map of report (intermittent)

### ISSUE THREAD

**Issue by RachelGEsri** [tedrick/Survey123-Testing#205]
**Application:** Website

**Device:** PC

**Operating System:** Windows 10

**Browser:** Chrome

**Error Description:** Exported report from website. Blue pinhead is cut off.

**How to reproduce:** Intermittent.

**Have you tested with another survey?** Not yet.

[PinheadCutOffSurvey123ReportIssue.docx](https://github.com/tedrick/Survey123-Testing/files/2770722/PinheadCutOffSurvey123ReportIssue.docx)

[PinHeadCutOffFiddler.zip](https://github.com/tedrick/Survey123-Testing/files/2770725/PinHeadCutOffFiddler.zip)

**Comment by BrandonArmstrong** [comment]
Thank you for  the testing and feedback

Raised internal issue
https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3251

Closing
