### ISSUE TITLE
Ugly error message

### ISSUE THREAD

**Issue by Temmermand** [tedrick/Survey123-Testing#206]
**Application:** Website 

**Device:** Desktop - HOLISTIC57 

**Operating System:** Windows 10 Enterprise, Version 1803

**Browser:** Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

Repro:
1) generate a report and save it as an item.
2) go into ArcGIS Online and delete that item.
3) try to download that report through survey123.
4) see ugly error message.

![image](https://user-images.githubusercontent.com/38793244/51351543-fa982100-1a5f-11e9-92a0-afea3b38871f.png)

![image](https://user-images.githubusercontent.com/38793244/51351572-113e7800-1a60-11e9-8e29-8447a71d53c7.png)

![image](https://user-images.githubusercontent.com/38793244/51351599-261b0b80-1a60-11e9-9c3d-ea0ca7a6a8e4.png)

**Comment by BrandonArmstrong** [comment]
Thanks for feedback
