### ISSUE TITLE
Wording for absent questions on a Page is odd

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#207]
**Application:**  Website

**Browser:** Chrome

**Error Description:** 
When there are no questions present on a Page, it states the following:
![image](https://user-images.githubusercontent.com/22916127/51352194-c4f43780-1a61-11e9-880d-cbd2acdda52f.png)

"The group does not have any question."

"Group" likely wouldn't register with a standard user. I know this is not a typical use case since there should always be at least one question on your page, but it does allow you to publish this way. So in the event there are no questions on a page, I'd expect a message like:

"This survey page does not have any questions."

**Comment by zhif7782** [comment]
Hi @sbubka94 ,
Thanks for the feedback, it will be fixed in the next 3.3 release.
