### ISSUE TITLE
Unable to create conditional display in report for select_multiple question

### ISSUE THREAD

**Issue by allisonmuise** [tedrick/Survey123-Testing#208]
**Application:** Connect | Field App | Website | On Premises | _Other_
website

**Browser:** _For the website_
chrome
**Error Description:** 
Survey contains a select_multiple question. Each choice causes additional questions to appear. Ideally, the report will include only the questions/responses for the selected choice(s)
I provided a single response to have the simplest test.
The questions/responses in the conditional section do not display.

**How to reproduce:**
Survey question:
![1-17-2019 2-05-35 pm](https://user-images.githubusercontent.com/2752195/51352314-156b9500-1a62-11e9-99ca-210d5507a77a.png)

Question in XLSX:
![1-17-2019 2-06-28 pm](https://user-images.githubusercontent.com/2752195/51352295-0b499680-1a62-11e9-85ea-08b809c04571.png)

Choice list showing names/values:
![1-17-2019 2-06-05 pm](https://user-images.githubusercontent.com/2752195/51352300-0e448700-1a62-11e9-8ae6-b6b32ffd7a11.png)

Print showing single response to question:
![1-17-2019 2-08-04 pm](https://user-images.githubusercontent.com/2752195/51352321-18ff1c00-1a62-11e9-9d60-5478ec07a8d3.png)

Report template showing conditional display. Output report does not contain this section:
![1-17-2019 2-07-09 pm](https://user-images.githubusercontent.com/2752195/51352335-20262a00-1a62-11e9-85b1-71e0490e071f.png)

Changing the conditional statement to test for ANY response works as expected. I did not test with multiple responses as I did not expect it to work if a single response was unsuccessful.

**Have you tested with another survey?** 
tested with other question types/conditional statements successfully.

**Comment by BrandonArmstrong** [comment]
@allisonmuise I believe the following would work for the specific event where "riprap" was selected from the multiple choice question, however, I understand that you would like for the statement to be dynamic in that it would display values for only the selected choices of the multiple_choice question, correct?

**Slope Protection**
${if slopetypes==”riprap”}
**Riprap**
Average diameter of riprap: ${ripdiameter}
Condition: ${ripcondition}
Action required: ${ripaction}
${/}

**Comment by BrandonArmstrong** [comment]
Thank you for comments

Internal Issue created for further investigation related to conditional if statements and multiple choice questions

https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3282

**Comment by oopsliu** [comment]
Hi @allisonmuise , this is supported now on [the beta website](https://survey123beta.arcgis.com) of survey123, and documentation can be found [here ](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={52509931-65C3-4602-B5CB-3B9CECE3BFBD})or [here](https://github.com/tedrick/Survey123-Testing/issues/299). We would love to have you test it out and share any feedback or issues you may encounter.

**Comment by allisonmuise** [comment]
@oopsliu Thanks! I'll take a look next week.
