### ISSUE TITLE
Unselecting report records does not update the default item title

### ISSUE THREAD

**Issue by Temmermand** [tedrick/Survey123-Testing#209]
**Application:** Website 

**Device:** Desktop - HOLISTIC57 

**Operating System:** Windows 10 Enterprise, Version 1803

**Browser:** Google Chrome Version 71.0.3578.98 (Official Build) (64-bit) and Edge and IE and Firefox.

Issue: Prior to generating a report, you can select record. 

If you select 2 records, the software reads as:
Selected records only (2)
Survey_2 records_20190117......

If you select another record, the software updates as:
Selected records only (3)
Survey_3 records_20190117......

However, if you deselect a record, the software only partially updates as:
Selected records only (2)
Survey_3 records_20190117......

It should probably update to read as:
Selected records only (2)
Survey_2 records_20190117......

![image](https://user-images.githubusercontent.com/38793244/51352502-a9d5f780-1a62-11e9-9dee-011573c958c6.png)

**Comment by BrandonArmstrong** [comment]
Thank you for testing. 

Raised internal issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3252
Closing
