### ISSUE TITLE
Feedback: New webform

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#21]
**Requirements:** Survey123 Field App and Connect from Early Adopter community: https://earlyadopter.esri.com/project/home.html?cap=%7bE69EF91F-4574-4B98-882C-651F7B518EB7%7d or from test-flight for IOS (you will need to download the test flight app from the store and receive an invite from Esri).

-----------------------------------------------
**Overview:**
Please provide feedback on the new webform (used by Survey123 Connect published surveys).  Please include issues, screenshots if applicable and the XLSX file used for the comment.

**Steps**
Using your own surveys or the community samples in connect - publish the survey and open it up in the webform:

![image](https://user-images.githubusercontent.com/24929507/31698955-e3b360f0-b40b-11e7-8a59-2b65e6c3cf66.png)

Explore the form functionality and verify that submission is successful.

Capture any feedback in new issues

**Comment by jchaconas** [comment]
The "compact" appearance when using "groups" does not appear to be functioning properly. The groups should be collapsed by default upon opening. There is also no way to collapse/expand a group in the webform version.

The title of the survey does not appear in the webform version.

**Comment by ahandelman** [comment]
Pulldata function does not seem to work. I get an error that the csv file doesn't exist. My survey is set to pull the coordinates for a geopoint field from a csv file based on the location response drop-down question above it.

**Comment by rush2paras** [comment]
The autocomplete is not working in web form from a survey published using survey 123 connect.

**Comment by moore-jonathon** [comment]
Jonathon Moore New Zealand testing. Web app doesn't load properly on IE, displays a constant loading screen even after several minutes.

**Comment by moore-jonathon** [comment]
Web app fails to load on IE. Loading screen displays but does not load. Problem occuring across multiple different survey forms after multiple attempts

**Comment by JohnHasthorpe** [comment]
Have you cleared the browser cache?

**Comment by moore-jonathon** [comment]
Have cleared browser cache and still having the same issue. May be a one off, will keep trying





________________________________

**Comment by phil-wilson** [comment]
Can you confirm the URL you are using, and also can you share the survey? What version of IE on what OS version?

**Comment by phil-wilson** [comment]
Can you test the same survey in prod (normal URL)? It may be a dev website only related issue?

**Comment by moore-jonathon** [comment]
https://survey123dev.arcgis.com/share/0ee14f74ce0642d0b1b923883602f30b



Not sure I can share this survey at this time sorry



Version 11.0.9600 of IE



OS Windows 7 SP1 x64





________________________________

**Comment by moore-jonathon** [comment]
Hi Philp

Just tested it in prod and works fine. Dev website is still having the same issue testing it on a different computer today.

Cheers,
Jonathon

Jonathon Moore
GIS Advisor | Community Services / Ratonga Whanaungatanga Hapori | Wellington City Council
P 04 830 1258 | M 021 270 8158
E Jonathon.Moore@wcc.govt.nz<mailto:Jonathon.Moore@wcc.govt.nz> | W Wellington.govt.nz<http://wellington.govt.nz/> | [Facebook] <https://www.facebook.com/wellingtoncitycouncil>  | [Twitter] <http://twitter.com/wgtncc>


The information contained in this email is privileged and confidential and intended for the addressee only.
If you are not the intended recipient, you are asked to respect that confidentiality and not disclose, copy or make use of its contents.
If received in error you are asked to destroy this email and contact the sender immediately. Your assistance is appreciated.

[http://wellington.govt.nz/~/media/Images/email-signatures/wcc-banner-new.jpg]

**Comment by phil-wilson** [comment]
@zhif7782 Is there a reason @moore-jonathon survey works in Prod and not Dev?

**Comment by zhif7782** [comment]
It may be caused by an unintentional bug on DEV website, @phil-wilson @moore-jonathon , would you mind to share a XLSForm file that can reproduce the issue? (work on PROD but not on DEV)

cc @huoyixin

**Comment by moore-jonathon** [comment]
Can’t seem to replicate the issue with the same survey forms anymore sorry. Looks like the PROD and DEV versions are both working

Jonathon Moore
GIS Advisor | Community Services / Ratonga Whanaungatanga Hapori | Wellington City Council
P 04 830 1258 | M 021 270 8158
E Jonathon.Moore@wcc.govt.nz<mailto:Jonathon.Moore@wcc.govt.nz> | W Wellington.govt.nz<http://wellington.govt.nz/> | [Facebook] <https://www.facebook.com/wellingtoncitycouncil>  | [Twitter] <http://twitter.com/wgtncc>


The information contained in this email is privileged and confidential and intended for the addressee only.
If you are not the intended recipient, you are asked to respect that confidentiality and not disclose, copy or make use of its contents.
If received in error you are asked to destroy this email and contact the sender immediately. Your assistance is appreciated.

[http://wellington.govt.nz/~/media/Images/email-signatures/wcc-banner-new.jpg]
