### ISSUE TITLE
Clicking the gear icon in Survey123 Connect logs you out of the application

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#210]
**Application:** Connect

**Operating System:** Win 10

**How to reproduce:**
>Login to Survey123 Connect
>Click the Gear Icon for Portal/Settings
>It automatically logs you out

Tested with 2 accounts in 2 different orgs

**Comment by BrandonArmstrong** [comment]
Thank you for testing

Internal Issue exists for this behavior as well as a Technical Support BUG

Internal Issue: https://devtopia.esri.com/Melbourne/Survey123/issues/2282
Support: BUG-000114140
