### ISSUE TITLE
Connect app scaling issues on high DPI screen

### ISSUE THREAD

**Issue by maxi6834** [tedrick/Survey123-Testing#211]
**Application:** Connect

**Device:** MS Surfacebook, 250% DPI

**Operating System:** Win10

**Browser:** N/A

**Error Description:** Sign in UI looks really small

**How to reproduce:** Sign in to QAExt. Look at Sign In UI
![image](https://user-images.githubusercontent.com/5098162/51353499-ab54ef00-1a65-11e9-8b81-c3b02d14a7a4.png)

This looks really small, maybe 2 inch wide on the physical screen

Compare to ArcGIS Pro Sign In dialog (looks to be of correct size)

![image](https://user-images.githubusercontent.com/5098162/51353640-0f77b300-1a66-11e9-9016-81f86bb0ac68.png)

**Have you tested with another survey?**

**Comment by BrandonArmstrong** [comment]
Converted to internal issue:
https://devtopia.esri.com/Melbourne/Survey123/issues/2897
