### ISSUE TITLE
Report submitted data and time don't match user data and time

### ISSUE THREAD

**Issue by Temmermand** [tedrick/Survey123-Testing#212]
**Application:** Website 

**Device:** Desktop - HOLISTIC57 

**Operating System:** Windows 10 Enterprise, Version 1803

**Browser:** Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

Repro:
1. generate a report that captured the submitted time

Issue:
Report submitted data and time don't match user data and time

![image](https://user-images.githubusercontent.com/38793244/51353673-20282900-1a66-11e9-9d35-6269bfd5e83c.png)

![image](https://user-images.githubusercontent.com/38793244/51353690-2918fa80-1a66-11e9-8a38-b2239677ab45.png)

**Comment by BrandonArmstrong** [comment]
@Temmermand Is this in reference to a feature report?  The screenshot appears to be of the individual response windows after selecting a record from the dataset in the Survey123 website

Thanks

**Comment by Temmermand** [comment]
@BrandonArmstrong Good question. I could have done a better job describing the issue. This is prior to generating a report. All I did was click on the Data tab and click on a record. The panel appear that showed the details for that record. The dates from the survey were off from the submitted time by one day. I assumed this was a bug, but it may have been user error, if no one else is reporting this issue. 

I suspect that the date on the Submitted Time is the actual, correct date (12/31). If the user reported (12/30), then it could have been a user error (more likely) or something wrong with the device (also possible). It seems to be a common pattern for several surveys from the same person on an iPhone. 

Unfortunately, I deleted many of the records that showed the pattern. Only two remain, and they both show December 30 in the record and December 31 in the Submitted Time. 

I don't know if they were submitted via browser or native app. 

We may want to chalk this up as something that we can't reproduce, unless you are also seeing this with other customers.

**Comment by Temmermand** [comment]
The only other thing worth noting is that, for at least these two records, there was no point recorded. That was likely a user error, but I don't know if that could have a carry over effect on this field. 

For other records that I made on that same survey from my iPhone, there is no difference between the dates.
