### ISSUE TITLE
Reports with a null geopoint display an odd maps

### ISSUE THREAD

**Issue by Temmermand** [tedrick/Survey123-Testing#213]
**Application:** Website 

**Device:** Desktop - HOLISTIC57 

**Operating System:** Windows 10 Enterprise, Version 1803

**Browser:** Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

Repro:
- collect Survey123 without a geopoint (perhaps as a web survey through Safari without permission to access location services)
- generate a report with a map.

![image](https://user-images.githubusercontent.com/38793244/51353875-b9573f80-1a66-11e9-9134-810455dc1e13.png)

![image](https://user-images.githubusercontent.com/38793244/51353910-cffd9680-1a66-11e9-9dbb-16071637b6a3.png)

![image](https://user-images.githubusercontent.com/38793244/51353948-f15e8280-1a66-11e9-8e3a-75142930222f.png)

![image](https://user-images.githubusercontent.com/38793244/51354000-1e129a00-1a67-11e9-9051-42d07c77be94.png)

**Comment by BrandonArmstrong** [comment]
Thank you for feedback

If the geopoint was not collected or altered to a desired location, it should not be included in the report template for the particular feature
