### ISSUE TITLE
No way to trigger re-calculation of values for inbox items

### ISSUE THREAD

**Issue by allisonmuise** [tedrick/Survey123-Testing#214]
**Application:** Connect | Field App | Website | On Premises | _Other_
field app
**Device:** _Important for Field App especially_
windows (have repro's on iOS, android as well
**Operating System:** _Provide version, i.e., Android 5.0.1_
Windows 10 (also multiple versions of iOS & android)
**Browser:** _For the website_

**Error Description:** 
User story: Infrastructure inspection where different components are assigned different status values. 
Infrastructure inspection form is loaded from inbox to bring in many static attributes
Need to display the count of each of the status value option in read-only format on the survey
Need to calculate an overall score for the infrastructure based on the counts of the status values.

The counts of the status values (uneditable) do not update, and there is no way to recalc them/tell the survey to override the (null) inbox values

The overall score can be recalculated because it's editable, but the answer isn't correct because it's based on the un-re-calculated count values.

Would be nice if there was a way to tell the survey that the inbox values should always be overridden for certain fields so that they can dynamically update based on other answers/actions in the survey.

**How to reproduce:**

**Have you tested with another survey?**

**Comment by BrandonArmstrong** [comment]
Attached to existing internal issue
