### ISSUE TITLE
No information received from Bad Elf Pro receiver

### ISSUE THREAD

**Issue by colinlawr** [tedrick/Survey123-Testing#215]
**Application:** Field App

**Device:** Google Pixel 2, Bad Elf GNSS Pro+

**Operating System:** Android 9.0

**Browser:** n/a

**Error Description:** "No Position Received" when connected to Bad Elf Pro+ in a survey. Location Info was blank as well as the Skyplot and Debug windows. The bad elf device indicated satellites were in view and in use and I was able to get a location from within Collector for Android. 

I tested with a Bad Elf GNSS Surveyor and had no issues getting a position fix. 

**How to reproduce:**

1. Connect to Bad Elf Pro receiver using a device running Android 9
2. Configure this as the Location Provider within the settings
3. Go outside in a clear area to acquire a solid fix
4. Open a survey and the message "no position received" is continuously displayed

**Have you tested with another survey?** 

yes, not survey specific

**Comment by BrandonArmstrong** [comment]
Thank you for feedback

This could have been related to a need for a firmware update on the GNSS Pro + receiver

Closing for now
