### ISSUE TITLE
Filters feel counter-intuitive

### ISSUE THREAD

**Issue by RachelGEsri** [tedrick/Survey123-Testing#216]
**Application:** Website

**Device:** PC

**Operating System:** Windows 10

**Browser:** Chrome

**Error Description:** 

ADDING FILTERS:
- In all the current softwares (ex. Pro, ArcGIS Online interfaces) you must add an expression, then click ADD and then your expression is applied.
- In the Survey123 page, you click Apply to apply the filter you're in the middle of building, not Add Expression... Add Expression creates a new line. This is confusing and may be better to be more similar to other existing interfaces.

REMOVING FILTERS:
- If you only have one expression, you can't click the X to the right of the filter to remove it.
- If you try to click the trash can, the expression value clears out but the rest of the expression remains.
- This is counter-intuitive compared to other existing softwares - I would expect the entire line to disappear when clicking the trash can or X.

**How to reproduce:** See above.

**Have you tested with another survey?** N/A

**Comment by BrandonArmstrong** [comment]
Thank you for feedback

Added to document containing general UI feedback for website
