### ISSUE TITLE
Multiline input captures focus and it's impossible to move to another page

### ISSUE THREAD

**Issue by maxi6834** [tedrick/Survey123-Testing#217]
**Application:** Field App 

**Device:** Samsung S7

**Operating System:** Current Android

**Browser:** N/A

**Error Description:** 

**How to reproduce:** Create a survey with two pages. First page should include only one control: multiline text. Second page should contain some other controls. Publish it. In Field App, go to Collect, and click Multiline control. The keyboard will popu and cover "<" and ">" buttons. There's no way to get rid of the keyboard, so you will not be able to get to the second page. The only way out I found was to click gear icon in keyboard. Then it goes away and I'm able to click the buttons at the bottom of the app.
 
![image](https://user-images.githubusercontent.com/5098162/51354416-61213d00-1a68-11e9-84c4-7b2c8ab39f76.png)

**Have you tested with another survey?**

**Comment by BrandonArmstrong** [comment]
Thank you for feedback

This behavior may be specific to Samsung Keyboard and might be able to be addressed by pushing the back button on the device. Testing on a Samsung Galaxy S9 I am able to select a control to minimize the keyboard after entry as well as with a Android HTC Bolt

Closing for now
