### ISSUE TITLE
Failed to parse "${ObjectID}". Field "${ObjectID}" does not exist or cannot be found in current parsing scope.

### ISSUE THREAD

**Issue by RachelGEsri** [tedrick/Survey123-Testing#218]
**Application:** Website

**Device:** PC

**Operating System:** Windows 10

**Browser:** Chrome

**Error Description:** Cannot seem to successfully use ${ObjectID}. When I include this in my template, and when Survey123 site tries to validate template for report use, I receive the error:

"Failed to parse "${ObjectID}". Field "${ObjectID}" does not exist or cannot be found in current parsing scope."

**How to reproduce:** Include ${ObjectID} on a template.

**Have you tested with another survey?**  No

**Comment by zhif7782** [comment]
Hi @RachelGEsri , 
Thanks for your feedback.

Would you mind confirming if the object id field name in your feature layer is exact `ObjectID`? The name is case sensitive when performing the syntax checking for the report template.

**Comment by RachelGEsri** [comment]
Good call, that was the issue! I had ObjectID in my template and it’s actually created by the Survey123 website as ObjectId. Once I fixed the D to a d, it worked.

Thanks!

------------------------------------------------------------------------------------

Rachel Guttmacher | Support Services
Esri | 380 New York St | Redlands, CA 92373 | USA
T 909 793 2853 x3308 | rguttmacher@esri.com | esri.com

THE
SCIENCE
OF
WHERE™
