### ISSUE TITLE
CHALLENGE: Editing with repeats (Parameters)

### ISSUE THREAD

**Issue by JohnHasthorpe** [tedrick/Survey123-Testing#22]
By default, editing of repeats means that you can add new repeats, but you can’t see or edit previously submitted ones. If you want to do something different, then you need to configure your survey to add the newly supported _bind::esri:parameters_ column to your survey XLSForm and populate it with an appropriate parameter. Parameters are entered in the format of space separated key=value pairs that are added to each repeat - with values that contain spaces enclosed in quotes:e.g. key="value with space". The parameters that you can use are as follows:

> **allowAdds** – Controls whether new rows can be added to a repeat. This can be set to true or false, but the default is true: i.e. allowAdds=true. Note that this paramater only affects surveys that have already been submitted (in the sent box) or downloaded to the inbox. When collecting a new survey, new related rows can always be added irrespective of the parameter.
> 
> **allowUpdates** – Controls whether answers in existing repeats can be updated/edited. This can be set to true or false, but the default is false: i.e. allowUpdates=false. Again, note that this only affects related data that has already been submitted (in the sent box) or downloaded to the inbox. Any related data not yet submitted, is always editable.
> 
> **query** - This parameter controls which which repeated records are downloaded to the device for viewing and editing purposes. If the query parameter is not present, then no records will be downloaded. You can download related records by entering query='1=1'. esults in all the download of all related records (i.e. the equivalent of "1=1"). You can also return subsets of related records by defining a sql where clause. Entering query="occupant_name='John'" will return all records with a value of John in the occupant_name field. Note that under the hood, the above specifies the definitionExpression parameter for the feature service. Tip: A shorcut to have all related records downloaded consists of adding the query parameter without an values. An example of this is provdided in the sample Edit_Repeats XLSForm below.
> 
> **orderBy** – This parameter enables you to specify the order that related records are displayed in the app. e.g. orderBy=occupant_name will oder related records by the occopant_name field. nder the hood this specifies the orderByFields parameter for the feature service.
> 

**Challenge:** Using your own survey(s) or sample/community surveys in Connect, that include repeats, attachments, and have the inbox enabled (ideally with data sets larger than 2000 features) add the _bind::esri:parameters_ column into the Survey sheet of the XLS. 

Republish the survey in connect, each time entering the required parameters into the  _bind::esri:parameters_  column to achieve the following (in any combination):

1) Return all repeat records (query)
2) Limit the repeat records returned based on a query (query="occupant_name5='John'")
3) Prevent the addition of new repeat records (query allowAdds=false )
4) Allow the update of existing (i.e. previously submitted) records (query allowUpdates=true )
5) Sort returned repeat records by a field (query orderBy=occupant_name6)

Verify that the parameters are working as expected.

**Comment by IsmaelInRedlands** [comment]
Tested Editing with Repeats with the Police Department of City of Rancho Cucamonga.
They wanted to enable editing on this survey:  [RCPD Homeless Contact & Log.xlsx](https://github.com/tedrick/Survey123-Testing/files/1260963/RCPD.Homeless.Contact.Log.xlsx)

We first tested without any parameters. Worked well.
Then we implemented query and allowadds=true, which worked flawlessly too.
Finally we tested allowupdates=true just for fun, although the workflow does not require it. Worked well.

This was an easy test as there was literally no data captured already, but proved this new functionality working on a basic real scenario.

Only minor flaw we found was on the web form, which did not allow us to submit any data. The geopoint question within the repeat was highlighted in red.

**Device:** iPhone6, iOS 10.3.2
**ArcGIS Online**

**Operating System:** _Provide version, i.e., Android 5.0.1_

**Comment by tedrick** [comment]
Jess, Christan, Rose, Kanchana, Justin, Sarah

**Comment by kunjoo91** [comment]
[MPHD VC Assignment v2.zip](https://github.com/tedrick/Survey123-Testing/files/1318810/MPHD.VC.Assignment.v2.zip)

Changed it to allowUpdates=true query, it worked. I was able to see the repeats from the Inbox.

The inbox shows the Modified date as the time I refreshed the inbox, and not the time of last edit. Not sure if that is expected behaviour. Please find below a screenshot.

![image](https://user-images.githubusercontent.com/24254822/30661124-d8a10c0a-9df7-11e7-9692-7d3b3f11da65.png)

The older version of Inbox has the modified date as the actual modified date.

![image](https://user-images.githubusercontent.com/24254822/30661443-d5ebc972-9df8-11e7-8e0c-7033efae89ed.png)

**Comment by JohnHasthorpe** [comment]
2.4 testing complete
