### ISSUE TITLE
Changing the max. value of Likert items after publishing

### ISSUE THREAD

**Issue by Temmermand** [tedrick/Survey123-Testing#220]
**Application:** Website 

**Device:** Desktop - HOLISTIC57 

**Operating System:** Windows 10 Enterprise, Version 1803

**Browser:** Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

After you publish with 4 values in a Likert question type, you can't edit the number of values. I wanted to add a fifth Likert option.

You can still change the label and the values of the items, just not the max. value.

![image](https://user-images.githubusercontent.com/38793244/51355910-6b920580-1a6d-11e9-8ffd-4ef823861f97.png)

**Comment by zhif7782** [comment]
Hi @Temmermand ,
Thank you for the feedback.

I've logged it to the issue https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/1563 in our backlog.
