### ISSUE TITLE
Enhancement: Report- dynamic display of specific responses 

### ISSUE THREAD

**Issue by jerjer007** [tedrick/Survey123-Testing#222]
**Application:** Connect | Field App | Website | On Premises | _Other_

**Device:** _Important for Field App especially_

**Operating System:** _Provide version, i.e., Android 5.0.1_

**Browser:** _For the website_

**Error Description:** 

**How to reproduce:**

**Have you tested with another survey?**

**Comment by jerjer007** [comment]
Example, if a survey with a urgency or priority question, that the response could be in a different color or type in the report; such as Red for urgent or priority 1, and Green for a less urgent or low priority.

**Comment by zhif7782** [comment]
Hi @jerjer007 , 
This can be achieved by using conditional elements in the feature report template, please see details in the help topic: https://doc.arcgis.com/en/survey123/browser/analyze-results/featurereporttemplates.htm.
