### ISSUE TITLE
Can't go back from "This survey does not exist or is not accessible."

### ISSUE THREAD

**Issue by Temmermand** [tedrick/Survey123-Testing#223]
**Application:** Website 

**Device:** Desktop - HOLISTIC57 

**Operating System:** Windows 10 Enterprise, Version 1803

**Browser:** Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
Repro:
1. Click on a survey that doesn't exist.
2. See an error message.
3. Click the back button on the browser. 
4. See the same error message.

![image](https://user-images.githubusercontent.com/38793244/51356213-9761bb00-1a6e-11e9-963e-336f62166062.png)

![image](https://user-images.githubusercontent.com/38793244/51356194-8a44cc00-1a6e-11e9-9362-e3aceab24f3a.png)

**Comment by zhif7782** [comment]
Hi @Temmermand ,
Thanks for the feedback.

Is there any steps to "Click on a survey that doesn't exist."? From your screenshots for the My Surveys page, seems the two surveys are normal.
