### ISSUE TITLE
FEEDBACK: Editing Surveys in Survey123 website (and other places)

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#224]
With the 3.5 release, Survey123 will support web editing of surveys that do not have repeat sections.  You'll be able to do this directly in the Survey123 website via the Data tab:
<img width="468" alt="Screen Shot 2019-06-04 at 10 51 37 AM" src="https://user-images.githubusercontent.com/1319289/58901816-c17ee700-86b6-11e9-85db-b773269de3c3.png">

You can also do this manually or configure applications to do so using URL parameters.  For full documentation, refer the [Early Adopter Community page](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={6C996764-3C47-4FBD-B7F6-6B348717CCAF}), but the basics are:

> Editing in web forms is enabled through URL parameters. For example:
> 
> https://survey123qa.arcgis.com/share/5d2cdded51734869a23aa28ecedb7862?mode=edit&objectId=1&version=latest
> 
> Lets break down the URL parameters:
> 
> - **mode=edit**  Puts the web form in editing mode. When in editing mode, the web form expects you to indicate which survey record will be edited.
> - **objectId=1**  Indicates the exact survey record that will be loaded into the web form for editing. Please note that the parameter name is case sensitive: objectID, objectid, ObjectID, ObjectId are incorrect. The exact parameter name is objectId.
> - **version=latest**  This parameter forces the web form to load the latest version of the Survey123 web app. We use this parameter ONLY for testing purposes. Once the editing feature is publicly released you will NOT want to use this parameter.

**Comment by BrittanyDahl** [comment]
I like the new look of the editing, including bringing in the colours (set from Connect), and honouring the Closing/Opening settings: 

OLD Style:
![image](https://user-images.githubusercontent.com/20454586/59082197-52fb8c80-8935-11e9-81cf-c8c37907d144.png)

NEW Style honouring colours:
![image](https://user-images.githubusercontent.com/20454586/59083507-f7cc9880-893a-11e9-9bde-38a51a0fdcea.png)

Honouring closing & opening the survey from the Collaborate tab:    
![image](https://user-images.githubusercontent.com/20454586/59082201-5bec5e00-8935-11e9-926f-b1eed34cabf6.png)

**Comment by BrandonArmstrong** [comment]
Thank you for testing and the feedback @BrittanyDahl
