### ISSUE TITLE
FEEDBACK: Added ability to preview or save a new survey which is created by others and shared with you.

### ISSUE THREAD

**Issue by Shwujeng** [tedrick/Survey123-Testing#225]
With the current release of the Survey123 website, users can now choose to 'Preview' or 'Save As' with surveys that have been shared with them but owned by others.

Once a survey has been shared with a user or group, the user's role will dictate what further actions can take place.  For instance...

A user with a publisher role can either 'Preview' or 'Save As'.
![image](https://user-images.githubusercontent.com/29442153/58913778-ca30e680-86d1-11e9-80f9-9ed8c4c1a363.png)

User's with Data Editor, User, or Viewer roles can only Preview the survey.
![image](https://user-images.githubusercontent.com/29442153/58913810-e03ea700-86d1-11e9-923d-00d6f5bf23d3.png)

Try this out and let us know what you think!

**Comment by BrandonArmstrong** [comment]
Jamie
