### ISSUE TITLE
CHALLENGE: Use Grid Theme to create a survey that mimics the layout of an existing paper form

### ISSUE THREAD

**Issue by brettstokes** [tedrick/Survey123-Testing#226]
Support for _Grid Theme_ in Survey123 v3.5 brings with it the ability to have multiple questions on the same row in your form. The layout of your form can be configured by applying 'w' appearance tags to your Groups, and to Questions within those groups.

See [EAC documentation](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={C38BB9B8-1096-4315-8BA4-137136B99F40}) and explanation below to **create a survey that mimics the layout of an existing paper form**. Please comment with your experience / feedback.

> By setting the style column in the settings sheet to theme-grid, groups in your survey can be set to display the contained questions in a grid. Set a group's appearance to w followed by the number of cells used to divide your grid into. For example, w8 will divide each row of your grid into eight cells. The relative width of each question in this group can be set in the same way; when the stated widths of the questions adds up to the number of cells set for the group, the next questions will be on a new line. These widths can be set along with most other appearance types.
> 
> Note:
> Currently, relative widths are not supported for month-year, week-number, year, likert, distress, and signature appearance types. If a relative width is set, the question will revert to its default appearance.
> 
> A width can't be applied to a repeat. Instead, it needs to be applied to a group within the repeat.
> 
> A nested group will only occupy one of the parent group's cells.

Here is an example if needed:

![image](https://user-images.githubusercontent.com/46305628/58933034-5b26c100-87a9-11e9-9559-a1e059013aac.png)

**Comment by BrandonArmstrong** [comment]
Ethan
Francisco
Morgan

**Comment by fandrade86** [comment]
I have retested the grid them survey with the attached XLS form and no issue was found.

[ServiceNotif_05022019.xlsx](https://github.com/tedrick/Survey123-Testing/files/3263067/ServiceNotif_05022019.xlsx)

**Comment by usernamenottaken** [comment]
I started out testing the grid theme using one of the sample forms (Grid Theme with Pages and Repeats) and noticed that when you have two selects of different sizes in the same grid row the list vertically aligns from the bottom instead of from the top.  This causes a gap between the question and the shorter list of options.
![image](https://user-images.githubusercontent.com/5882560/59064942-8842a480-8879-11e9-9707-d080e117f65b.png)

**Comment by ez4gis** [comment]
"Grid Theme - Vehicle Inspection.xlsx" worked nice. "Grid Theme with Pages and Repeats.xlsx" have issue with portrait mode on iPad.

**Comment by morganwaterman** [comment]
Receive an unnecessary warning message when inputting "w" values in the appearance column.
![AppearanceError_GridTheme](https://user-images.githubusercontent.com/51456665/59068642-85d84e80-8869-11e9-9ecd-9779491a8154.PNG)

**Comment by morganwaterman** [comment]
If w values are not specified (default) in the appearance column for questions within a group, the width for each question is not equally divided across the interface. If there are two questions in the group, the first question seems to take on a value of w1 and the second autocompletes to fill the the width of the interface. If there are more than two questions in the group, all questions except the last one seem to take on a value of w1, while the last question autocompletes.
Sample XLS:
[Test 3 - Grid Theme.xlsx](https://github.com/tedrick/Survey123-Testing/files/3263634/Test.3.-.Grid.Theme.xlsx)
When no "w" value is specified for the Siblings group:
![GridTheme_defaultvalues](https://user-images.githubusercontent.com/51456665/59068883-6130a680-886a-11e9-839b-1c4ad12877d8.PNG)
When w8 is specified:
![GridTheme_w8](https://user-images.githubusercontent.com/51456665/59068921-74437680-886a-11e9-913f-58bd01a0b606.PNG)
When w10 is specified:
![GridTheme_w10](https://user-images.githubusercontent.com/51456665/59068932-7b6a8480-886a-11e9-9e4a-1960fc3c81b9.PNG)

**Comment by morganwaterman** [comment]
Question: Why is "field-list" the tag to start a new page within the "theme-grid pages" style? This does not seem like an intuitive tag to start a new page.

**Comment by usernamenottaken** [comment]
When building a survey using the grid theme I cannot get the borderColor to change when I set it for the group (under the body::esri:style column).  Also, is there a way to change the border color for the grid cells?

**Comment by danmcilroyGA** [comment]
Have noticed horizontal appearance on select one questions; when the width is too narrow (ie w1), select one questions either stack (with to vertical) or overprint. This is even the case when there is ample room for for the selections (tested with yes_no)

Both yes_no questions were set to horizontal in the image below:

<img width="1195" alt="Screen Shot 2019-06-07 at 2 26 44 pm" src="https://user-images.githubusercontent.com/40751679/59081537-fcd91a00-8931-11e9-9213-21eb6dc28871.png">
