### ISSUE TITLE
CHALLENGE: Apply multiple watermarks to an image 

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#228]
With version 3.5 of Survey123 Connect and the Field App we have added the ability to apply watermarks to your images.  This means that you can stamp the date, longitude/latitude, images, logos, and other metadata directly on to your photos at time of capture.  

![Watermark_30size](https://user-images.githubusercontent.com/6314443/58988262-22312100-8796-11e9-8ce4-a6627a295005.jpg)

This can be accomplished by referencing the documentation provided in the [Early Adopter Community ](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={9F7C39A6-80C6-4A2C-A5A5-79D5926C8927})

Your mission, should you decide to accept it, is to design a survey using Survey123 Connect that contains an image question with a statement in the **bind::esri:parameters** column that draws at least 2 watermarks on to the image at time of capture.  

_hint: make use of positional statements to determine where the watermark will be placed on the image (i.e. topLeftWatermark, topRightWatermark, bottomCenterWatermark, etc.)_

Although the documentation provided in the EAC is a far better resource, please find a large portion of it below.

<hr />
<p><strong>XLSForm Design Consideration</strong></p>

<p><strong>bind::esri:parameters column</strong>&nbsp;- This column in the XLSForm will be used to define what information will be stamped on the image and where it will be placed&nbsp;on the image:</p>

<p><strong>Image size:</strong>&nbsp;A photo taken in Survey123 will be saved as a .jpg file, with a quality level dependent on your device&#39;s camera. You can set the desired image size on the Settings &gt; Images tab in Survey123 Connect. The following four options are available:</p>

<ul>
	<li>Small is 320x240 for a 4:3 photo, 320x69 for a panorama photo, and 320x320 for a square photo.</li>
	<li>Medium is 640x480 for a 4:3 photo, 640x137 for a panorama photo, and 640x640 for a square photo.</li>
	<li>Large is 1280x960 for a 4:3 photo, 1280x734 for a panorama photo, and 1280x1280 for a square photo.</li>
	<li>Unrestricted allows any photo size to be attached to the survey.</li>
</ul>

<p>By default, image size is set to Medium.</p>

<p><em>*Tip: Try selecting a larger image size prior to publishing in order to increase the resolution and quality of the output.</em></p>

<p><em>There is a known issue related to the use of Unrestricted image size on iOS devices with watermarks. If set in Connect, unrestricted images on iOS will be saved as Large image size when using watermarks.&nbsp;</em></p>

<hr />
<p><u>Example:</u></p>

<p><span data-cc-colorbutton="fg" style="color:#0000ff">watermark=</span><span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">USNG</span> &nbsp;<span data-cc-colorbutton="fg" style="color:#cc0099">@[usng]</span><span class="cc-color-fg--custom3-l1" data-cc-colorbutton="fg" style="color:cc-color-custom3-l1"> </span><span data-cc-colorbutton="fg" style="color:#ff6600"><span>\n</span></span><span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">Compass</span> <span data-cc-colorbutton="fg" style="color:#cc0099">@[compass]</span>&amp;<span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">s</span><span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2"><span>ize</span>=25</span>&amp;<span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">size=25</span>&amp;<span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">color=red</span>&amp;<span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">o</span><span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">utlineColor=white</span>&amp;<span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">position=topRight</span></p>

<p>Let&rsquo;s break this down:</p>

<p><span data-cc-colorbutton="fg" style="color:#0033ff">watermark =</span> When placed in the bind:esri::parameters column it starts&nbsp;the formula that will be used to determine which information will be stamped on the image.</p>

<p><span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">USNG&nbsp;</span> this freestanding text is one of many watermark <em>properties</em> that can be used. Some other properties used in this example are size, color, outline color, and position. Refer to the&nbsp;documentation below regarding other watermark <em>properties</em>.</p>

<p><span data-cc-colorbutton="fg" style="color:#cc0099">@[usng]</span> - the @[ ] notation is used to define a placeholder.&nbsp; These placeholder values are populated at the moment of image capture.&nbsp; The notation differs from expression variables, and is unique to watermarks.</p>

<p><span data-cc-colorbutton="fg" style="color:#ff6600"><span>\n</span></span><span class="cc-color-fg--custom3" data-cc-colorbutton="fg" style="color:cc-color-custom3"><span> </span></span>&ndash; used to define line breaks</p>

<p>&amp; - used to separate parameter properties</p>

<p>Other Examples:</p>

<p><span data-cc-colorbutton="fg" style="color:#0000ff">watermark=</span><span data-cc-colorbutton="fg" style="color:#cc0099">@[latitude longitude:dms]</span></p>

<p><span data-cc-colorbutton="fg" style="color:#0000ff">watermark=</span><span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">USNG</span> <span data-cc-colorbutton="fg" style="color:#cc0099">@[usng]</span>&amp;<span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">size=50</span>&amp;<span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">color=red</span>&amp;<span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">o</span><span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">utlineColor=white</span>&amp;<span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">position=topRight</span></p>

<p><span data-cc-colorbutton="fg" style="color:#0000ff">topLeftW<span data-cc-colorbutton="bg">atermark=</span></span><span data-cc-colorbutton="fg" style="color:#cc0099">@[latitude longitude:ddm]</span><span data-cc-colorbutton="fg" style="color:#ff6600">\n</span><span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">Compass</span> <span data-cc-colorbutton="fg" style="color:#cc0099">@[compass]</span>&amp;<span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">size=50</span>&amp;<span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">color=red</span>&amp;<span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">outlineColor=white</span></p>

<p><span data-cc-colorbutton="fg" style="color:#0000ff">bottomLeftWatermark=</span><span class="cc-color-fg--custom2" data-cc-colorbutton="fg" style="color:cc-color-custom2">Lat </span><span data-cc-colorbutton="fg" style="color:#cc0099">@[latitude:dms]\nLon @[longitude:dms]</span></p>

<div style="border-bottom:solid #eaecef 1.0pt; padding:0in 0in 4.0pt 0in">
<p style="border:none; margin-bottom:8pt; margin-left:0in; margin-right:0in; margin-top:0in; padding:0in"><em>* Tip:&nbsp;if your expression includes spaces, try adding &quot; &quot; around&nbsp; the properties after the watermark parameter i.e. watermark=&nbsp;</em></p>

<p style="border:none; margin-bottom:8pt; margin-left:0in; margin-right:0in; margin-top:0in; padding:0in">&nbsp;</p>

<p style="border:none; margin-bottom:8pt; margin-left:0in; margin-right:0in; margin-top:0in; padding:0in"><u><em><strong><span data-cc-colorbutton="fg" style="color:null"><span>Use the documentation below or download attached Watermark Sample XLSForm to get started</span></span></strong></em></u></p>

<hr />
<h2>Watermark Parameter</h2>

<ul>
	<li>watermark=</li>
	<li>topLeftWatermark=</li>
	<li>topCenterWatermark=</li>
	<li>topRightWatermark=</li>
	<li>leftCenterWatermark=</li>
	<li>centerWatermark=</li>
	<li>rightCenterWatermark=</li>
	<li>bottomLeftWatermark=</li>
	<li>bottomCenterWatermark=</li>
	<li>bottomRightWatermark=</li>
</ul>

<h2>Watermark Parameter Properties</h2>

<ul>
	<li>
	<p><strong>text</strong>&nbsp;-&nbsp;<em>Text of the watermark. This parameter is implicit if the text is specified as the first parameter.&nbsp;<code>\n</code>&nbsp;will insert line breaks</em></p>
	</li>
	<li>
	<p><strong>color</strong>&nbsp;-&nbsp;<em>Text color</em></p>
	</li>
	<li>
	<p><strong>outlinecolor</strong>&nbsp;-&nbsp;<em>Defaults to same as text color</em></p>
	</li>
	<li>
	<p><strong>outlineWidth</strong>&nbsp;-&nbsp;<em>Outline width in pixels. Default is&nbsp;<code>1</code></em></p>
	</li>
	<li>
	<p><strong>haloColor</strong>&nbsp;-&nbsp;<em>Default contrasting color is automatically chosen unless explicitly specified</em></p>
	</li>
	<li>
	<p><strong>size</strong>&nbsp;-&nbsp;<em>Text size in pixels</em></p>
	</li>
	<li>
	<p><strong>font</strong>&nbsp;-&nbsp;<em>Name of font to use for text. Default will use Survey123 app font</em></p>
	</li>
	<li>
	<p><strong>bold</strong>&nbsp;-&nbsp;<em>true or false (Default is false)</em></p>
	</li>
	<li>
	<p><strong>italic</strong>&nbsp;-&nbsp;<em>true or false (Default is false)</em></p>
	</li>
	<li>
	<p><strong>position</strong></p>
	</li>
</ul>

<p style="margin-left:40px"><em>Location on image to place watermark. Default is&nbsp;</em>bottomRight<em>&nbsp;Other options are -</em></p>

<p style="margin-left:40px"><em>topLeft,&nbsp;topCenter,&nbsp;topRight</em></p>

<p style="margin-left:40px"><em>leftCenter,&nbsp;center,&nbsp;rightCenter</em></p>

<p style="margin-left:40px"><em>bottomLeft,&nbsp;bottomCenter,&nbsp;bottomRight</em></p>

<ul>
	<li><strong>margin</strong>&nbsp;-&nbsp;<em>Margin in pixels from edge of image</em></li>
	<li>
	<p><strong>image</strong>&nbsp;-&nbsp;<em>Filename of image in&nbsp;<strong>media</strong>&nbsp;folder</em></p>
	</li>
	<li>
	<p><strong>imageSize</strong>&nbsp;-&nbsp;<em>Size of image in pixels. If not specified then source image size will be used.</em></p>
	</li>
</ul>

<p><em>Boolean values can be specified in a variety of formats including 0 1 false true no yes n y t f</em></p>

<h2>Colors</h2>

<p>Colors may be specified in several supported notations</p>

<ul>
	<li>Hex notation - e.g.&nbsp;<code>#rgb</code>,&nbsp;<code>#rrggbb</code></li>
	<li>Standard HTML color names as per list on&nbsp;<a href="https://doc.qt.io/Qt-5/qml-color.html" rel="nofollow">https://doc.qt.io/Qt-5/qml-color.html</a></li>
</ul>

<h2>Placeholders</h2>

<p>Special placeholders may be specified that are populated at the moment of capture. Placeholder are differentiated from expression variables with a slightly different notation.</p>

<p>@[name]&nbsp;or&nbsp;@[name:format]&nbsp;if the optional&nbsp;format&nbsp;is included.</p>

<ul>
	<li>name&nbsp;- Specifies the value to be substituted in to the placeholder</li>
	<li>format&nbsp;- An optional format for the value.</li>
</ul>

<h2>Names</h2>

<h4>Latitude/Longitude</h4>

<ul>
	<li>latitude</li>
	<li>longitude</li>
	<li>latitude longitude</li>
	<li>longitude latitude</li>
</ul>

<h4>Latitude/Longitude formats</h4>

<ul>
	<li>dd&nbsp;- Decimal degrees (default)</li>
	<li>dms&nbsp;- Degrees minutes seconds</li>
	<li>ddm&nbsp;- Degrees decimal minutes</li>
</ul>

<p style="margin-left:40px"><strong><em>e.g. watermark=&quot;@[latitude longitude:dms]&quot;</em></strong></p>

<ul>
	<li>mgrs&nbsp;-&nbsp;format&nbsp;species precision</li>
	<li>usng&nbsp;-&nbsp;format&nbsp;species precision</li>
	<li>utm</li>
	<li>altitude</li>
	<li>speed&nbsp;- Speed of travel</li>
	<li>direction&nbsp;- Direction of travel based on location sensor</li>
	<li>accuracy&nbsp;or&nbsp;horiontalAccuracy</li>
	<li>compass&nbsp;- Compass reading</li>
</ul>

<h4>Date/Time</h4>

<ul>
	<li>
	<p>timestamp -&nbsp;Timestamp from location (Not available if there is no valid location)</p>
	</li>
	<li>
	<p>date, time, datetime&nbsp;- Date/time from device clock</p>
	</li>
</ul>

<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<strong><em>e.g. watermark=&quot;@[datetime:d MMM yyyy HH:mm]&quot;</em></strong></p>

<h4>Date/Time Formats</h4>

<ul>
	<li>long&nbsp;- Long format (Default) - See&nbsp;https://doc.qt.io/archives/qt-5.8/qml-qtqml-date.html</li>
	<li>short&nbsp;- Short format - See&nbsp;https://doc.qt.io/archives/qt-5.8/qml-qtqml-date.html</li>
	<li>narrow&nbsp;- Narrow format - See&nbsp;https://doc.qt.io/archives/qt-5.8/qml-qtqml-date.html</li>
	<li>dateformat&nbsp;- Refer to documentation for date/time format options -&nbsp;https://doc.qt.io/archives/qt-5.8/qml-qtqml-date.html</li>
</ul>

<p style="border:none; margin-bottom:8pt; margin-left:0in; margin-right:0in; margin-top:0in; padding:0in">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</p>
</div>

<h2 style="margin-bottom:8pt; margin-left:0in; margin-right:0in; margin-top:0in">Limitations</h2>

<ul>
	<li style="margin: 0in 0in 8pt;">Watermarks cannot be applied to images that have already been uploaded.</li>
	<li style="margin: 0in 0in 8pt;">Watermarks cannot not be applied to images captured via the &#39;annotate&#39; or &#39;draw&#39; appearance applied to the image question.</li>
</ul>

**Comment by BrandonArmstrong** [comment]
Everyone!

**Comment by fandrade86** [comment]
Hello,

Issue found - Referencing data from a attribute value . I am referencing cell B3 (Username - Free Text Option)

[Issues Found.xlsx](https://github.com/tedrick/Survey123-Testing/files/3262944/Issues.Found.xlsx)

![Watermark Referecing AttributeValue](https://user-images.githubusercontent.com/21234095/59056961-2b7dc480-884e-11e9-940f-8eb62e403c8e.png)

**Comment by fandrade86** [comment]
As for testing for place holders such as datetime, latitude logitude and compass, testing was successful.

I also testing for position being topLeft and topRight, it was successful.

Size of the text, I went 25 with the image size setting being 1280 pixels and I liked how the text viewed. Testing was successful.

Watermark was tested in attached xls form image1 (Test Picture#1).

[Issues Found.xlsx](https://github.com/tedrick/Survey123-Testing/files/3263015/Issues.Found.xlsx)

![Watermark Referecing PlaceHolders](https://user-images.githubusercontent.com/21234095/59058163-e313d600-8850-11e9-8aed-e96392d94d6e.png)

**Comment by usernamenottaken** [comment]
I successfully tested adding a watermark based on a calculation.  The image included in the watermark changed depending on the answer to one of the survey questions and the Facility ID included as text was also dependent upon an answer to a survey question.
![watermark](https://user-images.githubusercontent.com/5882560/59062743-9641f680-8874-11e9-9e63-74d2c2df57e5.PNG)

**Comment by morganwaterman** [comment]
I also could not pull data from a question into the watermark. See xls form--the value inputted in the ${surveyor} field does not display in the image for the 10th watermark choice. 
[Test 5 - Watermark.xlsx](https://github.com/tedrick/Survey123-Testing/files/3263592/Test.5.-.Watermark.xlsx)

**Comment by houtanesri** [comment]
watermark=HelloWorld or watermark="HelloWorld" will not show up as a watermark.
watermark="Hello World" does work as intended.
It appears that for text to be recognized as text, it needs to have a space in the middle of it.

**Comment by BrandonArmstrong** [comment]
Thank you @houtanesri.  We have logged an internal issue regarding this behavior and have added reference to your findings.
https://devtopia.esri.com/Melbourne/Survey123/issues/3139

**Comment by BrandonArmstrong** [comment]
Thank you for testing @usernamenottaken.  @fandrade86 and @morganwaterman we have found that referencing values from previous questions will require first constructing the body of the watermark statement in a separate field (i.e. note) by using the calculation column to pull the value from a preceding field and then reference that retrieved value from the note in order to construct the remainder of the body for the watermark statement.  More information will be provided in the Help doc for the topic as well as a sample.
