### ISSUE TITLE
Feedback: GeoNet panel in Survey123 Connect

### ISSUE THREAD

**Issue by IsmaelInRedlands** [tedrick/Survey123-Testing#23]
**Context:** A new panel has been added Survey123 Connect showing GeoNet discussions, blog posts and more.  Keep your notes and feedback regarding this panel in this issue.

**Comment by jessnoo** [comment]
the first thing i wanted to do was search based on something i needed to do -- recommend adding a search bar

**Comment by JohnHasthorpe** [comment]
2.4 testing complete
