### ISSUE TITLE
CHALLENGE: Apply color scheme to both groups and repeats

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#230]
With version 3.5 of Survey123 Connect and the Field App, we have introduced the ability to apply a color scheme to groups and repeats.  

The challenge is to apply a different color to at least 2 different groups or repeats within the same survey.  

In order to accomplish this task, you will need to use the documentation below...

The style parameters can be placed in the `body::esri:style `column for the group or repeat that will inherit the color.  If this column does not currently exist in the XLSForm that you will be testing with, you can manually add it yourself.

adding `backgroundColor="pink"` to a group question will set the background color for the group to pink. The color can be a color name, #rrggbb or #aarrggbb value.

In addition, a border color can be applied to the border around the group or repeat.

This looks like `borderColor=purple`

Try this out and show us your results.

**Comment by BrandonArmstrong** [comment]
Jamie
Melanie
Ethan

**Comment by usernamenottaken** [comment]
The background color and border color worked great.  It would be helpful if you could also define the input text color and the text color for each group and repeat as well.  Currently the input text color appears to be defined for the entire survey and the text color would have to be defined for each label using the font tag.
![Text Color with Different Backgrounds](https://user-images.githubusercontent.com/5882560/59061386-63e2ca00-8871-11e9-9281-efbd3b4a2aee.PNG)

**Comment by ez4gis** [comment]
not specific to color scheme, just general UI issue -- tried "Grid Theme with Pages and Repeats.xlsx". layout looks great on iPad in landscape mode, but don't looks good in portrait.

![IMG_0731](https://user-images.githubusercontent.com/21694444/59065193-03e42780-8861-11e9-86a4-5f7c7c665c56.PNG)
![IMG_0733](https://user-images.githubusercontent.com/21694444/59065198-05adeb00-8861-11e9-8b62-ecd04091f39d.PNG)

**Comment by ez4gis** [comment]
background color not working for Repeat for when style is set to "theme-grid pages". 
xlsx file here: [EZ-Form-PagesAndRepeats-Test1.xlsx](https://github.com/tedrick/Survey123-Testing/files/3263512/EZ-Form-PagesAndRepeats-Test1.xlsx)

![image](https://user-images.githubusercontent.com/21694444/59067065-78b96080-8865-11e9-904f-a657f4a4feaa.png)

background color changes after removing "theme-grid" from the style setting.

**Comment by BrittanyDahl** [comment]
Background colour and border colour working:
![image](https://user-images.githubusercontent.com/20454586/59076783-1f136d80-891b-11e9-9b09-5b43947b5a91.png)

A potential enhancement would be to be able to colour the excel spreadsheet, and have this follow through into the style field, or the actual form. As I've seen examples of where users have colour coded questions within the rows of groups in order to organise the spreadsheet.
See example below:
![image](https://user-images.githubusercontent.com/20454586/59076953-f50e7b00-891b-11e9-9e0b-830cca6a62d5.png)

**Comment by J8L** [comment]
Using Grid-Theme border colour is not supported (yet!). I have a group with two groups inside it.

![Grid-Theme_Group_Border1](https://user-images.githubusercontent.com/42594789/59085402-d02cfe80-8941-11e9-87bb-a8ef7dafd45d.JPG)
![Grid-Theme_Group_Border2](https://user-images.githubusercontent.com/42594789/59085411-d6bb7600-8941-11e9-8a14-24e100d85470.JPG)

**Comment by g8f** [comment]
Love the new colour scheme functionality. THANKS.
I was also wondering, if you could look into giving us the ability to edit style colours (found in Settings tab of Survey123 Connect) from the XLX form.
The reason I ask is - this'll then enable us to create surveys using 'dark' or 'light' colour schemes (maybe beneficial for undertaking surveys at night time compared to day time). Ideally, I'd like the current-default settings to be used during the day, and maybe a black background with white text colour for night time.
And even better - we could write a simple JavaScript function to calculate the ambient light - and change the colour scheme on the fly.
Regardless - love this new feature.
Thanks so much,
Gee

**Comment by g8f** [comment]
Hi guys,
Another potential feature request would be to - use **Dynamic Labels** in body::esri:style column. As, I'd like to change the color of a group dependent on answers.
Thanks.
