### ISSUE TITLE
CHALLENGE: Collect polyline and polygon using the web app

### ISSUE THREAD

**Issue by oopsliu** [tedrick/Survey123-Testing#232]
With version 3.5 of Survey123 web app we have added the support for polyline and polygon question types in addition to the geopoint question type. You can now collect polyline and polygon using the web app on a desktop browser(Safari, Chrome, Firefox, Edge and IE11) or a mobile browser (Safari and Chrome).

![image](https://user-images.githubusercontent.com/7564300/59048229-fc03a200-88b7-11e9-897d-41452af055ff.png)
![image](https://user-images.githubusercontent.com/7564300/59048283-1473bc80-88b8-11e9-9fad-6af042aedf83.png)

The challenge is to **submit responses to both polyline and polygon questions (these two question types has to be created by Survey123 Connect) using desktop and mobile browsers**, and please comment with your observations / feedback.

**Comment by BrandonArmstrong** [comment]
This was not ready to be tested
