### ISSUE TITLE
FEEDBACK: Change survey status to open or closed

### ISSUE THREAD

**Issue by oopsliu** [tedrick/Survey123-Testing#233]
With version 3.5 of Survey123 website we have added the Survey status section of the **Collaborate** tab, which provides the option to prevent responses to your survey. When your survey is closed, no users will be able to submit any responses to it, and will be presented with a message provided by you when they attempt to access your survey. A survey can either be opened and closed manually, or scheduled to only be open for a specific time.

![image](https://user-images.githubusercontent.com/7564300/59017390-04d38400-8876-11e9-8909-34eee2ad5da9.png)

> Note: This feature is currently only available in the Survey123 web app. Closing to responses is not honored by the Survey123 field app.

Please comment with your observations / feedback

**Comment by BrandonArmstrong** [comment]
Francisco
Morgan

**Comment by morganwaterman** [comment]
Great! I tested the closed message and scheduling functionality in multiple browsers and everything worked as expected. I also confirmed that the field app does not yet support the status functionality--you can download/submit surveys from the field app when the survey is closed.

**Comment by fandrade86** [comment]
The testing for this was successful.

I marked the survey as closed and i was unable to access the survey via the web browser. 

![Closed](https://user-images.githubusercontent.com/21234095/59069827-47449300-886d-11e9-818a-f527f30dc607.png)

**Comment by BrittanyDahl** [comment]
I got this working successfully for a Survey published from Connect v3.3, once I had changed the version settings to "always use latest version (3.5)". 

![image](https://user-images.githubusercontent.com/20454586/59081431-67d62100-8931-11e9-9d44-d01d696be76e.png)
 
Before ticking that option, I could hit the closed button in the Collaborate tab and hit save, but upon going to the survey found that it was not closed.

I think it should be made clear in the documentation that you need to change that version setting if you have published up the survey from an earlier version of connect (even though it gave me the options to try to close the survey, it won't work). 


![example_of_survey123_closing issue](https://user-images.githubusercontent.com/20454586/59081792-555ce700-8933-11e9-9751-9aa262532cb1.gif)

**Comment by zhif7782** [comment]
@BrittanyDahl , thank you for the feedback, will add a corresponding message in the UI.

**Comment by BrandonArmstrong** [comment]
Thank you for testing @BrittanyDahl @fandrade86 @morganwaterman 

feedback added to interal issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/1439
