### ISSUE TITLE
FEEDBACK: Survey123 Enterprise On Premises installer

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#235]
Feedback will be related to testing of the Survey123 website on-premises installation.

Installation files and instructions can be found at the Early Adopter Community:
[Documentation](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid=%7B5a8e51ed-4a87-43fe-a67d-2b7829af130f%7D&artid=%7B069BB65F-7C30-4422-B48A-DA5DFE1859FE%7D)
[Download](https://earlyadopter.esri.com/project/version/default.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid=beb1a53bed9e470e9b609402a33d970b)

Please try to install (and connect to your ArcGIS Enterprise installation) and provide feedback.

**Comment by jill-edstrom** [comment]
When going through the postInstall, it's confusing to have "ArcGIS Enterprise URL" written twice and then have "https://www.arcgis.com" as the example.  It would make more sent to only have "ArcGIS Enterprise URL" written once and then provide an example of an Enterprise URL, with the web adaptor name included.

![PostInstall1](https://user-images.githubusercontent.com/8356246/62961931-9f8a9a80-bdb2-11e9-93d3-ab669e42a3f5.PNG)

**Comment by jill-edstrom** [comment]
Survey123 should be capitalized in this portion of the postInstall.

![PostInstall2](https://user-images.githubusercontent.com/8356246/62962082-fa23f680-bdb2-11e9-97cc-fb37d8d2721d.PNG)

**Comment by jill-edstrom** [comment]
When going through the post-install, I have some suggestions that could make the workflow potentially clearer:

- State that 5443 and 8080 are the default ports for Survey123 Enterprise On-Premise.  Just allowing users to put in any ports they want may have them try for a port they are familiar with, such as 443 or 6443 - which would cause problems for the user.

- Be consistent with the post-install being called "post-install" or "postInstall".

- Be clear on what PFX file we're supposed to point to.  At first, I thought it was the PFX file for the machine where Survey123 is installed, not the PFX file already associated with Portal for ArcGIS.  Lucky for me, this was the same PFX file since I'm working with a single machine site but this won't always be the case for users.

- Consider changing PFX "passphrase" to PFX "password" as this the term associated with PFX files.

**Comment by mgayheart1** [comment]
Consider supporting a 1-M relationship between the on prem Survey123 api and portals. It would be helpful for large enterprise customers to be able to centralize a single in house S123 api instance that serves multiple portals they maintain. A good example of Esri tech supporting multiple portals is ArcGIS Pro, which allows you to switch active portals. Right now, the config file points at a single portalUrl, but it seems like the key could be "portals" and either be an array of urls or a dictionary of portal names to portal urls.

**Comment by jill-edstrom** [comment]
When adding the redirect URIs for the on-premise installation, my portal's URL was already listed in the JSON.  Based on the PDF, I would have thought it shouldn't have showed up at all.

![OAuth](https://user-images.githubusercontent.com/8356246/62964394-c3041400-bdb7-11e9-998d-f46fbcc823c8.PNG)

**Comment by mgayheart1** [comment]
![image](https://user-images.githubusercontent.com/13985570/62964455-e16a0f80-bdb7-11e9-967e-0e65ef59710f.png)

**Comment by Zachary-Sutherby** [comment]
Saved Portal for ArcGIS credentials yields an "Invalid token" message when running the post install. 

With credentials saved in web browser: 

![Creds1](https://user-images.githubusercontent.com/54078266/62965535-28f19b00-bdba-11e9-8d94-0f77ca339b24.JPG)

Post installer message: 

![Creds2](https://user-images.githubusercontent.com/54078266/62965556-33139980-bdba-11e9-8449-3ab3fb4f41db.JPG)

With credentials not saved in web browser: 

![Creds3](https://user-images.githubusercontent.com/54078266/62965597-458dd300-bdba-11e9-80be-8498755e05fa.JPG)

Post installer works as expected: 

![Creds4](https://user-images.githubusercontent.com/54078266/62965623-50486800-bdba-11e9-9f6d-2d7c3f2532c6.JPG)

Behavior was reproducible in Google Chrome (76.0.3809.100), Mozilla FireFox (68.0.1), and Internet Explorer (11.3085.14393.0).

**Comment by mgayheart1** [comment]
Would be nice for tab to move between Label, Hint, etc. to make filling out survey simpler.
![image](https://user-images.githubusercontent.com/13985570/62965284-89340d00-bdb9-11e9-860d-2ec8e3e06751.png)

**Comment by mgayheart1** [comment]
After I create a survey online, I can download it from S123 Connect. If I try to Update the survey, it fails.
![image](https://user-images.githubusercontent.com/13985570/62966824-b0d8a480-bdbc-11e9-99e2-1967289be510.png)

**Comment by mgayheart1** [comment]
After downloading my survey in S123 Connect, it doesn't preview the same as it looks in S123 online. Examples:
1. The survey description is added as it's own page.
2. Only a subset of questions are displayed on page 2 (which should be page 1).
3. The final page is empty.

When I look at the excel file that was downloaded, it seems to be a reasonable representation of the survey I created so I don't know why the preview is so different.

![image](https://user-images.githubusercontent.com/13985570/62967122-365c5480-bdbd-11e9-9e28-1d8cbd4751f9.png)

**Comment by mgayheart1** [comment]
2 of 3 options in Online button of S123 connect don't behave correctly.
![image](https://user-images.githubusercontent.com/13985570/62967659-432d7800-bdbe-11e9-9681-eba14c2d576f.png)

1. Open in Survey123 web app opens to https://dev0009396.esri.com/share/ff0cf8e39c804b68890b0897d6ba0a61?portalUrl=https://dev0009396.esri.com/portal. It should open to https://dev0009396.esri.com:5443/share/ff0cf8e39c804b68890b0897d6ba0a61?portalUrl=https://dev0009396.esri.com/portal (note the 5443 port).

2. Open in Survey123 website opens to https://survey123.arcgis.com/surveys/ff0cf8e39c804b68890b0897d6ba0a61/overview?portalUrl=https:%2F%2Fdev0009396.esri.com%2Fportal. It should open to https://dev0009396.esri.com:5443/surveys/ff0cf8e39c804b68890b0897d6ba0a61/overview?portalUrl=https:%2F%2Fdev0009396.esri.com%2Fportal.

**Comment by mgayheart1** [comment]
Consider adding the redirect url step in Portal Admin to the post-install of survey123 api. This would require user to provide admin user / pwd. This might break the paradigm of my earlier comment about supporting 1-M portals. You would have to include a workflow of adding a portal to survey123 on prem website that would do the portal admin step on the backend and would prompt for admin user/password.

**Comment by jill-edstrom** [comment]
Is there a way to connect from the Portal home app to Survey123 ...:5443?  Other apps, such as Insights, will show up in the app launcher once installed.

![PortalHome](https://user-images.githubusercontent.com/8356246/62968659-5e00ec00-bdc0-11e9-898d-a458977dbb65.PNG)

**Comment by mgayheart1** [comment]
After making a small change to survey in S123 connect (changed the label of a page), I tried to publish the survey. It hangs on 

> Getting service information

 and the log file has this final entry:

> <15>1 2019-08-13T19:58:00Z Dev0009396 Survey123ConnectforArcGISBeta 35152 - [AppStudio@11205 category="qml" function="onSuccess" filename="PublishServiceCheck.qml" line="644"] qml: Feature serviceInfo: https://dev0009396.esri.com/server/rest/services/Hosted/survey123_ff0cf8e39c804b68890b0897d6ba0a61_fieldworker/FeatureServer -> {
>   "allowGeometryUpdates": true,
>   "capabilities": "Create,Editing,Query,Update,Uploads,Sync",
>   "copyrightText": "",
>   "currentVersion": 10.71,
>   "description": "",
>   "editorTrackingInfo": {
>     "allowAnonymousToDelete": false,
>     "allowAnonymousToUpdate": false,
>     "allowOthersToDelete": false,
>     "allowOthersToQuery": false,
>     "allowOthersToUpdate": false,
>     "enableEditorTracking": true,
>     "enableOwnershipAccessControl": true
>   },
>   "enableZDefaults": false,
>   "fullExtent": {
>     "spatialReference": {
>       "latestWkid": 4326,
>       "wkid": 4326
>     },
>     "xmax": 180,
>     "xmin": -180,
>     "ymax": 90,
>     "ymin": -90
>   },
>   "hasVersionedData": false,
>   "initialExtent": {
>     "spatialReference": {
>       "wkid": 4326
>     },
>     "type": "extent",
>     "xmax": 180,
>     "xmin": -180,
>     "ymax": 90,
>     "ymin": -90
>   },
>   "isLocationTrackingView": false,
>   "layers": [
>     {
>       "id": 0,
>       "name": "surveyPoint"
>     }
>   ],
>   "maxRecordCount": 2000,
>   "maxViewsCount": 0,
>   "serviceDescription": "View Feature Service (fieldworker) for survey ff0cf8e39c804b68890b0897d6ba0a61",
>   "serviceItemId": "66f8268437534c5280fc32e31f634fba",
>   "sourceSchemaChangesAllowed": true,
>   "spatialReference": {
>     "latestWkid": 4326,
>     "wkid": 4326
>   },
>   "supportedQueryFormats": "JSON",
>   "supportsApplyEditsWithGlobalIds": true,
>   "supportsDisconnectedEditing": false,
>   "supportsReturnDeleteResults": true,
>   "syncCapabilities": {
>     "supportsAsync": true,
>     "supportsAttachmentsSyncDirection": true,
>     "supportsPerLayerSync": true,
>     "supportsPerReplicaSync": false,
>     "supportsRegisteringExistingData": true,
>     "supportsRollbackOnFailure": false,
>     "supportsSyncDirectionControl": true,
>     "supportsSyncModelNone": true
>   },
>   "syncEnabled": true,
>   "tables": [
>     {
>       "id": 1,
>       "name": "metadata"
>     }
>   ],
>   "units": "esriDecimalDegrees"
> }
> <12>1 2019-08-13T19:58:00Z Dev0009396 Survey123ConnectforArcGISBeta 35152 - [AppStudio@11205 category="default" filename="PublishServiceCheck.qml" line="286"] qrc:/qml/Connect/PublishServiceCheck.qml:286: **_TypeError: Cannot read property 'tableName' of undefined_**
> <15>1 2019-08-13T19:58:03Z Dev0009396 Survey123ConnectforArcGISBeta 35152 - [AppStudio@11205 category="Portal" function="expression for onStateChanged" filename="Portal.qml" line="240"] Portal: Application state changed: 2
>

**Comment by mgayheart1** [comment]
To test the Update process in S123 connect, I switched the api back to the survey123.esri.com/api location. When updating, I get this error:
![image](https://user-images.githubusercontent.com/13985570/62973997-17b18a00-bdcc-11e9-917f-d4f21d1340ea.png)

In looking at the excel file, it looks like the survey description is being created as if it was a group without a label. This may explain why S123 wasn't previewing the survey correctly.

![image](https://user-images.githubusercontent.com/13985570/62974161-72e37c80-bdcc-11e9-8fc0-a7da0ec55820.png)

**Comment by Zachary-Sutherby** [comment]
When changing the Survey status using the On-Premises install using a survey that was published from Survey123 Connect (3.5.166) the message "Failed to save: {"error":{"code":400,"messageCode":"CONT_0102","message":"Info file for item not found","details":[]}}" is obtained. The Survey status does indeed change, the browser window just needs to be refreshed. The behavior is not reproducible when using a survey created and published using the web designer. 

 Initially clicking save: 

![Surveystatus](https://user-images.githubusercontent.com/54078266/62974606-762b3800-bdcd-11e9-9970-9ab1db5f5b1b.JPG)

After refreshing the web browser: 

![Surveystatus1](https://user-images.githubusercontent.com/54078266/62974623-7d524600-bdcd-11e9-86be-e3da337ea09d.JPG)

**Comment by Zachary-Sutherby** [comment]
I am not 100% sure if this is the correct workflow, but to add the on-premise install of Survey123 to the App Switcher in Portal for ArcGIS I added an application and choose "Web Mapping", "Ready to Use", "JavaScript", specified the URL as "https://some-machine.domain.com:5443?portalUrl=https://some-othermachine.
domain.com/webAdaptorName" , and gave it a title and tags. 

From there I copied the URL from the Item Details page and went to the Portal settings > General > Add app > for App Item URL paste the URL from the Item Details page. 

I was then able to access the on-premise install of Survey123 for ArcGIS using the App Switcher waffle. 

After clearing the browser cache I logged back into my Portal for ArcGIS and selected the Survey123 application I had created. A new tab opens trying to access the login page and the page just loops in a refreshing state and never loads. 

![AppSwitcher](https://user-images.githubusercontent.com/54078266/62979787-982ab780-bdd9-11e9-9d3b-421f7145936e.JPG)

**Comment by Shwujeng** [comment]
Submitted by Ariel from disconnected lab:
Post install pages
1. Consider offering an example of how to format the enterprise url (ex: should /portal be included?)
2.  why is ArcGIS Enterprise URL listed twice?
![image](https://user-images.githubusercontent.com/29442153/62984235-3e30ee80-bde7-11e9-9912-db92ce47a9bd.png)
3. Consider not having survey123hub be the default since hub is a different product that is not compatible with enterprise, maybe survey123website?
4. Consider specifying on the below page that if you change the app id name you will need to go re-register the item
![image](https://user-images.githubusercontent.com/29442153/62984259-60c30780-bde7-11e9-9569-ad68976ab752.png)
Consider specifying that it should be the web adaptor name for your portal
![image](https://user-images.githubusercontent.com/29442153/62984278-746e6e00-bde7-11e9-8e5b-be49acccfad0.png)
Can there be some context around 5443 being the survey123 port and when this should be changed?
![image](https://user-images.githubusercontent.com/29442153/62984307-8819d480-bde7-11e9-8eae-8131e45d52c3.png)
Consider specifying that you want the portal cert and changing the wording to something like "Choose the type of https certificate used for your portal"
![image](https://user-images.githubusercontent.com/29442153/62984326-9667f080-bde7-11e9-9d19-25e965cd944c.png)
1. Change the word server, it's the survey123 service
2. Make the word or more prominent, right not reads like you should do both
Say what to do after you restart the service
![image](https://user-images.githubusercontent.com/29442153/62984339-a7186680-bde7-11e9-8a88-20c32b81798c.png)

**Comment by Shwujeng** [comment]
Reported by Ariel:
Signing in to the webpage
Was still using arcgis.com until I cleared my cache
![image](https://user-images.githubusercontent.com/29442153/62985626-147ac600-bded-11e9-8a3b-dd6f6ee9ee51.png)

**Comment by Shwujeng** [comment]
Reported by Ariel:
Portal Item
Consider having an item in portal or some way to get from portal to the website w/o having to enter a url into the browser.

**Comment by Shwujeng** [comment]
Reported by Ariel:
Map in Analyze tab
The map in the analyze tab doesn't load, it's calling an agol basemap.
![image](https://user-images.githubusercontent.com/29442153/62985708-5efc4280-bded-11e9-8962-baa31117680b.png)
![image](https://user-images.githubusercontent.com/29442153/62985710-61f73300-bded-11e9-8d06-933ab9ad972d.png)

**Comment by Shwujeng** [comment]
Reported by Ariel:
Data Page Doesn't Load.
Making calls to arcgis.com for basemap but the layer doesn't load either.
![image](https://user-images.githubusercontent.com/29442153/62985750-8bb05a00-bded-11e9-9171-7a7c37448444.png)
