### ISSUE TITLE
FEEDBACK: Single choice grid

### ISSUE THREAD

**Issue by marikavertzonis** [tedrick/Survey123-Testing#237]
-   A set of select_one questions that all use the same choice list.
 -   A group that contains the select_one questions which has the table-list appearance.
 - For more info see https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={53842113-1E06-44F6-8C35-03157C5DB6C3}

**Comment by fandrade86** [comment]
The single choice grid works great. Created a survey for customer satisfaction and it looks great. See recommendation on image below. It would be great that the creator of the survey123 would have more control over the size.

![9-6-2019 11-21-35 AM](https://user-images.githubusercontent.com/21234095/64451331-cfb71780-d098-11e9-8eb6-b975d87e1482.png)

**Comment by zhif7782** [comment]
@fandrade86 , thank you for the feedback. Do you expect to expand the form on-the-fly only for this question or expand the entire survey when publishing if you know there's such question in the survey? We have an issue in our backlog to support the "widescreen" mode in the web app so the form with can adjust the width of the screen, can this satisfy the need?

**Comment by fandrade86** [comment]
The expanding would be for the form as a whole. I believe the widescreen would take care of the request.

**Comment by zhif7782** [comment]
Thanks for the confirmation.
