### ISSUE TITLE
Enhancement: Handling existing install

### ISSUE THREAD

**Issue by jfangit** [tedrick/Survey123-Testing#24]
**Application:** Connect

**Device:** Windows

**Operating System:** Windows 10

**Browser:** Chrome

**Error Description:**  Handling the existing install more gracefully. Maybe ask the use if you want to uninstall and then uninstall the existing version before installing the current version.

**How to reproduce:** Have 2.3 installed. Try to install 2.4 beta.

**Have you tested with another survey?**  No

**Comment by JohnHasthorpe** [comment]
2.4 testing complete

**Comment by JohnHasthorpe** [comment]
Internal issue: https://devtopia.esri.com/Melbourne/Survey123/issues/1913
