### ISSUE TITLE
CHALLENGE: Where near me

### ISSUE THREAD

**Issue by marikavertzonis** [tedrick/Survey123-Testing#241]
The goals of this challenge are to
- Use an offline basemap in Survey123
- Capture a line or polygon by using your physical location

Steps:
- Half the group will capture a line feature, the other half a polygon. You will be allocated one or the other.
- Use the same survey as you used for the **Where in the world** challenge
- Add the supplied offline basemap to your survey so it can be used
- Ensuring device is offline, go outside and capture the feature by walking the boundary or length of the feature capturing vertices
- As a group come back and compare the results to the reference features in the **Where near me** webmap. Whose ever line or polygon best matches the reference feature, wins all the glory!

**Comment by danjoyce-origin** [comment]
I think the add vertex at map cross-hair is kind of redundant.  It's more intuitive to add a point by tapping on the map, which is the default behaviour.

**Comment by g8f** [comment]
First point can't be my current location

**Comment by brettstokes** [comment]
Thanks @g8f. I've created an internal issue and linked to your comment.
