### ISSUE TITLE
FEEDBACK: Polygon/Line collection (Field App)

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#242]
Geotrace (line) and geoshape (polygon) question types are now supported. To get started, all you need to do is include a **geotrace** or **geoshape** question type into your XLSForm and publish via Connect. Current survey templates do not yet include these new questions types in the XLSForm -  they don't appear in the drop-down list. You will need to add geotrace or geoshape manually to your form.
![xlsform](https://user-images.githubusercontent.com/1319289/64195240-d85be380-ce35-11e9-9555-5f913332ce8e.png)

## Line / Polygon capture methods

Feedback from the 3.3 Beta implementation led us to introduce distinct methods for line / polygon capture. Initially we have added *sketch* and **vertex**, which are mutually exclusive geometry capture methods that apply to both lines and polygons in the 3.6 Beta builds. The method is specified in the **body::Esri:style** column of your geotrace or geoshape questions using the tags `method=sketch` or `method=vertex`. If no method is specified in your XLSForm, sketch is applied. The `method=vertex` tag is automatically added to geotrace and geoshape questions for surveys that are created from existing line / polygon feature layers, but this can be removed if required. 

## Custom Styling for Lines and Polygons

The 3.6 Beta builds add the ability to customise basic styling for lines (color and width) and polygons (line / fill color and width). Styling customizations are made using the following tags in the **body::esri:style column** of your geotrace and geoshape questions:

- **lineColor=**  applies to lines and polygons
- **lineWidth=** applies to lines and polygons
- **fillColor=** applies to polygons only

Colors may be specified by *HTML Name* or even made partially transparent using a Hexadecimal Color Code (#AARRGGBB).  Multiple tags are separated by a space, eg: `lineColor=black fillColor=#800000FF lineWidth=3`.

Please create surveys with polygons or lines, using the different capture methods and provide feedback

**Comment by g8f** [comment]
Enhancement request - Ability to calculate lats and lons of vertices from a 'geotrace' or 'geoshape' question type into a text field. I understand this probably could be done using webhooks and looking into the geometry attribute or by using repeats (and adding points individually)
Gee

**Comment by brettstokes** [comment]
@g8f I've logged the enhancement request for adding pulldata @geotrace & pulldata @geoshape. Thanks!

**Comment by DerekLaw** [comment]
Tested the geotrace capability - very cool! 2 comments:

1. The current help doc topic (Lines and Polygons) does not mention that you can select the newly added feature and rotate the map, then also return to "north view" - this was shown to me by @BrandonArmstrong - this might be worth adding in the doc.

2. I tried out the geotrace question in a web form - seems to work well, but I don't think the UX for the undo/redo buttons work well. I was not able to use either tool. I would draw a line, then attempted to click undo and it was not selectable. 

![Undo_option_not_available](https://user-images.githubusercontent.com/1037228/64449923-cc6e5c80-d095-11e9-9271-819968d51dfb.png)

**Comment by sbubka94** [comment]
When testing out data collect in Connect, the blue circle indicating my GPS location is obstructing the view. Seems unnecessarily large.
![image](https://user-images.githubusercontent.com/22916127/64450407-f70ce500-d096-11e9-8ba8-db871c257a80.png)
![image](https://user-images.githubusercontent.com/22916127/64450443-0be97880-d097-11e9-8cdd-7ac694ecc835.png)

**Comment by sbubka94** [comment]
In the same setting (Connect), when I first enter the geoshape question and attempt to use the scroll wheel on the mouse to scroll out, it automatically zooms back into my fixed location. The + and - buttons do the same behavior. You have to leave the map and come back for the behavior to stop.

**Comment by sbubka94** [comment]
I think there should be a "trash" button for erasing the sketch, rather than just incorporating the "delete" function into the sketch button.

**Comment by Zachary-Sutherby** [comment]
When specifying two parameters in the body::esri:style column if specified incorrectly using a comma instead of a space the geotrace question type does not display the sketch options in the field app. 

The Geoshape question type does not see the same behavior. When using the correct workflow using a space the behavior is not reproduced.  

![SurveyStyleIncorrectParam](https://user-images.githubusercontent.com/54078266/64451649-7dc2c180-d099-11e9-8729-b4f9ba6b0591.JPG)

**Comment by Zachary-Sutherby** [comment]
When a Geotrace or Geoshape question types are nested in a repeat and the map parameter is specified in the body::esri:style column. The web map does not display in Survey123 Connect when previewing the survey. It displays perfectly fine in the field app, just not the preview in Survey123 Connect. 

The behavior is not reproducible with Geopoint questions types in repeats, only Geotrace and Geoshape. 

![S123ConnectWM1](https://user-images.githubusercontent.com/54078266/64452850-14907d80-d09c-11e9-9f50-623c72cab285.JPG)
![S123ConnectWM2](https://user-images.githubusercontent.com/54078266/64452853-165a4100-d09c-11e9-8fe5-5b49b005bfff.JPG)

**Comment by sbubka94** [comment]
Smart shapes do not work for "angled" shapes, so a rectangle that isn't perfectly facing north will not draw on the angle.
