### ISSUE TITLE
FEEDBACK: Polygon/Line Collection (Web App)

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#243]
Geotrace (line) and geoshape (polygon) question types are now supported. To get started, all you need to do is include a **geotrace** or **geoshape** question type into your XLSForm and publish via Connect (support for authoring via the web designer will come in a future version of Survey123). Current survey templates do not yet include these new questions types in the XLSForm -  they don't appear in the drop-down list. You will need to add geotrace or geoshape manually to your form.
![xlsform](https://user-images.githubusercontent.com/1319289/64195240-d85be380-ce35-11e9-9555-5f913332ce8e.png)

Provide feedback on collecting polygons and lines via the web app.

**Comment by g8f** [comment]
Future enhancement request - ability to calculate all lats and lons of vertices from a 'geoshape' or 'geotrace' question type - into a text type question. I believe this probably could be done using webhooks and looking into the 'geometry' attributes, or by using repeats (and adding them as individual points).

**Comment by fandrade86** [comment]
Tested Polygons with smart shapes and free hand sketch and no issues found. It is great how the measurement is displayed once the polygon is displayed.

**Comment by DerekLaw** [comment]
I tried out the geotrace question in a web form - seems to work well, but I don't think the UX for the undo/redo buttons works well. I was not able to use either tool. I would draw a line, then attempted to click undo and it was not selectable. 

EDIT: The undo/redo works for the "by vertex edit mode", not for sketch edit mode. Although the help doc suggests that undo is available with the sketch option.

![Undo_option_not_available](https://user-images.githubusercontent.com/1037228/64449923-cc6e5c80-d095-11e9-9271-819968d51dfb.png)

**Comment by DerekLaw** [comment]
After I drew a line feature in a web form, the line length was shown in the geotrace question - but the value was not calculated in the following line length calculation question. This same set-up works in the mobile app. Is this expected?

Mobile App (on Android)

![1](https://user-images.githubusercontent.com/1037228/64450988-122c2480-d098-11e9-94e3-5221a6f8715e.png)

Web Form

![2](https://user-images.githubusercontent.com/1037228/64451002-19533280-d098-11e9-885b-8536e7641f66.png)

**Comment by zhif7782** [comment]
@DerekLaw , thanks for the feedback. Created an internal issue https://github.com/ArcGIS/survey123-webform/issues/669 to implement the `distance()` and `area()` in the web app, also will try to hide undo/redo for the sketch mode which they actually cannot be used to reduce the confusion.
