### ISSUE TITLE
FEEDBACK: distance() and area() functions

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#244]
Geotrace and geosphape questions can also by used in calculations to display and record geometry attributes such as length (line), and perimeter & area (polygon). The `distance()` and `area()` functions are used to build an expression with the geotrace or geoshape question. The functions will return the length in meters and area in square meters so you may need to convert these or perhaps round them in your calculations depending on your requirements.

**Comment by DerekLaw** [comment]
I tested the distance function and it worked well, Looked good in the survey in the mobile app, but this did not seem to work in the web form, is this expected?

Mobile app:

![1](https://user-images.githubusercontent.com/1037228/64458602-9f787480-d0aa-11e9-8fd4-8c0da2be178c.png)

Web form:

![2](https://user-images.githubusercontent.com/1037228/64458606-a30bfb80-d0aa-11e9-9bc1-0988e5557a28.png)

**Comment by zhif7782** [comment]
@DerekLaw , thanks for the feedback. `distance()` and `area()` functions are not supported in the web app yet, created an internal issue for this: https://github.com/ArcGIS/survey123-webform/issues/669.
