### ISSUE TITLE
CHALLENGE: Map handicapped parking in Esri Campus

### ISSUE THREAD

**Issue by IsmaelInRedlands** [tedrick/Survey123-Testing#246]
1- Open this survey in the Survey123 field app: https://arcg.is/C0D5e  and then put your phone in airplane mode and disable WIFI.

![aa](https://user-images.githubusercontent.com/5918689/64454177-2f182600-d09f-11e9-85b0-3413b5b3de3b.png)

2- Get outside and create polygons for every handicapped parking area you see. We do not want you to create a polygon for every parking spot, just for the areas. Work in disconnected mode.
3- For each of the handicapped parking areas, specify how many parking spots it contains.  Capture no less than 3 areas in total.
4- Once back in the office, count the polygons you captured in the Outbox folder and submit all data
5- Review all submitted data and experience with Ismael when you are  back in the holistic lab
* Did all polygons you captured successfully upload?
* Any crashes during data capture?
* Any other issues?

**Comment by NeilMYoung** [comment]
I found it worked fairly well. I submitted 3 polygons. The map was just a grey background, but I assume that is because I am not in Redlands... It would be nice to have option of to stream gps vertices. Maybe its there and I missed it.

**Comment by IsmaelInRedlands** [comment]
@NeilMYoung   You care correct, the offline map was constrained to Redlands.

**Comment by IsmaelInRedlands** [comment]
When attempting to drop a vertex in the trash can, the compass icon is on the way. 
Reported by Deborah.

**Comment by IsmaelInRedlands** [comment]
@zhif7782  When reporting area, we should adjust the units.
![Untitled](https://user-images.githubusercontent.com/5918689/64457725-43acec00-d0a8-11e9-90e4-84f4689f00e3.png)

**Comment by IsmaelInRedlands** [comment]
@zhif7782  No need to show the length and area fields in the table. They should be notvisible by default like ObjectID, GlobalID, CreationDate etc
![Untitled2](https://user-images.githubusercontent.com/5918689/64458255-b10d4c80-d0a9-11e9-84d6-d82f75c5cc41.png)

**Comment by IsmaelInRedlands** [comment]
Usability feedback geotrace and geoshape: @phil-wilson https://www.youtube.com/watch?v=xX3d_-1-XQM

**Comment by DerekLaw** [comment]
I performed this test, everything worked fine for me. I was able to download the survey without any issues, when I switched to airplane mode and no wifi, the tile package loaded fine. I went outside and was able to collect 3 polygon features using the vertex edit mode. Returned back to the lab and was able to submit the surveys after getting back on the wifi.

Using Google Pixel 2 device, Android v9

**Comment by IsmaelInRedlands** [comment]
Users are currently allowed  to create 2-vertex polygons. These polygons fail to submit. 
See video. 
http://www.youtube.com/watch?v=89N-DO0G-AE

**Comment by IsmaelInRedlands** [comment]
@zhif7782  Checked polygons in reports. Working good.

**Comment by zhif7782** [comment]
Internal issues:
* Hide length/area columns for polyline/polygon: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3876
* Auto adjust the length/area unit if the user has not changed it manually: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3877
