### ISSUE TITLE
Need to re sign in every time go from Settings back to Gallery

### ISSUE THREAD

**Issue by marikavertzonis** [tedrick/Survey123-Testing#250]
**Application:** Connect

**Device:** Windows Desktop

**Operating System:** 10

**Error Description:** 
Users are going into Settings to enable Standard maps, even if they hit Cancel, when they return to the gallery they are signed out. Whilst figuring out why expected link content is not appearing, users are going back to settings several time to be sure, and they keep getting signed out.

**Comment by phil-wilson** [comment]
Related internal dev issue: https://devtopia.esri.com/Melbourne/Survey123/issues/3332

**Comment by phil-wilson** [comment]
This has been fixed in the final 3.6 release.
