### ISSUE TITLE
BUG: .tpk offline basemap zoom and scale error

### ISSUE THREAD

**Issue by Leeevans-aecom** [tedrick/Survey123-Testing#251]
**Application:** Field App

**Device:** DELL Precision 5530

**Operating System:** Windows 10

**Browser:** MS Edge

**Error Description:**  The .tpk offline basemap continues to zoom but the feature does not scale when the Level of Detail is exceeded (Manage Areas).

**How to reproduce:** Drawing a polyline over the downloaded basemap

**Have you tested with another survey?** No
[Survey123 for ArcGIS 5_09_2019 1_14_38 PM.zip](https://github.com/tedrick/Survey123-Testing/files/3577422/Survey123.for.ArcGIS.5_09_2019.1_14_38.PM.zip)

**Comment by phil-wilson** [comment]
Thanks @Leeevans-aecom. We have a current known issue with zooming past the extent of the min/max zoom level of the layer which is more apparent when using offline web map areas.

I have linked this issue and your comments to our internal issue for more investigation: https://devtopia.esri.com/Melbourne/appstudio-plugins/issues/144

**Comment by phil-wilson** [comment]
This has been fixed and will be available in the final 3.6 release.
