### ISSUE TITLE
upload log file option

### ISSUE THREAD

**Issue by efernandez-esriau** [tedrick/Survey123-Testing#252]
A suggestion ( a new feature enhancement maybe?). When users send data back, could there be an option to send back the log file ( if logging is enabled) to either Portal\AGOL or to an inbox? Alternative to retrieving the log files from the device\iTunes?

**Comment by phil-wilson** [comment]
Thanks @efernandez-esriau. We already have this in our backlog as an enhancement to be able to send logs via email or another method automatically. I have added your comments to the issue.

Internal dev issue: https://devtopia.esri.com/Melbourne/Survey123/issues/899
