### ISSUE TITLE
FEEDBACK: Map UX enhancements (Web App)

### ISSUE THREAD

**Issue by zhif7782** [tedrick/Survey123-Testing#253]
In 3.6 release, the web app introduces two UX enhancements for the map:
* Large map mode for a desktop browser: There's a new enlarge map icon on the map so you can expand the map size to capture a geometry more easily.
  * This applies to geopoint, geotrace, geoshape questions.
  * ![aaa](https://user-images.githubusercontent.com/7665168/64324855-b27f3c00-cff9-11e9-93b2-bccd652f4f41.gif)
* Click to set location: For a geopoint question, previously, you need to pan the map to set the location of the geopoint to the center of the map. In 3.6 release, instead of pan to set location, you can now click the map to set the location of the geopoint question directly.
  * Clicking the locate my position icon or clicking an address search result will now change the geopoint location automatically.
  * For a mobile browser, instead of click to set location, there's a new button in the lower right corner to explicitly set the location the current map center so you can still capture an accurate location on a mobile device.

**Comment by wowallace** [comment]
1. The Map choices - the name Basic (Basemaps only) vs Standard (All) seem very similar to me.
Maybe Basic vs Advanced or All Maps, something more intuitive?

2. Enable Sync seems not to be what it is, according to Ishmael?
Maybe rename it enable index(es), if that is what it is doing?

**Comment by billwie** [comment]
Large map for desktop browser: unable to test due to bug in Survey123Dev against ArcGIS Enterprise 10.5.1. Logged. may circle back around and test against ArcGIS Online

Click to set location: functions in Windows and iOS

**Comment by zhif7782** [comment]
Connect issues handled cc @brettstokes , double checked this works against a 10.5.1 portal.
