### ISSUE TITLE
bind::esri:warning on "select_one yes_no" questions

### ISSUE THREAD

**Issue by g8f** [tedrick/Survey123-Testing#256]
**bind::esri:warning** and **bind::esri:warning_message** don't seem to work on **select_one yes_no** question types @marikavertzonis

**Comment by tedrick** [comment]
@g8f - the bind:esri:warning/bind:esri:warning_message questions work only with geopoint questions at this time.  Can I suggest you file an ENH or ArcGIS Idea to track this?
