### ISSUE TITLE
Transparent blue fill on geotrace or geoshape controls

### ISSUE THREAD

**Issue by billwie** [tedrick/Survey123-Testing#257]
**Application:**  Field App 

**Device:**  Windows 10 x64

**Operating System:** Windows 10 x64

**Browser:** _For the website_

**Error Description:** 
blue transparent fill appears on map when first opened. For geopoint questions once you pan the map this transparent fill disappears, however for geotrace or geoshape the transparent fill remains. only appears to affect windows. IOS is not affected.

**How to reproduce:**

**Have you tested with another survey?**

**Comment by BrandonArmstrong** [comment]
this was likely due to attempted location collection indoors.  Closing
