### ISSUE TITLE
Survey123Dev - TypeError:Cannot read property 'maps' of null against ArcGIS Enterprise

### ISSUE THREAD

**Issue by billwie** [tedrick/Survey123-Testing#258]
**Application:** Website (Survey123Dev)

**Device:** Google Chrome/WIndows

**Operating System:** Windows 10 x64

**Browser:** _For the website_

**Error Description:** Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**How to reproduce:**
Using Survey123Dev against 10.5.1 SAML authenticated portal. Go to any survey and go to the Collaborate tab. Copy the link from "Share this survey" and open in a new tab. I receive this error:

Error: Initializing form...

TypeError: Cannot read property 'maps' of null

**Have you tested with another survey?** Yes, one geopoint, one geoshape survey both authored with Connect 3.6.132

**Comment by zhif7782** [comment]
@billwie , thanks for the feedback. I've created an internal issue https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3879 and expect to fix it before the 3.6 release.
