### ISSUE TITLE
Basic/Standard Map verbiage ideas

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#259]
Basic & Standard are somewhat synonymous in terms of the type of map being used. Other ideas for this option:

Standard & Advanced
Basic & Advanced
Basic & Enhanced
Standard & Enhanced

**Comment by phil-wilson** [comment]
@sbubka94 Thanks for the feedback and suggestions. We actually put a lot of thought and discussion into the name of these two options. The reason we have used "Basic" and "Standard" is that the map types which are now supported as "Standard" are the standard map types that nearly all other Esri applications (desktop and mobile) support. Web maps, vector tile basemaps, vector services, raster services, mmpk, vtpk are all standard map types that Pro, Desktop, Collector, Explorer, Navigator, Web App Builder etc can support in one way or another.

Therefore Survey123 is now supporting the "standard" suite of maps that Esri uses, we are not doing anything additional or special that would warrant calling it enhanced or advanced maps.

The option "basic" therefore makes sense as this option is basic and limited compared to "standard" as it only support raster basemaps and tpks.
