### ISSUE TITLE
Unable to click the gear icon in Connect

### ISSUE THREAD

**Issue by kunjoo91** [tedrick/Survey123-Testing#26]
**Application:** Connect

**Device:** Windows 10

**Operating System:** Windows 10

**Error Description:**  Unable to click the gear icon in Connect (double arrow cursor appears)

**How to reproduce:**

![image](https://user-images.githubusercontent.com/24254822/29838158-3ad6f556-8caf-11e7-9b51-e665d31a3884.png)

**Have you tested with another survey?** Does not apply

**Comment by JohnHasthorpe** [comment]
@kunjoo91 Can you confirm the device you are using?

**Comment by JohnHasthorpe** [comment]
2.4 Testing complete. Closing issue as known issue.
