### ISSUE TITLE
Survey123 Connect UI enhancement

### ISSUE THREAD

**Issue by DerekLaw** [tedrick/Survey123-Testing#260]
This is an enhancement suggestion: for the Survey123 Connect Settings dialog:

![7](https://user-images.githubusercontent.com/1037228/64453654-ead85600-d09d-11e9-9ccf-f0c01e1dcf63.png)

In addition to the option rename as others have suggested, it might be worthwhile to also add 1-2 lines of text (below the 'Map Types' text) that explains what this option allows you to do/functionality. Or minimally, can you please add a hyperlink to the appropriate help topic that explains what this does?

**Comment by DerekLaw** [comment]
Q: What is the logic behind the arrangement/order of the "sub menu" items that appear when you click 'Settings' in Connect?

Right now it seems kind of random, can you perhaps sort them in alphabetical order (left to right)?

![8](https://user-images.githubusercontent.com/1037228/64459182-267a1c80-d0ac-11e9-8375-802071b1f870.png)

**Comment by phil-wilson** [comment]
@DerekLaw Thanks for the feedback. Hyperlinks to doc do not work on all platforms as the doc is not mobile friendly in all cases on website. So while this will work on desktop, it may not work on small mobile devices well. The description of these options will be well documented. Eventually standard will be the default and basic will be removed. For this initial release of additional maps we have chosen to keep basic as default to minimise impact this may have on people who are using raster basemaps. 

As for the order of tabs in Connect settings, currently they are in order of workflow/most used. When creating a survey the General, Style and Map tabes would be used most, whereas the Inbox, Sent and Linked Content would be used left often once set the first time.
