### ISSUE TITLE
Keyboard issues on iOS

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#262]
**Application:** Field App 

**Device:** iPhone xs Max

**Operating System:** iOS 12.4

It may be useful to include some "how-to" tips for the keyboard on iOS considering it's much less intuitive than the Android keyboard. In the image below, the keyboard covers the Photo image and there is no "done" or "collapse" keyboard button like in Android. You have to lightly swipe down on the keyboard to get it to disappear, which is not very intuitive unless you happen to know the trick.

![image](https://user-images.githubusercontent.com/22916127/64460559-86be8d80-d0af-11e9-9c5f-5b2bdc59cee4.png)

**Comment by phil-wilson** [comment]
@sbubka94 Thanks for this feedback, unfortunately this behaviour is controlled by iOS and we can not change or modify how or when the keyboard appears or when it covers or does not covers button. iOS applies some logic to when it should cover or not cover parts of the screen depending where the input control and cursor is currently located on the screen.

As we use a keyboard with return to ensure the input will tab to next control, the done button which will minimise keyboard can not be displayed as well.

I have created a doc issue to add a FAQ about how to minimise the keyboard on iOS.
