### ISSUE TITLE
Strangeness when going from Connect to Web

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#263]
**Application:**  Website

**Browser:** Edge

**How to reproduce:**
>Create survey in Survey123 Connect
>Go to survey123dev.arcgis.com
>Go to Design tab of the survey
>Change the theme color
>Publish > NOTE: It says "all changes will be saved" > Publish
>Switch to another tab > NOTE: it prompts you to save your changes
>If you click Don't Save, the Design page will revert to your original theme but the published survey does show the new theme color...

Also when I do this, it breaks geoshape and geotrace questions. Even if I go back to Connect and republish from there, the map remains broken on the web.

**Comment by zhif7782** [comment]
@sbubka94 , thanks for the feedback. I can reproduce the "it prompts you to save your changes" issue. cc @oopsliu 

Could you provide more information on how the publishing breaks geotrace/geoshape questions? Does it break the question itself or the map associated with the question, e.g. set in the body::esri:style column?

**Comment by oopsliu** [comment]
Created internal issue for the save theme issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3880
