### ISSUE TITLE
Linked Content - Enhancement Request

### ISSUE THREAD

**Issue by fandrade86** [tedrick/Survey123-Testing#265]
Ability to view linked content on the web version of Survey123.

Scenario:
- Create a survey for customers to report online streetlights that are currently out and the map displays all pole/street lights in our Server and previously reported streetlights that are out.

Reason:
- This would help reduce calls to customer service and customers would report streetlights that are out that have not been reported. But it would also make the streetlight fixing process more transparent for the customer and they can view the status of the issue.

**Comment by phil-wilson** [comment]
@fandrade86 Thanks for the enhancement request, we are already working on supporting linked content in the Survey123 website and web app so you can see the same basemap everywhere.
