### ISSUE TITLE
FEEDBACK: Survey123 Enterprise 3.7 On Premises installer

### ISSUE THREAD

**Issue by brettstokes** [tedrick/Survey123-Testing#266]
Feedback will be related to testing of the Survey123 website on-premises installation.

Installation files and instructions can be found at the Early Adopter Community:
[Documentation](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={67B445AB-9031-4679-B6C1-84FDB9D19AB8})
[Download](https://earlyadopter.esri.com/project/version/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={beb1a53b-ed9e-470e-9b60-9402a33d970b}&artid={8AA8B736-B68C-4625-971E-5BD8D26D4944})

Please try to install (and connect to your ArcGIS Enterprise installation) and provide feedback.

**Comment by DerekLaw** [comment]
**Documentation feedback**

I realize the documentation for this capability is still in beta and still new, but it should clearly state upfront the system requirements needed to enable this capability:

- Do I have to have a minimum base deployment of ArcGIS Enterprise running to make this work?
- Can I deploy this only on a single machine or multi-machine deployment of Enterprise?
- Under the "Deployment Notes" section, it says:

"The Survey123 On-Premises installer can be deployed on the same machine as your Portal instance or on a standalone server_."

What do you mean by "standalone server" - the GIS Server component? or just a stand alone ArcGIS Server install without Portal? Need to be really clear and specific here.
- Is there any differences/advantage if I install on the Portal machine vs the GIS Server machine? Can I install on the separate machine?
- Is this functionality available for Windows only or what about Linux OS?
- What ArcGIS User Type level do I need to be to set this up? Minimum Portal Admin privileges, right?

**Comment by DerekLaw** [comment]
When I attempted to access the Survey123 post install page, I bypassed the security cert warning, but then got an "invalid token" error

![ErrorMsg](https://user-images.githubusercontent.com/1037228/67032081-bfe31800-f0c7-11e9-87e3-a1ffb602dc87.png)

**Comment by DerekLaw** [comment]
When I finished the Survey123 Enterprise post install "wizard", I see this final message window. I understand what the first action is, but have no idea what **Run `npm start`** means

![Picture2](https://user-images.githubusercontent.com/1037228/67033895-81e7f300-f0cb-11e9-90c2-43c64d2f7e18.png)

**Comment by billwie** [comment]
For step 3 (run post install) of the installation i was unable to use my machine name or fully qualified machine name, however localhost worked. probably due to our security configuration. still testing to see if remainder of the install works.

**Comment by billwie** [comment]
For step 3, (Run Post Install)i get the certificate error but do not get a working page when i use the fully qualified server name Something.domain.com. It runs when i use just the machine name.

**Comment by brettstokes** [comment]
closing as this feedback has been addressed or moved to internal issues
