### ISSUE TITLE
FEEDBACK: Survey123 Enterprise - Reverse Proxy Instructions

### ISSUE THREAD

**Issue by brettstokes** [tedrick/Survey123-Testing#267]
Feedback will be related to testing the instructions (see below) for setting up a reverse proxy so that your On-Premises website can be accessed through normal 80/443 http/https ports.

**Comment by brettstokes** [comment]
### **Background**
These instructions are aimed at users who have already installed and configured the Beta version of Survey123 Enterprise - the On-Premises version of the Survey123 website and API. 

Initially, Survey123 Enterprise will require administrators to specify HTTP/HTTPS ports when they install and configure the package on their local infrastructure. By default, the Survey123 website will be accessible on ports 5080/5443 (HTTP/HTTPS).  Many users, however, will want to access the website using normal HTTP/HTTPS ports, 80/443.  You are probably familiar with the ArcGIS Web Adaptor, which does this for ArcGIS Enterprise (Portal/Server).  While the Survey123 team is looking into possibly being supportable by the Web Adaptor in the future, the initial release will rely on a reverse proxy to accomplish this. 

A reverse proxy is the generic procedure for having a website accessible via a different port/server.  Below are the instructions for setting up a reverse proxy with IIS: 

### **Requirements**

- **A web server running IIS**. Ideally, this is the same web server as you have installed your ArcGIS Web Adaptors on - this provides the advantage of not needing to worry about [cross-origin resource sharing](developer.mozilla.org/en-US/docs/Web/HTTP/CORS) (CORS) with the Enterprise installation.  NOTE: You will need to have administrative access on this web server.
- **Install the IIS URL Rewrite module**.  You need to ensure the [IIS URL Rewrite module](www.iis.net/downloads/microsoft/url-rewrite) is installed on your web server.

### **Setup Instructions**

1. Open IIS Manager on your web server.
2. Expand the 'Sites' entry in the left sidebar and select the site you want to access Survey123 from; in many cases, this will be 'Default Web Site'.  Right-click on the site and select Explore to open a Windows Explorer window there.
3. Create a new folder called **_survey123_**, this will be the access point for Survey123. 
4. Download and unzip the attached [web.config](https://github.com/tedrick/Survey123-Testing/files/3731884/web.config.zip) file and copy it into this new folder. You can choose an alternative name for this folder but just remember to edit the web.config file in a text editor to reflect this folder name:
​
![image](https://user-images.githubusercontent.com/46305628/66878485-cdd06480-f005-11e9-91db-b1c225d4fc63.png)

5. If your Survey123 Enterprise is not installed on the machine on which you are configuring your reverse proxy (or you have changed the http port for Survey123 Enterprise), you will need to update the server name in the inbound rules section of the web.config file. Otherwise you can leave this as ‘http://localhost:5080/’:

![image](https://user-images.githubusercontent.com/46305628/66878562-21db4900-f006-11e9-9620-79c3dccf2b8e.png)

6. Close Explorer. In IIS Manager, right-click on the site again and select 'Refresh' to show the new folder.

7. Select the folder.  In the IIS section of the configuration properties, double-click on 'URL Rewrite':

![image](https://user-images.githubusercontent.com/46305628/66878602-5818c880-f006-11e9-9394-a6e1a3560901.png)

8. In the URL Rewrite ‘Actions’ pane, click on 'View Server Variables'.  Click ‘Add’ under the ‘Actions’ panel on the right and add 2 variables:
- **HTTP_ACCEPT_ENCODING** (this will be in a dropdown list)
- **HTTP_X_ORIGINAL_ACCEPT_ENCODING**
Go 'Back to rules'.

9. You can now access your locally hosted Survey123 On-Prem website using the URL:
                 eg **_https://some-machine.domain.com/survey123_**

**Comment by billwie** [comment]
Our standard IIS configuration did not include the URL Rewrite module, however I was familiar with it and was able to install it from here. https://www.iis.net/downloads/microsoft/url-rewrite. it was important to make sure you got the correct version (x64 for most users).
