### ISSUE TITLE
Error when submitting post installation (final step) in Chrome

### ISSUE THREAD

**Issue by cdarti** [tedrick/Survey123-Testing#269]
**Application:** On Premises

**Browser:** Chrome 
Checking for updates
Version 77.0.3865.120 (Official Build) (64-bit)

**Error Description:**
When submitting the post installation (last step), get the following error:
![image](https://user-images.githubusercontent.com/12465858/67032931-74316e00-f0c9-11e9-8408-9e46214b2014.png)

 

**How to reproduce:**

**Have you tested with another survey?**

**Comment by BrandonArmstrong** [comment]
added to https://devtopia.esri.com/Melbourne/Survey123-OnPremises/issues/43
