### ISSUE TITLE
BUG: Opening Connect settings seems to log me out

### ISSUE THREAD

**Issue by jessnoo** [tedrick/Survey123-Testing#27]
**Application:** Connect 

**Device:** _Holistic lab desktop machine_

**Operating System:** _Windows 10 Enterprise_

**Browser:** _n/a_

**Error Description:** when i open connect settings to enable diagnostics, it seems like i'm logged out

**How to reproduce:**

1. Open Survey123 Connect for ArcGIS version 2.4.3.2
2. Sign in and see your surveys
3. Click the gear near the version number >> Survey 123 Connect Settings opens
4. Click cancel to close the window >> Notice that you've been signed out of your account

**Have you tested with another survey?** Not relevant

**Comment by JohnHasthorpe** [comment]
This is a known issue - 2.4 complete, so closing this now.
