### ISSUE TITLE
Survey123 on premise installation experience

### ISSUE THREAD

**Issue by cdarti** [tedrick/Survey123-Testing#270]
**Application:**  On Premises

**Error Description:** Installation user experience should match the experience when installing enterprise (in particular for the URL for Portal). Usually stick point is certificate... May be godo to see a message at the end indicating that the installation was successful.

**How to reproduce:**

**Have you tested with another survey?**

**Comment by brettstokes** [comment]
Thanks for the feedback @cdarti. Closing as implemented with latest build - status page has also been added to the post installation to indicate success.
