### ISSUE TITLE
Configuring Survey123 Connect to sign into ArcGIS Enterprise

### ISSUE THREAD

**Issue by DerekLaw** [tedrick/Survey123-Testing#271]
Survey123 Connect with On Premises configuration of Survey123 Enterprise
Windows Server 2019 Standard

Followed the steps to configure Survey123 Connect v3.6 to connect and sign into ArcGIS Enterprise with Survey123 Enterprise installed. It worked following the documented steps, but it took a long time for Survey123 Connect to "connect" and load the login dialog. Possibly 8 - 10 mins. Is this expected?

If yes, perhaps show a progress dialog or something to assure that end user that the connection did not hang?

**Comment by brettstokes** [comment]
8-10 minutes is not expected but was likely due to the holistic lab resources and set up.
