### ISSUE TITLE
Unable to create a new survey error

### ISSUE THREAD

**Issue by jerjer007** [tedrick/Survey123-Testing#273]
After running the post install and opening a new browser (pointing to my local VM install) I started the create a new survey process.  This error message appeared after submitting my newly created survey:

![image](https://user-images.githubusercontent.com/46798139/67036715-f3767000-f0d0-11e9-9604-581023659d8a.png)

When I tried to recreate the survey (the fields were already populated when I clicked "Create new survey" again), there was a message in red type that said, that there was already a survey with that name (after clicking "Create").
![image](https://user-images.githubusercontent.com/46798139/67037148-d2624f00-f0d1-11e9-8c52-07ad1f9c2d0a.png)
If the survey failed to be created, why was the name of the survey stored?

**Comment by zhif7782** [comment]
Similar to https://github.com/tedrick/Survey123-Testing/issues/277#issuecomment-543732976.

@jerjer007 , thanks for the question "If the survey failed to be created, why was the name of the survey stored?", created an internal issue in the dev repo https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3976 to enhance the UX in a future release.

**Comment by BrandonArmstrong** [comment]
@zhif7782 This issue was resolved after holistic lab PE renewed expired credentials on the Portal.  Will close particular issue
