### ISSUE TITLE
Survey123 Enterprise - Website login page

### ISSUE THREAD

**Issue by DerekLaw** [tedrick/Survey123-Testing#274]
Survey123 Enterprise
Windows Server 2019 Standard,

Feedback on the Survey123 website page when it initially loads, an end user can sign into Survey123 Enterprise with 2 options and I think their labels are a bit confusing.

![LoginPage](https://user-images.githubusercontent.com/1037228/67037851-30dbfd00-f0d3-11e9-9a50-1289753b41e5.png)

Why does it say: i) Sign in, and ii) Sign in with ArcGIS Enterprise? I have been using the first option "Sign in", which is a login to my Portal for ArcGIS instance. So what is the difference between the 2 options? Suggest rename the second option, or please clarify.

**Comment by zhif7782** [comment]
Hi @DerekLaw thanks for the catch. It should be "Sign in with ArcGIS Enterprise" and "Sign in with ArcGIS Online", will be fixed in https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3770#issuecomment-1916762.
