### ISSUE TITLE
Survey123 Connect - Attempted to publish a survey to ArcGIS Enterprise

### ISSUE THREAD

**Issue by DerekLaw** [tedrick/Survey123-Testing#275]
Survey123 Connect 
Windows Server 2019 Standard

Opened the Media Sample Survey in Survey123 Connect. Signed into ArcGIS Enterprise with Survey123 Enterprise installed. Tried to publish the survey and got an error:

![Survey123Connect_ErrMsg](https://user-images.githubusercontent.com/1037228/67039105-8c0eef00-f0d5-11e9-80db-76ce4d99d8f0.png)

**Comment by BrandonArmstrong** [comment]
@DerekLaw This may now be resolved.  It may have been related to an expired certificate that should now be fixed

**Comment by DerekLaw** [comment]
After the certificate update, I am now able to publish a survey from Connect to Enterprise. Works as expected. 👍

**Comment by brettstokes** [comment]
closing as resolved through certificate renewal
