### ISSUE TITLE
Survey123 Enterprise - issues with previewing and publihging

### ISSUE THREAD

**Issue by billwie** [tedrick/Survey123-Testing#276]
**Application:**  On Premises 

**Device:** windows pc

**Operating System:** 10_x64

**Browser:** Chrome

**Error Description:**
Survey is saved.

when attempting to preview receive error: Http failure response for https://innovategis.oxy.com/api/json2webform: 404 Not Found

when attempting to publish survey receive message 
Unable to publish the survey
{"code":-1,"message":"","readyState":4,"status":404,"statusText":"Not Found"}

A draft survey item does exist in My Surveys

**How to reproduce:**

**Have you tested with another survey?**

**Comment by brettstokes** [comment]
closing as moved to internal issue
