### ISSUE TITLE
Error message: "Unable to publish the survey"

### ISSUE THREAD

**Issue by jerjer007** [tedrick/Survey123-Testing#277]
After clicking "Publish" the app ran for several minutes then launched this error message:
![image](https://user-images.githubusercontent.com/46798139/67046299-d64b9c80-f0e4-11e9-80d1-b9f20e676963.png)

**Comment by zhif7782** [comment]
This could be caused by the combination of on-premises installation+test portal, may need more info to reproduce and debug... cc @BrandonArmstrong @brettstokes @oopsliu

**Comment by BrandonArmstrong** [comment]
@zhif7782 This behavior may have been related to the initial failing of the survey referenced in #273 After attempting to add fields to surveys that had previously failed, the error was encountered.  Attempted to reproduce using same VM and credentials but unable.  Closing
