### ISSUE TITLE
Web App Version page not applicable on on premise

### ISSUE THREAD

**Issue by cdarti** [tedrick/Survey123-Testing#278]
**Application:** On Premises

I do not think the Web App Version page is still applicable:
![image](https://user-images.githubusercontent.com/12465858/67048622-655ab380-f0e9-11e9-9f31-4d79d7cc683f.png)

May need a way for the admin to know when updates are available however.

**Comment by zhif7782** [comment]
Hi @cdarti , all versions of the web app are included in the on-premises installation package, technically, this page should work as the online version. The difference would be that the "Always use the latest version" option will stay on the latest web app version comes along with the on-premises build but not advance forever. 

Would you mind sharing if still encounter any issue with this page?

cc @brettstokes 

![image](https://user-images.githubusercontent.com/7665168/67095349-455de980-f1e8-11e9-89c8-f3788899ef47.png)

**Comment by BrandonArmstrong** [comment]
Closing with feedback provided by @zhif7782
