### ISSUE TITLE
Survey123 for Windows authentication appears to run three times

### ISSUE THREAD

**Issue by jfangit** [tedrick/Survey123-Testing#28]
**Application:** Field App

**Device:** Windows 10

**Operating System:** Windows 10

**Browser:** Chrome

**Error Description:** Using enterprise authentication option, if asked to type in user name and password twice afterwards

**How to reproduce:** Start the Survey123 for Windows, click on Sign In, select Enterprise login, type you AGOL url. if asks for login info. you type in the login info. Another login dialog appears. 

**Have you tested with another survey?** No
![survey123login](https://user-images.githubusercontent.com/7094931/29838548-537b57ae-8cb0-11e7-8a76-9c85c079eb07.PNG)
![survey123login2](https://user-images.githubusercontent.com/7094931/29838550-57a50596-8cb0-11e7-9d88-5b78a73a6c8f.PNG)

**Comment by IsmaelInRedlands** [comment]
Hi Justin. Once you login twice when setting up the initial connection, do you ever get prompted  twice again?

**Comment by jfangit** [comment]
Hi Ismael, after the initial login, if I close/restart Survey123, no login is required.

**Comment by IsmaelInRedlands** [comment]
Thanks for confirming. The expected behavior when using IWA is  that when using either Connect or the App on Windows you no longer need to login once the connection has been made.  Having to provide your credentials twice when configuring the connection is expected.  Thanks for reporting.

**Comment by jfangit** [comment]
Related to this issue, when you sign out and close the app and restart the app, instead of presenting the Sign In dialog, the application shows the last survey you've worked on. And you can select the survey and the Collect button is also active and you can actually bring up the form. When you click on the options drop down, it shows Sign In as an option. When you try to log in, only the first dialog shows (IWA url).
![signout1](https://user-images.githubusercontent.com/7094931/29843047-9082341a-8cbf-11e7-80b1-f737aa3fe1f9.PNG)
![signout2](https://user-images.githubusercontent.com/7094931/29843050-94992f7c-8cbf-11e7-975f-48f73fccc396.PNG)
![signout3](https://user-images.githubusercontent.com/7094931/29843054-96b9debe-8cbf-11e7-9ff6-67e9ef8f1e7b.PNG)
![signout4](https://user-images.githubusercontent.com/7094931/29843061-992773be-8cbf-11e7-984d-81863b7f038d.PNG)

**Comment by jfangit** [comment]
After reporting this, I realized that this most likely because the survey was shared to everyone.

**Comment by jfangit** [comment]
Ismael, when I signed out and signed back in through the Enterprise login, only the first login (IWA) appeared).

**Comment by JohnHasthorpe** [comment]
2.4 testing complete. Closing
