### ISSUE TITLE
Message displayed not making sense

### ISSUE THREAD

**Issue by cdarti** [tedrick/Survey123-Testing#280]
**Application:** On Premises

**Operating System:** _Provide version, i.e., Android 5.0.1_

**Browser:**Chrome
**Error Description:** 
When submitting a survey with an error, the following message is displayed:
"Please press here to fix 1 error(s).

Nothing happened when I press here... Still need to go and fix the error.

**How to reproduce:**

**Have you tested with another survey?** 
![image](https://user-images.githubusercontent.com/12465858/67050454-6857a300-f0ed-11e9-98cb-d20bff9dead7.png)

**Comment by zhif7782** [comment]
Hi @cdarti , thanks for the catch! Created an issue in the dev repo to refine the string for the next release: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3975
