### ISSUE TITLE
Fix hyperlink on Group Settings subtab - under the Collaborate tab

### ISSUE THREAD

**Issue by DerekLaw** [tedrick/Survey123-Testing#281]
Survey123 Enterprise on ArcGIS Enterprise 10.7.1
Windows Server 2019 Standard

Edit suggestion: on the Survey123 website installed in Enterprise, Collaborate tab > Group Settings subtab, suggest edit the 2nd hyperlink (Group topics) in the text to go to ArcGIS Enterprise help doc, instead of the AGOL help doc. Text should also refer to the Enterprise doc, not the AGOL doc.

![helplink](https://user-images.githubusercontent.com/1037228/67050674-e74cdb80-f0ed-11e9-8651-922c4e9e54f0.png)

**Comment by DerekLaw** [comment]
FYI, I noticed there are several help links to go to AGOL help - they should probably go to Enterprise help doc.

**Comment by zhif7782** [comment]
Hi @DerekLaw , thanks for the catch! Created an issue in the dev repo to further fix this: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/3974.

**Comment by brettstokes** [comment]
closing as internal issue created in survey123-hub repo
