### ISSUE TITLE
Preview basename does not display

### ISSUE THREAD

**Issue by cdarti** [tedrick/Survey123-Testing#283]
**Application:** On Premises

**Operating System:** _Provide version, i.e., Android 5.0.1_

**Browser:** Chrome

**Error Description:** 
Preview map using raster basemap stuck on Loading.

![image](https://user-images.githubusercontent.com/12465858/67051576-5297ad00-f0f0-11e9-80a0-6fbc90af8ddb.png)

Basemaps show on Design form.
![image](https://user-images.githubusercontent.com/12465858/67051625-72c76c00-f0f0-11e9-8917-0ce6e7f37a04.png)

**Comment by BrandonArmstrong** [comment]
Thanks @cdarti
