### ISSUE TITLE
FEEDBACK: Improvements with Inbox performance

### ISSUE THREAD

**Issue by Shwujeng** [tedrick/Survey123-Testing#285]
With the latest 3.7 beta version of the field app, there have been significant improvements dedicated to performance when loading records in the Inbox.  This can especially be seen when loading hundreds of records or more.
With v.3.6:
![36_inbox_refresh](https://user-images.githubusercontent.com/29442153/67988999-d1abdb80-fbee-11e9-9a55-8f11eb573236.gif)
With v.3.7:
![37_inbox_refresh](https://user-images.githubusercontent.com/29442153/67989030-e4beab80-fbee-11e9-8752-4619269432d0.gif)

Please test out these improvements by loading your own surveys in the inbox using your mobile devices.

If you do not have a survey to test, feel free to use the following:

Scan this survey and open it with field app:
![image](https://user-images.githubusercontent.com/29442153/67903855-ed00e300-fb29-11e9-98b2-a2128065e025.png)

**Comment by BrandonArmstrong** [comment]
Pablo
Jerry

**Comment by gisguy007** [comment]
Tested with iPhone7+ version 3.7.31 Beta - Survey123 worked like a champ!  Using the Far_rockaway survey,  2000 records were loaded just almost instantly!  Clicking on the "Map" tab loaded the points to the map very quickly- in a few seconds!

**Comment by gisguy007** [comment]
Searching the inbox records can cause the app to crash. REPO: Click on "Inbox", after records load, try to type in a search word, as you are typing,... crash!

**Comment by Shwujeng** [comment]
Crash issue with search in Inbox only occurred with v.3.7.32 but the crash issue is no longer repro with v.3.7.33 with both iOS and android.

**Comment by Shwujeng** [comment]
Crash issue was still repro with newer build, internal issue is logged as https://devtopia.esri.com/Melbourne/Survey123/issues/3475
