### ISSUE TITLE
FEEDBACK: Feature Report Preview Mode

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#286]
Please leave feedback related to testing Preview Mode in the Survey123 Beta website

<h2>Background</h2>

<p>Survey123 Feature&nbsp;Report is an out-of-the-box functionality to help you generate high quality documents of your submitted surveys. Previously, we only supported Microsoft Word (.docx) as the output format. Starting with Survey123 3.7 beta, you can choose to save the output file as Portable Document Format (.pdf) or&nbsp;Microsoft Word (.docx). A new Preview mode has also been added in 3.7, allowing you to test and refine your report template without consuming credits.</p>

<hr />
<h2>Preview feature report</h2>

<p>As a survey owner, you may want to review the look and feel of your report as you design it.&nbsp; The Preview option lets the author of the&nbsp; survey generate reports with your template and data without incurring into credit consumption. Preview reports are always generated in PDF format and include a &quot;Sample Report&quot;&nbsp;watermark. The preview capability is only available to the author of the survey.</p>

<p style="margin-left:40px">&bull;&nbsp;&nbsp; &nbsp;Go to the Survey123 beta website: <a href="https://survey123beta.arcgis.com" target="_blank">https://survey123beta.arcgis.com</a>. If this is your first visit, you will see the terms and conditions of using the beta website. You must review and accept these terms and conditions before continuing.<br />
&bull;&nbsp;&nbsp; &nbsp;Sign in with your ArcGIS Online account and open the feature report panel on the Data tab of your survey.<br />
&bull;&nbsp;&nbsp; &nbsp;Upload your feature report template or choose an existing one. For more information, please refer to this <a href="https://community.esri.com/groups/survey123/blog/2019/07/23/understanding-survey123-feature-reports" target="_blank">GeoNet blog</a> &nbsp;and the Survey123&nbsp;<a href="https://doc.arcgis.com/en/survey123/browser/analyze-results/featurereporttemplates.htm" target="_blank">documentation</a>.<br />
&bull;&nbsp;&nbsp; &nbsp;Select the record or multiple records (by pressing ctrl or shift on your keyboard) that you wish to print or choose the option &ldquo;All records in the table&rdquo; in the left panel to print every record.<br />
&bull;&nbsp; &nbsp; Click &ldquo;Preview sample report&rdquo;.</p>

![manhole_inspect_holistic](https://user-images.githubusercontent.com/6314443/67979405-69063400-fbd9-11e9-884e-aa5ffff8825a.PNG)

<p style="text-align:center"><img alt="" height="599" src="/download/8c829191e0e54aafbfd3051689543f32/image%288%29.png" width="401" /></p>

<p style="margin-left:40px"><br />
&bull;&nbsp;&nbsp; &nbsp;The preview report will be generated without consuming ArcGIS Online credits and will open automatically in a new window. If the pop-up window is blocked by your browser, ensure you allow it (as shown for Google Chrome below) and then click &ldquo;Preview sample report&rdquo; again.</p>

<p style="text-align:center"><img alt="" height="auto" src="/download/c76e41616edd470baa65980e08bc5455/image%281%29.png" /></p>

<p style="margin-left:40px">&bull;&nbsp;&nbsp; &nbsp;The preview report will look the same as your final report, except that you will see a &ldquo;Sample Report&rdquo; watermark on each page indicating this is not a final report. You can then make changes to your template based on the preview report before generating final reports.</p>

<p style="text-align:center"><img alt="" height="auto" src="/download/7909ff3fbe2c4820b7a5af67e6cf27b3/image%283%29.png" /></p>

<h3 style="margin-left:40px">Note:</h3>

<p style="margin-left:40px">&bull;&nbsp;&nbsp; &nbsp;Preview sample report is only available to the survey owner.<br />
&bull;&nbsp;&nbsp; &nbsp;When printing multiple records in the preview report, only the first three records will be processed and printed.</p>

<hr />

**Comment by BrandonArmstrong** [comment]
Cory
Leonard

**Comment by lbarnhill** [comment]
As discussed, there should be a warning when trying to preview more than 3 records.  I selected 4 records in testing.  It seemed to go through the process of creating a preview but after a bit the screen flashed and nothing else happened.  I did it again to make sure I didn't miss something but got the same results.  It is my mistake but an error message before attempting preview of more than 3 records would save time and frustration.

I like the preview capability - it will save credits.

**Comment by gisguy007** [comment]
Previewing... If I select 3 or more (ALL)  to preview, a zip file is created and downloaded (which is great!); when I only select one record, and click on preview, it will open a new web browser tab- I'd like to have a zipped download instead.

**Comment by Shwujeng** [comment]
With Safari, user would need to click the small square icon at the address bar and click allow download. There is no additional warning message, so we might need to document this, otherwise, it will look like the preview mode is not doing anything.
<img width="488" alt="Screen Shot 2019-11-01 at 10 59 18 AM" src="https://user-images.githubusercontent.com/29442153/68055202-54936b80-fcad-11e9-8e1d-ba1436ebd4ae.png">

**Comment by zhif7782** [comment]
@lbarnhill, thank you for the feedback, I've logged an issue in the dev repo to make the message more intuitive: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/4019.

**Comment by zhif7782** [comment]
@gisguy007 , would you please share more information about your use case of containing only one report in a .zip package? Sees only include one file in a .zip package will introduce unnecessary unzip step when looking into the report. Or would you like to have the capability to show up the download dialog instead of opening the report in a new browser tab, even to download the report file directly instead of downloading a .zip package?

**Comment by zhif7782** [comment]
@Shwujeng , thank you for the feedback. It's currently a known issue which documented in [the EAC doc](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={335A0766-D00A-4465-83C9-8982B546091B}). I created an issue in the dev repo to see if there's anything we can improve before make it into the doc: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/4020.
