### ISSUE TITLE
FEEDBACK: Numbers Appearance improvement in field app.

### ISSUE THREAD

**Issue by Shwujeng** [tedrick/Survey123-Testing#289]
We have improved the number appearance in Beta 3.7. Compared with v.3.6, we eliminate the data loss isue and accelerates data capture.
With Beta 3.7, you will see:

- Data loss BUG can no longer be reproduced.
- The new keypad is easier to close
- Issue with duplicated ios and Survey123 keypad is gone
- New keypad does not require users to clear existing values (defaults or calculated values). This behavior is more natural and accelerates data capture.
- Decimal separator key only shows with decimals. Reduces confusion.
- Issue with ghost cursor only present in iOS 13
- Spinner appearance now working
- Size of keypad is good
- New icon for numbers appearance is better. Does not cause confusion.

Please try the number appearance with your own survey and let us know your feedback about the improvement.

**Comment by BrandonArmstrong** [comment]
Pablo
Leonard

**Comment by lbarnhill** [comment]
As long as the iPad is running the same version as published, it appears to work as expected.  The number pad is a little small but that could be my layout.

When I open a 3.7.37 created survey in iPad running v3.6.157 the small number pad and the keyboard both pop up.  I can enter data in either data entry tool

**Comment by lbarnhill** [comment]
The Icon representing the new number pad takes up space in the data field that will require me to modify my layout.  Same goes for the number pad - it appears only as wide as the space provided for the data entry field so the numbers are very small.

**Comment by BrandonArmstrong** [comment]
Thank you for the feedback @lbarnhill  As we discussed during the holistic, using grid theme with numbers will be tricky.  One suggestion was to allocate more 'w' values to the integer question with numbers appearance
