### ISSUE TITLE
Audio recordings are sometimes longer than 30 seconds

### ISSUE THREAD

**Issue by bethanyw** [tedrick/Survey123-Testing#29]
**Application:** Field App

**Device:** Field App on iPhone

**Operating System:** iOS 10.3.3

**Browser:** N/A

**Error Description:** Audio recordings are sometimes longer than 30 seconds on iOS

**How to reproduce:**

1) Use the Field app to download a survey with an audio field
2) Tap the microphone icon to record an audio file
3) Let the audio keep recording until the audio file times out
4) The file was 32 seconds long

Note: while the survey result still submitted successfully, it looks like the 30 second time limit can be pushed a bit. See attached screenshot

![img_0057 002](https://user-images.githubusercontent.com/24254787/29842767-c9acbbee-8cd7-11e7-9bbc-4e81d629f562.png)

**Have you tested with another survey?**

**Comment by JohnHasthorpe** [comment]
Issue raised: https://devtopia.esri.com/Melbourne/Survey123/issues/1912
