### ISSUE TITLE
FEEDBACK: Basic math operators in feature report

### ISSUE THREAD

**Issue by zhif7782** [tedrick/Survey123-Testing#290]
### Background
When creating a feature report, there is a possibility that it requires to output some number calculations which have not been defined in survey design (XLSForm file). Allowing math calculations in the feature report template could simplify the entire workflow and calculate numbers on-the-fly in the report.

### Steps

1. Go to the Survey123 beta website: https://survey123beta.arcgis.com and open the Feature Report panel on the Data tab of your survey.
2. Create your feature report template or choose an existing one. For more information, please refer to this [GeoNet blog](https://community.esri.com/groups/survey123/blog/2019/07/23/understanding-survey123-feature-reports)  and [the documentation](https://doc.arcgis.com/en/survey123/browser/analyze-results/featurereporttemplates.htm).
3. Modify your report template by adding any expression which utilizes the new math operators capability. Note: Math operators require two number variables. 
    * ![image](https://user-images.githubusercontent.com/7665168/68029225-c1c8f000-fcf1-11e9-88f5-782dfba5e9c6.png)
    * Examples:
      * `${num1+num2}` returns the sum of num1 and num2.
      * `${(num1/num2) | round:2}` returns num1 divides num2 and keep two decimal places of the result.
      * `Image size: ${((image1 | getValue:"size")/1024/1024) | round:2}MB` outputs the image size in MB with 2 decimal places.

### Notes

* There may be syntax error when trying to write complex placeholder, please check if you need to add (nested) brackets to make sure the report engine understand the calculation sequence.

**Comment by BrandonArmstrong** [comment]
Cory
Leonard

**Comment by cwhit45** [comment]
I was able to add the photo size calculation.  Worked very well, even within a repeat. 
![Screen Shot 2019-11-01 at 2 41 04 PM](https://user-images.githubusercontent.com/57266287/68055254-d6879280-fcb5-11e9-99e5-537a7a5f2699.png)

**Comment by lbarnhill** [comment]
I created a new report using v3.7.37 and was successful in creating a basic math function adding 5 different fields and dividing the total by 12.  
{(field1+field2+field3+(field4*12)+field5)/12)}
I modified the template in Word, deleted the original report from the Feature Report sidebar, and uploaded the modified report template.
This will be very useful.

**Comment by BrandonArmstrong** [comment]
Thank you for the feedback @cwhit45 and @lbarnhill
