### ISSUE TITLE
Add a "Cancel" option to the 'action' list when reviewing recorded surveys

### ISSUE THREAD

**Issue by gisguy007** [tedrick/Survey123-Testing#291]
The options are limited when reviewing recorded surveys (see screenshot below). Currently there are only two choices: 1) Edit and resend survey; and 2) Copy the sent data to a new survey. How about adding a "Cancel" button that would take the user back to the previous screen? 
![image](https://user-images.githubusercontent.com/43858983/68045364-8b11bc00-fc96-11e9-9a87-d06d7fb96914.png)

**Comment by tedrick** [comment]
Thanks for the feedback and apologies for the delay in response.  This menu can be dismissed by tapping/clicking in an area not in the pop-up, but I can see how an explicit cancel action would be more understandable.  Could I suggest you create an idea at https://ideas.arcgis.com ?  That is the best place to log this.
