### ISSUE TITLE
Layer filter from AGO not honored in Survey123 website

### ISSUE THREAD

**Issue by marikavertzonis** [tedrick/Survey123-Testing#292]
**Application:**  Website

**Device:** Windows

**Operating System:** 10

**Browser:** I tested with Firefox

**Error Description:** Survey built on existing feature service which has a layer filter defined in AGO. When i view the survey results in the website, all records are listed. Should start with the filtered layer. The filtering inside the Survey123 website, should further filter the records. 

**How to reproduce:** 
 - In AGO apply a layer filter (on Visualization tab of the item) and save the layer. 
 - Create a survey from the feature layer in Connect and publish
 - Open the survey in the website
      - see that the number of records on the survey tile in the gallery lists the full amount (not the filtered amount)
      - see that the number of records on the data tab is the full amount of records

**Have you tested with another survey?** Jamie Lambert (Exxon Mobil) first shows us this with his data, I repro'ed it with the Guardrail End Treatment sample from our new learn lesson. Its in the appstudioext org, but i can duplicate it in another org if required, however i expect this behaviour will happen on any survey from a feature service.

**Comment by marikavertzonis** [comment]
@zhif7782 - i had a look in the website repo expecting to see this one - but couldn't find it. Could you review and see if its something we can consider working on.

**Comment by zhif7782** [comment]
@marikavertzonis , thanks for the catch! Created a new issue in the dev repo https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/4033. Actually this affects all the web components... Similar to the issue in the field app: https://devtopia.esri.com/Melbourne/Survey123/issues/1553.
