### ISSUE TITLE
Would like to return x records within y meters of current location in Inbox

### ISSUE THREAD

**Issue by marikavertzonis** [tedrick/Survey123-Testing#293]
User (Jamie Lambert from Exxon Mobil) has a lot of records in his survey, related to linear infrastructure. ie: a long line of lots of points.
The type of query that would suit his work is to search for x records with y meters of the users location. eg: this might represent the number of jobs today - say 50 records within 500m.

**Comment by tedrick** [comment]
Migrated to internal repo.
