### ISSUE TITLE
Suggestion: Show which fields are missing

### ISSUE THREAD

**Issue by roemhildtg** [tedrick/Survey123-Testing#294]
The problem:

In large survey's its extremely difficult to figure out which fields are missing. It could be a typo, it could be a field that is supposed to be `null` esri type, or other issues. But the error message is not helpful.

This happens in all survey123 connect apps on any platform:

![image](https://user-images.githubusercontent.com/5471079/68782697-6a832380-05ff-11ea-9984-92f2b3e93b57.png)

The steps to reproduce are:
1. Connect your survey to a custom feature layer using the settings, `submission_url` setting. Set it to a feature service like `https://maps.arcgis.com/sharing/rest/content/items/<itemId>`
2. Add  field that's not present in the service to your survey.
3. The error pops up but it does not explain which field is missing.

The solution:

Just display the field names. It would make life SO much easier!

Thanks for all the hard work on survey123. Its by far one of our favorite esri products!

**Comment by tedrick** [comment]
Thanks Gregg!  I've moved your comments to the internal development discussion on this.

**Comment by roemhildtg** [comment]
10-4! Thanks for the info. Btw, is this an appropriate place to post issues like this? I'm a regular user of github and stumbled upon it when searching and it seemed active.

**Comment by tedrick** [comment]
@roemhildtg - this repo is designed for use with specific testing events.  Esri Support, ArcGIS Ideas and/or GeoNet are the best place to raise enhancements or bugs.
