### ISSUE TITLE
FEEDBACK: Feature Report Preview Mode

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#295]
Please leave feedback related to testing Preview Mode in the Survey123 Beta website

<h2>Background</h2>

<p>Survey123 Feature&nbsp;Report is an out-of-the-box functionality to help you generate high quality documents of your submitted surveys. Previously, we only supported Microsoft Word (.docx) as the output format. Starting with Survey123 3.7 beta, you can choose to save the output file as Portable Document Format (.pdf) or&nbsp;Microsoft Word (.docx). A new Preview mode has also been added in 3.7, allowing you to test and refine your report template without consuming credits.</p>

<hr />
<h2>Preview feature report</h2>

<p>As a survey owner, you may want to review the look and feel of your report as you design it.&nbsp; The Preview option lets the author of the&nbsp; survey generate reports with your template and data without incurring into credit consumption. Preview reports are always generated in PDF format and include a &quot;Sample Report&quot;&nbsp;watermark. The preview capability is only available to the author of the survey.</p>

<p style="margin-left:40px">&bull;&nbsp;&nbsp; &nbsp;Go to the Survey123 beta website: <a href="https://survey123beta.arcgis.com" target="_blank">https://survey123beta.arcgis.com</a>. If this is your first visit, you will see the terms and conditions of using the beta website. You must review and accept these terms and conditions before continuing.<br />
&bull;&nbsp;&nbsp; &nbsp;Sign in with your ArcGIS Online account and open the feature report panel on the Data tab of your survey.<br />
&bull;&nbsp;&nbsp; &nbsp;Upload your feature report template or choose an existing one. For more information, please refer to this <a href="https://community.esri.com/groups/survey123/blog/2019/07/23/understanding-survey123-feature-reports" target="_blank">GeoNet blog</a> &nbsp;and the Survey123&nbsp;<a href="https://doc.arcgis.com/en/survey123/browser/analyze-results/featurereporttemplates.htm" target="_blank">documentation</a>.<br />
&bull;&nbsp;&nbsp; &nbsp;Select the record or multiple records (by pressing ctrl or shift on your keyboard) that you wish to print or choose the option &ldquo;All records in the table&rdquo; in the left panel to print every record.<br />
&bull;&nbsp; &nbsp; Click &ldquo;Preview sample report&rdquo;.</p>

![manhole_inspect_holistic](https://user-images.githubusercontent.com/6314443/67979405-69063400-fbd9-11e9-884e-aa5ffff8825a.PNG)

<p style="text-align:center"><img alt="" height="599" src="/download/8c829191e0e54aafbfd3051689543f32/image%288%29.png" width="401" /></p>

<p style="margin-left:40px"><br />
&bull;&nbsp;&nbsp; &nbsp;The preview report will be generated without consuming ArcGIS Online credits and will open automatically in a new window. If the pop-up window is blocked by your browser, ensure you allow it (as shown for Google Chrome below) and then click &ldquo;Preview sample report&rdquo; again.</p>

<p style="text-align:center"><img alt="" height="auto" src="/download/c76e41616edd470baa65980e08bc5455/image%281%29.png" /></p>

<p style="margin-left:40px">&bull;&nbsp;&nbsp; &nbsp;The preview report will look the same as your final report, except that you will see a &ldquo;Sample Report&rdquo; watermark on each page indicating this is not a final report. You can then make changes to your template based on the preview report before generating final reports.</p>

<p style="text-align:center"><img alt="" height="auto" src="/download/7909ff3fbe2c4820b7a5af67e6cf27b3/image%283%29.png" /></p>

<h3 style="margin-left:40px">Note:</h3>

<p style="margin-left:40px">&bull;&nbsp;&nbsp; &nbsp;Preview sample report is only available to the survey owner.<br />
&bull;&nbsp;&nbsp; &nbsp;When printing multiple records in the preview report, only the first three records will be processed and printed.</p>

<hr />

<h2>Embed</h2>
<p style="margin-left:40px">&bull;&nbsp;&nbsp; &nbsp;Embed your custom font files into the report template Word file and upload to Feature Report Template panel.<br />
&bull;&nbsp;&nbsp; &nbsp;Preview your report (in PDF format) using the template and make sure you are happy with the result.<br />
&bull;&nbsp;&nbsp; &nbsp;Print the report to PDF format or Word format, which should be in the same font and formatting.</p>

<hr />
<p>Please test these new features on the Survey123 beta website with your own surveys, and be sure to share any feedback or issues you may encounter in the <a

**Comment by gisguy007** [comment]
Enhancement: Change the preview 'link' to a button, similar to the "Generate" button; but change the color to something else, such as yellow.
![image](https://user-images.githubusercontent.com/43858983/69454520-3ef8eb00-0d1b-11ea-86e5-54d93223b0d7.png)

![image](https://user-images.githubusercontent.com/43858983/69454574-5c2db980-0d1b-11ea-827f-f270fc35396f.png)
![image](https://user-images.githubusercontent.com/43858983/69455120-88960580-0d1c-11ea-8a18-40b736679aa7.png)
