### ISSUE TITLE
FEEDBACK: Feature Report: Merge multiple records into a single output file

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#298]
<h2>Background:</h2>

<p>Survey123 Feature&nbsp;Report is an out-of-the-box functionality to help you generate high quality documents of your submitted surveys. Previously, we only supported the output of each survey record in a separate file when printing multiple selected records. Starting with Survey123 3.8&nbsp;beta, you can choose to merge multiple survey records into a single output file. For example, if you have a product satisfaction survey and you have collected more than 100 responses, you may want to bulk print all records for analysis and future reference in one document. Before this update, you could print all the records&nbsp;with one batch print action but you would get more than 100 standalone Word files. With the new beta merge output option, you can choose to merge all records into a single Word or <a href="https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&amp;arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&amp;artid={335A0766-D00A-4465-83C9-8982B546091B}" target="_blank">PDF output file</a> that includes all responses.</p>

<p><u><strong>Please note that the charging of 2.5 credits for a Feature Report is per feature, not per output file, so a merged report containing 10 records will charge 25 credits.</strong></u></p>

<h2>Steps:</h2>

<ul>
	<li>
	<p>Go to the Survey123 beta website:&nbsp;<a href="https://survey123beta.arcgis.com " target="_blank"><u href="https://survey123beta.arcgis.com/">https://survey123beta.arcgis.com&nbsp;</u></a>. If this is your first visit, you will see the terms and conditions of using the beta website. You must review and accept these terms and conditions before continuing.</p>
	</li>
	<li>
	<p>Sign in with your ArcGIS Online account and open the Feature Report panel on the Data tab of your survey.</p>
	</li>
</ul>

<ul>
	<li>
	<p>Select multiple records in the data table and select &quot;Merge multiple records to a single report file&quot;. You can sort the records by clicking the column header and then sort them by ascending or descending order. The sorted order of records will be preserved in the merged file.</p>
	</li>
</ul>

<p style="text-align:center"><img alt="" height="auto" src="/download/74b5dda9e8974b7bbf2af8e00b3f306a/image.png" /></p>

<p style="text-align:center"><u>Fig 1. Sort records&nbsp;</u></p>

<p style="text-align:center"><img alt="" height="auto" src="/download/aed23eb24ad945c6a716a9d6f74d59f1/image%282%29.png" /></p>

<p style="text-align:center"><u>Fig 2. Merge to a single file&nbsp;</u></p>

<ul>
	<li>
	<p>Upload your feature report template or choose an existing one. For more information, please refer to this&nbsp;<u href="https://community.esri.com/groups/survey123/blog/2019/07/23/understanding-survey123-feature-reports"><a href="https://community.esri.com/groups/survey123/blog/2019/07/23/understanding-survey123-feature-reports" target="_blank">GeoNet blog</a>&nbsp;</u>&nbsp;&nbsp;and the Survey123&nbsp;<u href="https://doc.arcgis.com/en/survey123/browser/analyze-results/featurereporttemplates.htm"><a href="https://doc.arcgis.com/en/survey123/browser/analyze-results/featurereporttemplates.htm" target="_blank">documentation</a>&nbsp;</u>.</p>
	</li>
</ul>

<p><u><em>Tip: if you want to have&nbsp;each printed record starts in a new page, you can insert a Page Break at the end of your report template.&nbsp;</em></u></p>

<p style="text-align:center"><img alt="" height="auto" src="/download/b80f79f048144351b58757f07875fc2b/image%283%29.png" /></p>

<p style="text-align:center"><u>Fig 3. Insert Page Break in the report template&nbsp;</u></p>

<ul>
	<li>
	<p>Click &quot;Preview sample report&quot; to make sure you are happy with the output result.</p>
	</li>
	<li>
	<p>Specify a file name, folder and output format and click &quot;Generate&quot;.</p>
	</li>
	<li>
	<p>The result is a single file containing all selected records in the same sorted order as the Data table, and each new record will be presented in a new page if you included page break in the template.</p>
	</li>
</ul>

<p style="text-align:center"><img alt="" height="523" src="/download/1e5dd8f66c3c4e2c99d177fdad15d30f/image%284%29.png" width="837" /></p>

<p style="text-align:center"><u>Fig 4. Merged output file with page breaks</u></p>

<p><strong>Note: report files larger than 512MB before merging will be split into multiple files.</strong></p>

<hr />
<p>Please test these new features on the Survey123 beta website with your own surveys, and be sure to share any feedback or issues you may encounter in the&nbsp;<u href="https://earlyadopter.esri.com/project/forum/topic.html?cap=e69ef91f45744b98882c651f7b518eb7&amp;forid={F93A6A79-F627-4727-8868-FC5E73406706}" target="_blank"><a href="https://earlyadopter.esri.com/project/forum/topic.html?cap=e69ef91f45744b98882c651f7b518eb7&amp;forid={F93A6A79-F627-4727-8868-FC5E73406706}" target="_blank">Survey123 Beta Website Feedback forum</a>&nbsp;</u>.</p>

<p>Thank you&nbsp;again for testing and contributing to the next release of Survey123 for ArcGIS.</p>

**Comment by gisguy007** [comment]
Merged preview or merged generated report- the last survey record was missing the image.  This was REPO'ed on other accounts using the same survey records.  It didn't matter if two records were selected or 5 records were selected, the last record was always missing the image (preview or generated).  The survey is 'Public' and is called: "Flood Control Debris". 
Below is a screenshot of the printing template:
![image](https://user-images.githubusercontent.com/43858983/69453161-2cc97d80-0d18-11ea-8bc1-e80a8d6038fa.png)
UPDATE: When the image input was moved up in the template, so that it wasn't at the end, the preview and generated reports came out as expected with no issues. Thus, if the last query in the template is an image, expect the last record in a 'merge' will be missing the picture.

**Comment by ivodev1** [comment]
When we use merge, if the feature report ends before the last line of the page, the next feature report starts immediately on the same page. It would be better to have each feature report, despite being merged, to start on a new page.
![ShortTemplate](https://user-images.githubusercontent.com/58088614/69454747-bf1f5080-0d1b-11ea-9c33-b9a33525b484.png)

Additionally, the page length for the word report and PDF is different: [example: 
![Word_vs_PDF_MergeMultiple](https://user-images.githubusercontent.com/58088614/69454857-03125580-0d1c-11ea-816e-3211cb3b3533.PNG)] This was noticed because of the issue above.

**Comment by OCrypter** [comment]
A cover page would be nice to have when merging multiple forms togethers. maybe a ${coverpage}${/coverpage} and maybe an outro ${lastpage} ${/lastpage} 

When merging, Have one cover page only and multiple reports in between without coverpages.

**Comment by OCrypter** [comment]
I have tried to merge 28 records together and create a pdf report. the PDF was created but the reporting engine gave an orange warning. 8 out of the 28 records had an issue generating a map. i was asking for a map at scale 5000

![image](https://user-images.githubusercontent.com/6771526/69460937-4f24c080-0d43-11ea-9296-b6c0def6d24a.png)

**Comment by OCrypter** [comment]
The word merge got back 4 errors out of 28

![image](https://user-images.githubusercontent.com/6771526/69461442-834cb100-0d44-11ea-902c-6b8006e82f77.png)

**Comment by BrandonArmstrong** [comment]
@gisguy007 thanks for the feedback
Internal Issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/4081
