### ISSUE TITLE
Enhancement: Allow for the ability to pause while recording an audio file

### ISSUE THREAD

**Issue by bethanyw** [tedrick/Survey123-Testing#30]
**Application:** Field App

**Device:** iPhone 5

**Operating System:** iOS 10.3.3

**Browser:** n/a

**Error Description:** n/a

**How to reproduce:** Provide the ability to pause while recording an audio file in the field app. It's currently only possible to stop a recording, which finalizes the file. Allowing to pause while recording would be a nice option.

**Have you tested with another survey?** n/a

**Comment by JohnHasthorpe** [comment]
Internal issue: https://devtopia.esri.com/Melbourne/Survey123/issues/1914
