### ISSUE TITLE
FEEDBACK: Create/Preview/Publish/Save as workflow on the Survey123 website

### ISSUE THREAD

**Issue by zhif7782** [tedrick/Survey123-Testing#300]
## Background

In the next release of the Survey123 web designer, we improved the underlying workflow of creating, preview and publishing a new survey. This allows us to eliminate the previous `metadata` table in the created source feature service and prepare for the coming new question types (equivalent to geotrace/geoshape in Survey123 Connect) in a near-future release for the web designer.

Although there is no functionality update at this time, we would like to invite you to test the create, preview, publish, save as workflow of the web designer to ensure there is no regression issue introduced by the current underlying change.

## Steps
Do any or all of the following workflows on the Survey123 website.

* New survey workflow: create a new survey, add various questions with different settings, save the survey as draft as needed, close and reopen the survey and continue editing, preview the survey, publish the survey, collect data with the survey and observe the results in the Data/Analyze tab.
* Old survey workflow: open any existing survey in your account on the beta website, try to make some changes by adding/removing questions, changing themes and save the survey as a draft, close and reopen the survey and continue editing, preview the survey, publish the survey, collect data with the survey and observe the results in the Data/Analyze tab.
  * **Note: please make sure to back up your survey or data if it's very important to you.**
* Save as: Try to save as any of the following surveys and observe if the newly created copy works as expected on the web designer.
  * New survey created on the beta website.
  * Old survey in your account created by yourself.
  * Old surveys created by others and shared with you which you can view result for.
* "Free mode": Just use the web designer as you want, try to find any bugs or issues.

<hr />
<p>Please test these on the Survey123 beta website with your own surveys, and be sure to share any feedback or issues you may encounter in the&nbsp;<u href="https://earlyadopter.esri.com/project/forum/topic.html?cap=e69ef91f45744b98882c651f7b518eb7&amp;forid={F93A6A79-F627-4727-8868-FC5E73406706}" target="_blank"><a href="https://earlyadopter.esri.com/project/forum/topic.html?cap=e69ef91f45744b98882c651f7b518eb7&amp;forid={F93A6A79-F627-4727-8868-FC5E73406706}" target="_blank">Survey123 Beta Website Feedback forum</a>&nbsp;</u>.</p>

<p>Thank you&nbsp;again for testing and contributing to the next release of Survey123 for ArcGIS.</p>

**Comment by zpelletier** [comment]
Created new survey, with just a few questions, previewed, published and opened on a device, **survey doesn't load correctly on device.** Captured a picture and viewed in the data/analyze section online with no problem.
![IMG_0117](https://user-images.githubusercontent.com/27016199/69451468-0cec8680-0d25-11ea-95f4-7e57efae98d9.PNG)
![IMG_0118](https://user-images.githubusercontent.com/27016199/69451470-0cec8680-0d25-11ea-87b1-94689f62666b.PNG)

**Comment by zpelletier** [comment]
Did a copy of a previous survey, made changes to the survey, changed out the Date field, added Date & Time together, changed the color scheme.  Publish, opened on device did collection, but survey will not send out, tried to edit the survey to see where errors were, noticed when going back in, some of the survey details are changed slightly.--like street address -the street number removed, next round, the phone number was changed.
![IMG_0119](https://user-images.githubusercontent.com/27016199/69452568-9ac97100-0d27-11ea-8228-57f7ad286559.PNG)
![IMG_0120](https://user-images.githubusercontent.com/27016199/69452569-9b620780-0d27-11ea-95b2-ab8fa9ad62df.PNG)

**Comment by Zachary-Sutherby** [comment]
When taking my survey published from the web designer in the Field app I saw that the survey was not displaying as expected. 

![5036](https://user-images.githubusercontent.com/54078266/69456452-8aad9380-0d1f-11ea-8901-3eeda4dae831.jpg)

The survey was published from the web app I then went back and added a question, a background, and some color changes in the web app.

**Comment by BrandonArmstrong** [comment]
@zpelletier it looks like the question that did not load properly in the field app is a "file" question, is this correct?  If so, it is a known issue that file upload is not supported in the field app.  Can you please confirm?

**Comment by BrandonArmstrong** [comment]
@Zachary-Sutherby 

are you referring to the likert question as the one not displaying as expected? This would be expected when viewed in the field app, as it is not supported there

**Comment by zpelletier** [comment]
> @zpelletier it looks like the question that did not load properly in the field app is a "file" question, is this correct? If so, it is a known issue that file upload is not supported in the field app. Can you please confirm?

Hi @BrandonArmstrong  looks like you are correct, I added the file upload to another survey in the regular Survey123 website, issue still persists. Survey doesn't load properly

**Comment by Zachary-Sutherby** [comment]
Hey @BrandonArmstrong, 

I had a select one and select multiple in the survey on top that did not load in the field app. I know I had made some changes to the survey design and republished it again. Unfortunately, I did not check the survey in the field app prior to making the changes and republishing.
