### ISSUE TITLE
FEEDBACK: Web app draft mode

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#302]
A form author can enable 'draft' mode in the Fieldworker collaboration settings.  This allows the form to save information locally in the browser and load it in if the user leaves the form partially done.  Enable draft mode and try:
- Partially filling in a form, closing the browser and reopening
- Filling in a form, submitting and reloading

Does it work how you would expect?

**Comment by BrandonArmstrong** [comment]
Chris
Kylie
Kanchana
Kim
Leonard

**Comment by czielinski-esri** [comment]
I created a Map question in my survey, and the line feature I added in the first draft of my survey was not saved.  This was seen in Chrome

**Comment by mappinista** [comment]
This also happened with polygon feature not saving. Using Chrome in Win10

**Comment by kyliedonia** [comment]
Same experience of the polygon feature not being remembered. Additionally, the map scale and extent were reset to how it was authored instead of what the user had been seeing. 

Other fields looked good.

**Comment by BrandonArmstrong** [comment]
Leonard: would be helpful if there was a method to name drafts in draft mode as opposed to default naming of values from fields that were filled out

**Comment by fendiaoxiaoshuazi** [comment]
@czielinski-esri @mappinista @kyliedonia Thanks for the feedback. We have logged the issue of unable to save polygon, polyline under the draft mode.

**Comment by fendiaoxiaoshuazi** [comment]
@kyliedonia Thanks for the feedback on saving map extent and scale in the draft mode, an [internal issue](https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/4198) has been created for the team to further investigate.

**Comment by fendiaoxiaoshuazi** [comment]
@BrandonArmstrong and Leonard. Thanks for the feedback in https://github.com/tedrick/Survey123-Testing/issues/302#issuecomment-580425180. Are you expecting a method to differentiate the draft answer and the default values?

**Comment by tedrick** [comment]
Thanks all for feedback.  Closing out issue.
