### ISSUE TITLE
FEEDBACK: Ranking question

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#303]
Survey123 is planning to introduce a new question that will allow users to rank items in a list.  

- Create a form with a ranking question - how easy/hard is it?
- How easy is it to use a ranking question in the web form?
- Can you create a feature report with the ranking question?  How does the data look in the report?

**Comment by BrandonArmstrong** [comment]
Josh
Alison
Dominic

**Comment by czielinski-esri** [comment]
Filling out the ranking question isn't intuitive.  Having to select the records before you can rank them is confusing

**Comment by JTHerman** [comment]
> 
> 
> Filling out the ranking question isn't intuitive. Having to select the records before you can rank them is confusing

I actually like this functionality because it gives users the option of either clicking to rank or dragging and dropping. Though I do see his point. I think it's more intuitive to drag and drop and if users have to click each option first, that may cause some confusion.

**Comment by dwalter-support** [comment]
I am having an issue with the "Show choices in random order" option which keeps throwing an error when attempting to publish.
![image_87](https://user-images.githubusercontent.com/60481934/73478171-95aa2300-4363-11ea-8ccd-7e59dced0b6e.png)

**Comment by czielinski-esri** [comment]
The Rank question does not display in the field app.

This is seen on:

- iOS
- Windows

**Comment by cdore1** [comment]
> I am having an issue with the "Show choices in random order" option which keeps throwing an error when attempting to publish.
> ![image_87](https://user-images.githubusercontent.com/60481934/73478171-95aa2300-4363-11ea-8ccd-7e59dced0b6e.png)

I am experiencing the same behaviour with ranking.  If I disable "Show choice in random order", I can then publish

**Comment by alisonesri** [comment]
**How easy is it to use a ranking question in the web form?**

Being able to click to rank the options or drag and drop the options to rank them is nice. 
It would be nice if we can click and drag the options into the ranking number right away instead of having to select them by clicking once and then having the option available to drag them into a different order. 

(please let me know if this makes sense)

**Comment by JTHerman** [comment]
Results of ranking questions appear lowercase in feature reports.

**Comment by alisonesri** [comment]
**Can you create a feature report with the ranking question? How does the data look in the report?**

The ranking results look clustered, there should be a space after each comma

**Comment by mappinista** [comment]
> **How easy is it to use a ranking question in the web form?**
> 
> Being able to click to rank the options or drag and drop the options to rank them is nice.
> It would be nice if we can click and drag the options into the ranking number right away instead of having to select them by clicking once and then having the option available to drag them into a different order.
> 
> (please let me know if this makes sense)

I agree that the ability to click and drag immediately without having to click to have a number "assigned" first would be more intuitive.

**Comment by JTHerman** [comment]
Not sure how this will be received, but I think it would be useful to be able to assign point values to each position. For example:

- Choice in position 1 gets three points.
- Choice in position 2 gets two points.
- Choice in position 3 gets one point.

This would allow users to visualize the results quantitatively. It would also be useful for summary reports.

**Comment by czielinski-esri** [comment]
> Not sure how this will be received, but I think it would be useful to be able to assign point values to each position. For example:
> 
> * Choice in position 1 gets three points.
> * Choice in position 2 gets two points.
> * Choice in position 3 gets one point.
> 
> This would allow users to visualize the results quantitatively. It would also be useful for summary reports.

This is something I've been thinking about as well.  If someone is utilizing a rank question, they likely need to be able to dig into the data a little bit more than having a list of values.  Maybe creating the same number of fields as there are ranking options would help.  That way any analysis like this could be done by the user without having to separate the values first.

**Comment by kyliedonia** [comment]
Not seeing in the field app, as reported earlier. This was on an iPhone 7 with iOS 13.3

**Comment by rbernstein80** [comment]
Not seeing the ranking options in the application on the phone. I am on an iPhone iOS 13.3 and I am using Flight Aware to access the application.
![ranking](https://user-images.githubusercontent.com/60482641/73482840-7794f080-436c-11ea-9a3f-456f16509aeb.jpeg)
![ranking](https://user-images.githubusercontent.com/60482641/73482841-782d8700-436c-11ea-9060-28b393dc1ccf.PNG)

**Comment by kyliedonia** [comment]
I'm unable to drag/drop them to reorder when filling out the survey in the browser.

**Comment by kyliedonia** [comment]
It would also be nice if there was a way to leave some items unranked (or equally last)

**Comment by kyliedonia** [comment]
Also nice to be able to say "we require you to rank 3 of these" (for example) as an author. The author should be able to set how many (if any) required in ranking.

**Comment by kyliedonia** [comment]
How these appear in the Analyze tab seems silly -- you see a bar or column chart showing how many times each was picked. But since all have to be used each time, it ends up being that you see a count of how many people have answered that question (just in a really weird chart representation). 

![image](https://user-images.githubusercontent.com/3945570/73499179-3ef91500-4374-11ea-85fa-e44b4ee57fe4.png)

This should either be presented in some otherway, or if rankings had different points could show kind of a ranking based on points attributed to each option.

**Comment by kyliedonia** [comment]
- When viewing the results in Map Viewer, it would be nice if the comma-delimited list could be formatted better. The popup is about reading the data, so showing the nice reader-friendly names (like when viewing the list of choices in Survey123) would be a nicer experience than seeing the values.
- In Survey123's data tab, click "Open in Map Viewer" and save the map. Open that map in Collector. The ranking is now a coded value domain, and I can only choose one.

**Comment by someevil** [comment]
I am having an issue with the "Show choices in random order" option which keeps throwing an error when attempting to publish.
![2020-01-31 11_08_00-Microsoft Edge](https://user-images.githubusercontent.com/15650380/73501650-ab2e5400-441a-11ea-83f4-d2d96ae6947f.png)
Deselecting 'random order' rectifies this problem.

**Comment by someevil** [comment]
I think the graphic moves way too slowly once we select an item (moves it to the top of list). I like that it shows the user it has moved, but I think users want to select options quicker than this graphic is allowing. Perhaps speeding the movement up would be beneficial.

**Comment by someevil** [comment]
I do not find the Analyse tab useful for the ranking question, the data provided is not necessary, perhaps hide this just as the map data is?
https://i.imgur.com/ebT7bnu.png

**Comment by someevil** [comment]
My org is not a big web form user, so this ranking made available to the field app would be ideal for me

**Comment by oopsliu** [comment]
@JTHerman Thanks for the feedback in https://github.com/tedrick/Survey123-Testing/issues/303#issuecomment-580394881, are you expecting the report to show choices labels instead of choice values?

**Comment by oopsliu** [comment]
@kyliedonia Thanks for the feedback, we have logged an [internal issue](https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/4192) for the enhancement to allow unranked choice.

**Comment by oopsliu** [comment]
@dwalter-support @cdore1 @someevil Thanks for the feedback, we are aware of the randomized option not working issue and it should be fixed soon and available to test on the next beta update.

**Comment by oopsliu** [comment]
@JTHerman @czielinski-esri @kyliedonia @someevil Thanks for the feedback and we are working on the Analyze tab which will use a score system to show the ranking results.

**Comment by oopsliu** [comment]
@czielinski-esri @JTHerman @alisonesri @mappinista @kyliedonia @someevil Thanks for the feedbacks on UX of the ranking question, [internal issue](https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/2272) has been created for the team to further investigate.

**Comment by oopsliu** [comment]
@czielinski-esri @kyliedonia @rbernstein80 @someevil Thanks for the feedback, we have logged your requirements for supporting Ranking question [in the field app](https://devtopia.esri.com/Melbourne/Survey123/issues/2209?#issuecomment-2054525).

**Comment by tedrick** [comment]
re-opening for Olympia holistic

**Comment by tedrick** [comment]
Thanks all for feedback.  Closing out issue.

**Comment by someevil** [comment]
I think the speed issue I was having back on Jan 31st has been resolved. Also there was no error when publishing this time. All good!
