### ISSUE TITLE
Challenge: Use the Create feature report module in Integromat to generate a PDF feature report

### ISSUE THREAD

**Issue by Shwujeng** [tedrick/Survey123-Testing#305]
It is now possible to select Portable Document Format (.pdf) as the file output option when using the Create feature report module in Integromat.

Please log in to the Integromat website and create a new scenario using the updated Create feature report module. Select .pdf as the Output Format in order to test this feature. 

![image](https://user-images.githubusercontent.com/29442153/73410812-2f1bfb00-42b8-11ea-90ce-f5ff8086e8a5.png)

You may also edit an existing module and change the Output Format to pdf and run the test.

**Comment by BrandonArmstrong** [comment]
Kanchana
Josh

**Comment by JTHerman** [comment]
If there are no feature report templates attached to a survey, the "Create feature report" module in Integromat auto-fills the template field with the survey name and does not thrown an error message. This leads to no resulting URL being generated and the HTTP module failing.

EDIT: Seems to only be reproducible with surveys published through S123 Connect.

**Comment by Shwujeng** [comment]
@JTHerman Could you provide a screenshot of the content in Create feature report module where it auto-fills the template field? I was not able to repro that using a survey I published from Connect without a feature report template. If you could share the screenshot and details of the connection you set in Integromat, that will be helpful to narrow down the issue.

**Comment by tedrick** [comment]
Thanks all for feedback.  Closing out issue.
