### ISSUE TITLE
Challenge: Feature Report Template Syntax-Stats and Summary Section.

### ISSUE THREAD

**Issue by Shwujeng** [tedrick/Survey123-Testing#306]
We are now supporting new syntax for getting statistics and the summary section in the feature report template. 

From Survey123 3.9 beta website, you can get statistical or aggregation results using new filter "stats" and specify the parameters of the stats filter.
![image](https://user-images.githubusercontent.com/29442153/73411260-95ede400-42b9-11ea-9a6c-57ffb7a21188.png)

We also introduce Summary section, which works as begining or ending pages with summary information of multiple records or statistical result in the feature report.
![image](https://user-images.githubusercontent.com/29442153/73411278-a3a36980-42b9-11ea-8f4b-21453a122f95.png)

Detailed information is provided in our online documentation on early adopter website and please use survey123 Beta website to test these new features:

[Feature Report Template Syntax-Stats and Summary Section](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={529926F6-DEDC-495F-AF85-B9F49287964F})

We will show you a demo to use Tree Health Survey and generate a statistic for the counts of tree issues recorded by severity level and add the statistical report in the summary session.

### **Sample of Syntax**
++++++++++++++++++

![image](https://user-images.githubusercontent.com/29442153/73322641-fa496e80-41f9-11ea-8c43-37f583cf959c.png)

### **Report Result**
++++++++++++++++

![image](https://user-images.githubusercontent.com/29442153/73322654-02091300-41fa-11ea-9040-270f7a7ece63.png)

Here is the result printout of the feature report in pdf format.
[Tree_Health_Survey__20200129171436.pdf](https://github.com/tedrick/Survey123-Testing/files/4131681/Tree_Health_Survey__20200129171436.pdf)
___

### **Additional syntax**
In addition to the above parameters used to formulate a filter for your survey, there are additional parameters and qualifiers that can be used to enhance your query to provide more specific information.

**where**: This filter is used to search for survey responses that contain specific values in a given field. For example, `where:"weather='sunny'"` will cause the filter to only use responses where the weather field contains the value sunny.

**!important**: This qualifier can be added to any filter, to override any constraints on the values that the filter returns. For example, if you were printing reports from only the last seven days, `where:"weather='sunny' !important"` would cause the filter to only use responses where the weather field contains the value sunny, but pulls from all applicable responses in the feature service, rather than just the responses selected to be printed.

**$inputParams**: This placeholder can be used within any filter to refer to the parameters used when printing a feature report, set through the Survey123 website. These parameters can then be further qualified to narrow down your response. For example, `orderByFields:"$inputParams"` will order the fields using the ordering set in the Survey123 website when printing reports. You can also use $inputParams to apply these parameters to repeats.
___
Please give it a try using this new feature report template syntax on our survey123 Beta website with your own survey.

**Comment by BrandonArmstrong** [comment]
Derek
Kanchana

**Comment by kunjoo91** [comment]
When I select multiple records it adds _${objectId} to the report name. Is that intentional?
![image](https://user-images.githubusercontent.com/24254822/73482048-e153d100-4351-11ea-9ae9-b767a903ca9b.png)

**Comment by DerekLaw** [comment]
I just realized that the survey I had intended to test this on, does not have any integer fields - it's composed of all string fields (a series of select one and select multiple questions). I was unable to test properly - sorry.

**Comment by kunjoo91** [comment]
I like the fact that the API recognizes the error in the original template.
It was able to pick up the error. It was q2 when the variable was actually supposed to be q8.

I would prefer this to be validated when uploading the template.

Max Question 8: ${#TestDeleteRelated_Records | stats:"max,q8,**max_q2**”} ${max_q8} ${/}

![image](https://user-images.githubusercontent.com/24254822/73482507-bcac2900-4352-11ea-9636-6563cc34ca0f.png)

**Comment by kunjoo91** [comment]
It would be good to provide more detail on syntax and expected behavior.

For Ex (Syntax): ${#TestDeleteRelated_Records | stats:"max,q8,**max_q2**”} **${max_q8}** ${/} --> The third paramater in the function is not optional. It was required to generate the statistic.

(Expected Behavior): I used all the report types (Split, Merge nextpage, Merge continuous), and I was getting seperate report sections for each record. Somehow I expected it to aggregate across all records, but it was aggregating only the values within one record.
[MergeNextpage.docx](https://github.com/tedrick/Survey123-Testing/files/4135929/MergeNextpage.docx)
[MergeContinuous.docx](https://github.com/tedrick/Survey123-Testing/files/4135930/MergeContinuous.docx)
[SampleTemplate.docx](https://github.com/tedrick/Survey123-Testing/files/4135931/SampleTemplate.docx)
[Split.zip](https://github.com/tedrick/Survey123-Testing/files/4135932/Split.zip)

**Comment by jbickmore** [comment]
Tried to do very basic count of features 
using chrome on windows pc
![image](https://user-images.githubusercontent.com/20099225/73503748-3ad70100-4421-11ea-825a-2e82aea193bf.png)
no counts are coming through??

**Comment by jim-moore** [comment]
For an integer field `number_1` and a text field `some_text`, find the sum and count respectively:

```
$<$summary>
Sum of Number 1: ${surveyPoint | stats:"sum,number_1"}
Count of Some text: ${surveyPoint | stats:"count,some_text"}
$</>
```

**Comment by Shwujeng** [comment]
When the summary session open/close tags are not in an individual line, running feature report will throw charging credits error.
![image](https://user-images.githubusercontent.com/29442153/73702306-39b40700-46a1-11ea-9d96-5acdf1e492d3.png)

Syntax example is as:
![image](https://user-images.githubusercontent.com/29442153/73702332-505a5e00-46a1-11ea-9681-fa8c5e462ada.png)

The error message is misleading and should throw more informative error message.
