### ISSUE TITLE
CHALLENGE: Create a polygon or line form, collect and review data

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#307]
Create a form with a polygon or line question, collect a few records and review the data in the Analyze and Data tabs.

Are there any issues collecting the polygon/line?  Do the collection tools work as you expect?

How does the data look in the Survey123 website once collected?

**Comment by BrandonArmstrong** [comment]
Celine
Kylie
Leonard
Erica

**Comment by JTHerman** [comment]
If there are no feature report templates attached to a survey, the "Create feature report" module in Integromat auto-fills the template field with the survey name and does not thrown an error message. This leads to no resulting URL being generated and the HTTP module failing.

**Comment by mappinista** [comment]
My survey used the dual-polygon map widget set to dual-polygon types of drawing. When I first opened the analyze tab, the geometries showed in the "Map" view and the legend was populated, but after I changed the basemap and scrolled down and back up, the geometries and legend items were gone.
![MappingWidgetBlankAnalyze](https://user-images.githubusercontent.com/14221059/73480251-cafc4400-4356-11ea-8b11-8d4358acacc1.JPG)

**Comment by mcavoye** [comment]
created a single question Line survey.

![image](https://user-images.githubusercontent.com/19191290/74057896-b55fcd80-4999-11ea-98fa-68d1c73057d6.png)

published survey, download survey to beta field app (windows standalone installer)

downloaded survey, go to collect data. NO MAP AVAILABLE!
![image](https://user-images.githubusercontent.com/19191290/74058078-17203780-499a-11ea-8294-175db58475c4.png)

**Comment by alex8odd** [comment]
The polygons are easy to draw and edit. This form of question would be more useful if more than one polygon or line can be added to each survey.

Suggestion for a multi-part mapping question (may be more applicable in Connect): 1) user selects a site location from a list of options, for example natural area sites; 2) the map zooms to the selected geometry, and then the user draws the geometry.

When viewing the data, the map view is stagnant and does not pan and zoom to the selected data entry.
