### ISSUE TITLE
Survey123 About Info - Suggest update year

### ISSUE THREAD

**Issue by DerekLaw** [tedrick/Survey123-Testing#309]
**Application:** Connect | Field App |

**Device:** Google Pixel 2 phone 

**Operating System:** Android v10

**Browser:** _For the website_

**Error Description:** 

Opened both Survey123 Connect and the mobile app for Android v3.9.100, noticed in the About dialog that the date shows "Copyright 2019"  - suggest update to 2020

![about_dialog](https://user-images.githubusercontent.com/1037228/73476621-76050180-4347-11ea-9e48-8a782e428283.png)

**How to reproduce:**

Just open the apps and view the About dialog

**Have you tested with another survey?**  N/A

**Comment by phil-wilson** [comment]
Thanks @DerekLaw. This has been updated in all our apps and will be available in the final release.
