### ISSUE TITLE
Enhancement: Allow Users to Select an Image from the Gallery when using the Draw Option

### ISSUE THREAD

**Issue by gibbonsbr** [tedrick/Survey123-Testing#31]
**Application:** Field App

**Device:** All

When using the 'Draw' appearance for images, it would be really helpful to allow the user to select an image from the gallery in addition to taking a new picture. 

For some forms like manhole inspections, we have a standard image that we markup for each inspection. The template image could be preloaded onto the devices for field inspections and then selected for markups. For other forms, we use screenshots from Collector or the Survey123 map for markups. This would be especially helpful for building inspections, where we use a screenshot of the building from Collector to markup for inspections completed in Survey123 (currently using a 3rd party application for the markups).
![image](https://user-images.githubusercontent.com/31450043/29843657-a6d056e6-8cda-11e7-9741-3c3987fb3a03.png)

**Comment by JohnHasthorpe** [comment]
Internal issue: https://devtopia.esri.com/Melbourne/Survey123/issues/1820

**Comment by JohnHasthorpe** [comment]
2.4 Testing complete
