### ISSUE TITLE
Add field(s) to feature service by default when one republishes after adding 1 or more fields to the survey

### ISSUE THREAD

**Issue by kimberly-peter** [tedrick/Survey123-Testing#310]
**Application:** Connect 

**Device:** PC

**Operating System:** Windows 10

**Browser:** _For the website_

**Enhancement request:** If I add a question to the survey, I cannot think of a reason why I wouldn't want the required field added to the underlying feature service. Maybe just warn that "One or more fields will be added to the survey. Existing survey records will not contain data for these new fields."
![image](https://user-images.githubusercontent.com/8865041/73480540-e9f6d800-434e-11ea-949c-9a1b56e3be88.png)

**How to reproduce:**

**Have you tested with another survey?**

**Comment by tedrick** [comment]
Thank you for the detailed suggestion - I've created an internal discussion issue to address this in the future.
