### ISSUE TITLE
Can't get Keyboard to go away after text form entry

### ISSUE THREAD

**Issue by billwie** [tedrick/Survey123-Testing#311]
**Application:**  Field App 

**Device:** iphone 7plus

**Operating System:** iOS v13.3

**Browser:** _For the website_

**Error Description:** 
Unable to close onscreen keyboard after entering in text field. You have to click the hamburger menu in the top right. My test survey is not long enough that scrolling is enabled but it's annoying to have to do this to reach the submit button.

**How to reproduce:**
write something in a text field

**Have you tested with another survey?** 
No

**Comment by cdore1** [comment]
I had a the same issue with iPhone and text - the keyboard would not go away until I decided to submit the survey

**Comment by Shwujeng** [comment]
@billwie @cdore1 Could you try to swipe down the keyboard? Usually swipe down the keyboard will work to close it on iPhone.

**Comment by phil-wilson** [comment]
Closing as keyboard on iOS can be closed by swipe down action.
