### ISSUE TITLE
Make it easier to fill out the same survey again in the web

### ISSUE THREAD

**Issue by kyliedonia** [tedrick/Survey123-Testing#313]
**Application:** Website

**How to reproduce:** Fill out a survey and submit it. On the thank you screen, it is hard to get back and fill out the survey again. Right now, I have people refresh the page. It would be nice if there was a button for filling it out again (or if clicking on the title or something took you back to filling it out).

The "Reset" button does do this now, if drafts are enabled for a survey, but that's not super-intuitive.

**Comment by fendiaoxiaoshuazi** [comment]
Thank you for the feedback. In the design page, there is a checkbox that says "Show message to prompt the user to submit another record" at the bottom of the settings panel. If the creator checks the checkbox, on the thank you screen, "Press here to submit another survey" will show under the thank you message.

**Comment by kyliedonia** [comment]
Cool thanks! I hadn't seen that.
