### ISSUE TITLE
Overview Graphs

### ISSUE THREAD

**Issue by Bark0s** [tedrick/Survey123-Testing#314]
**Application:** Website 

**Device:** Browser

**Operating System:** N/A

**Browser:** Chrome

**Suggestion** Overview graph - second circle - Total Participants - it'd be great to see multiple users on the graph.  Yes they are listed in a table below the graph but it'd be good if they were coloured coded in the table and then shown on the graph.  

So when a user clicks on the Total Participants circle the survey doesn't load but the graph changes.

**Comment by marikavertzonis** [comment]
options to consider:
 - when click on **Total Participants** show a line for each participant on the existing graph, or,
 - when click on the individual user entry in the table below, change the single line in the graph to represent that individual user

![image](https://user-images.githubusercontent.com/5713624/73511565-1c313400-443a-11ea-898b-41068828ce35.png)

**Comment by oopsliu** [comment]
Thanks for the feedback, created internal issue for the enhancement: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/4193.
Closing.
