### ISSUE TITLE
Creating new geometry

### ISSUE THREAD

**Issue by Bark0s** [tedrick/Survey123-Testing#316]
Can the Backspace functionality available in the desktop apps be available in the map widget in Browser?  eg.  Click to place a number of vertices, realise the last two were placed incorrectly, then press backspace twice, they erase, then I can proceed.

**Comment by Bark0s** [comment]
The editing after commit is nice though.

**Comment by brettstokes** [comment]
Added to Feature Requirements repo (https://github.com/ArcGIS/survey123-feature-requirements/issues/258)
