### ISSUE TITLE
iPhone 11 camera zoom

### ISSUE THREAD

**Issue by Bark0s** [tedrick/Survey123-Testing#317]
**Application:** Field App

**Device:** _Important for Field App especially_

**Operating System:** iOS 13.3

When initiating the camera to take photos to attach to questions I get a zoom slider.  This slider goes from 1 to 189x zoom.  189 is excessive and for me, useless.  Perhaps people with attached lenses need this range.  

The iPhone 11 has a second camera that is 0.5x zoom, so being able to switch to this would be good.  I don't know what the zoom is for the iPhone 11 Pro's third camera.  Consider including that too.

**Comment by tedrick** [comment]
Thanks for the feedback.  We've taken this internally to research and consider for a future release.
