### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by jbickmore** [tedrick/Survey123-Testing#318]
Am wanting to capture costs ($) in a survey

I want the field to be float or double and limited to 2 decimal places also having relevant currency symbol
eg $4,500.55 

In many cases the cents wont be required so dont want to force people to enter 100.00 rather than 100

I would need to be able to sum this field in a dashboard or other report

Ideally being able to select "Currency" in the Appearance collumn would be great

Have searched forums for ways to do this but I dont think it is covered??

**Comment by marikavertzonis** [comment]
we should consider this as a control add-in example.

**Comment by tedrick** [comment]
Noted as a potential add-in.  Closing
