### ISSUE TITLE
Capture period of time

### ISSUE THREAD

**Issue by jbickmore** [tedrick/Survey123-Testing#319]
I need to capture an amount of time that has been spent on a particular job or time that is estimated is needed

EG It might be estimated that 2 hours 30 mins is required to fix a fence

The best way I have been able to do this is 2.5 (representing 2 hrs 30 mins)
A spinner would be great for hours and minutes with hours limited to 24 and minutes limited to 60. 

**Application:** Connect | Field App | Website | On Premises | _Other_

**Device:** _Important for Field App especially_

**Operating System:** _Provide version, i.e., Android 5.0.1_

**Browser:** _For the website_

**Error Description:** 

**How to reproduce:**

**Have you tested with another survey?**

**Comment by marikavertzonis** [comment]
we should consider this as a time control add-in.

**Comment by oopsliu** [comment]
Internal issue: https://github.com/ArcGIS/survey123-feature-requirements/issues/255
