### ISSUE TITLE
Feedback: Favorites do not apply to items inside a repeat.

### ISSUE THREAD

**Issue by fcxagerr** [tedrick/Survey123-Testing#32]
**Application:** Connect | Field App

**Device:** _iPhone 7_, _Dell Laptop_

**Operating System:** _iOS10_, _Windows 10_

**Error Description:** When selecting 'Set as favorite answers' only answers outside of a repeated group are saved as favorites.

**How to reproduce:** In a survey with both repeated and non-repeated questions, set answers as favorites. When pasting favorites in another survey, only non-repeated answers will paste.

**Have you tested with another survey?** Yes

**Comment by JohnHasthorpe** [comment]
Internal issue raised. 2.4 complete - so closing this issue.
