### ISSUE TITLE
Deleting Related Record using Survey123 Website Data Tab

### ISSUE THREAD

**Issue by someevil** [tedrick/Survey123-Testing#320]
I have many surveys which have related tables. These related tables all capture inspection data, so many inspections happen on individual assets, over time.

When you view data in the Survey123 Data page, you can select a row in your related table, it will display a good summary down the right of screen, this will include information from original assets, and all related tables. 

Now from time to time we need to delete a related record item (inspection), but we do not want to delete the original asset, nor do we want to delete all other inspections carried out on this asset.

The issue we have is that when we click the trash can icon, it warns us that we will delete all related items, and original record.... not good.

I think this needs a review, as there is no way to delete just this one record using the web. The workaround I am using is dragging the table into ArcPro, select the single row and delete from there.
![2020-01-31 12_19_31-Desktop](https://user-images.githubusercontent.com/15650380/73505017-5b08bf00-4425-11ea-8af5-a4fff34ab9a0.jpg)

**Comment by oopsliu** [comment]
Thank you for the feedback @someevil We have logged an [internal issue](https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/4195) for the enhancement.
Closing.
