### ISSUE TITLE
Different usernames captured

### ISSUE THREAD

**Issue by jbickmore** [tedrick/Survey123-Testing#321]
Noticed that 1 user has 4 different spellings of his username??

He was using survey123 on an iphone. most of the surveys were captured on same afternoon

The username is not a field he can edit (or even see) within the survey

![image](https://user-images.githubusercontent.com/20099225/73506656-5266b780-442a-11ea-9dbc-805c61ad1f3b.png)

**Application:** Connect | Field App | Website | On Premises | _Other_

**Device:** _Important for Field App especially_

**Operating System:** _Provide version, i.e., Android 5.0.1_

**Browser:** _For the website_

**Error Description:** 

**How to reproduce:**

**Have you tested with another survey?**

**Comment by phil-wilson** [comment]
@jbickmore As discussed during the holistic testing day, if you can please try to reproduce this on another device, of have the same user try again on same device. Also suggest to uninstall and reinstall the app fully. The username and other user sign in details are written to a setting .json file in ~\ArcGIS\AppStudio\Settings\ folder. If you open this file in text editor you can see what is coming from the AGO/Portal account and this is what is used for the username and email question type.

Closing this issue and noted as bug. If you continue to see this issue occur and can reproduce it can you please log it with Esri support so we can capture further information and repro steps.
