### ISSUE TITLE
Guidance hint

### ISSUE THREAD

**Issue by Bark0s** [tedrick/Survey123-Testing#322]
Can all text and and integer fields please have custom guidance hints available?  There are already guidance hints for integers that show 123 in grey but it'd be good to have them.

Then we might be able to no longer show field names and have even neater forms.  

Please see example below

![image](https://user-images.githubusercontent.com/60490129/73512031-218f7e00-443c-11ea-8f53-4a7eeeeccebc.png)

**Comment by phil-wilson** [comment]
Thanks @Bark0s for the enhancement request. We have added this to our internal repo and backlog and will keep you updated when it gets implemented.
