### ISSUE TITLE
Feedback: New Map question type in Survey123 web designer

### ISSUE THREAD

**Issue by IsmaelInRedlands** [tedrick/Survey123-Testing#324]
**Context**: With version 3.9 we will be replacing the Geopoint question in web designer with a new Map question type. The Map question types lets you publish surveys to capture either a point, line or polygon geometry.

As a guidance for your own testing and feedback:

* Create surveys with different geometry types. Is the user experience for the survey author straight-forward?
* Use the new Map question in the web and field apps. Is the user experience for the end user of the survey straight-forward?
* Look at the results of your surveys using the Data and Analyze tabs. Can you properly view, query and analyze the results of surveys with lines and polygons?

If you need inspiration:
* Create a survey for citizens to report no-spray zones within their city:
    * Date and time of request
    * Area not to be sprayed
    * Justification for the request
* Create a survey for volunteers to report segments of a river that have been surveyed
    * Date and time of survey
    * Segment of the river that has been surveyed
    * Species found through the survey: Bird A, Bird B, Bird C, Bird C etc

**Comment by BrandonArmstrong** [comment]
Nicole
Nobu
Alison Walker
Leonard

**Comment by nicsi76** [comment]
I couldn't find a way to move the extent of the map while drawing a polygon - I ran into the search field and had to scroll out to be able to continue drawing in the right place. 
I would also like an option to disable the search field.

**Comment by asmyrk** [comment]
When editing the Survey, I click on the Map to edit the question, and sometimes the panel is just blank.  I have to click to a different question and come back or refresh the page.

**Comment by asmyrk** [comment]
![Screenshot 2020-02-20 at 12 00 33 PM](https://user-images.githubusercontent.com/31287579/74968818-b6045500-53d8-11ea-9477-7be4ff989092.png)
This is what I get when I go to capture a line or polygon in the Field App on my iPhone.  Survey123 3.9.144 right?  Am I missing something?

**Comment by asmyrk** [comment]
![Screenshot 2020-02-20 at 12 03 03 PM](https://user-images.githubusercontent.com/31287579/74968989-08de0c80-53d9-11ea-9854-7a9bfa227db6.png)
This is what I get when I just do a point.  I see the coordinates of my phone but no map.

**Comment by nicsi76** [comment]
![image](https://user-images.githubusercontent.com/11991954/74969142-add20700-5424-11ea-8586-b6df7668a104.png)
Same for polygons :-(

**Comment by nicsi76** [comment]
I really like the way you can enlarge the map when filling the form in the browser!

**Comment by asmyrk** [comment]
Works in the web app, but it seems I can only digitize.  I can't use GPS to collect anything.

**Comment by asmyrk** [comment]
A little tricky to edit a shape once you've created it.  Seems it's easier to just wipe it out and start again.  I try to grab a vertex and end up moving the whole shape.  Or I try to pan the map and end up moving the shape.  Maybe there could be buttons on the edit screen that would specify what action you're doing.  Editing a vertex or moving a feature.

**Comment by nicsi76** [comment]
> A little tricky to edit a shape once you've created it.  Seems it's easier to just wipe it out and start again.  I try to grab a vertex and end up moving the whole shape.  Or I try to pan the map and end up moving the shape.  Maybe there could be buttons on the edit screen that would specify what action you're doing.  Editing a vertex or moving a feature.

Interesting, I found it very handy.

**Comment by nobu-EJ** [comment]
Creating Area using "Shape" option is too strict. I could not create a Circle polygon.
![s123](https://user-images.githubusercontent.com/4115177/74971139-f0b2cf80-5462-11ea-8d02-ca2bc6ebe82c.gif)

**Comment by nobu-EJ** [comment]
Custom Basemap doesn't display in the Survey.
Steps:
 1. Create and set custom basemap gallery in the organization settings.
  https://www.esri.com/arcgis-blog/products/arcgis-online/mapping/custom-basemap-gallery/
 2. Add this map to the gallery.
  https://www.arcgis.com/home/item.html?id=cb6b3b6b478d4d46b98073420a1196b5
 3. Launch Survey123 Web -> Add Map
 4. Select basemap which set at step2. Then, zoom to Japan.
![image](https://user-images.githubusercontent.com/4115177/74989643-de4e7c80-53f5-11ea-887e-45390a06894a.png)
  Custom Basemap should be displayed at this mode.
 5. Click Preview or open the Survey. Then, custom basemap will be disappeared.
![image](https://user-images.githubusercontent.com/4115177/74989707-10f87500-53f6-11ea-8ad5-1ff9a7785406.png)

**Comment by oopsliu** [comment]
@nicsi76 @asmyrk @nobu-EJ Thanks a lot for the feedbacks, we have created dev issues for them.

**Comment by oopsliu** [comment]
@nobu-EJ The issue you mentioned in https://github.com/tedrick/Survey123-Testing/issues/324#issuecomment-589409607 has been fixed in survey123beta.arcgis.com. Thank you again for the feedback!
