### ISSUE TITLE
Feedback: Configure a survey with an offline map

### ISSUE THREAD

**Issue by IsmaelInRedlands** [tedrick/Survey123-Testing#325]
**Context:** While still flagged as Beta, the Survey123 released version supports the configuration of offline maps using vector tile packages and mobile map packages. Check out this [help topic](https://doc.arcgis.com/en/survey123/desktop/create-surveys/preparebasemaps.htm) for more details.

Test this functionality providing feedback about:

* Experience for associating the map with an existing survey (in Connect)
* Experience for the end user (Does it crash, is it fast, is it intuitive?)

If you need maps:
* [Vector Tile Package of Redlands](https://www.arcgis.com/home/item.html?id=c50810eb7ff54b40b5c1213ab6ea01e4)
* [Create your own OSM Vector Tile Package](https://apl.esri.com/jg/OSMVectorTileExport/index.html)

**Comment by BrandonArmstrong** [comment]
Pablo
Ohan
Celine
Nicole

**Comment by nicsi76** [comment]
I find the process quite straight forward. To avoid usage of mobile data for downloading the offline map would it maybe be possible to do a setting to "download offline map only when on WiFi" like in audible?
