### ISSUE TITLE
Bug: Loading the inbox fails with certain feature layers

### ISSUE THREAD

**Issue by jessnoo** [tedrick/Survey123-Testing#33]
**Application:**  Field App 

**Device:** _Desktop in holistic lab_ also happens in iOS devices

**Operating System:** _Windows 10 Enterprise_

**Browser:** _n/a_

**Error Description:** with a survey that is using an existing feature layer, trying to load the inbox or submit new surveys results in the app spinning endlessly

**How to reproduce:**

test service item: http://stategovernment.maps.arcgis.com/home/item.html?id=c612fc717ca3427691e608e8922fe32a

note, this item was published from Pro

survey form for the item: 
[Resilience FS UVR Symbols.xlsx](https://github.com/tedrick/Survey123-Testing/files/1261848/Resilience.FS.UVR.Symbols.xlsx)

1. publish a survey based on the hosted layer -- be sure to enable the inbox
2. open Survey 123 Field App
3. Download survey
4. go to Inbox and Refresh >> spins endlessly 

with log file enabled, there are errors: 
<12>1 2017-08-29T21:46:44Z HOLISTIC44 Survey123forArcGIS 5768 - [AppStudio@11205 category="default" filename="XFormData.qml" line="1426"] qrc:/qml/XForms/XFormData.qml:1426: TypeError: Cannot read property 'name' of undefined

<12>1 2017-08-29T21:46:47Z HOLISTIC44 Survey123forArcGIS 5768 - [AppStudio@11205 category="default" filename="XFormFeatureService.qml" line="856"] qrc:/qml/XForms/XFormFeatureService.qml:856: TypeError: Cannot read property 'name' of undefined

[Survey123forArcGIS-20170829-144627 LOG.txt](https://github.com/tedrick/Survey123-Testing/files/1261869/Survey123forArcGIS-20170829-144627.LOG.txt)

**Alternate Test**
test service item: http://stategovernment.maps.arcgis.com/home/item.html?id=683273c1b41c41e194af34b38dfedc60
this item was published from Pro

same form as above.  note the only intended difference between this service and the other service is the symbology.  this has a simple renderer, the failing service has a unique value renderer.

1.  publish a survey based on the hosted layer -- be sure to enable the inbox
2. open Survey 123 Field App
3. Download survey
4. go to Inbox and Refresh >> updates as expected

**Have you tested with another survey?** 

yes... 

- tried with a different layer using a unique value renderer - this worked as expected
- tried creating a new hosted feature layer using the problem one as a template - this worked as expected

**Comment by jessnoo** [comment]
source pro project used for publishing the original problem layer.  sample above was simplified some, but still demonstrates the problem.
[VulnerabilityAssessment_2_0_Release2.zip](https://github.com/tedrick/Survey123-Testing/files/1261886/VulnerabilityAssessment_2_0_Release2.zip)

**Comment by jessnoo** [comment]
here's the source pro project -- 
[CommunityResilience_2_0_Demo_Release2aprx.zip](https://github.com/tedrick/Survey123-Testing/files/1261893/CommunityResilience_2_0_Demo_Release2aprx.zip)

**Comment by jessnoo** [comment]
could it possibly have something to do with these groupings?

![image](https://user-images.githubusercontent.com/6181441/29847561-185721c8-8cd1-11e7-8ecc-97f45f4e58fa.png)

**Comment by tedrick** [comment]
Investigated & responded via e-mail:

>It looks like the ArcGIS Online org this is published to requires log in- hence me getting challenged.  Changing the url to go on www.arcgis.com corrected the matter.
>
>I believe the issue is an unusual configuration of this specific feature service – it consists of 1 layer that has an id of 1 .  This in theory can be done through manual id settings in ArcMap and ArcGIS Pro; however, I’m actually not able to publish a service that replicates this- my attempts fail during publishing.  If you can keep the service up for us to use in diagnosis, it would be helpful in resolving the error in Survey123.
>
>A couple of things that may influence your survey/feature service design:
1) the Feature Service has a domain that contains a space in its name.  Survey123, due to the XLSForm standard, does not support choice lists with a space.  This can be worked around by substituting an underscore for a space in the choice list
2) The domains have values that contain spaces; this is strongly discouraged by the XLSForm Spec and generates a warning in Survey123

**Comment by JohnHasthorpe** [comment]
Issue raised: https://devtopia.esri.com/Melbourne/Survey123/issues/1851

**Comment by JohnHasthorpe** [comment]
2.4 testing complete
