### ISSUE TITLE
FEEDBACK: Feature Report PDF Generation

### ISSUE THREAD

**Issue by Shwujeng** [tedrick/Survey123-Testing#330]
<h2>Print to PDF format</h2>

<p>Currently, in Survey123 3.6 or earlier, you are only able to generate reports in Microsoft Word (.docx) format. Starting with Survey123 3.7 beta we have added support for PDF, which will be beneficial for many users.</p>

<p><u><strong>Please note that the &ldquo;Print to PDF&rdquo; service will consume ArcGIS credits at the same rate as .docx format reports (2.5 credits per feature generated), even as a beta feature (unless the Preview mode is used).</strong></u></p>

<p>Follow these steps to create PDF feature reports:</p>

<p style="margin-left:40px">&bull;&nbsp;&nbsp; &nbsp;Go to the Survey123 website: <a href="https://always" target="_blank">https://survey123.arcgis.com</a> and open the Feature Report panel on the Data tab of your survey.<br />
&bull;&nbsp;&nbsp; &nbsp;Upload your feature report template or choose an existing one. For more information, please refer to online documentation: 

https://doc.arcgis.com/en/survey123/browser/analyze-results/printsurveyresults.htm

&bull;&nbsp;&nbsp; &nbsp;Select the record or multiple records (by pressing ctrl or shift on your keyboard) that you wish to print or choose &ldquo;All records in the table&rdquo; in the left panel to print every record.</p>

<p style="margin-left:40px">&bull;&nbsp;&nbsp; &nbsp;Preview the report using &quot;Preview sample report&quot;&nbsp;as described above, to make sure you are happy with the result.<br />
&bull;&nbsp;&nbsp; &nbsp;Select &ldquo;Portable Document Format&nbsp;(.pdf)&rdquo; from the drop-down &quot;Format&rdquo; list.&nbsp;</p>

![pdf_beta](https://user-images.githubusercontent.com/6314443/67983571-344aaa80-fbe2-11e9-827e-2e6e67de66f3.png)

<p style="text-align:center"><img alt="" height="298" src="/download/54ee2429df6041e59ec8c64baf55cc44/image%286%29.png" width="389" /></p>

<p style="margin-left:40px"><br />
&bull;&nbsp; &nbsp; Click &ldquo;Generate&rdquo;, and the report will be generated in PDF format. You can see your recent work in the &ldquo;Recent tasks&rdquo; panel.<br />
&bull;&nbsp;&nbsp; &nbsp;Similar to the preview mode, if you have generated a single PDF report it will open automatically in a new window. You may need to change your browser settings to allow pop-ups.</p>

<p style="text-align:center"><img alt="" height="auto" src="/download/8f83adddfa654e928667a14b443c2dd9/image%284%29.png" /></p>

![pdf_output](https://user-images.githubusercontent.com/6314443/67983845-c18dff00-fbe2-11e9-855d-639b6c2ca952.PNG)

**Comment by BrandonArmstrong** [comment]
Francisco
Allison
Ohan

**Comment by OCrypter** [comment]
The checkboxes are not consistent between Word & PDF ( with and without save fonts )
![image](https://user-images.githubusercontent.com/6771526/74968466-e48a2c00-53e8-11ea-90ec-363822e67f67.png)

**Comment by oopsliu** [comment]
Thanks @OCrypter for the feedback!
