### ISSUE TITLE
Cursor is jumping when filling text field 

### ISSUE THREAD

**Issue by nicsi76** [tedrick/Survey123-Testing#333]
When filling a form in the field app with a multiline text field the cursor jumps from the writing position to a couple of lines up (seemed a random position). 

Experienced on iPhone, Software Version 13.3.1

How to reproduce: 
Create a form with a text field in multiline appearance with a length of 500 and fill in text in the field app.

Not reproducable in 3.7.57 so far.

**Comment by tedrick** [comment]
@nicsi76, 

Thanks for reporting this.  This is due to an issue in the Qt framework; we are evaluating a patch that can address this issue.
