### ISSUE TITLE
Feedback: Improvement to Image questions

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#335]
Survey123 3.10 features some improvements to capturing photos.

First, multiple photos per question are now supported.  This can be enabled by specifying the `multiline` appearance for an image question.  This works regular image, draw and annotate questions; it does not work with signature questions.

Secondly, the method of image capture can also be set.  This allows you to restrict the form to only capture a new photo, for example.  This is set specifying `method=<CAPTURE_METHOD>` the `bind::esri:style` column on the image question.  The supported methods are:
- `browse` (select an existing file)
- `camera` (device camera)
- `map` (annotate question - image capture of a map)

As part of this, the photo question tools have also been improved.  'View' and 'Rename' tools have been added; to accomodate this, a 'More Actions' button is now present and includes the rotation tools.  Additionally, when using a multiple image question, there are 'next/previous' image navigation buttons to the side of the image question.

Set up your forms to capture multiple photos and provide feedback
- Any issues setting up multiple images in the form?
- Does specifying the capture method work as you expect?
- Any concerns or feedback with the controls?

[Image_Improvements.xlsx](https://github.com/tedrick/Survey123-Testing/files/4617641/Image_Improvements.xlsx)

**Comment by tedrick** [comment]
Redlands holistic lab session participants (5/14/2020):
Please check your name if you are interested in testing this feature.

- [ ] Adrienne Allegretti
- [ ] Aldous Tsang
- [ ] Bobby Home
- [ ] Brandon Whitney
- [ ] Carlos Maulen
- [ ] Chad Nunemacher
- [x] Charmel Menzel
- [ ] Chris Lesueur
- [ ] Christopher Eby
- [x] Cory Whittaker
- [ ] Dabney Hopkins
- [ ] Jerry Jacobsen
- [ ] Juliano Kersting
- [x] Kevin Deege
- [ ] Kyle Jones
- [ ] Kyle Wikstrom
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Melanie Kaminski
- [x] Michael Penokie
- [ ] Mike Cox
- [ ] Nichole Ueberschar
- [ ] Rich Kerr
- [x] Steven Temmermand
- [ ] Theresa Maier
- [x] Zachary Sutherby

**Comment by Shwujeng** [comment]
Redlands holistic lab session participants (5/14/2020):
Please check your name if you are interested in testing this feature.

- [ ] Adrienne Allegretti
- [ ] Aldous Tsang
- [ ] Bobby Home
- [ ] Brandon Whitney
- [ ] Carlos Maulen
- [ ] Chad Nunemacher
- [ ] Charmel Menzel
- [ ] Chris Lesueur
- [ ] Christopher Eby
- [ ] Cory Whittaker
- [ ] Dabney Hopkins
- [ ] Jerry Jacobsen
- [ ] Juliano Kersting
- [ ] Kevin Deege
- [ ] Kyle Jones
- [ ] Kyle Wikstrom
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Melanie Kaminski
- [ ] Michael Penokie
- [ ] Mike Cox
- [ ] Nichole Ueberschar
- [ ] Rich Kerr
- [ ] Steven Temmermand
- [ ] Theresa Maier
- [ ] Zachary Sutherby

**Comment by tedrick** [comment]
Redlands holistic lab session participants (5/14/2020):
Please check your name if you are interested in testing this feature.

- [ ] Adrienne Allegretti
- [ ] Aldous Tsang
- [ ] Bobby Home
- [ ] Brandon Whitney
- [ ] Carlos Maulen
- [ ] Chad Nunemacher
- [x] Charmel Menzel
- [ ] Chris Lesueur
- [ ] Christopher Eby
- [x] Cory Whittaker
- [ ] Dabney Hopkins
- [ ] Jerry Jacobsen
- [ ] Juliano Kersting
- [x] Kevin Deege
- [ ] Kyle Jones
- [ ] Kyle Wikstrom
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Melanie Kaminski
- [x] Michael Penokie
- [ ] Mike Cox
- [ ] Nichole Ueberschar
- [ ] Rich Kerr
- [x] Steven Temmermand
- [ ] Theresa Maier
- [x] Zachary Sutherby

**Comment by adgealleg** [comment]
This worked as expected and I had no issues capturing the images. The only issue I had was if I scrolled through the images I took, past the first image, it would set to 0 and then you couldn't scroll back to the first image in the preview. The only way to get back again to see the images taken would be to take another photos.

**Comment by MichalKEsri** [comment]
After a few minutes of working the page become inactive and greyout:

![s1](https://user-images.githubusercontent.com/65359966/81969556-03a4ee00-95d3-11ea-9ae5-0b032057d216.png)

**Comment by sirhcybe** [comment]
This worked as expected and this addresses some complaints I've had from clients when I had images in a repeater (they didnt like that there were two delete buttons in that case). The only thing I would like to see changed is that there should be some kind of indication that you can add multiple photos. Maybe a plus sign on the camera icon to show that you can continue adding new ones? Right now I could easily assume that pressing the camera again will overwrite the existing photo, not add additional ones.

**Comment by nicsi76** [comment]
It would be nice if you could select a couple of pictures at the same time from the device with the multiline appearance. 

> The only issue I had was if I scrolled through the images I took, past the first image, it would set to 0 and then you couldn't scroll back to the first image in the preview. The only way to get back again to see the images taken would be to take another photos.

I can confirm this behaviour.

**Comment by sirhcybe** [comment]
With an annotate question set to map style it loads to a blank canvas. It makes more sense to me to load to the map since the map is now the only option of things to annotate.

**Comment by marikavertzonis** [comment]
- [ ] Ben Van Kesteren
- [ ] Sarah Allerton
- [ ] Jamie Lambert

**Comment by someevil** [comment]
I agree with @sirhcybe , I expected the map to be visible as soon as I press the capture button, it is not intuitive to have to then select the map icon.
![blankscreen](https://user-images.githubusercontent.com/15650380/82012715-00d1f800-96bc-11ea-8ac0-801eab60f78e.gif)

**Comment by someevil** [comment]
I have not tested annotation before today, and I have no idea what this little 'pencil head' button is for? Perhaps its more relevant on other devices? Iphone and Field app had same confusion for me.
Just seems to toggle arrows on and off??

![2020-05-15 14_55_12-ArcGIS Survey123 (Beta)](https://user-images.githubusercontent.com/15650380/82012854-44c4fd00-96bc-11ea-9b42-61ef0b58d981.jpg)
![2020-05-15 14_55_26-ArcGIS Survey123 Connect (Beta)](https://user-images.githubusercontent.com/15650380/82012858-455d9380-96bc-11ea-9ed1-27e2c1bf26fb.jpg)

**Comment by someevil** [comment]
Perhaps add a little 'plus' sign to the camera icon, for multi photo questions.

If you look at this screenshot, the user will have no idea that they can add several photos. I would actually assume I could only add the one if I were to see this on an app.

![image](https://user-images.githubusercontent.com/15650380/82013205-0d0a8500-96bd-11ea-8625-51bf9f2f22a3.png)

**Comment by someevil** [comment]
When using the 'add photo from folder' button on the iphone, I was expecting to be able to select many photos at once. Just as we do in facebook etc. Can we 'tick' the photos we want to attach, to bulk upload many?
