### ISSUE TITLE
Custom JavaScript functions

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#336]
With the 3.10 release of Survey123, we are planning to release custom JavaScript function support for both the field and web apps.  Custom JavaScript functions allow you to attach custom business logic to your form.  This can be used for a number of scenarios:
- complex math that cannot be handled through the XLSForm specification
- interacting with an API to query a custom data source
  - request data from a 3rd party API, such as weather data or VIN lookup
  - query an ArcGIS Feature Service to conduct a query based on the location in the form

What you should do:
- **CHALLENGE**: Create a form that uses a JavaScript function to look up ZIP code based on location.  You can use https://services.arcgis.com/P3ePLMYs2RVChkJx/ArcGIS/rest/services/USA_ZIP_Code_Areas_anaylsis/FeatureServer/0 as the ZIP code areas
- **CHALLENGE**: Create a form that can sum a value based on a category in a repeat.  Using this form: [PizzaParty.xlsx](https://github.com/tedrick/Survey123-Testing/files/4618183/PizzaParty.xlsx) as a base, add a JavaScript function that will provide the total number of slices per pizza type.
- **CHALLENGE**: Create a form with a custom JavaScript function that meets your needs
- **FEEDBACK**: Do the functions work well in **both the field app and web app** equally well?

### Introduction
The syntax for using your own JS functions with pulldata is as follows:
`pulldata("@javascript","yourJSFile.js","yourFunction","parameter1","parameter2")`

Your custom JavaScript files must be stored in a folder called 'scripts' within the survey directory.  You can add as many function parameters as needed. In the example above, the JS function is expecting 2 parameters, but you could more or less as needed by your own function.

### Repeats

A useful application is the ability to pass all values from across a repeat into your JavaScript functions. The pulldata("@javascript", ...) function supports two different styles of implementation for retrieving the values from a repeat. Which one you choose depends on the way you want to handle values from a repeat in your JS function. 

1. Repeat name - if a repeat name is passed in the JavaScript function will receive the parameter as an array of rows of all the values in the repeat.
`pulldata("@javascript", "yourJSFile.js", "yourFunction", ${repeat1}, "question1")`
2. Question from within a repeat - if a question from within a repeat is passed in the JavaScript function will receive an array of values from the specified question.
`pulldata("@javascript", "yourJSFile.js", "yourFunction", ${question1})`

### Other Properties

Sometimes, particularly when using JS to access web services and secure ArcGIS services, you may need some properties that are not available through standard XLSForms. For this reason, we have also extended the collection of properties you can obtain through property() function as follows:
`property('propertyname')`
- portalurl
- token
- online - Boolean value indicating if device has network connectivity.
- utcoffset - Offset in minutes from UTC for the local timezone.
Note: This can also be done in JavaScript via var utcOffset = - new - Date().getTimezoneOffset
- language - Language in use by current survey.
- locale - Locale object in use for current survey. Only useful for JavaScript functions.
- localeinfo - AppStudio LocaleInfo object for current survey. Only useful for JavaScript functions. LocaleInfo contains the language code in various notations.
- timezone - Timezone code.

### Known limitations
- You cannot use DOM (web page layout); this means you normally cannot make use of frameworks such as JQuery, Ember, Angular, etc.
- You cannot access local files.
- You cannot make asynchronous calls.
- Your JS function won't execute if survey is downloaded in the field app by a user outside your organization (or someone not logged in).

### Samples
To provide you some patterns find the following samples below:
- [Introduction to custom JS Functions in Survey123 Exercises.zip](https://github.com/tedrick/Survey123-Testing/files/4618104/Introduction.to.custom.JS.Functions.in.Survey123.Exercises.zip) - Introduction guide & basic challenge
- Connect to 3rd party APIs:
  - [JS_Weather.zip](https://github.com/tedrick/Survey123-Testing/files/4621657/JS_Weather.zip)
  - [VINLookup.zip](https://github.com/tedrick/Survey123-Testing/files/4618110/VINLookup.zip)
- Using repeats in a function to calculate standard deviation: [Standard_Deviation.zip](https://github.com/tedrick/Survey123-Testing/files/4618111/Standard_Deviation.zip)

### Known limitation
- Repeat values are not yet supported in the web application

**Comment by Shwujeng** [comment]
Redlands holistic lab session participants (5/14/2020):
Please check your name if you are interested in testing this feature.

- [ ] Adrienne Allegretti
- [ ] Aldous Tsang
- [ ] Bobby Home
- [ ] Brandon Whitney
- [ ] Carlos Maulen
- [ ] Chad Nunemacher
- [ ] Charmel Menzel
- [ ] Chris Lesueur
- [ ] Christopher Eby
- [ ] Cory Whittaker
- [ ] Dabney Hopkins
- [ ] Jerry Jacobsen
- [ ] Juliano Kersting
- [ ] Kevin Deege
- [ ] Kyle Jones
- [ ] Kyle Wikstrom
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Michael Penokie
- [ ] Mike Cox
- [ ] Nichole Ueberschar
- [ ] Steven Temmermand
- [ ] Theresa Maier
- [ ] Zachary Sutherby

**Comment by sirhcybe** [comment]
This is very powerful and I like it a lot. I don't have a specific use case in mind but it strikes me that it could be useful to have the geometry engine from the JS API available. It may not be needed by enough people to build it into the app but having a sample available to show this functionality could be useful.

**Comment by nicsi76** [comment]
Should this also work with portal? I don't seem to be able to get the token from the pulldata('@property', 'token')  and also retrieving it via the js does not seem to work.

**Comment by tedrick** [comment]
@nicsi76 - what javascript function where you using?  Were you accessing a resource on that's part of your ArcGIS Enterprise or something in ArcGIS Online (I would expect a request to an ArcGIS Online resource to fail as you presented an ArcGIS Enterprise token).

**Comment by nicsi76** [comment]
@tedrick - Thanks for your response.
Of course the problem was sitting in front of the computer ;-) 
The problem: having stored the js file first in an extensions folder before reading that it's now called scripts and of course working on the wrong copy of the script. 

Great enhancement that you don't have to restart connect each time you changed the script. 

Remaining problem: When starting the form in a web browser (edge) I get this error:

**Comment by oopsliu** [comment]
@nicsi76 Could you please share the survey and JS file you tested?

**Comment by nicsi76** [comment]
@oopsliu , I had to reinstall the current version and made some changes, will have to try again what it does now. I will let you know!
