### ISSUE TITLE
Enhancement: GeoNet visibility

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#34]
**Application:** Connect 

**Device:** Windows

**Operating System:** Win 10

For the new GeoNet visibility, it would be nice to have an option to toggle this one and off by default. For example, there could be an option on the Settings tab that would allow you to specify whether or not you want to see the GeoNet activity upon launching Connect.

I can see there is the option to pull the side panel in far enough that it becomes invisible, but if you close Connect and re-launch, it reverts back.

**Comment by JohnHasthorpe** [comment]
2.4 testing complete

**Comment by JohnHasthorpe** [comment]
Internal issue raised: https://devtopia.esri.com/Melbourne/Survey123/issues/1911
