### ISSUE TITLE
Feedback: Require Survey updates

### ISSUE THREAD

**Issue by brettstokes** [tedrick/Survey123-Testing#340]
With the 3.10 release, Survey123 is introducing the ability for survey authors and organization administrators to require users to download survey updates (if available) before any new data can be submitted. This requirement can now be applied to all surveys by administrators via [Organizational Settings](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={D471B901-C9A2-486C-9B86-56949E84B0FB}) or it can also be applied to individual surveys by authors via Connect.

### Feedback
Try enabling Organization Settings and use the editor in Connect or new Organization - Settings page on the website to set `"requireSurveyUpdate": true`. Provide feedback on using this organization setting for requiring survey updates. Also, try out enabling this require update setting on an individual survey via the survey Settings → General tab .
- Do you think the individual survey setting should be enabled by default?
- How did you find using the Organization Setting editor in Connect / website?

**Comment by tedrick** [comment]
Redlands holistic lab session participants (5/14/2020):
Please check your name if you are interested in testing this feature.

- [ ] Adrienne Allegretti
- [ ] Aldous Tsang
- [ ] Bobby Home
- [ ] Brandon Whitney
- [ ] Carlos Maulen
- [ ] Chad Nunemacher
- [x] Charmel Menzel
- [ ] Chris Lesueur
- [ ] Christopher Eby
- [x] Cory Whittaker
- [ ] Dabney Hopkins
- [ ] Jerry Jacobsen
- [ ] Juliano Kersting
- [x] Kevin Deege
- [ ] Kyle Jones
- [ ] Kyle Wikstrom
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Melanie Kaminski
- [x] Michael Penokie
- [ ] Mike Cox
- [ ] Nichole Ueberschar
- [ ] Rich Kerr
- [x] Steven Temmermand
- [ ] Theresa Maier
- [x] Zachary Sutherby

**Comment by someevil** [comment]
I have enabled this 'force update' at the organisation level, and updated a couple of surveys (none have the 'require update' set to disabled, and it is correctly forcing the user to update all surveys. Working well. Tested on Windows Field App, Iphone and Samsung Tablet

**Comment by someevil** [comment]
![image](https://user-images.githubusercontent.com/15650380/82015502-3b3e9380-96c2-11ea-855d-ae19ff54b3b5.png)

I think the comments can be expanded to let the administrator know that if this is checked on, it doesnt matter what you have set at an individual survey level, this will force it upon all surveys.
