### ISSUE TITLE
Challenge: Set different map questions in your survey to use different default basemaps

### ISSUE THREAD

**Issue by brettstokes** [tedrick/Survey123-Testing#342]
### Challenge
Create or open an existing survey in Connect that uses a number of map questions. Use the `map=` parameter in the **body::esri:style** column of your XLSForm to set the default basemap for that map question. Publish the map and observe the outcome in the field app.

### Question level basemap defaults
To set a different default basemap for each individual **geopoint**, **geotrace** and **geoshape** question in a survey, you can use the `map= itemid` or `"mapname"` parameter in the **body::esri:style** column in the XLSform. You may need to manually add the **body::esri:style** column to your existing XLSform if it is not present. Check out the Advanced template in Connect for all the latest updates.

The parameter syntax simply uses the **itemid** or **"mapname"** following the **map=** and can even include both parameters in case the map cannot be found by searching **"mapname"** or **itemid**. To combine multiple parameters separate them by two vertical bars, ie ||. If using **itemid** the parameter does not require quotations, however if using **"mapname"** the parameter must be wrapped in quotations to ensure it is handled correctly when the map name contains spaces. Here are all the supported formats and some example combinations:

- map=itemid
- map="mapname"
- map="itemid||mapname"
- map=itemid1||itemid2||itemid3
- map="mapname1||mapname2||mapname3"
- map="itemid1||mapname1||itemid2||mapname2||itemid3||mapname3"

The above parameters will set the default basemap for the first basemap found that matches by itemid or map name for the specific map question only that the parameter has been applied to. Any other **geopoint**, **geotrace** or **geoshape** questions in the same survey will still use the default basemap set at survey level or organization level if they don't have a parameter set.

You can also set offline map packages as the default basemap using the **body::esri:style parameter**, using the exact title of the package as you see it in the Linked Content settings:

_map="My Offline MMPK"_

By using a combination of the survey level default basemap settings and the question level basemap settings you can fully customize which questions use which basemaps, and ensure the basemap being used is fit for purpose for the workflow and activity being undertaken in the field app.

**Comment by Shwujeng** [comment]
Redlands holistic lab session participants (5/14/2020):
Please check your name if you are interested in testing this feature.

- [ ] Adrienne Allegretti
- [ ] Aldous Tsang
- [ ] Bobby Home
- [ ] Brandon Whitney
- [ ] Carlos Maulen
- [ ] Chad Nunemacher
- [ ] Charmel Menzel
- [ ] Chris Lesueur
- [ ] Christopher Eby
- [ ] Cory Whittaker
- [ ] Dabney Hopkins
- [ ] Jerry Jacobsen
- [ ] Juliano Kersting
- [ ] Kevin Deege
- [ ] Kyle Jones
- [ ] Kyle Wikstrom
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Michael Penokie
- [ ] Mike Cox
- [ ] Nichole Ueberschar
- [ ] Steven Temmermand
- [ ] Theresa Maier
- [ ] Zachary Sutherby

**Comment by marikavertzonis** [comment]
- [ ] Julian Pilois
- [ ] Ben Van Kesteren
- [ ] Talia Liney

**Comment by talialiney** [comment]
I have a survey with two geopoint map questions, using the body::esri:style column I had no issues changing the basemap for one question - trialed using multiple formats and combinations with no issues. For the other question, however, this does not work. I tried with different maps and formats with no success. Just to note, in the question that doesn't work I have no trouble changing the basemap to ones loaded in linked content.

**Comment by brettstokes** [comment]
Note: Map question not working is in group, the map question that is working is in repeat.

**Comment by Shwujeng** [comment]
@talialiney Could you share the xls form you were encountering the issue with map question inside a group?
Geopoint within a group or a repeat seems to work fine with "map=" setting. If you could share the xls form you are using, that will be helpful to narrow down the issue.

**Comment by talialiney** [comment]
[GEA Baseline 1.xlsx](https://github.com/tedrick/Survey123-Testing/files/4632551/GEA.Baseline.1.xlsx)
