### ISSUE TITLE
Challenge: Additional Query Syntax of Feature Report Template Syntax-Stats and Summary Section

### ISSUE THREAD

**Issue by oopsliu** [tedrick/Survey123-Testing#343]
**In 3.9 beta we supported new syntax for getting statistics and the summary section in the feature report template, and we added additional parameters in 3.10 beta to enhance the query.**
___
### **3.9 Beta**
From Survey123 3.9 beta website, you can get statistical or aggregation results using new filter "stats" and specify the parameters of the stats filter.
![image](https://user-images.githubusercontent.com/29442153/73411260-95ede400-42b9-11ea-9a6c-57ffb7a21188.png)

We also introduce Summary section, which works as begining or ending pages with summary information of multiple records or statistical result in the feature report.
![image](https://user-images.githubusercontent.com/29442153/73411278-a3a36980-42b9-11ea-8f4b-21453a122f95.png)

Detailed information is provided in our online documentation on early adopter website and please use survey123 Beta website to test these new features:

[Feature Report Template Syntax-Stats and Summary Section](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={529926F6-DEDC-495F-AF85-B9F49287964F})

We will show you a demo to use Tree Health Survey and generate a statistic for the counts of tree issues recorded by severity level and add the statistical report in the summary session.

### **Sample of Syntax**
++++++++++++++++++

![image](https://user-images.githubusercontent.com/29442153/73322641-fa496e80-41f9-11ea-8c43-37f583cf959c.png)

### **Report Result**
++++++++++++++++

![image](https://user-images.githubusercontent.com/29442153/73322654-02091300-41fa-11ea-9040-270f7a7ece63.png)

Here is the result printout of the feature report in pdf format.
[Tree_Health_Survey__20200129171436.pdf](https://github.com/tedrick/Survey123-Testing/files/4131681/Tree_Health_Survey__20200129171436.pdf)
___

### **NEW in 3.10: Additional syntax**
In addition to the above parameters used to formulate a filter for your survey, there are additional parameters and qualifiers that can be used to enhance your query to provide more specific information.

**where**: This filter is used to search for survey responses that contain specific values in a given field. For example, `where:"weather='sunny'"` will cause the filter to only use responses where the weather field contains the value sunny.

**!important**: This qualifier can be added to any filter, to override any constraints on the values that the filter returns. For example, if you were printing reports from only the last seven days, `where:"weather='sunny' !important"` would cause the filter to only use responses where the weather field contains the value sunny, but pulls from all applicable responses in the feature service, rather than just the responses selected to be printed.

**$inputParams**: This placeholder can be used within any filter to refer to the parameters used when printing a feature report, set through the Survey123 website. These parameters can then be further qualified to narrow down your response. For example, `orderByFields:"$inputParams"` will order the fields using the ordering set in the Survey123 website when printing reports. You can also use $inputParams to apply these parameters to repeats.
___
Please give it a try using this new feature report template syntax on our survey123 Beta website with your own survey.

**Comment by Shwujeng** [comment]
Redlands holistic lab session participants (5/14/2020):
Please check your name if you are interested in testing this feature.

- [ ] Adrienne Allegretti
- [ ] Aldous Tsang
- [ ] Bobby Home
- [ ] Brandon Whitney
- [ ] Carlos Maulen
- [ ] Chad Nunemacher
- [ ] Charmel Menzel
- [ ] Chris Lesueur
- [ ] Christopher Eby
- [ ] Cory Whittaker
- [ ] Dabney Hopkins
- [ ] Jerry Jacobsen
- [ ] Juliano Kersting
- [ ] Kevin Deege
- [ ] Kyle Jones
- [ ] Kyle Wikstrom
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Michael Penokie
- [ ] Mike Cox
- [ ] Nichole Ueberschar
- [ ] Steven Temmermand
- [ ] Theresa Maier
- [ ] Zachary Sutherby

**Comment by marikavertzonis** [comment]
- [ ] Nathan Duncan
- [ ] Sarah Allerton
- [ ] Peter Mckenzie

**Comment by nwduncan** [comment]
Attempting to generate summary report (from the basic summary only template) and for one of our survey123 apps the task status is stuck on 'Uploading... 0%'. (see screenshot)
The dataset is quite large, with about 130 fields but will work for a single item. Can confirm that when testing on another smaller survey and multiple records are selected that the basic summary report will work.
![issue1](https://user-images.githubusercontent.com/10606760/82012000-f57dcd00-96b9-11ea-9718-7349a74ba0c8.png)

**Comment by badgerseatfrogs** [comment]
I'm creating a summary report - stuck at 50% - been running for 8 mins...
![image](https://user-images.githubusercontent.com/17342897/82013207-dcc0e780-96b8-11ea-840e-ecf7caa63ece.png)

**Comment by nwduncan** [comment]
As discussed in Zoom here's a single page and single file summary report which is getting zipped. Unsure if this is expected functionality.
[Building_Works_20_records_20200515151908.zip](https://github.com/tedrick/Survey123-Testing/files/4632417/Building_Works_20_records_20200515151908.zip)

**Comment by marikavertzonis** [comment]
regarding the 2 comments above about the report creation getting stuck - we tested further and suspect it might be related to the pop up required when creating pdf reports.
 - issue didn't happen when choosing docx report
 - when creating pdf report i got a message saying pop up was blocked after allowing the pop up, the zip file did download. the enty in the recent tasks did stay as 'Converting 0%' even after the download happened
 - the screenshot shows the message in the blocked pop up and the 'Converting 0%' message in recent tasks
![Pop up blocked on pdf report creation](https://user-images.githubusercontent.com/5713624/82019234-341b8380-96ca-11ea-81ca-0ee08c53e788.png)
 - the two users were using chrome and i was using new edge
