### ISSUE TITLE
CHALLENGE: Co-author role for a survey

### ISSUE THREAD

**Issue by zhif7782** [tedrick/Survey123-Testing#347]
In 3.10 release, there will be a beta feature in the website to allow the survey owner to share the survey with other users as co-author, so other uses can help the survey owner manage the survey, including update survey design, view/edit survey data, set up webhooks etc.

As a co-author, you can do most of the operations to a survey as the survey owner, except the following:

- My Surveys: delete the survey
- Design: publish the survey for the first time
- Collaborate: share the survey with other users as submitter, stakeholder, co-owner
- Data: upload a new feature report template

#### Prerequisites
to complete this workflow, you need

* Two two accounts in an organization
* Both of accounts need to be in the same [shared update group](https://doc.arcgis.com/en/arcgis-online/share-maps/create-groups.htm#ESRI_SECTION1_12B3CD7ADAF843DB90182A01824B3152).

#### Workflow
* Sign in the Survey123 website as user A (survey owner), open the Collaborate page of an existing survey or a newly created survey.
* In Collaborate->Update survey, share the survey with the shared update group which the user B (a co-author) is in.
* Sign out the website, sign in again with the user B
* In the All surveys tab or Surveys I can update tab of the My surveys page, find the user A's survey that shared with you.
* Try to complete the following tasks:
  * My surveys: update the survey info, save the survey as a new one in your account.
  * Design: update the survey design, preview, save, publish.
  * Collaborate: configure draft mode, multiple submissions, open/close status of the survey.
  * Data: view the survey results, edit any survey data, edit a feature report template, print a feature report.
  * Analyze: view the survey results.
  * Settings: change the version lock setting, manage webhooks.

### Feedback

Try out the above workflow and provide any feedback, such as:

* Any but in the workflow.
* Any missing capabilities in the workflow.
* The wording on the website UI may need to improve.

### Note

Survey123 Connect does support the co-author role currently. However, you can use a survey published from Survey123 Connect in this workflow from the website.

**Comment by Shwujeng** [comment]
Holistic lab session on 6/4/2020 Redlands:
- [ ] Bobby Horne
- [ ] Chris Ferner
- [ ] Kylie Donia
- [ ] Matthew Baber
- [ ] Matthew Woodlief
- [ ] Mike Cox
- [ ] Red Cylwik

**Comment by mrwoodlief** [comment]
maybe a no brainer, but a note adding the co-author must be assigned a Survey123 licenses would good

**Comment by mrwoodlief** [comment]
Overall the workflow works great. Its pretty clear on what I can and cannot do as the co-author. I like the explanations.

**Comment by chrisferner** [comment]
workflow worked as expected. was able to perform all tasks w no confusion. agree that the ability to add a report would be key.

**Comment by kyliedonia** [comment]
1. In the demo, the group showed the survey form and layer. In my group, I also see the hosted feature layer views for the survey (the fieldworker and stakeholder ones). Is that expected?

**Comment by tedrick** [comment]
Note @chrisferner has seen issues with the ability to change ownership when items are shared in update groups

**Comment by Zachary-Sutherby** [comment]
We had noted that this is a current known limitation, it would be nice to use Co-ownership of surveys with surveys that were created from referenced feature services. 

When I had tested I received a 500 message on the addToDefinition request: 

![CoOwnerRegisteredFS](https://user-images.githubusercontent.com/54078266/83805079-13f53980-a664-11ea-9272-131090d2d2e5.JPG)

If the HAR file is of interest I have it on "\\\sutherby1\mobileTaskforce\06_04_Survey123Holistic\survey123beta.arcgis.com.har"

This workflow can be used as a workaround or expected workflow for ENH-000129361.

**Comment by tedrick** [comment]
Thank you for the feedback- we have made a note to properly document license requirements.

@Zachary-Sutherby - referenced feature services can be tricky to work with as there is no guarantee the survey author has the capability to update them.
