### ISSUE TITLE
Challenge: Enhanced Search Capabilities: Barcodes and Search Terms, and new URL Parameters

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#348]
With the 3.10 release of survey123, we're introducing several improvements to make it easier to find the form or record you need.
1. The Survey Gallery now has a search bar with access to the barcode scanner.  In addition to text search, you can also pass in an 'arcgis-survey123' URL and the application will respond.
2. The Inbox search bar now supports a barcode scanner.  It also supports the following search terms to narrow the search to one record:
  - objectid:<OID>
  - globalid:<GUID>
3. Configure logging to an AppStudio console by scanning the barcode.  This will work if the device logging and the device with the console are on the same network.

**Challenge:** Create a QR code to open a specific feature in the Inbox

**Comment by Shwujeng** [comment]
6/9/2020 Holistic testing Redlands session:
- [ ] Abdullah Almoammar
- [ ] Abigail Stephens
- [ ] Amy Peters
- [ ] Andrew Makowicki
- [ ] Ash Comer
- [ ] Ben Keller
- [ ] Chris Gabris
- [ ] Chryse Kruse
- [ ] Eric Ford
- [ ] Faisal Basudan
- [ ] Francisco Andrade
- [ ] Jamie Lambert
- [ ] Jerry Jacobsen
- [ ] Jessica Rosales
- [ ] John Bickmore
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Melanie Baker
- [ ] Michael McGill
- [ ] Michael Penokie
- [ ] Mike Cox
- [ ] Ohan Oumoudian
- [ ] Pablo Cabrera
- [ ] Sepideh Sepehr
- [ ] Sue Enyedy-Goldner
- [ ] Walter Simonazzi
- [ ] Zachary Sutherby

**Comment by marikavertzonis** [comment]
I was able to successful create a QR code on a website, from the following URL, and scan it from the survey gallery page.

`arcgis-survey123://?itemID=2bd39e78637741fda8eee1e5f75f7eab&filter=globalID:d6b6b8eaa1f14304828faf8be54b09ec&action=edit`

Testing on Android 6.0.1 (Trimble TDC100) it successfully launched in edit mode.
