### ISSUE TITLE
logging into survey123.arcgis.com via enterprise login, then tried to log into ArcGIS.com crashes

### ISSUE THREAD

**Issue by jfangit** [tedrick/Survey123-Testing#35]
**Application:** Website

**Device:** Windows 10

**Operating System:** Windows 10

**Browser:** Chrome

**Error Description:**  Logged into Survey123.arcgis.com via enterprise login. now tried to get to arcgis online using the same enterprise login via okta page. survey123 logo appears and then crashes. clearing the browser cache fixes the problem.

**How to reproduce:** as in the Error Description

**Have you tested with another survey?** No

**Comment by zhif7782** [comment]
Hi @jfangit @tedrick , can you please provide more info about how to reproduce the issue?
* What type of authentication is the enterprise login using? 
  * Can we have a test account to reproduce the issue?
* How to "get to arcgis online using the same enterprise login via okta page"? Seems there's no entry to ArcGIS Online from https://esri.okta.com or https://esri.okta.com/app/UserHome

**Comment by tedrick** [comment]
@zhif7782 - Several ArcGIS Online organizations used by Esri (particularly Business Development) use Okta as their enterprise login provider.  This provides an icon on their Okta login page - see, for example, mine:
<img width="1132" alt="screen shot 2017-08-31 at 10 58 49 am" src="https://user-images.githubusercontent.com/1319289/29937810-a2f10950-8e3b-11e7-9151-459d099f0f5e.png">

This opens up the organization home page with the identity from Okta attached.

As you can see, I've got several organizations to test from; it we need to get an organization linked up, put in a service request (IST needs to do some configuration on the Active Directory as well as Okta IIRC)

**Comment by JohnHasthorpe** [comment]
2.4 testing complete

**Comment by zhif7782** [comment]
Internal issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/1949
