### ISSUE TITLE
Shared theme setting not applied in Survey web designer

### ISSUE THREAD

**Issue by kdeege** [tedrick/Survey123-Testing#350]
Setting the option to use the organization's shared theme does not set the shared theme to be used for survey appearance when a new survey is crested 

Turn on shared theme:
![share](https://user-images.githubusercontent.com/3604299/81964111-24c20a80-95e4-11ea-8260-1c108c9af400.PNG)

Organization's "Dutch" colors

![dutch](https://user-images.githubusercontent.com/3604299/81964453-98fcae00-95e4-11ea-8f74-ebc40a9db1b4.PNG)

Creating a new survey after setting this option in Survey Web designer results in the Appearance being set to the default:

![theme](https://user-images.githubusercontent.com/3604299/81964704-fa248180-95e4-11ea-81a3-da6a330d1761.PNG)

The organization shared theme is applied in Survey 123Connect Beta:

![connect_theme_organge](https://user-images.githubusercontent.com/3604299/81968582-92713500-95ea-11ea-91a5-0f7e9682b48f.PNG)

**Comment by oopsliu** [comment]
@kdeege Thanks for the feedback! For the current release, the organization settings are for Field app only, but we do have plans to support it in web in the future.
