### ISSUE TITLE
Feedback: Administrator View User Interface of Organization Surveys

### ISSUE THREAD

**Issue by menzelc** [tedrick/Survey123-Testing#351]
**Is your feature request related to a problem? Please describe.**
When filtering by member, all members are listed.  
![image](https://user-images.githubusercontent.com/4838513/81966130-0ad5f700-95e7-11ea-8bcf-46d86d1daaa3.png)

**Describe the solution you'd like**
List only those members that have created Survey123 apps

**Describe alternatives you've considered**
none.

**Comment by someevil** [comment]
That would be very hand. There are only about 4 creators in our organisation, but my list is showing all 50 users.

**Comment by someevil** [comment]
When I click organisation, I am presented with a list of 11 surveys... I am expecting to see EVERY survey within my organisation. It seems to be a very random selection of 11 (they are not only a selection of surveys by me, but others are included)

If I select my username from the drop down, I can see 17 surveys, and as I scroll through my users I am seeing surveys that are not appearing on that initial organisational view page.

Click the GIF below to play:
https://i.imgur.com/VwQlYtF.gifv

**Comment by Zachary-Sutherby** [comment]
To expand on the member filter present on the Organization Survey's tab are there plans to filter by share settings of surveys not exclusively by survey ownership?

For example "Show me all surveys that are public", "all surveys shared to this group", or "all surveys that members of group X can view the results for".

**Comment by oopsliu** [comment]
Thank you all for the feedback!
@Zachary-Sutherby This is currently not in the product plan but I have add your requirement to the backlog. Thank you again!
