### ISSUE TITLE
Feature Report: Creating a new template

### ISSUE THREAD

**Issue by sarahallerton** [tedrick/Survey123-Testing#354]
The first time you add a template, it gives you the option to select an Individual template, Summary template or both. However, to create a new/second it would be great to be able to select out the 3 options again instead of having to download a template and upload it etc. It would save time to have less buttons to click. This is an important requirement for my clients, to have as little steps as possible.

**Comment by brettstokes** [comment]
Closing as a new enhancement issue has been created in Survey123 Hub repo (https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/4372)
