### ISSUE TITLE
use lasso tool to select features in feature report

### ISSUE THREAD

**Issue by badgerseatfrogs** [tedrick/Survey123-Testing#355]
In the Feature Report map window it's great that you can generate a report from only selection of records. 
However, it would nice to be able to lasso a selection of features that would then select them in the associated table. This selection be used to generate a filtered test of test reports. 

![image](https://user-images.githubusercontent.com/17342897/82014232-578b0200-96bb-11ea-9a24-28a2e29f8f5b.png)

**Comment by tedrick** [comment]
Thanks for the suggestion!  I've filed this as a potential future enhancement
