### ISSUE TITLE
Feedback: Linked Content - Unlinking the default item

### ISSUE THREAD

**Issue by jap-eagle** [tedrick/Survey123-Testing#356]
**Describe the bug**
In the Linked Content tab in S123 Connect, you have a default map which is created when you publish the form. You are given the option to unlink the default map, however, when clicking "yes" to unlink it, no action is taken.

Would you expect to have the ability to unlink the default map?
If not, it would be helpful to be notified that it is not possible - or to not have the option.

**Application:** Connect
**Device:** Dell XPS 13
**Operating System:** Windows 10

**To Reproduce**
1. Go to Survey123 Connect
2. Click on a form and go to Linked Content
3. Click to unlink the default map
4. Click yes
5. No action is taken

**Expected behavior**
I would expect to be notified that it is not possible to unlink the default map or to not be given the option.

**Comment by brettstokes** [comment]
Closing as new issue has been created in Survey123 Devtopia repo (https://devtopia.esri.com/Melbourne/Survey123/issues/3796)
