### ISSUE TITLE
Feature Report: Not pulling through all images with the multiline function

### ISSUE THREAD

**Issue by sarahallerton** [tedrick/Survey123-Testing#357]
When I used the multiline functionality for images, I could view the images in ArcGIS Online and in the right side panel in the Survey123 website so I know that they both got submitted. However, when I used the Individual template, just as the default layout, it only pulled through one image.

**Comment by marikavertzonis** [comment]
Possible that this could be acheived by editing the default summary report with specific syntax... If available - might be good for us to include multiple images in the template summary report
