### ISSUE TITLE
Require Update (Survey level) not enforced if field app is not refreshed

### ISSUE THREAD

**Issue by J8L** [tedrick/Survey123-Testing#360]
After setting 'Require Update' in Connect and publishing, you can still collect and submit new surveys in the field app (tested on iPad) as long as you don't refresh the field app. In most cases in the field i don't expect users to refresh the app during field activities.

**Comment by tedrick** [comment]
Thanks for the comment,

The refresh mechanism is a 'pull' mechanism - we would need to identify additional points in the app's operation to make the check for updates,
