### ISSUE TITLE
Feedback: Linking Content to a Survey123 Form that you do not own.

### ISSUE THREAD

**Issue by jap-eagle** [tedrick/Survey123-Testing#361]
**Describe the bug**
In Survey123 Connect, I have a form which I created but I no longer own in ArcGIS Online, however, I am an Administrator in the organisation. When I go to the Linked Content tab, no default map is visible for this form and I am unable to add any other Linked Content.

Would I be expected to have the ability to add Linked Content if I am no longer the owner of the form?

I could still go to the Linked Content tab and navigate through maps to link, but upon clicking "ok" no action was taken.

From changing the owner back to myself I am now able to add Linked Content, however, the first item I add cannot be removed due to issue #356.

**Application:** Connect 
**Operating System:** Windows 10

Note:
For those involved in the session, the ownership of the form was the issue preventing me from linking to a web map - not projection/map ownership/layer sharing.

**Comment by brettstokes** [comment]
The issue here is that there is no messaging to tell you that you can't edit Linked Content for a survey you don't own. Closing as issue has been created in Survey123 Devtopia repo (https://devtopia.esri.com/Melbourne/Survey123/issues/3795).
