### ISSUE TITLE
Open Survey directly from the Download Page

### ISSUE THREAD

**Issue by nicsi76** [tedrick/Survey123-Testing#364]
**Is your feature request related to a problem? Please describe.**
I download a survey and then have to go first back to the overview page and look for the survey I have just downloaded to start data collection.

**Describe the solution you'd like**
After downloading a survey I would like to click directly on the survey in the download section and start my data collection.

**Comment by tedrick** [comment]
Thanks for the suggestion - this was previously available in Survey123 but was taken out due to user confusion.  I've filed this as potential topic to see if a better method to allow this can be designed.
