### ISSUE TITLE
CHALLENGE: Basemap setting for all geo* questions in Survey123 Connect and Web Designer.

### ISSUE THREAD

**Issue by Shwujeng** [tedrick/Survey123-Testing#365]
With 3.10 release, we are providing different methods to set the default basemap for geopoint, geotrace and geoshape questions. The basemap will be honored and maintained in Connect, Field app and web forms.

Here is a list of methods you can set the default basemap and you could see the details on our EAC documentation link [here](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&artid={7C93EFAC-E0ED-4605-8C36-FC63A701642C}):

1. Organization basemap default
2. Survey level basemap default
3. Question level basemap default

The basemap you set in Connect or web designer will be honored when you open the survey in field app or web form.

**CHALLENGE**

Connect and organization setting:
1. Use the above 3 methods to set your default basemap.
2. Open the survey in field app and confirm the basemap is honored.
3. Open the survey in web form([beta website](https://survey123beta.arcgis.com/)) and confirm the basemap is honored.

Web Designer(beta website) setting:
1. Use web designer([beta website](https://survey123beta.arcgis.com/)) and set the basemap of your map question and publish.
2. Open the survey in Connect and field app to confirm the basemap is honored.

**Comment by Shwujeng** [comment]
Holistic lab session on 6/4/2020 Redlands:
- [ ] Bobby Horne
- [ ] Chris Ferner
- [ ] Kylie Donia
- [ ] Matthew Baber
- [ ] Matthew Woodlief
- [ ] Mike Cox
- [ ] Red Cylwik

**Comment by gmcbride792** [comment]
Really like this new feature and the ability to set the basemap at the question level. Worked without issues in the testing I carried out

**Comment by mrwoodlief** [comment]
No problems on my end

**Comment by kyliedonia** [comment]
1. I set my survey to use the gray basemap (in the website designer). I opened the survey in the web to fill it out, and it used the right basemap. I opened it in the mobile app, and it is not using the gray basemap :(

**Comment by tedrick** [comment]
@kyliedonia - just to confirm, you used Survey123 3.10.227 (the currently available beta)?

**Comment by kyliedonia** [comment]
Arg! I installed from Testflight and saw it in progress, but it must not have worked. I'm seeing 3.9.149 in it right now. I installed again, and now the "About" shows 3.10.227B. 

I still don't see the gray basemap though. The survey did say it had an update available, and I downloaded it, but still no basemap update.

**Comment by Shwujeng** [comment]
@kyliedonia I was not able to reproduce the problem using 3.10.227 TestFlight build. I tried bith Light and Dark gray basemap and they all worked corretly in the field app.
Just to confirm, are you using the survey123beta.arcgis.com web designer to create map? The fix is only on beta website. 
If you publish survey with beta website designer with a selected basemap, it is now honored correctly in the field app(3.10.227).

**Comment by kyliedonia** [comment]
I'm 98% sure I was, but I tried republishing in the beta website to be sure. 

I had initially downloaded the survey in the 3.9 version of the field app and then updated it in 3.10. I tried deleting the survey and redownloading it, and now it shows the gray basemap.

**Comment by tedrick** [comment]
Thanks @kyliedonia - it sounds like the field app remembered the last map set in 3.9 across the upgrade (which is normally a desired behavior).
