### ISSUE TITLE
FEEDBACK: Administrator view on Survey123 website.

### ISSUE THREAD

**Issue by Shwujeng** [tedrick/Survey123-Testing#367]
With [Survey123 beta website](https://survey123beta.arcgis.com/), as an administrator, you will now access to new features of the survey organization setting. 
Once you log in to [survey123 beta webite](https://survey123beta.arcgis.com/) with admin role, you can do the following tasks:
 
1. Easily manage all organization surveys from a new admin gallery
2. Configure Survey123 specific settings for all organization surveys
3. Set Basemap group
4. Set Survey theme
5. Survey update policy (required or not)
<img width="915" alt="Screen Shot 2020-06-03 at 11 42 52 AM" src="https://user-images.githubusercontent.com/29442153/83676433-847e5680-a58f-11ea-9620-d7620d6462ef.png">

Please try the new admin features and provide us your feedback.

**Comment by Shwujeng** [comment]
Holistic lab session on 6/4/2020 Redlands:
- [ ] Bobby Horne
- [ ] Chris Ferner
- [ ] Kylie Donia
- [ ] Matthew Baber
- [ ] Matthew Woodlief
- [ ] Mike Cox
- [ ] Red Cylwik

**Comment by chrisferner** [comment]
When checking the option to select organization shared theme does that start from that point forward or does it convert surveys that used the default to the org theme? i checked and saved and do not see any difference.

**Comment by fandrade86** [comment]
Require Update Option - Testing (Successful):

This option works great and I can see us utilizing it to require our field personnel to be on the latest survey version form.

Below are screenshots of the testing:

Showing an update to the Survey123 Form

![Survey123 - Showing the Update](https://user-images.githubusercontent.com/21234095/83790553-3cbe0480-a64d-11ea-857b-e692a24f5746.png)

Requiring the Update to the Survey123 Form:

![Survey123 - Requiring the Update](https://user-images.githubusercontent.com/21234095/83790572-42b3e580-a64d-11ea-8fdf-2e49f96a7dd4.png)

Not Requiring the Update to the Survey123 Form After the Option was Removed:

![Survey123 - Not Requiring the Update Anymore](https://user-images.githubusercontent.com/21234095/83790589-49425d00-a64d-11ea-8b4c-f9f6b9a2e7b3.png)

**Comment by chrisferner** [comment]
Filter is great but is it possible to remove org members from the list who do not have any surveys?

**Comment by chrisferner** [comment]
Filter result count does not update if one is deleted. This user originally had 13, then i deleted 3 of his "test" survey's and the count stayed at 13.
![Screen Shot 2020-06-04 at 11 22 29 AM](https://user-images.githubusercontent.com/25673052/83791925-9c211200-a657-11ea-817c-6a76cf7a6b76.png)

**Comment by chrisferner** [comment]
Basemap: does this impact the map item? I set this to imagery using the admin view, then created a new survey, and added a Map and it didn't display the basemap and had topo selected as default.
![Screen Shot 2020-06-04 at 12 33 14 PM](https://user-images.githubusercontent.com/25673052/83797408-d4c4e980-a65f-11ea-8b04-4f5c21894099.png)

**Comment by tedrick** [comment]
Feedback from Chryse:
- the filter 'Member Name' looks like an option of type (Member Name, Number of submissions)- perhaps make it fixed to otherwise more prominent
- Provide filter by date

**Comment by tedrick** [comment]
Feedback from @chrisferner - 'All Surveys shows **all** surveys, including other org public surveys.  This should be limited to the org's surveys

**Comment by tedrick** [comment]
Feedback from @chrisferner - the setting labels do not accurately describe what is going on.  Appearance was interpreted to mean the theme of the form

**Comment by tedrick** [comment]
Thanks for the feedback.  The 'show all' is being addressed to only show your organization's surveys and have reworked the wording on the settings to make it clearer.  We have added most of the enhancements requests as issues to look at for future releases, though some of them will be dependent on ArcGIS Online's own search capabilities.
