### ISSUE TITLE
FEEDBACK: Additional Query Syntax of Feature Report Template Syntax-Stats and Summary Section

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#368]
From Survey123 beta website, you can get statistical or aggregation results using new filter "stats" and specify the parameters of the stats filter.
![image](https://user-images.githubusercontent.com/29442153/73411260-95ede400-42b9-11ea-9a6c-57ffb7a21188.png)

We also introduced the Summary section, which works as begining or ending pages with summary information of multiple records or statistical result in the feature report.
![image](https://user-images.githubusercontent.com/29442153/73411278-a3a36980-42b9-11ea-8f4b-21453a122f95.png)

Detailed information is provided in our online documentation on early adopter website and please use survey123 Beta website to test these new features:

[Feature Report Template Syntax-Stats and Summary Section](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={529926F6-DEDC-495F-AF85-B9F49287964F})

We will show you a demo to use Tree Health Survey and generate a statistic for the counts of tree issues recorded by severity level and add the statistical report in the summary session.

### **Sample of Syntax**
++++++++++++++++++

![image](https://user-images.githubusercontent.com/29442153/73322641-fa496e80-41f9-11ea-8c43-37f583cf959c.png)

### **Report Result**
++++++++++++++++

![image](https://user-images.githubusercontent.com/29442153/73322654-02091300-41fa-11ea-9040-270f7a7ece63.png)

Here is the result printout of the feature report in pdf format.
[Tree_Health_Survey__20200129171436.pdf](https://github.com/tedrick/Survey123-Testing/files/4131681/Tree_Health_Survey__20200129171436.pdf)
___

### **Additional syntax**
In addition to the above parameters used to formulate a filter for your survey, there are additional parameters and qualifiers that can be used to enhance your query to provide more specific information.

**where**: This filter is used to search for survey responses that contain specific values in a given field. For example, `where:"weather='sunny'"` will cause the filter to only use responses where the weather field contains the value sunny.

**!important**: This qualifier can be added to any filter, to override any constraints on the values that the filter returns. For example, if you were printing reports from only the last seven days, `where:"weather='sunny' !important"` would cause the filter to only use responses where the weather field contains the value sunny, but pulls from all applicable responses in the feature service, rather than just the responses selected to be printed.

**$inputParams**: This placeholder can be used within any filter to refer to the parameters used when printing a feature report, set through the Survey123 website. These parameters can then be further qualified to narrow down your response. For example, `orderByFields:"$inputParams"` will order the fields using the ordering set in the Survey123 website when printing reports. You can also use $inputParams to apply these parameters to repeats.
___
Please give it a try using this new feature report template syntax on our survey123 Beta website with your own survey.

**Comment by Shwujeng** [comment]
Holistic lab session on 6/4/2020 Redlands:
- [ ] Bobby Horne
- [ ] Chris Ferner
- [ ] Kylie Donia
- [ ] Matthew Baber
- [ ] Matthew Woodlief
- [ ] Mike Cox
- [ ] Red Cylwik
