### ISSUE TITLE
FEEDBACK: Ranking Question

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#369]
The new ranking question in web designer allows respondents to rank a list of items by dragging and dropping each item in order of preference.  

![Ranking](https://user-images.githubusercontent.com/5918689/81947200-20cac400-95b5-11ea-8899-be584f5f17f3.gif)

### Known concerns
In previous holistic testing, we received a number of requests to allow for only a partial selection (i.e., select the top 3, leaving the rest unselected).  This will be researched for a future release - it's technically outside the XLSForm specification and we will need to develop a way to work around that.

### Feedback
* Does the question work well in online surveys? Test with a small (up to 5) and large list (up to 15).
* Is the user experience for sorting items intuitive?
* Explore the output of this question through the Analyze tab in the Survey123 website. Are the results presented in an intuitive way?
* Test the output of this question in a custom report.

**Comment by Shwujeng** [comment]
Holistic lab session on 6/4/2020 Redlands:
- [ ] Azin Sharaf
- [ ] Bobby Horne
- [ ] Chad Nunemacher
- [ ] Chris Ferner
- [ ] Chryse Kruse
- [ ] Eric Ford
- [ ] Francisco Andrade
- [ ] Gareth McBride
- [ ] Jonathan Faoro
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Leandro Zamudio
- [ ] Matthew Baber
- [ ] Matt Woodlief
- [ ] Marco Amaya
- [ ] Michael Penokie
- [ ] Mike Cox
- [ ] Rad Cylwik
- [ ] Sue Enyedy-Goldner

**Comment by mrwoodlief** [comment]
The question format works well for short 5-10 questions, anything longer it becomes a bit annoying. I'd like to the ability to set a constraint, like you have to at least select your top 5 and the rest can go unranked

**Comment by jerjer007** [comment]
Ranking was tested using 5 choices and 20 choices.  Both worked well.  I like the "Reset" button.  It cleared all of the ranking numbers and I found it was easier to just 'tap' on choices rather than dragging them to positions. Maybe this should be an option (non-numbered) during the designing process.

**Comment by rcylwik** [comment]
Tested with up to 15 choices with no issue.  Would it be possible to select multiple choices via Ctrl when dragging?

**Comment by gmcbride792** [comment]
Ranking worked well during testing, I had a recent ask whereby a submitter would select 3 ranked locations they would be willing to re-deploy to out of a list. I would agree the ability to set a constraint on how many choices are required would be a great addition. Is a minimal appearance possible to minimize the list before/after selections have been made?

**Comment by sueeg** [comment]
I tested this an it worked well.  Liked the combination of chart and table on the Analyze tab. i did a simple summary report and it worked. Maybe I missed this somewhere but can I have values displayed by their label and not the database name ? Also is there an example showing how to split out multiple choices from the rankings into separate table cells ? Thanks (sorry I came in later from another meeting and just picked this topic).

**Comment by tedrick** [comment]
Feedback from Chris - is it possible to include an 'other' option?

**Comment by tedrick** [comment]
@sueeg is not seeing labels for ranking questions when in the summary section

**Comment by tedrick** [comment]
Thanks you for the feedback - we will consider the suggested improvements in the future.
