### ISSUE TITLE
Feedback: Survey123 website (in Portal environment) Data tab doesn't function in Internet Explorer

### ISSUE THREAD

**Issue by fcxagerr** [tedrick/Survey123-Testing#37]
**Application:** Connect | Field App | Website | On Premises | _ArcGIS Portal 10.5.1_

**Device:** _Dell Laptop_

**Operating System:** _Windows 10_

**Browser:** _Internet Explorer v11_

**Error Description:** Browser cycles permission requests and will not display data

![internet explorer](https://user-images.githubusercontent.com/31450288/29847713-f7c33676-8cd1-11e7-883a-e50cfe76247f.JPG)
_

**How to reproduce:** Attempt to open Data tab on an owned survey in Survey123 website in a Portal 10.5.1 environment

**Have you tested with another survey?** Yes

**Comment by zhif7782** [comment]
Similar with #36 , need more info about the portal to debug. 

I can open the Data page and view the individual response of a survey in the demo 10.5.1 portal: https://pm.demo.geocloud.com/arcgis successfully.
![image](https://user-images.githubusercontent.com/7665168/29864842-73a4db1c-8da6-11e7-8792-7b751298f720.png)

**Comment by fcxagerr** [comment]
We have a meeting with our MIS team today to discuss the deployment of our 10.5.1 Portals. I will bring up this issue to our internal team and I will let you know if we come up with a fix.

If my team is still unable to resolve this, I will get you some security specifics and I will see what kind of access I can grant you to our portals.

**Comment by fcxagerr** [comment]
The issue appears to be resolved in Internet Explorer. See issue #36

**Comment by zhif7782** [comment]
@fcxagerr please feel free to close the issue if you feel it's resolved. Of course we can reopen it if it is reported again.

**Comment by JohnHasthorpe** [comment]
2.4 testing complete
