### ISSUE TITLE
Attempting to Create a Survey Form on Internet Explorer

### ISSUE THREAD

**Issue by fandrade86** [tedrick/Survey123-Testing#370]
Unable to create a Survey form via Website on Internet Explorer.

I switched over to Google Chrome and I had no issue.

I am on Internet Explorer 11.53.18362.0

![image](https://user-images.githubusercontent.com/21234095/83792309-c078f080-a64f-11ea-84b5-f5013e6ca0f7.png)

Below is the screenshot of the error I am receiving:

![image](https://user-images.githubusercontent.com/21234095/83792378-d4245700-a64f-11ea-9ac9-e352f1e4929a.png)

Error Details:
{"code":-1,"message":"","description":"Object doesn't support property or method 'get'","number":-2146827850,"stack":"TypeError: Object doesn't support property or method 'get'\n at e.prototype.addItem (https://survey123beta.arcgis.com/assets/js/main-v3.10.beta9.js:2:1841809)\n at Anonymous function (https://survey123beta.arcgis.com/assets/js/main-v3.10.beta9.js:2:1589570)\n at e.prototype.invoke (https://survey123beta.arcgis.com/assets/js/main-v3.10.beta9.js:2:129224)\n at onInvoke (https://survey123beta.arcgis.com/assets/js/main-v3.10.beta9.js:2:654920)\n at e.prototype.invoke (https://survey123beta.arcgis.com/assets/js/main-v3.10.beta9.js:2:129224)\n at t.prototype.run (https://survey123beta.arcgis.com/assets/js/main-v3.10.beta9.js:2:124494)\n at Anonymous function (https://survey123beta.arcgis.com/assets/js/main-v3.10.beta9.js:2:136502)\n at e.prototype.invokeTask (https://survey123beta.arcgis.com/assets/js/main-v3.10.beta9.js:2:129881)\n at onInvokeTask (https://survey123beta.arcgis.com/assets/js/main-v3.10.beta9.js:2:654832)\n at e.prototype.invokeTask (https://survey123beta.arcgis.com/assets/js/main-v3.10.beta9.js:2:129881)","data":{"id":null,"owner":null,"title":"Delelet_Test","created":null,"description":null,"tags":[],"thumbnail":"","snippet":null,"formItemInfo":{"typeKeywords":[],"ownerFolder":"ca266b1c347d4352b2e7ec24d8e6a841"},"form":{"isUpdatedWebMap":false,"_ruleCount":0,"_whitelists":["layerName","portalUrl","header","subHeader","questions","rule","rules","submit","footer","themes","settings","version","extensions"],"_objectIdCounter":{"question":0,"page":0,"group":0},"layerName":"survey","isCreatedByExistingFeatureService":false,"portalUrl":"https://www.arcgis.com","header":{"_whitelists":["isVisible","content"],"isVisible":true,"content":""},"subHeader":{"_whitelists":["isVisible","content"],"isVisible":true,"content":"
Description content for the survey
"},"questions":[],"rules":[],"rule":{},"version":"3.10","themes":[{"_whitelists":["id","name","header","form","webpage","isEnabled"],"_supportedFormStyles":["header","form","webpage"],"id":null,"name":"theme-color1","isEnabled":true,"header":{"cssStyleInfo":{"background":"#B7DCC7","color":"#ffffff"},"_whiteLists":["backgroundColor","backgroundImage","backgroundImageFit","textColor"],"_backgroundImageUrlRegexp":"^url((.*?))$","backgroundColor":"#31872E","backgroundImageFit":"fill","backgroundOpacity":1,"backgroundType":"color","textColor":"#ffffff"},"form":{"cssStyleInfo":{"background":"#B7DCC7","color":"#505050"},"_whiteLists":["backgroundColor","backgroundImage","backgroundImageFit","backgroundOpacity","primaryColor","primaryTextColor","textColor","inputTextColor","inputBackgroundColor"],"_backgroundImageUrlRegexp":"^url((.*?))$","backgroundColor":"#ffffff","backgroundImageFit":"repeat","backgroundOpacity":1,"backgroundType":"color","textColor":"#505050","primaryColor":"#31872E","primaryTextColor":"#ffffff","inputTextColor":"#505050","inputBackgroundColor":"#ffffff","inputBackgroundOpacity":1},"webpage":{"cssStyleInfo":{"background":"#B7DCC7","color":"#505050"},"_whiteLists":["backgroundColor","backgroundImage","backgroundImageFit"],"_backgroundImageUrlRegexp":"^url((.*?))$","backgroundColor":"#B7DCC7","backgroundImageFit":"fill","backgroundOpacity":1,"backgroundType":"color","textColor":"#505050"},"_calculatedColor":{}}],"footer":{"_whitelists":["isVisible","content"],"isVisible":true,"content":"Powered by ArcGIS Survey123"},"submit":{"buttonText":"Submit","_whiteLists":["buttonText"]},"settings":{"_whitelists":["showQuestionName","thankYouScreenContent","recordStartEndTime","notificationsInfo","isVersionLocked","instanceName","openStatusInfo","multiSubmissionInfo","draftInfo"],"showQuestionNumber":false,"thankYouScreenContent":"

Great! Your data was sent successfully. Thanks.
","openStatusInfo":{"_whitelists":["status","schedule","closedStatusContent"],"status":"open","schedule":{"_whitelists":["start","end"],"start":null,"end":null,"startDate":null,"endDate":null},"closedStatusContent":"

This survey is currently closed. Thanks!
"},"recordStartEndTime":{"isEnabled":false,"fieldInfos":[]},"notificationsInfo":{"whiteLists":["webhooks","notifications"]},"isVersionLocked":true,"multiSubmissionInfo":{"_whitelists":["maxAllowed","showSubmitAnotherTip"],"maxAllowed":0,"showSubmitAnotherTip":false,"preventSubmissionContent":""},"draftInfo":{"_whitelists":["isEnabled"],"isEnabled":false}},"originalVersion":"3.10"},"publishedForm":null,"formVersion":null,"formFileName":null,"formInfoFile":{},"_whitelists":["id","owner","title","created","description","tags","thumbnail","snippet","formItemInfo","form","publishedForm","formVersion","formFileName","reportMerge","featureService","notifications","webhooks"],"_originalForm":{"isUpdatedWebMap":false,"_ruleCount":0,"_whitelists":["layerName","portalUrl","header","subHeader","questions","rule","rules","submit","footer","themes","settings","version","extensions"],"_objectIdCounter":{"question":0,"page":0,"group":0},"layerName":"survey","isCreatedByExistingFeatureService":false,"portalUrl":"https://www.arcgis.com","header":{"_whitelists":["isVisible","content"],"isVisible":true,"content":""},"subHeader":{"_whitelists":["isVisible","content"],"isVisible":true,"content":""},"questions":[],"rules":[],"rule":{},"version":"3.10","themes":[{"_whitelists":["id","name","header","form","webpage","isEnabled"],"_supportedFormStyles":["header","form","webpage"],"id":null,"name":"theme-color1","isEnabled":true,"header":{"cssStyleInfo":{"background":"#B7DCC7","color":"#ffffff"},"_whiteLists":["backgroundColor","backgroundImage","backgroundImageFit","textColor"],"_backgroundImageUrlRegexp":"^url((.*?))$","backgroundColor":"#31872E","backgroundImageFit":"fill","backgroundOpacity":1,"backgroundType":"color","textColor":"#ffffff"},"form":{"cssStyleInfo":{"background":"#B7DCC7","color":"#505050"},"_whiteLists":["backgroundColor","backgroundImage","backgroundImageFit","backgroundOpacity","primaryColor","primaryTextColor","textColor","inputTextColor","inputBackgroundColor"],"_backgroundImageUrlRegexp":"^url((.*?))$","backgroundColor":"#ffffff","backgroundImageFit":"repeat","backgroundOpacity":1,"backgroundType":"color","textColor":"#505050","primaryColor":"#31872E","primaryTextColor":"#ffffff","inputTextColor":"#505050","inputBackgroundColor":"#ffffff","inputBackgroundOpacity":1},"webpage":{"cssStyleInfo":{"background":"#B7DCC7","color":"#505050"},"_whiteLists":["backgroundColor","backgroundImage","backgroundImageFit"],"_backgroundImageUrlRegexp":"^url((.*?))$","backgroundColor":"#B7DCC7","backgroundImageFit":"fill","backgroundOpacity":1,"backgroundType":"color","textColor":"#505050"},"_calculatedColor":{}}],"footer":{"_whitelists":["isVisible","content"],"isVisible":true,"content":""},"submit":{"buttonText":"","_whiteLists":["buttonText"]},"settings":{"_whitelists":["showQuestionName","thankYouScreenContent","recordStartEndTime","notificationsInfo","isVersionLocked","instanceName","openStatusInfo","multiSubmissionInfo","draftInfo"],"showQuestionNumber":false,"thankYouScreenContent":"","openStatusInfo":{"_whitelists":["status","schedule","closedStatusContent"],"status":"open","schedule":{"_whitelists":["start","end"],"start":null,"end":null,"startDate":null,"endDate":null},"closedStatusContent":""},"recordStartEndTime":{"isEnabled":false,"fieldInfos":[]},"notificationsInfo":{"whiteLists":["webhooks","notifications"]},"isVersionLocked":true,"multiSubmissionInfo":{"_whitelists":["maxAllowed","showSubmitAnotherTip"],"maxAllowed":0,"showSubmitAnotherTip":false,"preventSubmissionContent":""},"draftInfo":{"_whitelists":["isEnabled"],"isEnabled":false}},"originalVersion":"3.10"},"reportMerge":{"templateItems":[]},"featureService":{"source":{"itemId":"","url":"","isView":false,"isRelatedToFormItem":false,"count":-1,"initialized":false,"exist":false,"featureServiceReachable":false,"surveyFeatureLayer":{"name":null,"fields":[]}},"metadata":{"itemId":"","url":"","isView":false,"isRelatedToFormItem":false,"count":-1,"initialized":false,"exist":false,"featureServiceReachable":false,"surveyFeatureLayer":{"name":null,"fields":[]}},"fieldworker":{"itemId":"","url":"","isView":true,"isRelatedToFormItem":false},"stakeholder":{"itemId":"","url":"","isView":true,"isRelatedToFormItem":false}},"_definedTypeKeyword":{"republish":"Redraft","redraft":"Redraft","draft":"Draft","survey123hub":"Survey123 Hub","survey123connect":"Survey123 Connect"},"_errors":[],"_trackChanges":[],"_isFormInited":false,"_currentUserRoles":["owner"],"_allowUserRoles":["fieldworker","stakeholder","qaqc","coowner","owner","admin"],"_webAppOpenMode":"web"}}

**Comment by Shwujeng** [comment]
@fandrade86 It might be the version of the IE you are using. I did not recevie error while creating survey with 11.1217.
Could you try to update the IE to the latest version to see if you are still getting error?
![image](https://user-images.githubusercontent.com/29442153/83794893-827dcb80-a653-11ea-9d33-48c79f3e92c5.png)
