### ISSUE TITLE
Test Flight App Crashed after Making Survey123 Setting Change

### ISSUE THREAD

**Issue by cnuner** [tedrick/Survey123-Testing#371]
Unsure if bug or not.....Test flight app crashed after making change to ArcGIS Survey123 Beta setting "require update to the latest version for all surveys" then pushing a new updated to AGOL via survey123 Connect while still in Test flight

Survey123 Field App(IOS via Apple TestFlight) 2.10.227
Survey123 Connect 3.10.188
iOS software version 13.3.1
Iphone 8

might be something to investigate though.  Once i reopened test flight app and opened updated survey it did prompt stating there was an updated needed like expected.

**Comment by tedrick** [comment]
@cnuner - Thanks for reporting this.  We do see the application occasionally crash the first time opening after being installed over an existing version of the application; based on our discussion this may be the case here.
