### ISSUE TITLE
Error messages for min/max numbers are off (also in live website & field app)

### ISSUE THREAD

**Issue by kyliedonia** [tedrick/Survey123-Testing#372]
**Describe the bug**
Error text for numbers with min or max set is off.

**Application:** Websit | field app
**Device:** Windows PC | iPhone, Android phone (Google Pixel 4)
**Operating System:** Windows 10 | iOS 13.3, Android 10
**Browser:** Chrome | n/a

**To Reproduce**
1. Add a number that has a min of 2 (or max of 5).
2. Start filling out the survey, and put in a number that is too low (or too high).
3. See error messages. 
    ![image](https://user-images.githubusercontent.com/3945570/83797853-1b164a80-a658-11ea-969d-352a4109906f.png)

But the min was set to 2 (and max to 5) but the error message reads like it has to be greater than 2 or less than 5, where 2 and 5 are valid choices. This is an error message only issue -- the accepted values do seem correct, as shown below:
    ![image](https://user-images.githubusercontent.com/3945570/83798005-63ce0380-a658-11ea-84e7-6936ebcf09af.png)

**Expected behavior**
Error message should reflect the correct min/max.

**Comment by tedrick** [comment]
Thanks for raising this @kyliedonia - I've filed an issue to revise the statement in a future release.
