### ISSUE TITLE
FEEDBACK: Changes to survey Settings tab in Connect

### ISSUE THREAD

**Issue by brettstokes** [tedrick/Survey123-Testing#373]
The latest build of Survey123 Connect includes some changes to the survey Settings tab. You will see the result of some of these changes, along with more general improvements to the Folders (Inbox, Sent, Outbox and Drafts) in the latest build of the Survey123 field app.

Please check out the new `Options` tab in Connect and publish surveys with different combinations of options enabled (eg view, edit, copy options for Inbox and Sent Folders). Observe your changes in the field app and provide feedback.

![image](https://user-images.githubusercontent.com/46305628/83844689-cbfd1200-a74a-11ea-9260-4eaf3f791400.png)

**Comment by Shwujeng** [comment]
6/9/2020 Holistic testing Redlands session:
- [ ] Abdullah Almoammar
- [ ] Abigail Stephens
- [ ] Amy Peters
- [ ] Andrew Makowicki
- [ ] Ash Comer
- [ ] Ben Keller
- [ ] Chris Gabris
- [ ] Chryse Kruse
- [ ] Eric Ford
- [ ] Faisal Basudan
- [ ] Francisco Andrade
- [ ] Jamie Lambert
- [ ] Jerry Jacobsen
- [ ] Jessica Rosales
- [ ] John Bickmore
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Melanie Baker
- [ ] Michael McGill
- [ ] Michael Penokie
- [ ] Mike Cox
- [ ] Ohan Oumoudian
- [ ] Pablo Cabrera
- [ ] Sepideh Sepehr
- [ ] Sue Enyedy-Goldner
- [ ] Walter Simonazzi
- [ ] Zachary Sutherby

**Comment by machl22** [comment]
For those organizations with larger datasets, for example in the case of site inspections by region, it would be very helpful for the end user to be able to dynamically query the inbox. Example, User A is responsible for inspections in California, from Survey123 field app, it'd be useful for end user to select California from dropdown to be able to limit necessary inspections to those located in California.

**Comment by lbarnhill** [comment]
Inbox documentation still states go to Settings > Inbox.  Inbox now part of Options

I selected Allow inbox surveys to be viewed then published but field app (v.251) does not show the inbox as available until I delete the original survey and download the newly published version (Require update... has been enabled)  After refresh, I received a list of 20 surveys (correct number) but all had the same name 1591722000000 14478.00 Bridge Inspection.  I opened several and they are each unique but the name is not helpful.  

Are previous images not viewable?  I can see none included in any previous survey

**Comment by lbarnhill** [comment]
Nice - In Settings > Options, I enabled both Allow...viewed and Allow...edited.  Upon opening item in Inbox, a new window opened asking to open as View or Edit.  Seems to work as the choice indicated.  Still **no images can be seen** in Edit mode and I was **unable to capture any additional images.**  If this is intended operation, this point should be clear in documentation

**Comment by Zachary-Sutherby** [comment]
All the settings that I had set in Connect were respected in the Field App and each functioned as expected. I know the Overview folder is in beta, one quirk I noticed with both the Inbox and the Sent folder enabled is it took a few taps to open the Overview and it seemed that 2 were open.

This was after testing with just the Sent folder enabled, republishing with only the Inbox folder enabled, and then republishing with both Sent and Inbox enabled so there were a few settings changes made and overwritten multiple times. 

![2020-06-09_11-06-23](https://user-images.githubusercontent.com/54078266/84184070-9ce3ea80-aa41-11ea-8d14-bbedde4817eb.gif)

Survey123 Log: 

[20200609-104747.log](https://github.com/tedrick/Survey123-Testing/files/4753979/20200609-104747.log)

Survey123 Connect Settings: 

![ConnectSettings](https://user-images.githubusercontent.com/54078266/84184113-b38a4180-aa41-11ea-9a32-079cb3b085a5.JPG)

**Comment by lbarnhill** [comment]
Attempting the Query Expression - is there a way to check the expression at publishing instead of waiting to find an error in the field app?  Received several "Code 400  - Cannot perform query."  I have not gotten the "LIKE" query to work at all.  This also appears to only work from Connect - Connect creates a predefined query and there is no option where the field app can query previous surveys to be returned to the inbox

Documentation is not very clear -- should state that caps matter and it does not state the very limited capabilities of sql 92

**Comment by lbarnhill** [comment]
Testing Overview - took a long time to load surveys the first time.  I could not get it to load all 20 surveys.  I restarted the app as well as re downloaded the survey.  They downloaded surveys also did not match my previous Where clause so I am not sure why those particular surveys were loaded. 
 There needs to be some documentation, and view options, especially on the naming and size of the point.
