### ISSUE TITLE
FEEDBACK: Use Drafts, Outbox, Sent, Inbox and Overview folders and observe changes in behaviour

### ISSUE THREAD

**Issue by brettstokes** [tedrick/Survey123-Testing#374]
This is related to https://github.com/tedrick/Survey123-Testing/issues/373 but more focussed on the folder behaviour. Please focus on using your existing Drafts, Outbox, Sent, Inbox workflows and provide feedback on the impact of the changes (see explanation below).

Previously, surveys could sometimes be duplicated across folders causing unwanted results. Now that the survey duplication has been fixed, **a survey record can only be in one 'folder' at a time**. If you're used to submitting a new record from your device and then refreshing the Inbox to see it updated there you will notice this difference. Previously the survey record would be in both your Sent and refreshed Inbox folders simultaneously. Now it will remain in your device's Sent folder (it is being filtered from the Inbox) until you delete it. Once deleted from your Sent folder, it will appear in your Inbox when refreshed.

The best practice for survey authors that use the Inbox to receive updated data is to disable the Sent folder entirely.

The new `Overview` folder will help you understand which survey records are in which folders without having to visit each folder individually. 
![image](https://user-images.githubusercontent.com/46305628/83845427-2f3b7400-a74c-11ea-8018-ad66da3ad71c.png)

Hint: The `Overview` folder can be be enabled in the Connect → Survey Settings → Options tab, in the `Beta` group at the bottom:
![image](https://user-images.githubusercontent.com/46305628/83845281-e4b9f780-a74b-11ea-8db5-dcacaafd4a8e.png)

It can also be enabled in the field app directly by pressing and holding on the Survey title in the survey info page.

**Comment by Shwujeng** [comment]
6/9/2020 Holistic testing Redlands session:
- [ ] Abdullah Almoammar
- [ ] Abigail Stephens
- [ ] Amy Peters
- [ ] Andrew Makowicki
- [ ] Ash Comer
- [ ] Ben Keller
- [ ] Chris Gabris
- [ ] Chryse Kruse
- [ ] Eric Ford
- [ ] Faisal Basudan
- [ ] Francisco Andrade
- [ ] Jamie Lambert
- [ ] Jerry Jacobsen
- [ ] Jessica Rosales
- [ ] John Bickmore
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Melanie Baker
- [ ] Michael McGill
- [ ] Michael Penokie
- [ ] Mike Cox
- [ ] Ohan Oumoudian
- [ ] Pablo Cabrera
- [ ] Sepideh Sepehr
- [ ] Sue Enyedy-Goldner
- [ ] Walter Simonazzi
- [ ] Zachary Sutherby

**Comment by sueeg** [comment]
Hi James, I have successfully turned on the Overview folder. However when I turn off Sent option in Connect settings and publish, Sent still appears in the field app both on iOS & WIndows even after survey refresh. And got a few crashes on iOS when I hit update surveys.

**Comment by cmkruse** [comment]
I was testing the different Options configurations and enabled the Overview option. I submitted one survey completely and left another in the draft. When I went to the overview and map option, this is what it showed: 
![image](https://user-images.githubusercontent.com/66691425/84185292-a3736180-aa43-11ea-819b-e1fb78fbd09b.png)
As you can see, the feature IDs are on top of one another, the 1 and 2. If I select the point it asks me if I want to submit the one that is in the drafts. I selected yes and then looked again and the map showed this: 
![image](https://user-images.githubusercontent.com/66691425/84185437-d87fb400-aa43-11ea-9b19-f324dec749e0.png)

The labels of the points are on top of each other, I don't know which survey I am selecting based on the map. While I can go to the list to see, the map display seems like it could be improved.

**Comment by tedrick** [comment]
Roshni - 

- Sent folder still appears if items are in sent folder after updating settings
- Inbox - removing edit to view only didn't seem to take on update
