### ISSUE TITLE
FEEDBACK: New Survey123 Field app login UI improvement.

### ISSUE THREAD

**Issue by Shwujeng** [tedrick/Survey123-Testing#375]
With the latest build of Survey123 field app, we have redesigned the login UI page to enhance the login experience.

In the initial login page, you have choices to specify a connection with either ArcGIS Online or an enterprise portal to sign in with. You could also choose to continue without signing in.
![image](https://user-images.githubusercontent.com/29442153/83917547-f55a7580-a72b-11ea-92e1-16cbe452cc2d.png)

Now you could directly manage your connection within the initial login page.

![image](https://user-images.githubusercontent.com/29442153/83917854-73b71780-a72c-11ea-89f0-5c36bfa92a52.png)

Please try to test this new signing in page UI changes, especially when connecting to an enterprise portal, and provide the feedback on your experience with this new change.

**Comment by Shwujeng** [comment]
6/9/2020 Holistic testing Redlands session:
- [ ] Abdullah Almoammar
- [ ] Abigail Stephens
- [ ] Amy Peters
- [ ] Andrew Makowicki
- [ ] Ash Comer
- [ ] Ben Keller
- [ ] Chris Gabris
- [ ] Chryse Kruse
- [ ] Eric Ford
- [ ] Faisal Basudan
- [ ] Francisco Andrade
- [ ] Jamie Lambert
- [ ] Jerry Jacobsen
- [ ] Jessica Rosales
- [ ] John Bickmore
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Melanie Baker
- [ ] Michael McGill
- [ ] Michael Penokie
- [ ] Mike Cox
- [ ] Ohan Oumoudian
- [ ] Pablo Cabrera
- [ ] Sepideh Sepehr
- [ ] Sue Enyedy-Goldner
- [ ] Walter Simonazzi
- [ ] Zachary Sutherby

**Comment by machl22** [comment]
New UI is much more intuitive. The landing screen is much easier for users, particularly those with Enterprise/Portal to connect, as opposed to the previous: settings icon>Add Portal workflow.

**Comment by AndrewMak91** [comment]
Signed in with an ArcGIS Enterprise Portal I had deployed a few months ago. Setting up and managing the connection was very seamless. Works similar to managing portals in ArcGIS Pro.

**Comment by Zachary-Sutherby** [comment]
I am not sure if this is related to the new log in UI, but after logging in if you sign out and then try to launch a survey that is not already downloaded on the device the Field App sits on the My Surveys page and does not throw an error message. 

In the 3.9 and prior releases of the Field App if you try to launch a survey either through a QR Code or using URL parameters you would be prompt with:

![Survey123Download3_9](https://user-images.githubusercontent.com/54078266/84180465-622b8380-aa3c-11ea-9476-36b41d445e79.png)

But in 3.10.251 if you try to launch a survey and you are not signed in nothing happens. 

![DownloadSurvey](https://user-images.githubusercontent.com/54078266/84180944-2d6bfc00-aa3d-11ea-91fd-f11dd0a1e355.gif)

Survey123 log below: 

[20200609-101647.log](https://github.com/tedrick/Survey123-Testing/files/4753775/20200609-101647.log)

Additional notes: 

Tested against ArcGIS Enterprise 10.8, not ArcGIS Online.
Only tested QR Code did not have a chance to test using URL Parameters just yet. 

All files also located in \\\sutherby1\MobileTaskforce\06_09_Survey123Holistic

**Comment by jerjer007** [comment]
I initially signed in using my ArcGIS Online account and that worked fine. I logged out and tried to log back in, to test a portal account, but my iPhone immediately logged me in automatically using my ArcGIS Online account. So, I navigated to Settings (survey app) and clicked on Connections. I saw my ArcGIS Online account. Then I looked to see if I could add a connection from this tab, but that option was not available. That would be a good enhancement- being able to add portal connections from the Settings/Connection tab.

**Comment by jerjer007** [comment]
I was able to continue without signing in and successfully download a public survey using the QR code. If I tried to scan a 'private' survey, then I was asked to sign-in.

**Comment by cmkruse** [comment]
I was able to successfully sign in with the AGOL option. It showed the loading screen saying that I was being signed in which I thought was helpful. However, when I went to download one of my recently updated surveys that I was testing in Connect, the app froze a bit and I was pushed back to the sign in. The survey that I downloaded is now in the opening screen, but the behavior seemed buggy to kick me out of my account and require the additional login.

**Comment by jerjer007** [comment]
The app hung while downloading several surveys (ArcGIS Online account). After ten minutes, it was still spinning and I closed the app. Reopening the app, I found, one of the surveys didn't completely download correctly because of the hang and didn't work properly.

**Comment by BigBoat8542** [comment]
I was able to log in successfully and clearly however when opening the login the login screen did not fit to the full window. This was successful however in both connect and the field app. It also had mentioned my location services were off, so I made note and turned them on for the app, however there isn't any notice to turn on your location it just offers other things to connect to. Steps listed out would be useful for other users

**Comment by jerjer007** [comment]
After choosing the "Continue without signing in", and opening the Connections tab (Settings) the ArcGIS Online account still has a check mark as if it is still active. If I click on it, nothing happens (expecting the log-in page).

**Comment by jerjer007** [comment]
Enhancement: Allow surveys to be deleted from the My Survey123 page. Currently, surveys need to be opened first, then they can be deleted.

**Comment by bearman1** [comment]
When I setup the connection to use our ArcGIS Enterprise account (https://gisportal.melbourne.vic.gov.au/enterprise) it uses the name 'ArcGIS Enterprise'. So the buttons are effectively doubled up as per below screen shot. How do I set that text for our portal instance (10.6.1)?
![image](https://user-images.githubusercontent.com/28586237/84211365-8b144d00-aafe-11ea-8758-ff570fb326a5.png)
