### ISSUE TITLE
FEEDBACK: General UI changes in Survey123vConnect and Field App.

### ISSUE THREAD

**Issue by Shwujeng** [tedrick/Survey123-Testing#376]
In the latest build of Survey123 3.10 Connect and field app, you may notice that some of UIs had been changed, including the general layouts, icons and popup dialogs.
When you test features across the Connect and field app, please pay attendtion to the new UI changes and popup/warning message dialogs. 

Your feedback on those UI changes will help us improving the Survey123 product to be more user friendly.

**Connect UI change examples:**
![image](https://user-images.githubusercontent.com/29442153/83923396-078de100-a737-11ea-9d34-731ac19178d3.png)
![image](https://user-images.githubusercontent.com/29442153/83923437-1eccce80-a737-11ea-812d-30a8aa3e7917.png)

**Field App UI change examples:**
![image](https://user-images.githubusercontent.com/29442153/83922581-67838800-a735-11ea-8c1e-e59c218fd60f.png)
![image](https://user-images.githubusercontent.com/29442153/83922817-e24ca300-a735-11ea-8283-ea9cfff1f2bb.png)

**Comment by Shwujeng** [comment]
6/9/2020 Holistic testing Redlands session:
- [ ] Abdullah Almoammar
- [ ] Abigail Stephens
- [ ] Amy Peters
- [ ] Andrew Makowicki
- [ ] Ash Comer
- [ ] Ben Keller
- [ ] Chris Gabris
- [ ] Chryse Kruse
- [ ] Eric Ford
- [ ] Faisal Basudan
- [ ] Francisco Andrade
- [ ] Jamie Lambert
- [ ] Jerry Jacobsen
- [ ] Jessica Rosales
- [ ] John Bickmore
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Melanie Baker
- [ ] Michael McGill
- [ ] Michael Penokie
- [ ] Mike Cox
- [ ] Ohan Oumoudian
- [ ] Pablo Cabrera
- [ ] Sepideh Sepehr
- [ ] Sue Enyedy-Goldner
- [ ] Walter Simonazzi
- [ ] Zachary Sutherby

**Comment by machl22** [comment]
The toggle for require update to the latest survey version is very profound. All too often it is necessary to provide substantial documentation and "helper videos" to guide users to pull delete existing version of survey and replace with subsequent version. This capability will substantially aid in providing a more intuitive user experience.
