### ISSUE TITLE
Challenge: Unlinking content

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#377]
In the last holistic testing session, several people discovered that it was not possible to unlink the default map from a form immediately after publishing.  This has been addressed in the new version of Survey123 Connect.  Please try to link and unlink content.

### Linked Content
To better manage and organise your basemaps, web maps and offline map packages, we have introduced a new feature in Connect on the Settings tab of a survey called Linked Content.

Linked Content allows you to search your ArcGIS organization for basemaps, web maps, offline map packages and offline web map areas and associate them with your survey. By selecting a supported map type and adding it to you survey, users can view the linked online basemaps and web maps in the basemap chooser in the field app, and if the linked map was an offline package, they can download the package via the "Download map" menu on the device.

To add linked content, you need to be signed in and your survey needs to have been published. You do not need to re-publish your survey after adding linked content, it will be automatically added provided you are online and signed in.

![image](https://user-images.githubusercontent.com/46305628/81799539-d1ed4200-9554-11ea-8631-f97bf10a995c.png)

To make it easier to search all your supported maps types, a handy filter has been added to the Linked Content → Add Map Link search menu to help narrow down the results.

![image](https://user-images.githubusercontent.com/46305628/81799586-e16c8b00-9554-11ea-9840-37b911e4832a.png)

**Comment by Shwujeng** [comment]
6/9/2020 Holistic testing Redlands session:
- [ ] Abdullah Almoammar
- [ ] Abigail Stephens
- [ ] Amy Peters
- [ ] Andrew Makowicki
- [ ] Ash Comer
- [ ] Ben Keller
- [ ] Chris Gabris
- [ ] Chryse Kruse
- [ ] Eric Ford
- [ ] Faisal Basudan
- [ ] Francisco Andrade
- [ ] Jamie Lambert
- [ ] Jerry Jacobsen
- [ ] Jessica Rosales
- [ ] John Bickmore
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Melanie Baker
- [ ] Michael McGill
- [ ] Michael Penokie
- [ ] Mike Cox
- [ ] Ohan Oumoudian
- [ ] Pablo Cabrera
- [ ] Sepideh Sepehr
- [ ] Sue Enyedy-Goldner
- [ ] Walter Simonazzi
- [ ] Zachary Sutherby
