### ISSUE TITLE
CHALLENGE: New URL Parameters

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#378]
With the 3.10 release, the field app URL parameters have been expanded to address a number of additional workflows.  

Try out the new parameters to do the following tasks
- Find matching surveys within a specific folder (Sent, Inbox)
- Open an existing form in read-only mode
- Refresh the Inbox
- Edit an existing record
- Open another application after completing a form action

### Parameters
Let's review the full URL parameters:
**Existing Parameters:**

Parameter | Type | Default | Folder/Action | Comments
-- | -- | -- | -- | --
itemID | `<UUID>` |   |   | Which form to open. If not specified Survey123 will launch, but not attempt to open a survey
center | `<Coordinate>` |   | collect | Survey location<br />`<lat>,<lon>`<br />`<lat>,<lon>,<alt>`<br />Latitude and longitude are in decimal degrees (WKID 4326)
field:`<fieldname>` | `<fieldvalue>` |   | collect | Populate survey questions. Multiple fields may be specified as required. The field name referred in the survey must be prefixed with `field:`. The value specified for the field must confirm to the requirements of the field.

**New Parameters:**

Parameter | Type | Default | Folder/Action | Comments
-- | -- | -- | -- | --
download | `<boolean>` | true |   | Automatically attempt to download the survey when the device is online
callback | `<url>` |   |   | Callback url
callback:`<status>` | `<url>` |   |   | Survey status<br />cancel<br />draft<br />submit
action | `<action>` | collect |   | Survey actions<br />collect<br />edit<br />view<br />copy
folder | `<folder>` |   | Not collect | Survey folders<br />inbox<br />drafts<br />outbox<br />sent<br />*
filter | `<filter>` |   | Not collect | `<Filter text>`globalId:`<guid>`field:`<fieldname>`:`<fieldvalue>`
update | `<boolean>` | false | inboxoutbox | Refresh inbox surveys if onlineSend outbox surveys if online
q:`<queryparameter>` |   |   | inbox | [Query parameters](https://developers.arcgis.com/rest/services-reference/query-feature-service-layer-.htm) <br />q:where=`<where clause>`<br />q:objectIds:`<oid>`<br />q:globalId:`<globalId>`

-  **Callback:** A callback is an action that will occur after a form action (Submit, Move to Drafts Folder, Cancel & Exit).  It is either an application URL (like arcgis-explorer://) or an HTTP url (like http://explorer.arcgis.app).  The generic callback will work for every action; a callback with a specific action will only work for that action.
- **Action:** How the form is opened.  This is normally paired with either `filter` or a set of `q:` parameters.  Collect, the default action, will create a new, blank record.  View will open the form completely read-only and Edit will open the form in edit mode.  Copy will use the data of the selected form as a template and create a new record. If the filter or q: parameters result in multiple records, the action will apply to the next selected record. If the filter or q: parameter result in a single record, that record will be opened
- **Folder:** Which folder will be searched using the filter parameter
- **Update:** Refresh the Inbox or force submittal attemps in the Outbox
- **Filter:** Filter searches the list of records already in the folder.  This is a text search in most fields, with special objectid:XX and globalid:XXXXXX key terms to search those fields
- **q:<queryparameter>:** Query the feature service for an existing record.  This parameter can use any of the feature layer query URL parameters; the most likely used will be the query or objectIds parameters.  Additionally, the resultRecordCount parameter can be used to help limit a where query to 1 record and the orderByFields can be used to order the results to retrieve a specific record based on criteria.  A special parameter, q:globalId, can be used to specify a feature based on globalId.  Not that the user must be able to connect to the feature service for this parameter to work; use the filter parameter to search the existing Inbox records.

### Scenarios

- Edit a record by GloablID: There are 2 different workflows for opening a record to edit, depending on if you are planning the process to use the Inbox or query the feature service (note: the Inbox does not need to be enabled).
  - Connected (%3D is = URL encoded):
`arcgis-survey123://?q:where=globalid%3D'<GLOBALID>'&action=edit&folder=inbox`
  - Disconnected:
`arcgis-survey123://?action=edit&folder=inbox&update=true&filter=globalid:<GLOBALID>`

- View the last inspection: While connected, this is possible using multiple q: parameters:
  - where (to limit to the correct asset)
  - sortField (to sort by date created)
  - resultRecordCount (to limit the result to 1 record)
  - `arcgis-survey123://?q:where=assetid%3D'<ASSETID>&q:orderByFields=CreationDate%20DESC&q:resultRecordCount=1&action=view&folder=inbox`

- Use the last inspection as a template for a new record: This modifies the 'view the last record' by changing the action to clone.
`arcgis-survey123://?q:assetid%3D='<ASSETID>&q:orderByFields=CreationDate%20DESC&q:resultRecordCount=1&action=clone&folder=inbox`

- Open Workforce after completing a form:  This uses the callback parameter to set that happens after submit/cancel
`arcgis-survey123://?callback=arcgis-workforce://`

**Comment by Shwujeng** [comment]
6/9/2020 Holistic testing Redlands session:
- [ ] Abdullah Almoammar
- [ ] Abigail Stephens
- [ ] Amy Peters
- [ ] Andrew Makowicki
- [ ] Ash Comer
- [ ] Ben Keller
- [ ] Chris Gabris
- [ ] Chryse Kruse
- [ ] Eric Ford
- [ ] Faisal Basudan
- [ ] Francisco Andrade
- [ ] Jamie Lambert
- [ ] Jerry Jacobsen
- [ ] Jessica Rosales
- [ ] John Bickmore
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Melanie Baker
- [ ] Michael McGill
- [ ] Michael Penokie
- [ ] Mike Cox
- [ ] Ohan Oumoudian
- [ ] Pablo Cabrera
- [ ] Sepideh Sepehr
- [ ] Sue Enyedy-Goldner
- [ ] Walter Simonazzi
- [ ] Zachary Sutherby

**Comment by marikavertzonis** [comment]
My goal was to start in Explorer, select a feature, edit it, and return to Explorer. I never got this complete circuit - I was able to launch Survey123 create a new feature and come back with the call back - and was able to launch in edit mode, but never the editing and call back together.

This url in the pop up of my webmap worked (click in Explorer, add record in Survey123, return to Explorer when survey sent)
`arcgis-survey123://?itemID=2bd39e78637741fda8eee1e5f75f7eab&callback=arcgis-explorer://`

These are variants that i tried - to get the Explorer -> Survey123 -> Explorer scenario working, but none worked:
 - `arcgis-survey123://?itemID=2bd39e78637741fda8eee1e5f75f7eab&filter=field:objectID:{objectid}&action=edit&update=true&callback=arcgis-explorer://`
 - `arcgis-survey123://?itemID=2bd39e78637741fda8eee1e5f75f7eab&filter=globalid:{globalid}&action=edit&folder=inbox&update=true&callback=arcgis-explorer://`

 - `arcgis-survey123://?itemID=2bd39e78637741fda8eee1e5f75f7eab&q:objectID:{objectid}&action=edit&update=true&callback=arcgis-explorer://`
- `arcgis-survey123://?itemID=2bd39e78637741fda8eee1e5f75f7eab&q:objectIDs:{objectid}&action=edit&update=true&callback=arcgis-explorer://`

 - `arcgis-survey123://?itemID=2bd39e78637741fda8eee1e5f75f7eab&q:where=globalid:{globalid}&action=edit&folder=inbox&update=true&callback=arcgis-explorer://`
 - `arcgis-survey123://?itemID=2bd39e78637741fda8eee1e5f75f7eab&q:globalid:{globalid}&action=edit&folder=inbox&update=true&callback=arcgis-explorer://`

**Comment by sueeg** [comment]
Hi James.
I tested the Explorer callback after completing a form = successful .
Also opening a survey with the inbox  successful.
Still working on opening record to edit by globalid. will update.

**Comment by BigBoat8542** [comment]
For the New URL parameters everything ran successfully. The explorer callback, using the inbox, using the filer and testing the record edits with globalid were completed without issue. This worked really well
