### ISSUE TITLE
FEEDBACK: Image Capture Method with annotate appearance

### ISSUE THREAD

**Issue by brettstokes** [tedrick/Survey123-Testing#379]
Following the last holistic testing session, changes have been made to the behaviour for `image` questions that use the `annotate` appearance. The camera is now launched by default, rather than bringing up a blank canvas. We think this is preferable for ~90% of the `annotate` use cases. If specifying a single capture method (using the `method=` parameter in the `bind::esri:style` column on the `image` question), that method will be launched instead of the canvas.

Please try out the new default behaviour with `image` questions that use the `annotate` appearance and provide feedback.

Also check out the behaviour when two capture methods are specified eg `method=map,browse`.

Options are:
- `browse` (select an existing file)
- `camera` (device camera)
- `map` (annotate question - image capture of a map)

**Comment by Shwujeng** [comment]
6/9/2020 Holistic testing Redlands session:
- [ ] Abdullah Almoammar
- [ ] Abigail Stephens
- [ ] Amy Peters
- [ ] Andrew Makowicki
- [ ] Ash Comer
- [ ] Ben Keller
- [ ] Chris Gabris
- [ ] Chryse Kruse
- [ ] Eric Ford
- [ ] Faisal Basudan
- [ ] Francisco Andrade
- [ ] Jamie Lambert
- [ ] Jerry Jacobsen
- [ ] Jessica Rosales
- [ ] John Bickmore
- [ ] Kylie Donia
- [ ] Leonard Barnhill
- [ ] Melanie Baker
- [ ] Michael McGill
- [ ] Michael Penokie
- [ ] Mike Cox
- [ ] Ohan Oumoudian
- [ ] Pablo Cabrera
- [ ] Sepideh Sepehr
- [ ] Sue Enyedy-Goldner
- [ ] Walter Simonazzi
- [ ] Zachary Sutherby

**Comment by cmkruse** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/66691425/84187490-fa2e6a80-aa46-11ea-964d-9eb8ae8e08c6.gif)

The video shows some expected and some unexpected behavior. The first few strokes show expected, you make the mark and then can include text. However, any straight line you have automatically turns into an arrow, which I think could be frustrating if that's not what the use want. It makes sense for the circle and square to automatically become those shapes, but a line turning into an arrow might not always make sense. Additionally, if the line/mark isn't long enough, it simply disappears and the annotation does not save on the canvas which is seen at the end of the GIF.

**Comment by cmkruse** [comment]
There's one point in the GIF above where I selected the three lines in the top corner of the screen and nothing happened. I'm not sure what the expected behavior is/ what is meant to happen when you select that button, but in my testing nothing happened but a small vibration on my phone. This could come off as buggy to user's if this is expected behavior.

**Comment by cmkruse** [comment]
The erase option in the annotate is to erase the entire canvas rather than individual annotations. I think user's might become frustrated that they can't select and erase certain annotations unless they delete all or only use the 'undo' and have to erase annotations in order of their creation.
