### ISSUE TITLE
BUG: Groups are greyed out on Collaborate tab

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#38]
**Application:** Website 

**Operating System:** Qin 10

**Browser:** Edge

**Error Description:** On Collaborate tab, > Submit, when checking 'Following Groups:' all of the Groups will stay greyed out and when hovering over the check box, it appears with a red X. But if you click the check box, it works. Same on Collaborate > Analyze tab
Going back and forth between Analyze and Submit will make all groups appear active again
Leaving the Collaborate tab and returning resets the behavior and groups appear greyed out again
(red X does not appear in screenshot but when hovering over any greyed out group, the red X appears)f

![image](https://user-images.githubusercontent.com/22916127/29848160-ca09a6aa-8cd3-11e7-8fa4-c0040f674b41.png)

**Comment by zhif7782** [comment]
Hi @sbubka94 thanks for the feedback. Seems you encountered a known issue only happens to Edge, where the check box displays in a wrong way but actually behaves correctly. You can use Firefox or Chrome as a workaround.
![abc](https://user-images.githubusercontent.com/7665168/29866301-9c73f15a-8daa-11e7-9568-371670c8255a.gif)

**Comment by JohnHasthorpe** [comment]
2.4 testing complete

**Comment by tedrick** [comment]
Filed as https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/1386, fixed for 2.4
