### ISSUE TITLE
[CHALLENGE] New choice question formats & filtering enhancements

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#381]
With 3.10, we are introducing a new way to load choices - from a CSV directly!  To do so, use either
- `select_one_from_file <CSV_NAME>`
- `select_multiple_from_file <CSV_NAME>`

![image-20200908141520-2](https://user-images.githubusercontent.com/1319289/93132817-20d5f000-f68b-11ea-847e-78951443d894.png)

 This can be useful for a number of reasons:
- Very large choice lists
- Choice lists that are constantly changing (see the blog post  for more information on managing this)
- Choice lists that are managed outside of Survey123

Additionally, there are significant improvements to cascading selects:

- select_multiple questions can have a cascading select, allowing you to filter the choices of multiple choice questions. Filtering a select_multiple choice works the same way as filtering a select_one.
- The choice_filter now supports the full set of XLSform functions

*Choice_filter functions*

With the support of XLSForm functions in chocie_filter, there are a number of techniques that you can use:

- If you have a series of questions where you want to remove choices selected in previous questions, you can now use the != operator: `name != ${prev_1}`
- You can base a cascade on the choices selected in a multiple choice question with the `selected(${q},<name>)` function.  For example: `selected(${states_visited},state_code)`. This can also be combined with `not()` to filter if a choice is not selected
- Choice filters can work with date information, such as months or years, using the `format-date()` function.  For example, if you have choices that should only be shown for certain months, `int(format-date(${date_q}, '%n')) = month`
- Multiple values in a filtering field can be searched by using the `regex()` function to see if the field contains a given value: `regex(filter_values, ${prev_q})`
- You can use `if()` statements to implement complex logic, allowing you to filter based on multiple criteria: `if(${filter_method} = 1, ${prev_q1} = filter_value, ${prev_q2} = filter_value)`

*Limitations*
- If using select_one_from_file in conjunction with the new randomize  option, other instances of that choice list within your survey will also be randomized (even without specifying randomize=true). 

*Challenge:*
- Create form using CSV choices.  Try updating the choices after publishing
- Use functions in choice filters - can you make a select_one filter to the choices selected in a select multiple?

**Comment by Shwujeng** [comment]
Redlands Holistic lab session on 9/16/2020 
- [ ]Alexandra Milanetti
- [ ]Benjamin Wan
- [ ]Carson Smulders
- [ ]Chad Nunemacher
- [ ]Chryse Kruse
- [ ]Francisco Andrade
- [ ]Glen Shepherd
- [ ]Jamie Lambert
- [ ]Jeff Swain
- [ ]Josh Taylor
- [ ]Kylie Donia
- [ ]Louis King Bosso
- [ ]Maggie Samson
- [ ]Manish Patel
- [ ]Ohan Oumoudian
- [ ]Sean Stasio
- [ ]Tarik Ceric
- [ ]Tyler Scuralli

**Comment by tedrick** [comment]
Samples from the Redlands Holistic Testing:
[Select_3.11.zip](https://github.com/tedrick/Survey123-Testing/files/5233652/Select_3.11.zip)
[choice_filter_improvements.xlsx](https://github.com/tedrick/Survey123-Testing/files/5233657/choice_filter_improvements.xlsx)

**Comment by jswiggy** [comment]
First off it looks like this type of question isn't available from the pick list when I tried the drop-down.  It did seem to recognize it when i finished typing it with no errors but when i saved it i got errors. 

![image](https://user-images.githubusercontent.com/5588635/93373918-06834a00-f824-11ea-88e1-ac3b5ed4b219.png)

![image](https://user-images.githubusercontent.com/5588635/93373996-1ef36480-f824-11ea-880e-dba4b0a31a64.png)
 This is what I got when hitting update.  So there is the error. What I did was remove the ranking in there and tried to get it to be read from the csv was my thought. I didn't see ranking listed  in the survey but perhaps it is in there in another place? Is there an help doc on the syntax needed for this?  I put the csv in the survey folder since the example didn't have much in the way of a full path. 

Any ideas?

**Comment by tedrick** [comment]
@jswiggy - could you share the CSV file you are using?

**Comment by jswiggy** [comment]
[choice_filter_improvements.zip](https://github.com/tedrick/Survey123-Testing/files/5234156/choice_filter_improvements.zip)

Here is the zipped up project. It is just your project and trying to add in the option for the csv.

**Comment by glenshep** [comment]
Looks to work well!
A couple of hurdles (user errors) along the way:
- ensure to save as CSV
- close the CSV before save/update

![image](https://user-images.githubusercontent.com/71058145/93424710-e757eb80-f8fb-11ea-93b6-eb2bd47cf194.png)

**Comment by J8L** [comment]
I have had a look at select_one questions and filtering the choice list. The method that i'm sure most people used in the past of duplication choices and applying different filter values (**example 1 in attached XLSForm**) is tried and true. No surprises there.

Using regex (**example 2 in attached XLSForm**) works, however **when you select then unselect a response, all values are shown from the choice list**. I would expect no results to be returned when nothing is selected.

In the example James provided (@tedrick choice_filter_improvements.xlsx), the 'Complex Select Multiple Filter' example works well and I like the layout on the 'choices' tab. Its nice and clear where as the regex example is harder to read.

I tried to use this layout on the 'choices' tab with a select_one question and couldn't get it to work at all (**example 3 in attached XLSForm**). I thought I could just use an if statement to basically get the same result as example 1.

I'm hoping I haven't just missed something obvious, but I'm also hoping its something obvious and an easy fix!

XLSForm attached.
[Holistic 3-11.xlsx](https://github.com/tedrick/Survey123-Testing/files/5239801/Holistic.3-11.xlsx)
