### ISSUE TITLE
[FEEDBACK] - Web form performance improvements

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#382]
As part of 3.11 development, a significant amount of effort has been placed to make the web form faster to load.  Try timing the load times for your form in survey123.arcgis.com and survey123beta.arcgis.com (you may want to use browser developer tools) and detail the load time, along with information on the form's complexity (how many questions, choices, calculations)?

**Comment by Shwujeng** [comment]
Redlands Holistic lab session on 9/16/2020 
- [ ] Alexandra Milanetti
- [ ] Benjamin Wan
- [ ] Carson Smulders
- [ ] Chad Nunemacher
- [ ] Chryse Kruse
- [ ] Francisco Andrade
- [ ] Glen Shepherd
- [ ] Jamie Lambert
- [ ] Jeff Swain
- [ ] Josh Taylor
- [ ] Kylie Donia
- [ ] Louis King Bosso
- [ ] Maggie Samson
- [ ] Manish Patel
- [ ] Ohan Oumoudian
- [ ] Sean Stasio
- [ ] Tarik Ceric
- [ ] Tyler Scuralli

**Comment by msamsonGIS** [comment]
**Test 1:**
**Browser:** Chrome 85.0.4183.102
**Survey:** Quite Complex, 4 pages with 150+ questions a 20+ calculations
- **Load Time from Dev tools in Survey123**: Load: Load: 1.44 s, Finish: 4.60 s
- **Load Time from Dev Tools in Survey123 Beta**: Load: 1.92 s, Finish: 4.39 s

**Test 2 with the same survey, incognito chrome browser:**
- **Load Time from Dev tools in Survey123**: Load: 1.65 s, Finish: 4.43 s
- **Load Time from Dev Tools in Survey123 Beta**: Load: 2.21 s, Finish: 4.92 s

**Test 3 with the same survey, Firefox browser:**
**Browser:** Firefox
- **Load Time from Dev tools in Survey123**: Load: 814 ms, Finish: 6.47 s
- **Load Time from Dev Tools in Survey123 Beta**: Load: 564 ms, Finish: 5.88 s

**Comment by csmulders-1992** [comment]
Survey Info: 
-150 lines
-12 Calculations
-19 Choices 

Load Info: 
Beta Webiste: Finish: 5.85 s, DOMContentLoaded 1.73 s, Load 2.39 s
Normal Website: Finish 6.96 s, DOMContentLoaded 3.68 s, Load 3.68 s

**Comment by kyliedonia** [comment]
I have a survey that's embedded in a dashboard, and the intent was to update the selected feature. When I was trying to use it, I found it loaded slowly enough that I often didn't bother to use the survey in the dashboard and instead would use another tool (Collector, Pro, or AGOL) to do the editing that I'd hoped to do using the Survey and Dashboard combo. I brought up that same dashboard and made a version of it using the beta Survey123 site. 

The loading time is unfortunately about the same (it's a pretty basic, 3 question survey). So this didn't do enough that I think it would make the experience of using it to edit in a dashboard a lot more performant.

**Comment by patelmanya** [comment]
Browser: Chrome  85.0.4183.102 (Official Build) (64-bit)
Survey: Simple with 21 questions with some image in the form background

Load Time from Dev tools in Survey123: timing: 348.53 ms
Load Time from Dev Tools in Survey123 Beta: timing: 299.80 ms

Test 2 with the different survey

Load Time from Dev tools in Survey123: timing: 304.12 ms
Load Time from Dev Tools in Survey123 Beta: timing: 276.35 ms


Test 3 with the different survey with background image for the webpage

Load Time from Dev tools in Survey123: timing: 310.92 ms
Load Time from Dev Tools in Survey123 Beta: timing: 330.75 ms (this took a long time in response but visually it looks the same loading as in the production)
