### ISSUE TITLE
[FEEDBACK] - Hidden appearance

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#383]
With 3.11, a new appearance, `hidden`, will be available to make a question non-visible.  This is distinguished from the `hidden` question *type* in that the question will retain the type of question as set in the type field (hidden question types default to text).  That will allow a numeric, date, or shape (geopoint, geotrace, geoshape) question to be not visible but submit the data of that type to the feature service.  Default or calculated values in hidden questions will be submitted to the feature service as normal, but just won’t be displayed on the survey form.

Use the hidden question appearance in your forms to hide values - are there any interactions with other field columns (constraints, relevant) that surprise you?

**Comment by Shwujeng** [comment]
Redlands Holistic lab session on 9/16/2020 
- [ ] Alexandra Milanetti
- [ ] Benjamin Wan
- [ ] Carson Smulders
- [ ] Chad Nunemacher
- [ ] Chryse Kruse
- [ ] Francisco Andrade
- [ ] Glen Shepherd
- [ ] Jamie Lambert
- [ ] Jeff Swain
- [ ] Josh Taylor
- [ ] Kylie Donia
- [ ] Louis King Bosso
- [ ] Maggie Samson
- [ ] Manish Patel
- [ ] Ohan Oumoudian
- [ ] Sean Stasio
- [ ] Tarik Ceric
- [ ] Tyler Scuralli

**Comment by j-taylor-esri** [comment]
Really like this feature. Will be useful in assuring users do not accidentally overwrite collected data. Good addition!

**Comment by J8L** [comment]
This should be good. Makes the XLSForm cleaner (in that the question Type can be set correctly and the question is still hidden).

Will 'hidden' replace 'hide-input'? Or will we see 'hidden' and 'hide-input' as options? From the description (top of page) it sounds like it combines functionality (across field app and web form). There is already a question Type called 'hidden', so I reckon that may cause some confusion.
