### ISSUE TITLE
[FEEDBACK] Rank Question Type

### ISSUE THREAD

**Issue by Zachary-Sutherby** [tedrick/Survey123-Testing#384]
With the 3.10 release of ArcGIS Survey123 we introduced the new _Ranking_ question type, this functionality was only supported on the Web Form and not Connect or the Field App. Please use this [documentation link](https://doc.arcgis.com/en/survey123/browser/create-surveys/quickreferencecreatesurveys.htm#GUID-1CCDB274-96A6-4C8A-918D-266661C9A205
) for more information on the Ranking question type in the Web Designer.

With the 3.11 release of Survey123 we are including an initial implementation of the `rank` question type for use in Connect and the Field App. 

To get started with `rank` questions, add a `rank` question type followed by the choice list_name to your XLSForm:
  
![Rank1](https://user-images.githubusercontent.com/54078266/93140888-0c4c2480-f698-11ea-865f-77a0790fa490.png)

![Rank2](https://user-images.githubusercontent.com/54078266/93140893-0eae7e80-f698-11ea-8ffb-5dd69093527c.png)
  
To avoid introducing any bias to your ranked choices, it is recommended that you present your choices in random order using `randomize=true` in the parameters column of the XLSForm. See [this link](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={617742EA-4586-4107-BA3D-F3E6C5982E73}) for more details.

The results of a `rank` question are stored as a comma-separated string, with the top choice first and the bottom choice last. For example: 
james,jordan,johnson,oneal,abdul-jabbar,chamberlain,russell,bryant,robertson,bird
 
<img src='https://user-images.githubusercontent.com/54078266/93140908-18d07d00-f698-11ea-90ca-86c9d29b2e77.png' width='250' height='500'/>

**Usage notes:**

You can apply the same 'smart' options (e.g. relevant, default, required, read only, etc.) as with any other question type. **When the choice list is initially presented, the items are not ranked (they don't show the ranking order numbers) unless a default has been set. No data will be sent for the rank question if the survey is submitted in this unanswered state. Touching or moving any choice will change the state from null to ranked, and the rank order values will appear next to each item.** It is recommended to set the `required` property as best practice to ensure answers being submitted are ranked. 

Choices can be dragged to their rank, and values will dynamically change as the choice is being moved. Double clicking on an item will automatically move it to the top of the list. Right double click (on supported platforms) to move an item to the bottom of the list. Choice images are supported in the thumbnail only with the initial version. 

**Limitations** - We're still actively working on supporting the rank question type and have identified a limitation when using with survey folders (inbox, drafts, outbox, sent). Clicking on the clear button (X) does not currently return the list to it's initial pre-ranked order.

We are working on a reset and clear button as well as an image preview for thumbnail images, and audio support for `rank` items.

**Comment by Shwujeng** [comment]
Redlands Holistic lab session on 9/16/2020 
- [ ] Alexandra Milanetti
- [ ] Benjamin Wan
- [ ] Carson Smulders
- [ ] Chad Nunemacher
- [ ] Chryse Kruse
- [ ] Francisco Andrade
- [ ] Glen Shepherd
- [ ] Jamie Lambert
- [ ] Jeff Swain
- [ ] Josh Taylor
- [ ] Kylie Donia
- [ ] Louis King Bosso
- [ ] Maggie Samson
- [ ] Manish Patel
- [ ] Ohan Oumoudian
- [ ] Sean Stasio
- [ ] Tarik Ceric
- [ ] Tyler Scuralli

**Comment by Zachary-Sutherby** [comment]
### Sample XLSForm: 

[Cars.zip](https://github.com/tedrick/Survey123-Testing/files/5233723/Cars.zip)

**Comment by cmkruse** [comment]
Comments:
- Functionality was easy to use and makes sense
- I think it would make more sense to have the 'randomization' the default option for this functionality, rather than having to set it in the parameters. So then in the parameters, the format would have to be 'randomization=false' and unless it was set this way, there would always be randomization.
- When I downloaded the Survey in the field app on iOS > I pressed the back arrow to take me to my device's surveys and the app booted me back to the welcome page. It still showed that I was logged in, but I could not press anywhere or move to a different screen. I had to end my session and start a new one and was then not able to reproduce the behavior, but wanted to make note of it.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/66691425/93374490-a2ed2280-f80b-11ea-8e94-c058c3baf5d2.png)
-I didn't have any issues with the ranking questions in the field app itself, it seemed very smooth, though I think there's a big issue with not maintaining the rank when you send the survey to the outbox as it defeats the purpose, but this is known.

**Comment by tscuralli** [comment]
I really like the simplicity of the ranking question.  It's very easy to set up and I feel the randomize option will help avoid bias for users.  

It was super easy to use and works nearly identical to a select_one or select_multiple question types.  I also like how the numbers do not appear until you move the options. I will continue testing further and any other things I notice I will make sure to post here.

**Comment by csmulders-1992** [comment]
Device: MotoG7 Power 
Survey: Cars.xlsx provided in github

Test1: Downloaded survey to device and moved the questions around. Worked as expected. 
Test2: Did not rank the choices > Submitted the survey > Submitted with no data as expected
Test 3: Made the rank required > Ranked choices > Submitted successfully

**Comment by glenshep** [comment]
Set the 'rank' question using Connect and successfully submitted re-ordered ranking from the field app on an iPhone 7 (OS13.3.1). The 'randomize=true' parameter worked great.
Did not run into any issues.

**Comment by sarahallerton** [comment]
The rank question is great and easy to use. 
Using Survey123 Connect for Windows, the ranks don't show unless you put the randomize=true parameters  in.
