### ISSUE TITLE
[Challenge] Polyline and Polygon Web form URL Parameters & JS API Support

### ISSUE THREAD

**Issue by Zachary-Sutherby** [tedrick/Survey123-Testing#385]
Many folks use Survey123's Web form URL parameters to prepopulate questions, hide questions, change the language of a form, etc. 

Currently the Web form URL parameters only support passing along XY coordinates for Geopoint questions. With the 3.11 release of ArcGIS Survey123 we are expanding our support to pass along XY coordinates in Geotrace and Geoshape questions as well. 

We currently use the `field:` method to specify our geotrace/geoshape field and pass along our XY vertices as a sequence of coordinates separated by a semi-colon with a coordinate being space separated sequence of latitude and longitude.  (ex. `<lat1> <lon1>;<lat2> <lon2>; <lat3> <lon3>;...`)

When passing along parameters to geotrace/geoshape field the syntax will use the following format: 

`https://survey123beta.arcgis.com/share/<Survey Item ID>?field:line=34.060696 -117.200086;34.055579 -117.200005;34.055615 -117.195642`

Same syntax for Polygon as well: 

`https://survey123beta.arcgis.com/share/<Survey Item ID>?field:poly=34.060696 -117.200086;34.055579 -117.200005;34.055615 -117.195642;34.060696 -117.200086`

### JS API Support

With the 3.11 release of ArcGIS Survey123 we are now supporting `setGeometry()` in the JavaScript API. 

The `setGeometry()` function takes an input of XLSForm spec, [Esri JSON Geometry Objects](https://developers.arcgis.com/documentation/common-data-types/geometry-objects.htm), as well as GeoJSON. The function returns void. 

`setGeometry()`

Dynamically set coordinates on geopoint, geoshape, geotrace question. 

Parameters:
- geopoint,geoshape,geotrace: object

Returns: 
_void_

### Challenge

- Configure the Survey123 Web form URL parameter to pass XY coordinates into Geotrace and Geoshape question types. 
- Configure the ArcGIS Survey123 Web App JavaScript API to pass along the following coordinate formats: 
     - XLSForm specification
     - Esri JSON Geometry Objects
     - GeoJSON

### Notes/limitations: 

The `setGeometry()` function and Web form URL parameters will only work on the main layer in a survey, not geometry in repeats. For the XLSForm specification in the `setGeometry` function the first and last points need to be the same to complete the polygon.

**Comment by Shwujeng** [comment]
Redlands Holistic lab session on 9/16/2020 
- [ ] Alexandra Milanetti
- [ ] Benjamin Wan
- [ ] Carson Smulders
- [ ] Chad Nunemacher
- [ ] Chryse Kruse
- [ ] Francisco Andrade
- [ ] Glen Shepherd
- [ ] Jamie Lambert
- [ ] Jeff Swain
- [ ] Josh Taylor
- [ ] Kylie Donia
- [ ] Louis King Bosso
- [ ] Maggie Samson
- [ ] Manish Patel
- [ ] Ohan Oumoudian
- [ ] Sean Stasio
- [ ] Tarik Ceric
- [ ] Tyler Scuralli

**Comment by Zachary-Sutherby** [comment]
### Samples: 

**Web form URL parameters:** 

Geotrace: `https://survey123beta.arcgis.com/share/2ba8f3997fdb4b8b8ad83c7b6a359feb?field:route=34.060696 -117.200086;34.055579 -117.200005;34.055615 -117.195642;34.055765 -117.193611;34.057147 -117.192204;34.057047 -117.191339;34.057753 -117.191389`

Geoshape: `https://survey123beta.arcgis.com/share/41169965bb3f45c1871670ea1914ac0a?field:aoi=34.060696 -117.200086;34.055579 -117.200005;34.055615 -117.195642;34.055765 -117.193611;34.057147 -117.192204;34.057047 -117.191339;34.057753 -117.191389`

**JS API `setGeometry()`**

https://jsfiddle.net/ZSutherby_Survey123/3hnyruos/82/

**Comment by glenshep** [comment]
![image](https://user-images.githubusercontent.com/71058145/93429138-03f82180-f904-11ea-82ba-6c5154d9bab8.png)

Love this functionality.
Quite fast to render in Connect.

**Comment by jPurush** [comment]
This doesn't seem to work as far as I can tell with all formats:  

a) XLSFormat and GeoJSON: 
     
-  [IS_VALID_PATH](https://devtopia.esri.com/Beijing-R-D-Center/survey123-core/blob/d826900b5956acc5904003e5d18d5a684d0dc6ce/src/classes/util/util.ts#L181) failing because there is a `_super` in the array at this point and that is processed as well as the numeric indices.  

b) EsriGeometry: 
    

- The `IsGeoJSON` function throws an [exception](https://devtopia.esri.com/Beijing-R-D-Center/survey123-core/blob/5088820ad0b4d10bf2ecbabfb3e342872b9dbea6/src/classes/geoJson/geojson.ts#L19) instead of returning false. 

Is this working on your test environment?
