### ISSUE TITLE
[FEEDBACK] - General performance test of your device's compass sensor

### ISSUE THREAD

**Issue by brettstokes** [tedrick/Survey123-Testing#387]
Different devices include a myriad of different compass sensors and some perform better than others. We have been compiling a list of how well our test devices perform as compasses, and have already noted quite a lot of variability. We're keen to hear how it works for you.

Please conduct the following quick test with as many devices as you have access to and list the results in the comments below:

1. With the latest Survey123 field app beta installed (3.11.141), enable the compass beta feature. Tap and hold on the title bar of the **_Settings_** page to reveal the **_Beta_** options. Once enabled, you will see a new option for **_Compass_** settings. Here is where you enable the compass feature within the app:

![image](https://user-images.githubusercontent.com/46305628/93172230-cbbeda80-f76d-11ea-859d-46fc81467b30.png)

2. Go to the **_Location Status_** page by tapping on the satellite icon in the top right hand corner of the screen.
3. Note the Compass Calibration status indicator (color ramp at the bottom of the screen corresponds to 0 → 100%). Try improve the calibration by keeping clear of magnetic interference and then moving your device in figure eight motions several times in horizontal, vertical and diagonal directions. Note the final status (estimate the percentage).
4. Ensure the magnetic declination value is set to 0 (this can be done in Settings → Compass → Magnetic Declination).
5. Observe the performance of level indicator (2 x sets of cross hairs) by tilting the device in different directions. You should see the same effect as a spirit level bubble - both cross hairs align when level. Place the device on a flat surface as far away from interference (other electronic devices, metal objects and magnets) as possible. 
6. Align the device to point towards north. Some devices will report this well, others will have wild approximations of north. Align the wild ones with what should be north to start. 
7. Rotate the device clockwise smoothly on the flat surface for a full rotation while observing the changing bearing value and cardinal direction abbreviation (eg WNW). Note how smoothly the bearing value changes, if the bearing matches the abbreviation, the behaviour of the level indicator and whether the directions are sensible compared to what you know as North, East, South and West.
8. Please include any screenshots or recordings.

![image](https://user-images.githubusercontent.com/46305628/93174187-eba3cd80-f770-11ea-9dc6-a8e6fe208898.png)

**Comment by brettstokes** [comment]
Here is a template for recording results:

- Device make and model:
- Final calibration status indicator:
- Performance observations:
  - bearing values:
  - cardinal direction abbreviations:
  - level indicator:

**Comment by brettstokes** [comment]
- **Device make and model:** Samsung S10+
- **Final calibration status indicator:** 100%
- **Performance observations:**
  - **bearing values:** values look accurate but seem to have a slow update rate.
  - **cardinal direction abbreviations:** don't show anything in the West (only N→E→S), eg at 270 degrees abbreviation shows "East"
  - **level indicator:** clearly not working and appears to be linked to bearing as it only changes when rotating device (not tilting).

--------------------------
- **Device make and model:** Apple iPhone XR
- **Final calibration status indicator:** ~95%
- **Performance observations:**
  - **bearing values:** values look accurate, update rapidly and smoothly.
  - **cardinal direction abbreviations:** match bearing values correctly.
  - **level indicator:** working as expected.

**Comment by Shwujeng** [comment]
Redlands Holistic lab session on 9/16/2020 
- [ ] Alexandra Milanetti
- [ ] Benjamin Wan
- [ ] Carson Smulders
- [ ] Chad Nunemacher
- [ ] Chryse Kruse
- [ ] Francisco Andrade
- [ ] Glen Shepherd
- [ ] Jamie Lambert
- [ ] Jeff Swain
- [ ] Josh Taylor
- [ ] Kylie Donia
- [ ] Louis King Bosso
- [ ] Maggie Samson
- [ ] Manish Patel
- [ ] Ohan Oumoudian
- [ ] Sean Stasio
- [ ] Tarik Ceric
- [ ] Tyler Scuralli

**Comment by msamsonGIS** [comment]
**Device make and model:** Google Pixel 3
**Final calibration status indicator:** 100% -> This started at 100% and did not change at all so I am suspicious of it actually working correctly.
**Performance observations:**

- **bearing values:** the values seem accurate but they will jump dramatically while slowly rotating, they do not increase/decrease slowly as the device moving slowly. They also do not settle when I am not moving. Leaving the device unmoving on a table it would quickly flip through adjacent values. 

- **cardinal direction abbreviations:** This is not working correctly as it is reporting East when the compass is clearly pointed West. 

![image](https://user-images.githubusercontent.com/71398737/93370039-3cbdcb00-f81e-11ea-9b34-f62b6f9af73c.png)

- **level indicator:** Works ok when I tilt the device from side to side but not forward and backwards. It does not appear to be as responsive as the bearing values.

**Comment by csmulders-1992** [comment]
-Device make and model: MotoG7 Power
-Final calibration status indicator: Between 90% and 100%
-Performance observations:
     -	bearing values: Update rapidly and looks accurate
     -cardinal direction abbreviations: Sometimes flips to show the reverse bearing. Also, no west bearing: 
        
![Screenshot_20200916-125750](https://user-images.githubusercontent.com/71400322/93370269-8ad2ce80-f81e-11ea-9424-fa3569170640.png)

     - level indicator: Not initially working -would just flip from side to side. Now showing correctly. Can successfully line up the 
       crosshairs

**Comment by amilanetti** [comment]
Device make and model: Google Pixel 3 (Android 10)
Final calibration status indicator: ~80% (did not seem to change so it was unclear if moving the device was actually calibrating it) 
Performance observations: 
bearing values: Changed very quickly but seemed accurate. Continued to change slightly even when the device was not moving. 
cardinal direction abbreviations: Incorrect when pointing S, SW, W, NW. Would show the opposite direction.
level indicator: Moved when tilting the device side to side but did not seem to respond when tilting the device top to bottom. 
![Screenshot_20200916-132730](https://user-images.githubusercontent.com/43791259/93373225-0e8eba00-f823-11ea-8a8a-27a403093eb1.png)

**Comment by cmkruse** [comment]
Device make and model: iPhone 7+
Final calibration status indicator: ~95 on my iOS device, I was trying to align it as instructed in the app, with the figure 8 movements and iOS automatically pulled up the 'undo' option which interfered. This isn't necessarily an issue, but could be a frustrating user experience.
Performance observations: Very smooth and easy to use, all bearing were there for me

**Comment by tscuralli** [comment]
Device make and model: Iphone 8
Final calibration status indicator: 97%
Performance observations: 
bearing values: Changed very quickly and accurately, no notice of any 'lag' or hesitation. If I move the device quickly, the bearing appears as accurate as if I move slowly
cardinal direction abbreviations: Accurate, was always showing the correct direction my device was point and changed smoothly as rotating clockwise or counterclockwise
level indicator: Shows my desk as not perfectly level which seems accurate as one of the legs is bent, so all in all the compass works very well on my iOS Device

**Comment by glenshep** [comment]
Device make and model: iPhone 7, OS: 13.3.1
Final calibration status indicator: 90-95%
Performance observations: very sensitive. no noticeable lag. heading/roll/pitch appeared to be very accurate.

**Comment by marikavertzonis** [comment]
- **Device make and model**: Trimble TDC100
- **Final calibration status indicator**: 100% (was this to start with, never changed)
- **Performance observations**:
    - **bearing values**: values look accurate but seem to have a slow update rate. ie: as you turn the device, values slowly (but smoothly move)
    - **cardinal direction abbreviations**: N and E ok, nonsense in S and W 
    - **level indicator**: moved smoothly, but never really lined up

**Comment by marikavertzonis** [comment]
- **Device make and model**: Nokia 8.1 (Android 10)
- **Final calibration status indicator**: 100%
- **Performance observations**:
    - **bearing values**: at north reports 20, at east reports 50, at south reports, 70 at west reports 340 
    - **cardinal direction abbreviations**: at north reports NNE, at east reports NE, at south reports, ENE at west reports SSE
    - **level indicator**: moved smoothly, but never really lined up

**Comment by davismmarques** [comment]
Device make and model:  Google Pixel 2, Android 10

Final calibration status indicator: ~90%
Performance observations:
  - There is a lot of jitter in the bearing value. When the phone is sitting still on top of my desk, the bearing value is still changing continuously, perhaps each ~500ms. When I hold the phone and attempt to maintain a fixed position, the bearing value changes very quickly due to small hand movements of my hand. It becomes difficult to read at that point. Consider throttling the UI changes so that the bearing and compass values only change if the delta is above some threshold. 
  - The motion of the compass as it transitions to a new North orientation is a bit visually uncomfortable to me. It appears to accelerate toward the new position then stops abruptly. Consider adding a dynamic easing function to the orientation of the compass graphic that transitions to the next orientation using an easeInOutCubic or easeInOutQuad curve (https://easings.net/).

bearing values:
  - When the phone is pointing north, the bearing is ~360 SSE, 0 or 1 N
cardinal direction abbreviations:
level indicator:
  - The level indicator is completely inaccurate and is always on the west side of the compass. The pitch responds appropriately but not to the correct scale. The roll and yaw are not responding correctly.

![Screenshot_20200917-151149](https://user-images.githubusercontent.com/66241247/93426258-060bb180-f8ff-11ea-89bb-2de33886e7f2.png)

**Comment by davismmarques** [comment]
Device make and model: Apple iPhone 6, iOS 12.4.8

Final calibration status indicator: 95-98%

Performance observations:
  - The animation of the compass from the current orientation to the next orientation would be improved with some easing. There is something a bit mechanical about the current motion, as though its snapping into place when it reaches the target orientation.

bearing values:
   - The bearing values look good

cardinal direction abbreviations:
   - The cardinal direction indicators are a good size for easy reading. Consider differentiating the text color from the compass direction markers.

level indicator:
  - In general, the level indicator appears to function without issue. The one circumstance that requires discussion is when the screen orientation flips over.  In that case, the level indicator ends on on the opposite side of the screen and is no longer correct.

**Comment by brettstokes** [comment]
I've updated the [document](https://esriis.sharepoint.com/:w:/r/sites/Survey123/_layouts/15/Doc.aspx?sourcedoc=%7BF921BD55-66AC-475A-A102-DD4F164079C1%7D&file=Compass%20comparison.docx&action=default&mobileredirect=true) listing all of the device performance test results in this issue. Closing.
