### ISSUE TITLE
[FEEDBACK] - Compass feature in the field app

### ISSUE THREAD

**Issue by brettstokes** [tedrick/Survey123-Testing#388]
Many mobile devices have a compass sensor that allows you to orient yourself or get direction bearings etc. This information can now be utilized by a new compass feature in the Survey123 field app, to display which direction your device (and you) are facing. This can be useful for recording compass bearing values or if you're working in unknown surroundings and trying to locate assets or existing survey records etc.

Please take a look at the [EAC Documentation](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid=%7B5a8e51ed-4a87-43fe-a67d-2b7829af130f%7D&artid=%7Bfa070185-80cf-40d9-b928-d195be0e9b34%7D) for this 3.11 beta feature, test it out and provide feedback on design, usability, performance etc. We'd also like to hear details on if/how you think the compass feature and `bearing` appearance will improve your workflows.

**Comment by Shwujeng** [comment]
Redlands Holistic lab session on 9/16/2020 
- [ ] Alexandra Milanetti
- [ ] Benjamin Wan
- [ ] Carson Smulders
- [ ] Chad Nunemacher
- [ ] Chryse Kruse
- [ ] Francisco Andrade
- [ ] Glen Shepherd
- [ ] Jamie Lambert
- [ ] Jeff Swain
- [ ] Josh Taylor
- [ ] Kylie Donia
- [ ] Louis King Bosso
- [ ] Maggie Samson
- [ ] Manish Patel
- [ ] Ohan Oumoudian
- [ ] Sean Stasio
- [ ] Tarik Ceric
- [ ] Tyler Scuralli

**Comment by jswiggy** [comment]
Tested the Compass, by default it reported -7.93914 which matches what NOAA seems to indicate per their website. It seems to move slowly when turning but when I stop turning.. it seems to jump ahead to catch up. I can't tell if it is a graphical thing or actually the values reported. My compass calibration quality didn't move after changing the declination.   Not sure what is going on there. I am in Charlotte, NC, and testing on the iOS version.

**Comment by tedrick** [comment]
From Chad:
Device make and model: Apple iPhone 8
Final calibration status indicator: ~95%
Performance observations:
bearing values: values look accurate but there is a lag when turning the phone moderately to quickly
cardinal direction abbreviations: match bearing values correctly.
level indicator: working as expected.

**Comment by jerjer007** [comment]
In Redlands, my magnetic declination was 11.5571; and the Compass Calibration was pegged in the 'green'. The test was performed using an iPhone 7+, and Beta version: 3.11.129β. While tapping on the compass value I did notice, after awhile, that there was a smaller letter "M" or a "T"next to the bearing value. I had not used this function before- and was wondering how I was supposed to determine when I was in True North mode or Magnetic when tapping/toggling.

Observation- I noticed that while in the Data tab (Location Status), that the Magnetic variation showed, "No data"; and that Direction also showed, "No Data".

I didn't see the "GNSS Location Status" (Just Location Status) or Survey Folders on my version.

**Comment by OCrypter** [comment]
i am using an Apple iPhone Model Xs - iOs 13.7 

I have noticed that the Compass in the app is a bit off from the iPhone compass. If we do a side by side comparison they are a bit off.  I have recorded videos - they are attached here.

When we are turning the phone in 360 mode, there is sort of a kick/adjustment when you stop turning it. 

Also, the NMEA logs - the one you can record the main location page - those logs returned empty.

https://drive.google.com
/file/d/11J3q4VFtHR0mUGwBxzwhAFoktEKYXohS/view?usp=sharing 
( you will need to put the URL together - just being concerned about security )
