### ISSUE TITLE
CHALLENGE: Complex Surveys in the Data & Analyze tabs

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#39]
**Requirements:** Survey123 Field App and Connect from Early Adopter community: https://earlyadopter.esri.com/project/home.html?cap=%7bE69EF91F-4574-4B98-882C-651F7B518EB7%7d or from test-flight for IOS (you will need to download the test flight app from the store and receive an invite from Esri).

-----------------------------------------------
**Overview**
With 2.5, the Survey123 website is able to visualize surveys with complex structures, including nested groups or group/repeat combinations.  Test your surveys in the Data & Analyze tabs- please note when you find questions missing or displaying oddly!

**Process**
Publish a survey in connect and launch it the survey123 website.
![image](https://user-images.githubusercontent.com/24929507/31699049-6ada634e-b40c-11e7-8cc5-357ba96eb791.png)
But make sure that you change the url from https://survey123.arcgis.com  https://survey123**dev**.arcgis.com to access our dev environment. 

Note that you will need to collect some data in order to test this - so submit some surveys either through the webform or field app, and then explore in the data and analyze tabs. Create new issues to provide feedback to us.

**Comment by tedrick** [comment]
Analyze tab has an error 'Cannot get Forms for Survey' example: https://survey123dev.arcgis.com/surveys/b88cf33ffedc4e34bdd0bf4a40986471/analyze

**Comment by tedrick** [comment]
Matt, Bethany

**Comment by ahandelman** [comment]
I get the same error as Tedrick. I created a test survey that only has a basic repeat and that seems to be the cause. Also the view in the analyze tab gets hung up and can't finish loading at the question just before the repeat (the one that feeds the repeat count).
Public survey I used here: https://survey123dev.arcgis.com/share/1a727bd87ddc4803b9a4b95285a96c0b
![image](https://user-images.githubusercontent.com/32681552/31403528-2b036a4a-adae-11e7-9287-0aa0c969859e.png)

**Comment by BKArmstrong** [comment]
encountering same behavior when attempting to access the Analyze tab in Chrome
![analyze_error](https://user-images.githubusercontent.com/6314443/31411643-128270f6-adc7-11e7-8a54-8a7be2a32a61.PNG)

**Comment by zhif7782** [comment]
@tedrick @BKArmstrong can you please share the survey results with public or upload the XLSForm file for us to debug?

**Comment by zhif7782** [comment]
Fix is available in DEV website now.
