### ISSUE TITLE
[FEEDBACK] - Connect form preview UI changes

### ISSUE THREAD

**Issue by bwebster1** [tedrick/Survey123-Testing#390]
There are several UI enhancements in Survey123 Connect 3.11, and one of the most noticeable is the survey settings interface that is available during survey design. Previously many of the survey settings were located within a settings menu at the top of the window. In Connect 3.11 the settings options are shown horizontally across the bottom of the screen, while the appearance-related options are shown vertically on the right side. The schema preview is also reformatted, and shows the layers/tables, fields, and field properties horizontally. The intent of these changes is to make the various survey settings more accessible during survey design. Does this interface make it easier to access survey settings while you configure a survey?

### Updated UI:

<img src="https://user-images.githubusercontent.com/67349330/93237289-c1341f00-f734-11ea-878b-1b8e4b5b0dbc.jpg" width="600">

<img src="https://user-images.githubusercontent.com/67349330/93237287-c09b8880-f734-11ea-8391-5ac20a7e41d6.jpg" width="600">

### Previous UI:

<img src="https://user-images.githubusercontent.com/67349330/93237265-b6798a00-f734-11ea-8fef-8bab540bd292.jpg" width="600">

<img src="https://user-images.githubusercontent.com/67349330/93237267-b6798a00-f734-11ea-954d-3751b55744d7.jpg" width="600">

<img src="https://user-images.githubusercontent.com/67349330/93237260-b5485d00-f734-11ea-87ac-805015644d02.jpg" width="600">

**Comment by Shwujeng** [comment]
Redlands Holistic lab session on 9/16/2020 
- [ ] Alexandra Milanetti
- [ ] Benjamin Wan
- [ ] Carson Smulders
- [ ] Chad Nunemacher
- [ ] Chryse Kruse
- [ ] Francisco Andrade
- [ ] Glen Shepherd
- [ ] Jamie Lambert
- [ ] Jeff Swain
- [ ] Josh Taylor
- [ ] Kylie Donia
- [ ] Louis King Bosso
- [ ] Maggie Samson
- [ ] Manish Patel
- [ ] Ohan Oumoudian
- [ ] Sean Stasio
- [ ] Tarik Ceric
- [ ] Tyler Scuralli

**Comment by J8L** [comment]
This is for the **Field App (3.11.141 beta)** on iOS (from TestFlight) - in the Download Surveys window, the icons on the left are all missing (they can be seen on the main survey page) and the default images are flashing. This is both old surveys and a new survey that I added an icon to.

![DownloadSurveys](https://user-images.githubusercontent.com/42594789/93542359-20479d00-f99c-11ea-89d4-30d9c987c364.png)
