### ISSUE TITLE
[CHALLENGE] - Feature Report Improvements

### ISSUE THREAD

**Issue by bwebster1** [tedrick/Survey123-Testing#392]
The latest build of the Survey123 website includes several new improvements to feature reports. These improvements include the following. 

### 1. Map/point questions can now be rotated with a new mapRotation filter.
   - Use case: Irregularly shaped areas of interest can now be displayed more effectively within feature reports.
   - Syntax: _${question_name|mapRotation: 90}_
   - Notes: This filter can be used in conjunction with the mapSettings filter. Map settings must be configured before the map rotation. Example:  (_${question_name|mapSettings:”topo”:40000|mapRotation: 90}_

<img width="350" src="https://user-images.githubusercontent.com/67349330/93244665-efb6f780-f73e-11ea-8378-bec1ad3781bc.JPG"><img width="350" src="https://user-images.githubusercontent.com/67349330/93245264-e712f100-f73f-11ea-84ef-8522e41e5ca8.JPG">

### 2. The index of a record within a repeat can now be returned.

  - Use case: This could be used in situations where the user wants to identify the order of records within a repeat. For example, this would be useful in a table showing a list of inspections in sequential order. 
  - Syntax: 
      _{#repeat1}
      {$feature | getValue: "position"}
     {/}_

<img width="350" src="https://user-images.githubusercontent.com/67349330/93249559-555ab200-f746-11ea-9bc9-679eb642af1b.JPG"><img width="400" src="https://user-images.githubusercontent.com/67349330/93249563-568bdf00-f746-11ea-8e14-28e0c7488048.JPG">

### 3. Improved UI of the report panel on the Data page

- The report panel UI has been improved in 3.11 to make the workflow more intuitive. For example, 
  - We move the file options section down to the template dropdown menu and only enable the option when the template is feasible
  - The Preview button is moved closer to the Generate button
  - Since it's been a while, the credit info description has been removed for saving more space
  - Old:
    - ![image](https://user-images.githubusercontent.com/7665168/93284168-a7620d00-f804-11ea-9d29-2f21df933322.png)
  - New: 
    - ![image](https://user-images.githubusercontent.com/7665168/93284092-7c77b900-f804-11ea-827e-9bc05c7352ab.png)

## Challenge:
Using the beta version of the Survey 123 website ([https://survey123beta.arcgis.com/surveys](https://survey123beta.arcgis.com/surveys)),

- Use the map rotation filter to rotate a map in a feature report. Try combining the map rotation filter with other map settings. 
- Use getValue: “position” to show a record’s repeat index in a feature report.
- Use the new report panel to see if it fits your workflow

**Comment by Shwujeng** [comment]
Redlands Holistic lab session on 9/16/2020 
- [ ] Alexandra Milanetti
- [ ] Benjamin Wan
- [ ] Carson Smulders
- [ ] Chad Nunemacher
- [ ] Chryse Kruse
- [ ] Francisco Andrade
- [ ] Glen Shepherd
- [ ] Jamie Lambert
- [ ] Jeff Swain
- [ ] Josh Taylor
- [ ] Kylie Donia
- [ ] Louis King Bosso
- [ ] Maggie Samson
- [ ] Manish Patel
- [ ] Ohan Oumoudian
- [ ] Sean Stasio
- [ ] Tarik Ceric
- [ ] Tyler Scuralli

**Comment by IsmaelInRedlands** [comment]
Feedback in attached PPT.
Highlights:
* Unable to use position.
* Rotation: 
    * It would be nice to be able to set the rotation mode: Arithmetic versus Geographic
    * It would be nice to be able to set the rotation angle using a variable. For example, I want to show in the report photos and maps side by side. The maps need to be rotated to reflect the direction (Azimuth) of the photos.
* Amazing job with the Quick Reference
* Can't really use the Integromat module with summary reports unless you allow me to pass a WHERE statement.  Passing a comma separated list of OIDs is a bit convoluted
* Summary templates that work on production do not work in beta

[Survey123 Reports in 3.11 Ismael Holistic Testing Sep 16.pptx](https://github.com/tedrick/Survey123-Testing/files/5233916/Survey123.Reports.in.3.11.Ismael.Holistic.Testing.Sep.16.pptx)
