### ISSUE TITLE
CHALLENGE: Audio questions in the Individual Response

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#40]
**Requirements:** Survey123 Field App and Connect from Early Adopter community: https://earlyadopter.esri.com/project/home.html?cap=%7bE69EF91F-4574-4B98-882C-651F7B518EB7%7d or from test-flight for IOS (you will need to download the test flight app from the store and receive an invite from Esri).

-----------------------------------------------
**Overview**
With version 2.4, we introduced the ability to record audio in Survey123.  With 2.5, we'll be able to make it accessible from the Individual Response view on the data tab.  Test it out!

**Process**
Publish a survey in connect that contains one or more questions with the type of audio and launch it the survey123 website.
![image](https://user-images.githubusercontent.com/24929507/31699049-6ada634e-b40c-11e7-8cc5-357ba96eb791.png)
But make sure that you change the url from https://survey123.arcgis.com  https://survey123dev.arcgis.com to access our dev environment. 

Note that you will need to collect some data in order to test this - so submit some surveys through the field app, and use the data tab to access the individual responce view and test.

Create new issues to provide feedback to us.

**Comment by tedrick** [comment]
Brandon, Charmel

**Comment by BKArmstrong** [comment]
While testing the accessibility of audio content within survey123 website, I was expecting to have the ability to play the audio from a player.  Meaning, I am surprised that I am still required to download the content (.mp4) 
![individual_response_audio](https://user-images.githubusercontent.com/6314443/31402656-83067b2c-adab-11e7-9358-ee1fba62b9ce.PNG)
prior to playing in an audio player.

**Comment by jchaconas** [comment]
There is no button/image to click on to play the audio file from the individual response. Using the Edge browser, nothing appears. While using Chrome, a small box with an 'x' appears under where the audio link should be. Clicking in the blank area does open up the audio file, however. 

![capture2](https://user-images.githubusercontent.com/32681246/31412859-922730ea-adcb-11e7-96d4-72852ab79131.PNG)

**Comment by zhif7782** [comment]
Hi @BKArmstrong , .mp4 file recorded by Android device cannot be played directly but only provided with a download link, this is a known limitation currently due to the [underlying MIME type is `application/octet-stream` rather than `video/mp4`](https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/1889#issuecomment-886538).

cc @tedrick @spatialdude

**Comment by rush2paras** [comment]
Tested successfully (Samsung s7) Android Version 7.0
