### ISSUE TITLE
Feedback: Data Tab menu redesign

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#41]
**Requirements:** Web browser.

-------------------------
**Overview**
The Data Tab on the Survey123 website is getting redesigned.  Work with it and provide feedback below.

**Process**
Log onto the website and explore existing surveys via the data tab. But make sure that you change the url from https://survey123.arcgis.com https://survey123dev.arcgis.com to access our dev environment. Test all functionality in the page and capture any feedback in new issues.

**Comment by tedrick** [comment]
Matt, Bethany

**Comment by menzelc** [comment]
Data View - Where is the Default extent defined?  Is this based on the AGOL org or somewhere in the Survey123 site?

**Comment by menzelc** [comment]
Using Firefox 56.0.1
Re:  Show individual response

When I first open Data tab, by default show individual response is on, it is green.

![image](https://user-images.githubusercontent.com/4838513/31404958-85ea0cf8-adcb-11e7-937c-b25053a674ac.png)

When I turn off show individual response, nothing happens:

![image](https://user-images.githubusercontent.com/4838513/31404979-a3b10eda-adcb-11e7-9157-6567fd14437c.png)

Next I turn on show individual response and this new window appears but nothing displays.  Is it b/c only one person responded (me)? 

![image](https://user-images.githubusercontent.com/4838513/31405038-c8c2742a-adcb-11e7-993c-63e3364fed9e.png)

**Comment by jchaconas** [comment]
I have had users not understand that they need to click on individual records to view the associated data(individual responses) for that record. Providing a button next to each record to make it appear selectable could help with this confusion.

**Comment by zhif7782** [comment]
@menzelc the default extent is the bounding box of all existing features (submitted records) in the feature layer, it will change dynamically while new feature added to the layer.

**Comment by zhif7782** [comment]
@jchaconas we are using the feature table dijit from ArcGIS API for Javascript now. Unfortunately, it's a technical limitation that we cannot do much extensibility to the table.

Thanks for the feedback though, we will consider the UX once we have the ability.

**Comment by zhif7782** [comment]
Bugs have been fixed on DEV, closing.
