### ISSUE TITLE
Feedback: Keep feature service when deleting forms

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#43]
**Requirements:** Web browser.

-------------------------
**Overview**
The Survey123 website will provide an option to let you keep the feature service (data) when you delete a form.  Provide feedback on the experience below.

**Process**
Log onto the survey123 website but make sure that you change the url from https://survey123.arcgis.com to https://survey123dev.arcgis.com to access our dev environment.
Alternatively test against Portal 10.6. 
Go to my surveys and open any survey, and then select the option to delete the survey.
![image](https://user-images.githubusercontent.com/24929507/31700259-d9cba4e6-b413-11e7-9f47-7cb25bb6f11e.png)

Delete the survey - with or without deleting the underlying data. 
Provide any feedback below, or in new issues.

**Comment by tedrick** [comment]
Bethany

**Comment by bethanyw** [comment]
I tested this with ArcGIS Enterprise 10.6 and AGOL with no issue

**Comment by moore-jonathon** [comment]
Jonathon Moore here. Tested this on the dev survey123 website and worked fantastically. Will this also be an option when deleting forms from survey123 connect?

**Comment by phil-wilson** [comment]
@moore-jonathon As explained yesterday, deleting of surveys and feature service can be managed in AGOL and Survey123 website. If there is a compelling reason and user case to be able to delete and manage the surveys and feature services separately in Connect, please let us know.
