### ISSUE TITLE
CHALLENGE: Tap & Hold Behavior

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#44]
**Requirements:** Survey123 Field App and Connect from Early Adopter community: https://earlyadopter.esri.com/project/home.html?cap=%7bE69EF91F-4574-4B98-882C-651F7B518EB7%7d or from test-flight for IOS (you will need to download the test flight app from the store and receive an invite from Esri).

-----------------------------------------------
**Overview**
Did you know that in the Survey123 Application, when you tap & hold on a survey's thumbnail, you go directly to the form?  There have been a few bugs before that have been fixed in 2.5 - try it out and let us know if it works how you'd like!

**Process**
Open the survey123 field app and go to My Surveys. Press and hold a survey to directly open the form. Provide any feedback on this behaviour below.

**Comment by BKArmstrong** [comment]
Seems to work as expected, without error.

**Comment by shortiejj** [comment]
Working on both MacAir and iPhone6

**Comment by edcookgis** [comment]
Working well on Samsung Android Device, Nice to have this fix!

**Comment by moore-jonathon** [comment]
Also working on my Samsung S6 :)
