### ISSUE TITLE
CHALLENGE: Recalculation of functions

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#45]
**Requirements:** Survey123 Field App and Connect from Early Adopter community: https://earlyadopter.esri.com/project/home.html?cap=%7bE69EF91F-4574-4B98-882C-651F7B518EB7%7d or from test-flight for IOS (you will need to download the test flight app from the store and receive an invite from Esri).

-----------------------------------------------
**Overview**
Some functions in surveys, like `now()` and `random()`, should generate new values each time you refresh them, without a change in other data.  Try out these functions in surveys and let us know if you don't see this occurring.

**Process**
Using your own surveys with now() or random() in the calculate field or the the sample provided in https://github.com/tedrick/Survey123-Testing/issues/45#issuecomment-335682010 - open the survey, clear the answers for the appropriate questions and then test the recalculate button. 

![image](https://user-images.githubusercontent.com/24929507/31701797-819d028c-b41e-11e7-99a6-9bfe2e6510e2.png)

The values should update.

Capture any feedback in the new issues or the comment below

**Comment by tedrick** [comment]
Brittany, Christine, Christian

**Comment by cwhitehe** [comment]
I have tested the now() and the random() functions with in my surveys and have had no issues. Every time I refresh I get an updated value and my other data remains.

**Comment by gibbonsbr** [comment]
I tested the now(), today(), and random() functions in different surveys without issue. I was able to refresh to get an updated value without losing any other data. 

If other rows used these values for calculations, the calculations updated successfully when the values were refreshed. The pulldata function also worked successfully against these values and updated as expected.

Relevancies based on these values also worked correctly, unless the user hit the x button to clear the value before refreshing, in which case some dependent values might be lost if the relevant condition is no longer true. 

The Inbox also worked successfully when using a statement that included these values. 

My only suggestion for this feature is that the refresh button is not always visible. For some questions, it would be nice if the form creator had the option to make the refresh button visible to the user.

**Comment by phil-wilson** [comment]
[Date Recalc Example.xlsx](https://github.com/tedrick/Survey123-Testing/files/1374240/Date.Recalc.Example.xlsx)

**Comment by deeplakhanpal** [comment]
Getting an updated values with Now() and other functions.

**Comment by moore-jonathon** [comment]
Functionally looks good on my testing. No issues
