### ISSUE TITLE
CHALLENGE: Images on forms

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#46]
**Requirements:** Survey123 Field App and Connect from Early Adopter community: https://earlyadopter.esri.com/project/home.html?cap=%7bE69EF91F-4574-4B98-882C-651F7B518EB7%7d or from test-flight for IOS (you will need to download the test flight app from the store and receive an invite from Esri).

-----------------------------------------------
**Overview**
With 2.5, we've fixed a few bugs with forms that have images:
- renaming of images could cause a crash or failure to submit
- forms with lots of images could cause a crash

**Process**
Using your own surveys or samples/communities in connect - publish a survey that contains multiple images, annotates, and signatures. Try to complete and submit multiple surveys and let us know if it crashes!

**Comment by mattwbradbury** [comment]
Should probably be a button or text indicating you can change the image name.

**Comment by jchaconas** [comment]
Using Survey123 Connect, I was attempting to upload images(26 total) using a repeat. Following is the error I received:


![snip](https://user-images.githubusercontent.com/32681246/31402183-17e6c6a4-adaa-11e7-947b-28cb2224f8ac.PNG)


[
  {
    "attachments": [
      null
    ],
    "id": "%Form_1",
    "adds": [
      {
        "attributes": {
          ">begrep": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        },
        "geometry": {
          "spatialReference": {
            "wkid": 4326
          },
          "x": -117.1655,
          "y": 33.999,
          "z": 0
        }
      }
    ]
  },
  {
    "attachments": [
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-265178c2f43740c48f61039211384b91.png"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-61b79bffaa9b42418b9216f1857d784a.png"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-2a6cde7db667457bbd54c16da0e36a3a.png"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-25d4759015ac473180b476e82f331fee.png"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-ba53702f5a134e4d88c42e4c053cf5bb.png"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-3c817c976d444e9c8d590d7c2a476ec1.png"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-ef251b07f4d54248822b713b45327827.png"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-ad72c07d298640d3965b82bcfd6b9473.png"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-a922a3e2cb8440d79007b6dbe72f13a8.png"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-2b49c655c6e84c5a946b0388e6e44862.png"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-ec8fc42ec7cd4aa4ba04e960ffe5a15b.png"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-d95b4db098d4471389f2c1868ba97b7c.png"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-a8b2d65b414146d78fa598eb1ec52592.jpg"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-12349afa8cf94eda98efa21a046ef029.jpg"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-430f708a29254e4c82d3ef275736879c.jpg"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-00e01b4921b140bd89a20674fba007a2.jpg"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-fef84a93cbdc4d269cf84ec7c4db26bb.jpg"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-1304faf0cf1f4877b497a6a54b8d140d.jpg"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-c73edc689efb403ead1276c0402caba7.jpg"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-11be71e6a1f64e5ca8a512f76dfb108e.jpg"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-7775f2cfad8d4465a8b95221c16c58dc.jpg"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-eec8530d6f2a4a7a80370723e86d536d.jpg"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-89a4b5ec17fa443f86c1bd1a2abfa31a.jpg"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-cc0459cf951e4f059e02bb382c174fa6.jpg"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-3064de878ee04ebca9dba31a2fe06fc1.jpg"
        }
      ],
      [
        {
          "editMode": 0,
          "fieldName": "image_test",
          "fileName": "image_test-1f830dc3d9c248258a2ec4a9954e6214.jpg"
        }
      ]
    ],
    "id": "$begrep",
    "adds": [
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      },
      {
        "attributes": {
          "<Form_1": "{8504427c-1c5e-4f45-b5bd-e4fe677e10d9}"
        }
      }
    ]
  }
]

**Comment by jchaconas** [comment]
Unable to change the image name in the browser. This feature only works on a mobile device.

**Comment by fcxagerr** [comment]
I crashed the app with a tablet running Android 6.0.1 (Marshmallow), I was trying to fill out a survey with 20+ photos but it recovered the survey along with all 20 photos.

All subsequent tests worked fine with large files, special character names, and 20+ photo attachments. I noticed that attaching panorama photos in the new Apple .HEIC format type will trigger a Code 400 error.

**Comment by sbubka94** [comment]
Issue #75

**Comment by phil-wilson** [comment]
[Audio Example.xlsx](https://github.com/tedrick/Survey123-Testing/files/1374238/Audio.Example.xlsx)

**Comment by shortiejj** [comment]
Tested up to 15 photos and rename, - no problem.
Saved as draft and went back in to add more photos - unable to rename photos but can rename on newly added photo which can only be captured under 'repeats' - no problem. however, this means the remaining unused pre-designed photo capture was unused.
Otherwise it works without crashing.

**Comment by phil-wilson** [comment]
@shortiejj As discussed on Friday, editing of attachments is not currently supported, however this is a feature we are working on releasing in the future. Currently if you open a survey from the Sent box or Inbox which contains image attachments, the image questions will be greyed out and unable to be edited. New images however can be added in a repeat section by adding a new repeat record when editing.
