### ISSUE TITLE
CHALLENGE: Import a certificate in iOS/Android

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#47]
With the new version of Survey123, we're becoming more strict in accepting valid SSL certificates for logging into ArcGIS Enterprise.  This can be a challenge on mobile OS environments.  We want feedback on how difficult it is to import a certificate (like the Esri Root CA) in these platforms to inform a future technical support article for users.

Look at https://blog.httpwatch.com/2013/12/12/five-tips-for-using-self-signed-ssl-certificates-with-ios/ and https://www.thesslstore.com/blog/trust-manually-installed-root-certificates-in-ios/ and try to follow the steps

**Comment by tedrick** [comment]
Bethany

**Comment by JohnHasthorpe** [comment]
Closing this in favour of a documentation issue. Wont be tested in this remote holistic.
