### ISSUE TITLE
CHALLENGE: UWP version of Survey123

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#48]
**Requirements:** UWP version of the Survey123 Field App from Early Adopter community: https://earlyadopter.esri.com/project/home.html?cap=%7bE69EF91F-4574-4B98-882C-651F7B518EB7%7d 

**Overview**
Survey123 plans to support the Windows Store (Universal Windows Platform).  There are a few known issues with the camera and microphone with the current version- we'd like you to try it out and see if you find more.  

**Process**
Download the UWP version of the app to your windows device. Use it to test a range of surveys (completion and submission) and capture any feedback in comments below.

**Comment by tedrick** [comment]
Diego

**Comment by dgalvanmeza** [comment]
Guide for side-loading .appx bundles outside of the Windows Store. Use the PowerShell method if not running Windows 10 Anniversary Update. 

- https://goo.gl/kVYeDN

**Comment by menzelc** [comment]
Can't load appx. for Windows 8.1.  Followed instructions from https://www.howtogeek.com/129535/how-to-sideload-modern-apps-on-windows-8/.  Obtained developers license and used PowerShell as Administrator but still can't install. 
![image](https://user-images.githubusercontent.com/4838513/31400750-b8f5cb4e-adbe-11e7-90b0-960dd243a3ab.png)

**Comment by dgalvanmeza** [comment]
I think UWP didn't exist in Windows 8.1. There's a post about it here: https://goo.gl/wpzSRY.

**Comment by dgalvanmeza** [comment]
The "resource level" icon appears as a '?' in the UWP version of the app.

**Comment by edcookgis** [comment]
Using Windows 10 Laptop with UWP Field App installed, no issues with Camera or Mic.
