### ISSUE TITLE
CHALLENGE: Login with Single-Signon SAML (i.e., Okta internal) in Windows

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#49]
In order to support logging into a Portal with an Enterprise login that uses Single Signon, Survey123 has a different login path - see http://server.arcgis.com/en/server/latest/administer/windows/using-windows-active-directory-and-pki-to-secure-access-to-arcgis-server.htm .  Before 2.5, this wouldn't work properly with Windows - a second copy of Survey123/Survey123 Connect would be launched.  

Try the login process and let us know of any issues.

**Comment by tedrick** [comment]
Diego, Alex, Christian

**Comment by cwhitehe** [comment]
I was able to login with the Survey 123 Field application for Windows and IOS with no issues. I also tested our SAML single login on the Survey 123 Connect for ArcGIS without any issues.
