### ISSUE TITLE
CHALLENGE: Working with signatures

### ISSUE THREAD

**Issue by IsmaelInRedlands** [tedrick/Survey123-Testing#5]
**Context:** We introduced signatures quite some time ago. To learn more about them check our [Signatures! blog post](https://geonet.esri.com/groups/survey123/blog/2015/08/23/signatures). Now, we lately have broken a few  things so we want to make sure everything is now back to normal. 

**Challenge:** You will author a survey with a signature question in it, and do various tests in your mobile device as well as in the Survey123 website.

1) Say you work for the Police Department and you are tasked to create an arrest form.  Author and publish a survey using Survey123 Connect including

> - Date and time of the arrest (required and set by default to now)
> - Location (required)
> - Charges (required)
> - Photo (required) 
> - Signature of the arrested person (required)

The key question to test is obviously the signature, but we  want you to add at least all of the above.  Sorry we are so picky!

2) Once you have authored the survey, we will want you to exercise it in the field. That is, you are going to download the survey into a device and do at least 5 arrests.  Ask an Esri staff member for handcuffs and a baton. ;)

`When inserting the signatures, please draw something that would help you later identify if any portion of the signature has  been cropped. Do not do random signatures, write or draw something that  means something.`

3) Use the Data tab in the Survey123 website to ensure that all your arrest reports have proper signatures.

After all the above is achieved, or if at any point if you cannot proceed, please answer the questions below by adding comments to this issue.

'NOTE: If at any point in time during this challenge you get  stuck, please contact Esri staff so we can get you going.

**Questions** 

* Were you able to submit all the data correctly? If not, report the error message you got.

* Were you able to see all the signatures in the survey123 website?

* Was the user experience for capturing signatures in the phone/tablet friendly?

* What is the operating system and phone you used for capturing the data?

`NOTE: Copy and answer all questions above into your own comment below.  If you want to add other  type of info into your own comments that is fair too.`

**Comment by IsmaelInRedlands** [comment]
**Summary:** Tested signatures using the Arrest Form community sample in Connect. I was able to publish and exercise against ArcGIS Enterprise 10.5.1 with no problem. Issues regarding cropping of signatures in previous versions of the app are fixed.

* Were you able to submit all the data correctly? Yes

* Were you able to see all the signatures in the survey123 website? Yes

* Was the user experience for capturing signatures in the phone/tablet friendly? Yes

* What is the operating system and phone you used for capturing the data? iOS

**Comment by tedrick** [comment]
Kanchana

**Comment by colinlawr** [comment]
Experiencing crashing behavior when a signature field is filled out and you quickly attempt to submit the survey. This seems to be the same behavior we are seeing with the Draw image type functionality. 

Reproduced on Android, Windows and iOS.

**Comment by sbubka94** [comment]
Reproduced on iOS 10.3.3, not tested on iOS 11 beta

**Comment by JohnHasthorpe** [comment]
2.4 testing complete
