### ISSUE TITLE
Feedback: GeoSearch box in myUSNG app

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#50]
**Requirements:** MyUSNG app from Early Adopter community: https://earlyadopter.esri.com/project/home.html?cap=%7bE69EF91F-4574-4B98-882C-651F7B518EB7%7d 

**Overview**
We're working on a geosearch box for Survey123; we prototyped it with the MyUSNG app.  This enables full flexibility in terms of what you can enter. 

**Process**
Download and test the app by entering coordinates and addresses, limiting the the search extent by clicking the globe icon in the search bar and copying and pasting coordinates. Let us know what you think of the geosearch functionality and how this would support your workflows in Survey123.

iOS: https://itunes.apple.com/us/app/myusng/id1281298855?mt=8
Android: https://play.google.com/store/apps/details?id=com.esri.myusng&hl=en

**Comment by tedrick** [comment]
Alexis, Charmel

**Comment by ahandelman** [comment]
On the 1.0.47 version of the app (current download version from itunes app store) the search bar function only searches for USNG grid references. When trying to search for a location it gives the following error: "Invalid USNG grid reference".
![img_2647](https://user-images.githubusercontent.com/32681552/31399749-3aa158b0-ada2-11e7-938b-6b02b920a903.PNG)
![fullsizerender](https://user-images.githubusercontent.com/32681552/31399757-40978686-ada2-11e7-9ef3-3fca148b9f1c.jpg)

**Comment by ahandelman** [comment]
Using the windows version of the 1.0.56 app. I wish when searching and selecting an item, the default zoom level was a bit more zoomed in.  This seems a bit too zoomed out.
![image](https://user-images.githubusercontent.com/32681552/31400346-1f373476-ada4-11e7-8c8b-ec5675f6e3f3.png)

It would also be nice to see a zoom slider. Right now it only appears that you can zoom using the wheel on the mouse. I can't test how this will function on the ios version on the phone since it isn't available, but it might be cumbersome to zoom. Also if I was on a laptop without a mouse this wouldn't be easy or intuitive.

**Comment by ahandelman** [comment]
The icon in the search bar that switches between searching only the area in the map or searching outside that area is not intuitive. I would not have found that on my own or figured that out if I was not shown in the demo. There is no text when you hover over the icon that says what it is and the text in the search bar doesn't change to indicate whether you are searching within the map area or globally. 
![image](https://user-images.githubusercontent.com/32681552/31400578-eecab1ae-ada4-11e7-8de5-84f603b95cb8.png)
![image](https://user-images.githubusercontent.com/32681552/31400582-f72b336e-ada4-11e7-8291-7415a9eda82c.png)

**Comment by menzelc** [comment]
On Android Samsung Galaxy S7, when I drag to the various screens the indicator on the top of the app does not highlight the proper page.

The "About" is highlighted but I'm at the USNG page.
![image](https://user-images.githubusercontent.com/4838513/31401299-7ef4ad46-adc0-11e7-864b-d783faca0978.png)


"About" is highlighted in blue after I panned to the Map page.

![image](https://user-images.githubusercontent.com/4838513/31401360-aa10a782-adc0-11e7-8d59-c2bf47d2c758.png)

**Comment by menzelc** [comment]
Version: 1.0.56
Nice to limit the geocoding to US since we are looking at the USNG :)

type in 100 and see what you get.

![image](https://user-images.githubusercontent.com/4838513/31401639-85d8dd48-adc1-11e7-8003-54e1f337089c.png)

**Comment by menzelc** [comment]
v 1.0.56 Android
Testing copying USNG location from email to USNG app

Email:
![image](https://user-images.githubusercontent.com/4838513/31401837-166fabe8-adc2-11e7-9bad-9759c347212d.png)

Copy from email:
![image](https://user-images.githubusercontent.com/4838513/31401860-2ec41bc0-adc2-11e7-924e-10a983da7518.png)

Looks good when I paste into map:
![image](https://user-images.githubusercontent.com/4838513/31401904-51182108-adc2-11e7-9b4b-afa609894ed8.png)

It Works!
![image](https://user-images.githubusercontent.com/4838513/31401948-6e56dea8-adc2-11e7-94e4-ad6250a5196d.png)

**Comment by menzelc** [comment]
USA Topo Map did not display quickly when I moved to new location.

![image](https://user-images.githubusercontent.com/4838513/31402100-f02a6274-adc2-11e7-9d39-9cf70a06837a.png)

No Topo :(
![image](https://user-images.githubusercontent.com/4838513/31402112-fd6c0726-adc2-11e7-95fb-3fedb4a07454.png)

Had to go to another basemap and then back to Topo for it to appear.

Yes, Topo  :)
![image](https://user-images.githubusercontent.com/4838513/31402155-295304b6-adc3-11e7-83b8-c15de7bb32e1.png)

**Comment by menzelc** [comment]
v 1.0.56 on Android Samsung.
The red USNG label on the map is not easy to read on several of the basemaps.

Including USA Topo Map
![image](https://user-images.githubusercontent.com/4838513/31402284-8f970452-adc3-11e7-84b0-7e7bea4ad44c.png)
