### ISSUE TITLE
CHALLENGE: Creating Surveys with 10.6 ArcGIS Enterprise

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#51]
10.6 ArcGIS Enterprise will support hosted feature layer views, allowing for the fieldworker and stakeholder view to be created.  Try working with a 10.6 prerelease portal (we can provide a sample if interested) and create surveys on it using the Survey123 website (or share surveys published with Survey123 Connect for Analysis).  Let us know if anything goes wrong!

**Comment by tedrick** [comment]
Bethany, Christine

**Comment by bethanyw** [comment]
Feedback: The survey templates (Advanced, etc) should be updated so the fields named to not use caps and lowercase names. Since this is an issue with ArcGIS Data Store now, an idea would be to fix these templates so they work with Enterprise and AGOL equally.

**Comment by JohnHasthorpe** [comment]
Not testing in this holistic session - so closing for now
