### ISSUE TITLE
BUG : Compromised formatting of screenshots when viewing content in 'Discussions' tab within the side panel of Survey123 Connect 

### ISSUE THREAD

**Issue by BKArmstrong** [tedrick/Survey123-Testing#52]
**Application:**
![survey123connect_sidepanel_discussions](https://user-images.githubusercontent.com/6314443/31399596-b524d25c-ada1-11e7-9d8f-91c682c81d42.PNG)
 Survey123 Connect

**Device:** Desktop

**Operating System:** Windows 7 64bit

**Browser:** _For the website_

**Error Description:** 

**How to reproduce:**

**Have you tested with another survey?**

**Comment by tedrick** [comment]
Dupe of #55
