### ISSUE TITLE
Bug/Enhancement-- Survey123 Connect example templates should be updated to not use field names with capital letters

### ISSUE THREAD

**Issue by bethanyw** [tedrick/Survey123-Testing#53]
**Application:** Connect

**Device:** Survey123 Connect 2.5.16 on Windows

**Operating System:** Windows 7 enterprise

**Browser:** _For the website_

**Error Description:** 

"This survey cannot be published - The field name Example in Form_17 must be lower case for Portal"

**How to reproduce:**

1) Click "New Survey"
2) Use the "Advanced" template
3) The template here uses field names that begin with a capital letter. At Enterprise 10.5 +, ArcGIS Data Store needs lowercase field names. The templates should be updated to use all lowercase names for the templates and samples so they are compatible in both Enterprise and AGOL.

**Have you tested with another survey?** 

Yes

**Comment by JohnHasthorpe** [comment]
Advanced template updated
