### ISSUE TITLE
Bug- When navigating between photos in a repeat question, any photos that were renamed will revert back to the original file name

### ISSUE THREAD

**Issue by bethanyw** [tedrick/Survey123-Testing#54]
**Application:** Field App

**Device:** Windows

**Operating System:** Windows 7 Enterprise

**Browser:** _For the website_

**Error Description:** 

N/A

**How to reproduce:**

1) Create a new xlsx form that has a photo question within a repeat (sample attached)

2) Publish this as a new survey (I did this to Enterprise 10.6, but I do not this this is an issue with Enterprise)
3) Download the survey to the 2.5.16 field app
4) Add an image attachment and rename the file
5) Click the + icon to add another photo
6) Click the back arrow to navigate back to the first image attachment

*Bug: the image will be renamed back to the original name when navigating within the repeat

**Have you tested with another survey?** 

Yes

[supt0001541_repeatphoto_106.xlsx](https://github.com/tedrick/Survey123-Testing/files/1372766/supt0001541_repeatphoto_106.xlsx)

**Comment by JohnHasthorpe** [comment]
Not reproducible in Windows 10 - will investigate through: https://github.com/ArcGIS/arcgis-survey123/issues/524
