### ISSUE TITLE
Enhancement: Ability to filter out Living Atlas content when creating a survey using feature services from ArcGIS Enterprise

### ISSUE THREAD

**Issue by bethanyw** [tedrick/Survey123-Testing#56]
**Application:** Connect

**Device:** Windows

**Operating System:** Windows 7 enterprise

**Browser:** _For the website_

**Error Description:** N/A

**How to reproduce:** 

1) Configure Survey123 Connect to use Enterprise 10.6\
2) Click "+New Survey" > Feature Service
3) This will pull in all content from Living Atlas, which is cumbersome, and makes finding feature services created by actual portal users difficult

*Enhancement: Have a setting that can be used to filter out Living Atlas content

**Have you tested with another survey?** 

Yes

**Comment by tedrick** [comment]
Added to internal issue: https://devtopia.esri.com/Melbourne/Survey123/issues/1449
