### ISSUE TITLE
In Connect and Survey123, when refreshing one datetime field that has a now() as calculation, the other field set with a now() is refreshed as well

### ISSUE THREAD

**Issue by cdarti** [tedrick/Survey123-Testing#57]
**Application:** Connect, Survey123 Windows x86

**Device:** Laptop Dell (Esri issued)

**Operating System:** Windows 10 Enterprise

**Browser:** na

**Error Description:** 
In Connect and Survey123, when clicking refresh to refresh one field that has an associated now() calculation, another field with now() as calculation is refreshed at the same time.

**How to reproduce:**

- Create 2 fields of type datetime both using now() under calculation.
- Open in Connect (xls file attached)
- Wait until the current time changes.
- Click Refresh next to one of the time.
- The other time is refreshed as well.

Note: it happens all the time in Connect but every other time in Survey123

**Have you tested with another survey?** 
yes. tested starting  with a new advanced template and with a new water usage template.
[testrefresh.xlsx](https://github.com/tedrick/Survey123-Testing/files/1372837/testrefresh.xlsx)

**Comment by JohnHasthorpe** [comment]
Internal issue: https://devtopia.esri.com/Melbourne/Survey123/issues/1892
