### ISSUE TITLE
Refresh button is not visible by default in datatime field with calculation

### ISSUE THREAD

**Issue by cdarti** [tedrick/Survey123-Testing#58]
**Application:**Field App

**Device:** Windows Dell Laptop, IPhone 5

**Operating System:**Windows 10 Enterprise, iOS 10.3.8

**Browser:** NA

**Error Description:Refresh button is not available by default on a calculated field. I need to click the field first to view the Refresh field.

**How to reproduce:**
- Open the survey and wait until the current time changes.
[testrefresh.xlsx](https://github.com/tedrick/Survey123-Testing/files/1372867/testrefresh.xlsx)
-Click one of the date fields. The Refresh button is now visible and may be clicked.

**Have you tested with another survey?** 
Yes

**Comment by JohnHasthorpe** [comment]
Internal Issue: https://devtopia.esri.com/Melbourne/Survey123/issues/1921
