### ISSUE TITLE
Refresh button does not refresh the datetime to now() 

### ISSUE THREAD

**Issue by cdarti** [tedrick/Survey123-Testing#59]
**Application:** Field App

**Device:** iPhone 5

**Operating System:** iOS 10.3.3

**Browser:** NA

**Error Description:** Refresh button does not work anymore after updating the times via the calendar. Worked ok initially but after working with the fields and refreshing/editing the Refresh stopped working.

**How to reproduce:**
Set 2 datetime fields with now() under calculation
Refresh fields, edit times via  calendars until Refresh stops responding.

**Have you tested with another survey?** 
Yes
[testfunction.xlsx](https://github.com/tedrick/Survey123-Testing/files/1372897/testfunction.xlsx)

**Comment by JohnHasthorpe** [comment]
Was not able to replicate this on IPhone 7 IOS 11 or 5 and 9.3.1. Will keep this open for the next round of holistic testing

**Comment by shortiejj** [comment]
Tested and working on MacAir OS X El Capitan v10.11.6 and iPhone6
