### ISSUE TITLE
CHALLENGE: Annotating Photos

### ISSUE THREAD

**Issue by IsmaelInRedlands** [tedrick/Survey123-Testing#6]
**Requirements:** Survey123 Field App and Connect from Early Adopter community: https://earlyadopter.esri.com/project/home.html?cap=%7bE69EF91F-4574-4B98-882C-651F7B518EB7%7d or from test-flight for IOS (you will need to download the test flight app from the store and receive an invite from Esri).

-----------------------------------------------

**Context:** With the 2.4 release we are introducing a new  appearance called 'draw'. This appearance is  similar to the 'signature' appearance. Like in the 'signature' appearance you are provided  with a canvas where you can easily scribble or  do some handwriting.  Now: the 'draw' appearance gives you more  room to do your drawings. You can also use the 'draw' appearance to annotate on images!

`As with any of the challenges for this holistic, we want you to take this VERY seriously. Think people will be using this 'draw' functionality all day long.... they will not do just 5 tree surveys... they will do tree surveys all day long. Make sure  the widget works well, feels well and does its job reliably.  We left our ego at home: if it is not good for you, let  us know!`

**Challenge:** You will author a survey with a draw question in it, and do various tests in your mobile device as well as in the Survey123 website.

1) Say you work for the City of Redlands and you need to put together a Tree Survey for the Public Works department. They want a survey where  they can map every Tree that needs trimming to avoid touching a power line.

> - Date of inspection (required and set by default to now)
> - Location of the tree (required)
> - Notes (required)
> - Photo (required) 

We will use the Photo question to capture  a photo of the tree along with an annotation that shows where the tree is touching the power line.  

2) Once you have authored the survey, we will want you to exercise it in the field. That is, you are going to download the survey into a device and do at least 5 tree surveys.  

3) Use the Data tab in the Survey123 website to ensure that all your tree surveys look good. Pay particular  attention to cropped images and rotation issues.

After all the above is achieved, or if at any point if you cannot proceed, please answer the questions below by adding comments to this issue.

'NOTE: If at any point in time during this challenge you get  stuck, please contact Esri staff so we can get you going.

**Questions** 

* Was the documentation good  enough for you to create the survey with the audio question? Describe any issues you may have encountered.

* Were you able to submit all the data correctly? If not, report the error message you got.

* Were you able to see all the tree surveys in the survey123 website?

* Was the user experience for annotating  photos in the phone/tablet friendly?

* What is the operating system and phone you used for capturing the data?

`NOTE: Copy and answer all questions above into your own comment below.  If you want to add other  type of info into your own comments that is fair too.`

**Comment by tedrick** [comment]
Justin, Colin, Matt

**Comment by sbubka94** [comment]
1. You cannot use an existing photo to draw on photos already stored on mobile device, you can only snap a new pic - Being able to pick photo from camera roll would be useful
2. You cannot use the draw function on a photo on the Windows field app; camera option would not make sense but there is no option to navigate to existing photos

**Comment by colinlawr** [comment]
To add on to Sarah's comments:

General limitation of draw functionality on the Windows Field app. There is no smart access drawing as there is on mobile version. There is no undo button. There is no ability to modify line style or thickness. 

Reproducing consistent crashing of the desktop field app when submitting a survey. The survey is set up as outlined in the challenge above. I have captured a log file. 

Colin

**Comment by mrwoodlief** [comment]
Once photo was taken, I didn't see an option to save my photo. When I tapped back, the photo did not appear and i could not submit response. Using iOS 10.3.3

**Comment by zpelletier** [comment]
Not able to use the draw function in the iOS 10.3.3, I submitted surveys, and then tried to go back into to edit them, thinking I would get the markup function, the pencil is there to edit but doesn't work.

**Comment by colinlawr** [comment]
The "clear sketch" button clears the annotation sketched on the photo but also removes the current photo as well. In this case a live photo was taken which would then be lost. If this is by design, the wording "clear sketch" is misleading.

**Comment by phil-wilson** [comment]
[Draw and Annotate Example.xlsx](https://github.com/tedrick/Survey123-Testing/files/1374243/Draw.and.Annotate.Example.xlsx)

**Comment by JohnHasthorpe** [comment]
Siew

**Comment by shortiejj** [comment]
Drawing horizontal and vertical lines, with smart sketching off, text on, do not draw the line but only allows to enter text input

**Comment by shortiejj** [comment]
Once annotations and drawings saved as draft, correction/modification to the annotations and drawings can no longer be done. Cases where this may be relevant would be when one realises mistakes drawn or wrongly annotated at a later date and needed to made correction before submitting a final

**Comment by deeplakhanpal** [comment]
Tested on IOS, able to attached image and annotate the image with text. All the data submitted successfully.
