### ISSUE TITLE
Survey crashes consistently when switching a particular question from 'Yes' to 'No'

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#61]
**Application:** Field App 

**Device:** iPhone 7 Plus

**Operating System:** iOS 11

**Error Description:** Survey will consistently crash after filling in many answers, then going back to the top of the survey and switching one of the responses

**How to reproduce:** The survey is the Homeless Count survey from the Community section of S123 Connect. See video: http://www.screencast.com/t/fMEfaMZXfAs
Switching 'Are you able to survey this person' from Yes to No causes the crash

>Log file attached
[Survey123forArcGISBeta-20171010-105228.log](https://github.com/tedrick/Survey123-Testing/files/1372908/Survey123forArcGISBeta-20171010-105228.log)

**Have you tested with another survey?** Not yet -

**Comment by JohnHasthorpe** [comment]
Was not able to replicate this on my IPhone 7 IOS 11

**Comment by JohnHasthorpe** [comment]
Further investigation required: https://github.com/ArcGIS/arcgis-survey123/issues/524#issuecomment-336035045
