### ISSUE TITLE
App Fails to Submit Attachments Anonynously when Queries are disabled in Feature Service 

### ISSUE THREAD

**Issue by IsmaelInRedlands** [tedrick/Survey123-Testing#64]
**Application:** Field App 

**Device:** This issue is agnostic of platform

**Operating System:** OS agnostic. 

**Error Description:**  Error 400

**How to reproduce:**
1) Publish a Survey from Connect including a signature question.
2) In ArcGIS.com, change the security settings of the feature service so queries are disabled
3) In Survey123 website share with everyone
4) Submit from the app **while logged out**. You will get an error 400

[Metro IPM PAR.xlsx](https://github.com/tedrick/Survey123-Testing/files/1372945/Metro.IPM.PAR.xlsx)
[IPM_Sites.zip](https://github.com/tedrick/Survey123-Testing/files/1372946/IPM_Sites.zip)

**Stakeholder**
* Reported by Tom Rippetoe   oregonmetro.gov   Reproduced  with 2.3, 2.4 and and 2.5 on Windows, Android and iOS

**Comment by IsmaelInRedlands** [comment]
@tedrick @JohnHasthorpe

**Comment by JohnHasthorpe** [comment]
@IsmaelInRedlands I can't replicate this:

Survey
https://survey123.arcgis.com/surveys/4729c18276694cd5801361ba6abcc28d/collaborate
Service
https://survey123.maps.arcgis.com/home/item.html?id=ec75fc788abd4a03b957ab4b9610a8dc

Am I missing something?

**Comment by JohnHasthorpe** [comment]
Interestingly - I could replicate the error, but only on re-submitting from the sentbox. I could submit new features without issue.

**Comment by IsmaelInRedlands** [comment]
@JohnHasthorpe 
My bad, the description was not good  enough.
You need to add a signature question to the form. I changed the original repro steps.
I can reproduce the problem ONLY when a signature question is added.

**Comment by IsmaelInRedlands** [comment]
@JohnHasthorpe  @tedrick 
Here is video showing exact steps to repro.
https://esri.box.com/s/cvzupdpu34w1frnyl1nz98okvpqgsw8o

**Comment by JohnHasthorpe** [comment]
Internal issue: https://devtopia.esri.com/Melbourne/Survey123/issues/1929
