### ISSUE TITLE
Enhancement: Provide dynamic filtering of search results when searching for surveys to Download on a Samsung S5

### ISSUE THREAD

**Issue by BKArmstrong** [tedrick/Survey123-Testing#65]
**Application:** Field App

**Device:** Samsung Galaxy S5

**Operating System:** Android 6.0.1

**How to reproduce:** Open Survey123 Field App (v 2.5) > Sign In > Download Surveys > start entering search values (expect it to start filtering immediately)  

after selecting 'Done' on the Android keyboard, it will filter, and then will begin working dynamically in subsequent searches

**Have you tested with another survey?** yes

**Comment by JohnHasthorpe** [comment]
A known issue: https://devtopia.esri.com/Melbourne/Survey123/issues/1443
