### ISSUE TITLE
Open in Map Viewer from the Data tab will not load in Chrome

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#67]
**Application:** Website 

**Browser:** Chrome 61.0.3163.100

**Error Description:** When choosing 'Open in Map Viewer' from the Data tab, the map viewer loads endlessly with the three green bars in Google Chrome. 
In Internet Explorer, the map viewer launches successfully but in a separate tab, whereas Chrome opens a sub-window to display the map.
Is this expected?

**Have you tested with another survey?** Tested  with 3 surveys (2 from Connect, 1 from Webform)

**Comment by BKArmstrong** [comment]
Also experiencing same behavior

**Comment by tedrick** [comment]
Internal Issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/1995
