### ISSUE TITLE
Link to Survey created using ArcGIS Enterprise 10.6 does not work

### ISSUE THREAD

**Issue by cdarti** [tedrick/Survey123-Testing#68]
**Application:** Website

**Device:** Laptop Dell

**Operating System:**Windows 10 Enterprise

**Browser:** Edge, Chrome

**Error Description:** 
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - https://survey123dev.arcgis.com/share/93292d4e9eba4d0089895743c310860e?portalUrl=https://base.webgistesting.net/portal

**How to reproduce:**
Create and share a new survey using
 https://survey123dev.arcgis.com/?portalUrl=https://base.webgistesting.net/portal

Copy the survey link and paste it in browser. The window does not open and the 3 green bars icon keep changing on the web page as if trying to load.

**Have you tested with another survey?**

**Comment by zhif7782** [comment]
Hi @cdarti , thanks for the feedback. As far as I know, there is still ongoing work for 10.6 Portal, to support the feature service view capability. We are also in progress to make the website to work against Portal 10.6. 

Will let you know once we've finished the development work so you can help test again.
