### ISSUE TITLE
Should have the option to hide geonet contents in Connect

### ISSUE THREAD

**Issue by cdarti** [tedrick/Survey123-Testing#69]
**Application:** Connect

**Device:** Dell Laptop

**Operating System: Windows Enterprise 10.5

**Browser:** NA

**Error Description:** 
It would be nice to have the option to turn off or hide GeoNet. It can feel a little crowded and the focus should be on the application not the online community.

**How to reproduce:**
NA

**Have you tested with another survey?** 
NA

**Comment by JohnHasthorpe** [comment]
Internal issue: https://devtopia.esri.com/Melbourne/Survey123/issues/1911
