### ISSUE TITLE
CHALLENGE: Verifications on images

### ISSUE THREAD

**Issue by IsmaelInRedlands** [tedrick/Survey123-Testing#7]
**Context:** By going through this challenge you will help us verify a few fixes we  have added to address issues working with photos. This may not be very sexy, but your help validating the fixes will be tremendous.

**Challenge:** 

* **Images and Favorites:** Read this issue and try with 2.4.  We have validated that 2.4 fixes the  problem in iOS and Android. Can you prove us wrong? https://geonet.esri.com/message/668520-bug-issue-with-favorites

* **Images and Repeats:** This is what people told us was wrong with Survey123 before 2.4... We believe this should all be fixed in 2.4. Can you prove  us wrong?
    * if you capture multiple photos in a repeat and leave the default picture name - no issue
    * if you change the name of the picture - it changes for all images, AND if you return back to a previous captured photo - the photo is gone.

* **Data loss after crash:** In the unlikely event  that the Survey123 app crashes, with 2.4 you will no longer lose data because the app will recover it.  We have  seen reports from users saying that sometimes the camera crashed the entire Survey123 app, so if you happen to see a crash please add a comment below indicating that you were able to crash the app and let us know if the new recovery workflow worked for you.

* **Big uploads:** We have changed the way big files are uploaded.  This will not be obvious to you but we  believe this  will improve  our ability to upload  larger  files  reliably. Please do the following test:

1. In a survey with an image question, manipulate the image settings in Connect so the images are uploaded 'unrestricted'. Add 5 photo questions into your survey. Publish your survey

![untitled](https://user-images.githubusercontent.com/5918689/29694095-71edee4c-88ee-11e7-94ad-662577e882f3.png)

2. Submit data uploading large images. For  example, upload panorama photos from your photo  library.

Report when the app fails to upload the images. For example, tell us if you were  able to submit one, or two or the whole  5 photos.  To validate that the photos were in fact  uploaded, please make sure you check in the Survey123 website using the Data tab that in fact  the images  were uploaded.

`NOTE: As you report your findings, please report the type of  device  you used to submit your data and if you submitted  data over the WIFI or not.`

**Comment by tedrick** [comment]
Alex, Sarah

**Comment by zpelletier** [comment]
I changed changed to unrestricted, only had 1 image in survey (panaromic of a volcano crater) and it crashed while trying to submit on iOS 10.3.3, received Send Error code: 413, continued to try to send again and Survey123 app crashes continously

**Comment by fcxagerr** [comment]
I was able to complete the steps in Images and Repeats without error. Even after an app crash with 5+ pictures (inside and outside of repeats) all images are recovered. Images also seem unaffected by Favorites.

Big images:
After setting image limits to 'unrestricted' I successfully added images over 50mb.

**Comment by tedrick** [comment]
@zpelletier - can you forward the image that crashes?  Also, how much free space is on the phone

**Comment by zpelletier** [comment]
![ipad storage](https://user-images.githubusercontent.com/27016199/29876303-f99727a6-8d61-11e7-9702-ef16a55b6c5b.png)
![survey123 not sent photo](https://user-images.githubusercontent.com/27016199/29876248-da1d0ab2-8d61-11e7-85c6-349d7094dbbd.png)

**Comment by tedrick** [comment]
Thanks @zpelletier - this isn't a crash per se (crashes are when Survey123 app stops and you're returned to the app icons page).

413 is 'request too large' - can you post the image you're trying to submit to this issue or at least provide it's size?

**Comment by zpelletier** [comment]
The image is 17.4 mb. It’s a panoramic done on a iphone

**Comment by tedrick** [comment]
Can you try to add it as an attachment via the Map Viewer and see if that is successful?

**Comment by zpelletier** [comment]
Not sure what you mean? In AGOL?

**Comment by tedrick** [comment]
Yes, in the AGOL Map Viewer

james

**Comment by zpelletier** [comment]
Received error, file size too large, exceeded upload size, check server max. size

**Comment by JohnHasthorpe** [comment]
2.4 testing complete - closing
