### ISSUE TITLE
Bug - An error pops up when accessing the Analyze tab, if the survey contains repeats

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#70]
**Application:** Website 

**Browser:** Chrome and IE

**Error Description:** If the survey contains repeats,an error is thrown on the Analyze tab: "Cannot get necessary XForms file for the survey."
![image](https://user-images.githubusercontent.com/22916127/31409806-f5d69aae-adc1-11e7-9c47-bde4dabcfdb5.png)

I also saw this error message on the Collaborate tab, but only one time. Cannot reproduce that

**Have you tested with another survey?** yes

**Comment by BKArmstrong** [comment]
encountering same behavior when attempting to access the Analyze tab in Chrome

**Comment by tedrick** [comment]
Internal Issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/1996
