### ISSUE TITLE
Bug - The sample report template link is broken, redirects to "site can't be reached"

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#71]
**Application:** Website 

**Browser:** Chrome and IE

**Error Description:** The link for the Sample Report Template redirects to a site that can't be reached
![image](https://user-images.githubusercontent.com/22916127/31411321-1b69bc3e-adc6-11e7-8113-d18562b6112c.png)

![image](https://user-images.githubusercontent.com/22916127/31411313-1382f616-adc6-11e7-8a33-cdee5a21e1fc.png)

**Comment by zhif7782** [comment]
@sbubka94 thanks for the feedback, will let you know once it's fixed.

**Comment by tedrick** [comment]
Internal Issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/1995
