### ISSUE TITLE
Bug - The Sample Report fails to populate the information

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#72]
**Application:**  Website

**Browser:** Chrome and IE

**Error Description:** Another issue has been logged stating that the link to the sample report does not work, so I grabbed the sample report from the released version of the website. The report fails to populate any of the values in the form. I got inconsistent results for the Submitted By and Submitted Time questions; sometimes the values would appear and other times not. But the Date of Report, Notes, Location, and Photos always fail to show up on the template

**How to reproduce:** Sample form + output attached

[Pothole Hazard Report_sampleTemplate.docx](https://github.com/tedrick/Survey123-Testing/files/1373471/Pothole.Hazard.Report_sampleTemplate.docx)
 
[Pothole Hazard Report_20171010142344.docx](https://github.com/tedrick/Survey123-Testing/files/1373492/Pothole.Hazard.Report_20171010142344.docx)

*Note that the Sample Report was grabbed from survey123.arcgis.com but this test was completed at survey123dev.arcgis.com

**Comment by zhif7782** [comment]
@sbubka94 , thanks for the feedback, will let you know once it's fixed.

**Comment by tedrick** [comment]
Internal Issue: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/1995

**Comment by yuezhaoBJ** [comment]
@sbubka94, thanks for your feedback and could you please attach the survey excel file? I think with that we can locate the problem much easier.

**Comment by sbubka94** [comment]
@yuezhaoBJ 

Sure thing - This is the Pothole Hazard Report template from the Community section of S123 Connect

[Pothole.xlsx](https://github.com/tedrick/Survey123-Testing/files/1388241/Pothole.xlsx)

**Comment by yuezhaoBJ** [comment]
@sbubka94 Thanks again for your help, now it can work as expect. You can try it later.
![image](https://user-images.githubusercontent.com/20676384/31648872-96c7bc06-b342-11e7-997c-7671b441f253.png)
