### ISSUE TITLE
Enhancement - Capability to show hidden fields in analyze tab

### ISSUE THREAD

**Issue by ahandelman** [tedrick/Survey123-Testing#73]
It would be nice to have the capability to see and analyze hidden fields in the analyze tab. Full control over which fields are analyzed would be even better. Currently hidden fields can only be seen in the attribute table in the data tab (but do not appear in the Show Individual Responses window)

**Comment by zhif7782** [comment]
Hi @ahandelman thanks for the feedback, added to our backlog in dev repo, will let you know once it's fixed.
