### ISSUE TITLE
Bug - Missing photo on Windows Field App

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#75]
**Application:** Field App 

**Device:** Windows

**Operating System:** Win 7

**Error Description:** The first time you try to insert an image, it will appear with the image name but the photo itself will not appear
![image](https://user-images.githubusercontent.com/22916127/31413129-be9d0ba8-adcc-11e7-8233-4b0577cc163c.png)

If you delete the photo and re-add, the problem does not occur again. Only the first time you try to add a photo, it will not appear. And this photo does not make it successfully to the service.

If you have a repeat, the repeated image will work. When you go back to view the repeat 1, it appears like this:

![image](https://user-images.githubusercontent.com/22916127/31413238-3119acf4-adcd-11e7-81e4-c9ad125d6f39.png)

**Comment by JohnHasthorpe** [comment]
Not reproducible in Windows 10 - will investigate through https://github.com/ArcGIS/arcgis-survey123/issues/524
