### ISSUE TITLE
Align right for labels

### ISSUE THREAD

**Issue by shortiejj** [tedrick/Survey123-Testing#76]
Unable to align right for labels. Centre and align left (default) works perfectly however.

**Comment by phil-wilson** [comment]
@shortiejj Can you provide some more details on this, and the user case where the right align for labels would be required. Do you have an example survey to demonstrate the requirement?

We do already support this functionality for languages that require right to left reading, however this is applied when your device is set to the language automatically.

**Comment by shortiejj** [comment]
Hi Phillip,

Can I get back to you end of this week? I have a number of things due at work and exam this week!
Thank you

Kind Regards

Siew Wei Goh

**Comment by shortiejj** [comment]
Hi Phillip,
Apology for the delay...
I have in mind to use right align for my "References", such as in my forms, I will have several groups where each are referred to specific rules. The idea to keep these "rules" to the right as I don't want them to be too much in the face and a little out of the way because it is something that the officer on the job would be very familiar with.
Will it be difficult to apply the same functionality you have already done for languages to English as well?
Thanks
SW

**Comment by phil-wilson** [comment]
Hi Siew,

Thanks for the feedback, I have logged a new feature enhancement in our system for this issue and added your comments to it.

Regards,
Phil.
