### ISSUE TITLE
FEEDBACK: New webform (2.6)

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#78]
Please leave general feedback for the new webform here.  If you have a specific bug or issue, please create a new issue for it.

**Comment by tedrick** [comment]
Colin,
Alison, Justin, Britney, Frank, Alison Walker

**Comment by sanderson2146** [comment]
![image](https://user-images.githubusercontent.com/29313687/35165682-210f289e-fd04-11e7-9a3d-db1851e41a7e.png)

**Comment by sanderson2146** [comment]
Form loads with language selector on English and form in Arabic, cannot change from Arabic to English
![image](https://user-images.githubusercontent.com/29313687/35165806-84e03c5a-fd04-11e7-99dd-def0d0c080bc.png)

**Comment by sanderson2146** [comment]
Cannot expand or collapse groups

**Comment by sanderson2146** [comment]
![image](https://user-images.githubusercontent.com/29313687/35166377-915324a0-fd06-11e7-9f2b-8c422020b9da.png)

**Comment by gibbonsbr** [comment]
Some surveys cannot be opened from the website. When trying to access these surveys from the website, I get an error that the survey does not exist or is inaccessible. The survey works as expected from the field app. It seems that this mostly happens with surveys that used a submission url when published from Survey123 Connect or that may have had the submission url changed after the initial publication.

**Comment by gibbonsbr** [comment]
Received the error: 
**Error: Initialing Form...** when trying to load a form that used nested conditional statements in a calculation.

**Comment by sbubka94** [comment]
When a survey is created from Web, there is no option to change basemaps for geopoint questions in the Web Browser

![image](https://user-images.githubusercontent.com/22916127/35168337-6eb05bbe-fd0d-11e7-8184-df44866a100b.png)

**Comment by sbubka94** [comment]
Just a suggestion...

If you make changes to your survey, but DO NOT click save, then publish, your form will in fact publish with those "unsaved" changes. It could be beneficial to have a quick loading bar that says "Saving..." or perhaps a note that says "All changes will be saved at time of publishing"...just in case the user is under the impression that their unsaved changes will not be published. I did not expect that unsaved changes would publish. It's a great security measure, but I can see it causing confusion.

**Comment by sanderson2146** [comment]
Calculating a geopoint doesn't appear to be working with this calculation: if(selected(${re_type},'indirect_public_information'), once(pulldata('pulldataadmin','latitude','name',${community}) + " " + pulldata('pulldataadmin','longitude','name',${community})), "")

**Comment by sanderson2146** [comment]
When change the date of a date/time question with a default of now then click the refresh button it clears out the field and I get the following message
![image](https://user-images.githubusercontent.com/29313687/35173545-a82f4ac2-fd20-11e7-8324-7cb9c93289fe.png)

**Comment by sanderson2146** [comment]
Pull data from a geopoint into fields doesn't work
![image](https://user-images.githubusercontent.com/29313687/35173917-14aa074a-fd22-11e7-8824-a38d087f9e4e.png)

**Comment by sanderson2146** [comment]
The background color appears to be defaulting to the toolbar background color but the green accents are still present creating an unfortunate color combination. Is there any way to change this?
![image](https://user-images.githubusercontent.com/29313687/35174145-1a10e05e-fd23-11e7-9dd2-207a4e091717.png)

**Comment by jfangit** [comment]
Opened an existing survey form in the new web form and created a new survey from the new website. I really like the new design. the look and feel of the new web form is much nicer.

**Comment by rosamondecook** [comment]
Some users prefer to navigate through a data entry form using the tab key. However, the tabbing sequence seems out of order and certain objects like the label on the GIS map have tab set on. The new boxes around the multiple choice items are nice. Can you cause them to highlight when you navigate to them using the tab key so it is easier to see where you are in the form?

**Comment by rosamondecook** [comment]
Personally, I prefer the GPS Location map zoom in to an entered location, like it does in the previous version. I do like the ability to select background maps.

**Comment by sbubka94** [comment]
If you design a survey in Connect with Date questions set to either "Year" or "Month-Year" the Web Form does not display just the Year/Month-Year, it also displays a specific date in the month or year

![image](https://user-images.githubusercontent.com/22916127/35176724-aac5a614-fd2f-11e7-99b3-bf43a0cb462a.png)

**Comment by colinlawr** [comment]
Sorry I guess this never posted...

It is great to see consistency between the web from coming from connect and from the web. I found a few issues with the web form:

-The ability to change basemap in the web form in a survey created in the web designer is not there.
-Time questions are now in 24-hr time format and I didnt find a way to configure this
-No button to quick select today's date or time - published from connect
-Map view does not zoom to current location as in old web form (only pans) - published from connect; this functionality only exists when published from web and opened in old web form
-Map view gps accuracy is missing
