### ISSUE TITLE
CHALLENGE: Barcode Scanning (Android Specific)

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#8]
**Context:** In version 2.4 of Survey123, we've enhanced the barcode scanning performance, especially in Android. Previously, barcode scanning would crash certain Android devices

**Challenge:** Attempt to scan a variety of barcodes.  The barcode types we support are listed in the (http://doc.arcgis.com/en/survey123/desktop/create-surveys/faqcreatesurveys.htm#anchor14)[Frequently Asked Questions].  To help generate barcodes, here are a few resources:
- https://www.scandit.com/barcode-generator/
- http://www.barcode-generator.org

Create a survey with multiple barcode fields.  Try scanning the codes multiple times.  Please leave notes below on the responsiveness and conditions that cause crashes, along with device information

**Comment by tedrick** [comment]
Christian, Bethany

**Comment by JohnHasthorpe** [comment]
2.4 testing complete
