### ISSUE TITLE
FEEDBACK: Android Photo Gallery

### ISSUE THREAD

**Issue by tedrick** [tedrick/Survey123-Testing#82]
In 2.6, we've introduced a new photo gallery for Android devices.  Please test it out on your phone and let us know if it works properly (we had to go through a number of tweaks to access photos across all of our test devices).  Also provide any other feedback on the interface or capability for us to look into enhancing in the future.

**Comment by tedrick** [comment]
Colin, Britney, Alex, Bill,

**Comment by colinlawr** [comment]
This new functionality looks good, I am glad it was introduced.

I was able to reproduce crashing behavior with multiple surveys when sending a survey with an attachment selected from the gallery. The first survey response will send successfully. But when revisiting the form to collect another survey then attaching a photo again and sending the survey the application crashes "Survey123 has stopped". You can restart the app and successfully send the survey from the outbox folder. 

Tested with samsung galaxy s7 edge running android 7.0

**Comment by tedrick** [comment]
Filed issue for @colinlawr 's behavior - https://devtopia.esri.com/Melbourne/Survey123/issues/2125

**Comment by colinlawr** [comment]
[Holistic_phototest3.xlsx](https://github.com/tedrick/Survey123-Testing/files/1653963/Holistic_phototest3.xlsx)

Here is a simple survey I can use to reproduce on my device. Workflow is:

- Publish attached survey
- Download to Android device
- Open survey -> attach photo -> send survey. Survey should send successfully
- Select Collect to send another survey -> attach another photo -> send survey -> app will crash

samsung galaxy s7 edge running android 7.0
photos stored on SD card
838 photos stored on SD card

*Sidenote: the sorting seems to be a little wonky in the gallery. The first ~20 photos appear to be in the correct order by date, but after that it seems to jump around. This might have to do with the photos being stored on an SD, or the way the gallery app groups into albums. As you mentioned, this is probably hard to track down with all of the different android phones out there.

**Comment by tedrick** [comment]
@colinlawr - in researching the android photo gallery crashing, it looks like it was being caused by an in-development 2.7 feature (inadvertently introduced into testing when the test version of Survey123 was updated).  Can you please retry with the released (Google Play store) version of Survey123 2.6?

**Comment by colinlawr** [comment]
@tedrick 

Tested and couldn't reproduce crashing anymore!
