### ISSUE TITLE
FEEDBACK: Report Template Enhancements

### ISSUE THREAD

**Issue by BrandonArmstrong** [tedrick/Survey123-Testing#83]
Please leave general feedback for the enhancements made to the web report templates here.  If you have a specific bug or issue, please create a new issue for it.

**Comment by tedrick** [comment]
Sarah, Christnne, Diego, Steve, Isiah, Christine, Justin, Bill W.

**Comment by sbubka94** [comment]
Enhancement suggestion for Custom Report Templates:

In the default Individual Response, I can print out the graphic with the stars for my rating question

![image](https://user-images.githubusercontent.com/22916127/35166088-81766e6c-fd05-11e7-9957-45bc05b75b38.png)

If I create a Custom Report and specify this field, I do not get the nice star graphic, I just get a number. It would be nice to be able to populate the graphic in the custom report

![image](https://user-images.githubusercontent.com/22916127/35166124-9eb51ea6-fd05-11e7-9f08-5e713846ec83.png)

**Comment by slawdis** [comment]
When generating a report from a template, it creates a Word Document (docx). It would be nice to have the option to use a PDF document instead.

**Comment by tedrick** [comment]
Filed enhancement for rating question - https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/2169

Added comments on PF support - https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/1872

**Comment by oopsliu** [comment]
@slawdis The option of printing the [Feature Report in PDF](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={5a8e51ed-4a87-43fe-a67d-2b7829af130f}&artid={335A0766-D00A-4465-83C9-8982B546091B}) is available now on https://survey123beta.arcgis.com, along with other[ new beta features for the next release.](https://earlyadopter.esri.com/project/article/item.html?cap=e69ef91f45744b98882c651f7b518eb7&arttypeid={4d0c881a-e4c4-4530-846f-512df374efc3}&artid={9E09462F-DFEB-405A-A334-5F1A232AE093}) We would love to have you have a test and share any feedback or issues you may encounter in the [Survey123 Beta Website Feedback forum](https://earlyadopter.esri.com/project/forum/topic.html?cap=e69ef91f45744b98882c651f7b518eb7&forid={F93A6A79-F627-4727-8868-FC5E73406706}) .
