### ISSUE TITLE
Date/Time Formatting Cutting Off Number

### ISSUE THREAD

**Issue by sanderson2146** [tedrick/Survey123-Testing#84]
**Application:** Field App

**Device:** Windows

**Operating System:** Windows 10

**How to reproduce:** Try to change the time to a time with 4 numbers on the default app size in windows.

![image](https://user-images.githubusercontent.com/29313687/35164900-16fccd0a-fd01-11e7-8114-8ac63d065256.png)

**Comment by tedrick** [comment]
Filed issue: https://devtopia.esri.com/Melbourne/Survey123/issues/2126
