### ISSUE TITLE
Survey123 closes when submitting an area mesured using Spike

### ISSUE THREAD

**Issue by cdarti** [tedrick/Survey123-Testing#85]
**Application:** Field App

**Device:** iPhone 5

**Operating System:** iOS 10.3.3

**Browser:** NA

**Error Description: I am using the default Spike sample survey. When I open a new survey then uses Spike to measure an area,  after I click Save in 2 cases instead of getting back to the Survey I got the opening screen for Survey123 and then the application closed. When reopening Survey123 I was asked whether to use the recovered survey. I said yes and it opened correctly. It worked correctly the 3rd time.
Tried it 6 more times and failed each time. Note that the recovered data does not include the area elements.

**How to reproduce:**
see  above
**Have you tested with another survey?** No

**Comment by tedrick** [comment]
Will attempt to replicate
