### ISSUE TITLE
Sign In dialog appears for geopoint after editing survey in website

### ISSUE THREAD

**Issue by billwie** [tedrick/Survey123-Testing#87]
**Application:** survey123qa.arcgis.com

**Device:** Windows PC

**Operating System:** Windows 10

**Browser:** Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Error Description:** A survey created with survey123.arcgis.com with a geopoint was edited by survey123qa.arcgis.com to add a comment field and two image fields. After republishing when attempting to enter a survey with the survey link the geopoint did not automatically show the map and when it was clicked a sign in dialog appeared (attached)

**How to reproduce:** see above. We are using survey123qa.arcgis.com with our 10.5.1 portal with SAML authentication.

**Have you tested with another survey?** working on testing with another user, same survey then another survey.

**Comment by billwie** [comment]
Confirmed under second user, same Portal 10.5.1 platform

**Comment by tedrick** [comment]
@billwie - this is currently expected behavior if the service is republished as part of the Web>Connect authoring process. The survey sharing setting will need to be reset.  Adding comments to existing issue

**Comment by billwie** [comment]
The survey was not shared with anyone.  I was connecting as the survey owner when I tested both.

Sent from my iPhone

On Jan 19, 2018, at 6:31 PM, James Tedrick <notifications@github.com<mailto:notifications@github.com>> wrote:


@billwie<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbillwie&data=02%7C01%7C%7C614777f88b084244138008d55f9d3178%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636520051094183567&sdata=AI2JVYSwG95EJ4emI64tpRCGI23yCuQX%2FNj2ZVIeXJM%3D&reserved=0> - this is currently expected behavior if the service is republished as part of the Web>Connect authoring process. The survey sharing setting will need to be reset. Adding comments to existing issue

**Comment by billwie** [comment]
Also, this exact workflow works correctly in survey123.arcgis.com, it does not work in survey123qa.arcgis.com
