### ISSUE TITLE
An Error occured while generating reports is displayed while the server is experiencing issues

### ISSUE THREAD

**Issue by cdarti** [tedrick/Survey123-Testing#88]
**Application:** Website

**Device:** Dell Laptop

**Operating System:** Windows 10

**Browser:** Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Error Description:** 

/api/reportMerge/_printByWordTemplate/execute Failed to load resource: the server responded with a status of 502 (Proxy Error)
init.js:180 Slow network is detected. Fallback font will be used while loading: https://survey123qa.arcgis.com/assets/font/b86524f7-009e-4c08-a266-c43f1fb68e5e-e89ad3b7.woff2
5/api/reportMerge/_printByWordTemplate/execute Failed to load resource: the server responded with a status of 502 (Proxy Error)

**How to reproduce:**
Generate a Report from the configuration window. Reports are created but eventually after doing other actions (variable), the message An Error occured while generating reports is displayed.
An Error occured while generating reports is displayed.

**Have you tested with another survey?** no

**Comment by asmyrk** [comment]
I've been seeing this on my reports also.  It seems intermittent and I can't figure out how to reproduce consistently.  But after I've clicked around in the page for a couple minutes, then the report generates as expected.

**Comment by tedrick** [comment]
in working with @cdarti , this likely due to survey123qa API in general or print report queue becoming full with requests.  Will research performance of the API.

**Comment by zhif7782** [comment]
Found by @yuezhaoBJ, it should be caused that there are lots of pressure on the service or the map image is too complicated to be printed in a sync way
Internal issue in dev repo: https://devtopia.esri.com/Beijing-R-D-Center/survey123-hub/issues/2181
