### ISSUE TITLE
error opening existing survey

### ISSUE THREAD

**Issue by allisonmuise** [tedrick/Survey123-Testing#90]
**Application:** 
Website

**Device:**
Windows

**Operating System:** _Provide version, i.e., Android 5.0.1_
Windows 10

**Browser:** _For the website_
Chrome 63.0.3239.132

**Error Description:** 
When opening a survey deployed through the Solution Deployment Tool, I receive and error message from survey123qa.arcgis.com and survey123dev.arcgis.com, whereas survey123.arcgis.com opens the survey without issue

**How to reproduce:**
1. Install the Solution Deployment Tool (http://solutions.arcgis.com/shared/help/deployment-tool/)
2. In ArcGIS Pro (tested using version 2.0.1) go to the Share tab and open the SDT. Use the tool to deploy the Homeless Count survey.
3. From survey123qa.arcgis.com, sign in to the org where the Homeless Count survey was deployed.
4. From My Surveys, click the Homeless Count survey. The browser shows the message "The survey does not exist or is not accessible."
5. Repeat steps 3 and 4 on survey123.arcgis.com and note that the information for the survey is displayed.

https://arcgis4localgov2.maps.arcgis.com/home/item.html?id=fec0863283914bf28c5307c08c065af6

**Have you tested with another survey?** 
Not yet

**Comment by tedrick** [comment]
Working with @allisonmuise , looks to be a cache issue on her computer
