### ISSUE TITLE
ENH: allow users to select a photo to be used for annotation

### ISSUE THREAD

**Issue by sbubka94** [tedrick/Survey123-Testing#93]
**Application:** Connect | Field App 

**Device:** iPhone 7 Plus iOS 11.2.2

Using the annotate appearance only allows the user to take a new picture with the camera to annotate. It would be useful to be able to look through your camera roll in case the picture has been taken earlier in the day and now requires annotation

**Comment by tedrick** [comment]
Added to internal issue https://devtopia.esri.com/Melbourne/Survey123/issues/1820
