### ISSUE TITLE
Map won't zoom to my location - HTC 10 Android 7.0

### ISSUE THREAD

**Issue by allisonmuise** [tedrick/Survey123-Testing#94]
**Application:** 
Website

**Device:**
HTC10

**Operating System:** 
Android 7.0.0 HTC Build NRD90M

**Browser:**
Chrome 63.0.3239.111 & default android browser

**Error Description:** 
Clicking the crosshairs on the map only moved the pointer to my location the first time it is clicked. If I try to zoom in on the map, then click the crosshairs the pin stays where it is. 

I have confirmed that I have shared my location with survey123qa.arcgis.com. 

I can occaisionally reproduce this on a Nexus 5x running Android 7.0 and the same version of Chrome

**How to reproduce:**
1. load app
2. Click location question
3. click crosshairs to zoom to my location. If prompted to share location, click 'Allow'.
4. try to zoom in to the map using pinch zoom to confirm that location is correct. Pin on map will move around as you zoom.
5. Try to re-center the pin on your location by clicking the crosshairs. It won't move, even if the pin is nowhere near your actual location. Sometimes I need to manually zoom around a bit, sometimes I need to click the +/- buttons before pinch zooming, but it almost always eventually stops working.

**Have you tested with another survey?** 
yes, tested with 3 different surveys on 2 devices. found on a survey with several different question types, but was also able to repro on a survey that had only 1 question - the geopoint. 

The crosshairs stop working once the lat/long values stop updating on pan.

**Comment by tedrick** [comment]
Logged into development repo
