### ISSUE TITLE
Error initializing Form...

### ISSUE THREAD

**Issue by franksoma** [tedrick/Survey123-Testing#95]
**Application:** Website - https://survey123qa.arcgis.com/surveys
**Browser:** FireFox Quantum 57.0.4 (64-bit)

**Error Description:** From Url: https://survey123qa.arcgis.com/surveys.  Opening survey “Restaurant Inspection” renders the following error (see snapshot).  I have shared the form and hosted features layer to everyone for troubleshooting purposes.
URL rendering error is: https://survey123qa.arcgis.com/share/d88dffef49a64c32aef2ba36aefa6d2a 

**How to reproduce:**

**Have you tested with another survey? No
[Restaurant Inspection.zip](https://github.com/tedrick/Survey123-Testing/files/1648101/Restaurant.Inspection.zip)

![image](https://user-images.githubusercontent.com/28578371/35174619-d8f7f4ac-fd24-11e7-9fb6-77e865f3cc07.png)

**Comment by tedrick** [comment]
@franksoma - it looks like the sample needs to be updated - the location calculation does not appear correct for the webform (which uses `concat`, not `+`, for text joining)

**Comment by tedrick** [comment]
Added to issue regarding this sample.
