### ISSUE TITLE
Make "Cache answer to this question" option available in Survey123 Connect/XLSform

### ISSUE THREAD

**Issue by jfangit** [tedrick/Survey123-Testing#96]
**Application:** Connect | Field App | Website | On Premises | _Other_
Connect
**Device:** _Important for Field App especially_
iOS
**Operating System:** _Provide version, i.e., Android 5.0.1_
iOS 9.3.4
**Browser:** _For the website_

**Error Description:** 
I recently built a survey123 form for County of San Bernardino Homeless Count. More than once, users requested the capability of defaulting to the previous value for fields such as Surveyor name, Surveyor phone number, and Map ID etc. Let's say a volunteer talks to 30 homeless people. Those three required fields would have exactly same values for all those surveys, but they now have to enter those type of fields 30 times. Being able to default to the initial values entered would be a huge time saver. I see that this is available in the web form but haven't able to do the same for the mobile app.
**How to reproduce:**

**Have you tested with another survey?**

**Comment by tedrick** [comment]
Added to enhancement issue - https://devtopia.esri.com/Melbourne/Survey123/issues/1507
