### ISSUE TITLE
Request: Webhook JSON Schema Preview

### ISSUE THREAD

**Issue by iaguilera14** [tedrick/Survey123-Testing#97]
**Application:** Connect

**Device:**  Laptop Mac

**Operating System:** Mac OS

**Error Description:** 
Allow for a preview of the JSON schema sent to the webhook endpoint. This would be a good thing to include in the future that could aid developers in handling the data sent by Survey123.

**Comment by tedrick** [comment]
Added to webhook internal issue: https://devtopia.esri.com/Melbourne/Survey123/issues/1987
